// ─────────────────────────────────────────────────────────────────────────────
// DIALOGUE PUNCTUATION WORKSHEET — a self-contained dashboard plugin (upper
// primary: Year 5+; ACARA Y5–6 — correctly punctuating dialogue beyond the
// Y3 basics: embedded quotes, quotes inside sentences, new-speaker lines).
//
// The dashboard loads this plugin by calling
// `AdvancedPunctuationWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Dialogue Punctuation", glyph "❞") and which grades
//     offer it (Year 5+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Dialogue Punctuation worksheet without affecting the framework
// or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Question/exclamation speech lines (they take '?'/'!' INSIDE the quotes, no
// trailing comma) vs statement lines (comma inside, none after the quote).
const SPEECH_QUESTIONS: readonly string[] = [
    'Who left the gate open', 'Where are my runners', 'Can we go to the beach today',
    'Is the canteen still open', 'Whose turn is it to set the table', 'What time is the bus coming'
] as const;
const SPEECH_EXCLAIMS: readonly string[] = [
    'Look out below', 'We won the grand final', 'That was so close',
    'What a brilliant idea', 'Help, a spider', 'My plane actually flew'
] as const;
const SPEECH_STATEMENTS: readonly string[] = [
    'I brought the sports kit', 'The movie starts at six', 'Dinner is nearly ready',
    'We are going to the museum', 'My project is on volcanoes', 'Training is cancelled today'
] as const;
const REPORTERS: readonly string[] = ['said Mia', 'asked Sam', 'called Leo', 'whispered Zoe', 'replied Ben', 'shouted Ava'] as const;

// Dialogue punctuation — THREE procedural kinds (upper primary):
//   0. MC: which ending is correct for the reported line ('? or !' inside
//      the quotes with no trailing comma; '.' with a comma)
//   1. written: punctuate the full reported line (answer string)
//   2. MC: two-speaker layout — which line pair correctly starts a new line
//      when the speaker changes
//
// NON-REPEATING SAMPLING: line x reporter cross-products keep the space past
// 100 pages; every question passes through sampleUnique keyed on prompt.
function generateAdvPunct(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 2);
            if (kind === 0) {
                // MC: pick the correctly punctuated reported line. Statements
                // take a comma INSIDE the quotes; ?/! take no comma.
                const useQ = rng.next() < 0.5;
                const useEx = !useQ && rng.next() < 0.5;
                const reporter = rng.pick(REPORTERS);
                if (useQ) {
                    const line = rng.pick(SPEECH_QUESTIONS);
                    const right = `"${line}?" ${reporter}.`;
                    const wrong1 = `"${line}?", ${reporter}.`;
                    const wrong2 = `"${line}"? ${reporter}.`;
                    const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                    return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
                }
                if (useEx) {
                    const line = rng.pick(SPEECH_EXCLAIMS);
                    const right = `"${line}!" ${reporter}.`;
                    const wrong1 = `"${line}!", ${reporter}.`;
                    const wrong2 = `"${line}!" ${reporter}!`;
                    const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                    return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
                }
                const line = rng.pick(SPEECH_STATEMENTS);
                const right = `"${line}," ${reporter}.`;
                const wrong1 = `"${line}." ${reporter}.`;
                const wrong2 = `"${line}", ${reporter}.`;
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 1) {
                // Written: fully punctuate the bare reported line.
                const reporter = rng.pick(REPORTERS);
                const isQ = reporter.startsWith('asked');
                const line = isQ ? rng.pick(SPEECH_QUESTIONS) : rng.pick(SPEECH_STATEMENTS);
                const right = isQ ? `"${line}?" ${reporter}.` : `"${line}," ${reporter}.`;
                return { prompt: `Punctuate the dialogue: ${line} ${reporter}.`, answer: right };
            }
            // MC: new-speaker layout — each speaker's words go on a NEW line.
            const line1 = rng.pick(SPEECH_STATEMENTS);
            const line2 = rng.pick(SPEECH_QUESTIONS);
            const right = `"${line1}," said Mia.\n"Where is the map?" asked Sam.`;
            const wrong1 = `"${line1}," said Mia. "Where is the map?" asked Sam.`;
            const wrong2 = `"${line1}," said Mia. asked Sam, "Where is the map?"`;
            const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
            return {
                prompt: `Which layout is right when the speaker changes? (${shown.join(' / ')})`,
                answer: right
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn.
export const advpunctSpec: WorksheetSpec = {
    id: 'advpunct',
    label: 'Dialogue Punctuation',
    icon: '❞',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('advpunct'),
    scope: () => 'quotes, commas & new speakers',
    generate: generateAdvPunct
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AdvancedPunctuationWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(advpunctSpec);
}
