// ─────────────────────────────────────────────────────────────────────────────
// DIALOGUE PUNCTUATION WORKSHEET — a self-contained dashboard plugin (upper
// primary: Year 5+; ACARA Y5–6 — correctly punctuating dialogue beyond the
// Y3 basics: embedded quotes, quotes inside sentences, new-speaker lines).
//
// The dashboard loads this plugin by calling
// `AdvancedPunctuationWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Dialogue Punctuation", glyph "❞") and which grades
//     offer it (listed for Years 3–6 in the upper-primary catalogue — the
//     ACARA material itself is Y5–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Dialogue Punctuation worksheet without affecting the framework
// or any other plugin.
//
// DENSITY (distribution quality pass): perPage dropped 16 → 6 (single
// column). Every family here is a WRITING task (punctuate a full line,
// compose an exchange) — six full-width rows give the room that work needs.
//
// SEMANTIC VARIETY (the old sheet's core flaw): the two-speaker layout
// family always printed the SAME second line ("Where is the map?" asked
// Sam), and the speech banks were only 6+6+6 lines. The banks are now
// 10 questions + 10 exclamations + 12 statements + 10 reporters, the
// two-speaker pairs vary BOTH lines and both reporters, and a new split-
// reporter bank (quote interrupted by the speaker) adds the third dialogue
// pattern Y5–6 texts use.
//
// TASK VARIETY: SIX connected families — interpret (pick the correctly
// punctuated line, pick the correct new-speaker layout), apply (punctuate a
// bare line, punctuate a split-quote line, compose a two-speaker exchange).
// Families are dealt from a KIND DECK for even spread.
//
// ANSWER VALIDITY: the punctuation rules are the standard ones taught at
// this level — question marks/exclamation marks sit INSIDE the quotes with
// no trailing comma; statements take a comma inside the quotes; a new
// speaker starts a new line; a split quote keeps its internal comma on both
// sides of the reporter. Every distractor breaks exactly one rule, so each
// MCQ has one defensible answer. Open-ended rows carry an "Example:" model.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Question/exclamation speech lines (they take '?'/'!' INSIDE the quotes, no
// trailing comma) vs statement lines (comma inside, none after the quote).
const SPEECH_QUESTIONS: readonly string[] = [
    'Who left the gate open', 'Where are my runners', 'Can we go to the beach today',
    'Is the canteen still open', 'Whose turn is it to set the table', 'What time is the bus coming',
    'Have you seen my library book', 'Did the team win the semi', 'How far is the nearest lake',
    'Why is the door locked'
] as const;
const SPEECH_EXCLAIMS: readonly string[] = [
    'Look out below', 'We won the grand final', 'That was so close',
    'What a brilliant idea', 'Help, a spider', 'My plane actually flew',
    'Happy birthday', 'Watch the ball', 'We made the finals', 'What a goal'
] as const;
const SPEECH_STATEMENTS: readonly string[] = [
    'I brought the sports kit', 'The movie starts at six', 'Dinner is nearly ready',
    'We are going to the museum', 'My project is on volcanoes', 'Training is cancelled today',
    'The owl hooted twice', 'I will feed the fish', 'Our train leaves at noon',
    'The garden needs water', 'Grandma arrived by bus', 'Tomorrow is the exam'
] as const;
// Reporters: "asked ..." pairs with question lines; the rest pair with
// statements and exclamations.
const REPORTERS: readonly string[] = [
    'said Mia', 'asked Sam', 'called Leo', 'whispered Zoe', 'replied Ben',
    'shouted Ava', 'asked Nina', 'said Tom', 'replied Ella', 'called Max'
] as const;
const ASK_REPORTERS: readonly string[] = ['asked Sam', 'asked Nina'] as const;
// Split-quote lines: [first part, second part] — one speaker's sentence
// interrupted by the reporter: "first," said Mia, "second."
const SPLIT_LINES: readonly [string, string][] = [
    ['I brought the sports kit', 'but Tom forgot his'],
    ['The movie starts at six', 'so we should leave now'],
    ['Dinner is nearly ready', 'please set the table'],
    ['We are going to the museum', 'not the playground'],
    ['My project is on volcanoes', 'not earthquakes'],
    ['Training is cancelled today', 'we will resume tomorrow'],
    ['I will feed the fish', 'you can water the plants'],
    ['Our train leaves at noon', 'be on time'],
    ['The garden needs water', 'grab the hose'],
    ['Tomorrow is the exam', 'study well']
] as const;

// Dialogue punctuation — SIX connected families (upper primary):
//   0. MC ending (interpret): which reported line is punctuated correctly
//      (question / exclamation / statement rule)
//   1. written punctuate (apply): punctuate the bare reported line
//   2. MC layout (interpret): new speaker = new line
//   3. MC split (interpret): which split-quote version is punctuated right
//   4. written split (apply): punctuate a split-quote line from its bare text
//   5. written compose (apply): write the two-speaker exchange for two given
//      lines (open-ended → "Example:" model answer)
//
// NON-REPEATING SAMPLING: line x reporter x split cross-products keep the
// space far past 100 pages; every question passes through sampleUnique keyed
// on prompt.
function generateAdvPunct(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const kindDeck = localDeck(rng, [0, 1, 2, 3, 4, 5] as const);
    return sampleUnique(
        count,
        () => {
            const kind = kindDeck.take();
            if (kind === 0) {
                // MC: pick the correctly punctuated reported line. Statements
                // take a comma INSIDE the quotes; ?/! take no comma.
                const roll = rng.next();
                const reporter = rng.pick(REPORTERS);
                if (roll < 1 / 3) {
                    const line = rng.pick(SPEECH_QUESTIONS);
                    const right = `"${line}?" ${reporter}.`;
                    const wrong1 = `"${line}?", ${reporter}.`;
                    const wrong2 = `"${line}"? ${reporter}.`;
                    const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                    return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
                }
                if (roll < 2 / 3) {
                    const line = rng.pick(SPEECH_EXCLAIMS);
                    const right = `"${line}!" ${reporter}.`;
                    const wrong1 = `"${line}!", ${reporter}.`;
                    const wrong2 = `"${line}"! ${reporter}.`;
                    const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                    return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
                }
                const line = rng.pick(SPEECH_STATEMENTS);
                const right = `"${line}," ${reporter}.`;
                const wrong1 = `"${line}." ${reporter}.`;
                const wrong2 = `"${line}", ${reporter}.`;
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 1) {
                // Written: fully punctuate the bare reported line. Question
                // lines only pair with "asked" reporters so the bare prompt
                // reads as natural speech.
                const isQ = rng.next() < 0.4;
                const isEx = !isQ && rng.next() < 0.4;
                const reporter = isQ ? rng.pick(ASK_REPORTERS) : rng.pick(REPORTERS);
                if (isQ) {
                    const line = rng.pick(SPEECH_QUESTIONS);
                    return { prompt: `Punctuate the dialogue: ${line} ${reporter}.`, answer: `"${line}?" ${reporter}.` };
                }
                if (isEx) {
                    const line = rng.pick(SPEECH_EXCLAIMS);
                    return { prompt: `Punctuate the dialogue: ${line} ${reporter}.`, answer: `"${line}!" ${reporter}.` };
                }
                const line = rng.pick(SPEECH_STATEMENTS);
                return { prompt: `Punctuate the dialogue: ${line} ${reporter}.`, answer: `"${line}," ${reporter}.` };
            }
            if (kind === 2) {
                // MC: new-speaker layout — each speaker's words go on a NEW
                // line. Both lines AND both reporters vary per question.
                const line1 = rng.pick(SPEECH_STATEMENTS);
                const line2 = rng.pick(SPEECH_QUESTIONS);
                const rep1 = rng.pick(REPORTERS.filter((r) => !r.startsWith('asked')));
                const rep2 = rng.pick(ASK_REPORTERS);
                const right = `"${line1}," ${rep1}.\n"${line2}?" ${rep2}.`;
                const wrong1 = `"${line1}," ${rep1}. "${line2}?" ${rep2}.`;
                const wrong2 = `"${line1}," ${rep1}. ${rep2}, "${line2}?"`;
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return {
                    prompt: `Which layout is right when the speaker changes? (${shown.join(' / ')})`,
                    answer: right
                };
            }
            if (kind === 3) {
                // MC: split quote — the reporter interrupts the sentence;
                // BOTH quote parts keep their internal comma.
                const [first, second] = rng.pick(SPLIT_LINES);
                const reporter = rng.pick(REPORTERS.filter((r) => !r.startsWith('asked')));
                const right = `"${first}," ${reporter}, "${second}."`;
                const wrong1 = `"${first}," ${reporter}. "${second}."`;
                const wrong2 = `"${first}", ${reporter}, "${second}."`;
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return { prompt: `Which is punctuated correctly? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 4) {
                // Written: punctuate a split-quote line from its bare text.
                const [first, second] = rng.pick(SPLIT_LINES);
                const reporter = rng.pick(REPORTERS.filter((r) => !r.startsWith('asked')));
                return {
                    prompt: `Add the quotation marks and commas: ${first} ${reporter} ${second}.`,
                    answer: `"${first}," ${reporter}, "${second}."`
                };
            }
            // Written compose: the child writes the whole two-speaker
            // exchange; the answer field is a LABELED model.
            const line1 = rng.pick(SPEECH_STATEMENTS);
            const line2 = rng.pick(SPEECH_QUESTIONS);
            return {
                prompt: `Write a two-speaker dialogue: the first speaker says "${line1}" and the second asks "${line2}".`,
                // Standalone reported lines: ?/! inside the quotes, NO comma
                // after them (the comma rule is for statement quotes only).
                answer: `Example: "${line1}," said Mia.\n"${line2}?" asked Sam.`
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn; perPage 6 keeps the
// writing-heavy sheet low-density.
export const advpunctSpec: WorksheetSpec = {
    id: 'advpunct',
    label: 'Dialogue Punctuation',
    icon: '❞',
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('advpunct'),
    scope: () => 'quotes, commas & new speakers',
    generate: generateAdvPunct
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AdvancedPunctuationWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(advpunctSpec);
}
