// ─────────────────────────────────────────────────────────────────────────────
// PREFIXES & SUFFIXES (AFFIXES) WORKSHEET — a self-contained dashboard plugin
// (upper primary: Year 3+; ACARA Y3–6 — morphemes, common prefixes and
// suffixes, AU spellings: -ise not -ize, -our forms).
//
// The dashboard loads this plugin by calling `AffixWorksheet(dashboard)` with
// its configurations + layouts (see plugins/index.ts). Within this function
// the plugin describes:
//   - its SIDEBAR LABEL ("Prefixes & Suffixes", glyph "±") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Prefixes & Suffixes worksheet without affecting the framework
// or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Prefix items: [prefix, base, whole word, meaning of the prefix].
// All AU spellings; meanings are the kid-level glosses taught in class.
const PREFIX_ITEMS: [string, string, string, string][] = [
    ['un', 'happy', 'unhappy', 'not'],
    ['un', 'pack', 'unpack', 'reverse'],
    ['un', 'fair', 'unfair', 'not'],
    ['un', 'lock', 'unlock', 'reverse'],
    ['re', 'write', 'rewrite', 'again'],
    ['re', 'read', 'reread', 'again'],
    ['re', 'fill', 'refill', 'again'],
    ['re', 'play', 'replay', 'again'],
    ['dis', 'agree', 'disagree', 'not'],
    ['dis', 'appear', 'disappear', 'opposite'],
    ['dis', 'honest', 'dishonest', 'not'],
    ['pre', 'view', 'preview', 'before'],
    ['pre', 'heat', 'preheat', 'before'],
    ['mis', 'spell', 'misspell', 'wrongly'],
    ['mis', 'read', 'misread', 'wrongly'],
    ['over', 'cook', 'overcook', 'too much'],
    ['under', 'size', 'undersize', 'too little'],
    ['sub', 'marine', 'submarine', 'under']
];

// Suffix items: [base, suffix, whole word, what the suffix does]. AU spellings
// (-ise, -our) and the doubling rule shown explicitly (run -> running).
const SUFFIX_ITEMS: [string, string, string, string][] = [
    ['care', 'less', 'careless', 'without'],
    ['help', 'ful', 'helpful', 'full of'],
    ['colour', 'ful', 'colourful', 'full of'],
    ['fear', 'less', 'fearless', 'without'],
    ['quick', 'ly', 'quickly', 'in that way'],
    ['slow', 'ly', 'slowly', 'in that way'],
    ['sad', 'ly', 'sadly', 'in that way'],
    ['real', 'ise', 'realise', 'make/become'],
    ['apolog', 'ise', 'apologise', 'make/become'],
    ['organ', 'ise', 'organise', 'make/become'],
    ['teach', 'er', 'teacher', 'person who'],
    ['play', 'er', 'player', 'person who'],
    ['sing', 'er', 'singer', 'person who'],
    ['hope', 'less', 'hopeless', 'without'],
    ['run', 'ing', 'running', 'doing now'],
    ['jump', 'ing', 'jumping', 'doing now'],
    ['walk', 'ed', 'walked', 'already happened'],
    ['jump', 'ed', 'jumped', 'already happened'],
    ['wonder', 'ful', 'wonderful', 'full of'],
    ['comfort', 'able', 'comfortable', 'able to be']
];

// Affixes — FOUR procedural kinds (upper primary):
//   0. written: "what does the prefix/suffix mean in '<word>'?" (gloss)
//   1. MC: which word contains the dealt prefix/suffix (3 options)
//   2. written: "add the prefix/suffix to '<base>'" (spelling answer)
//   3. MC: what does the dealt affix do (3 gloss options)
//
// NON-REPEATING SAMPLING: items are dealt from decks and every question
// passes through sampleUnique keyed on the printed prompt.
function generateAffix(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const prefixDeck = localDeck(rng, PREFIX_ITEMS);
    const suffixDeck = localDeck(rng, SUFFIX_ITEMS);
    // MC kind 3 glosses drawn from the item's own bank (same affix position).
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 3);
            const usePrefix = rng.next() < 0.5;
            const item = usePrefix ? prefixDeck.take() : suffixDeck.take();
            // Tuple layouts differ: PREFIX_ITEMS are [affix, base, whole,
            // meaning] while SUFFIX_ITEMS read [base, suffix, whole, meaning]
            // — normalise so `affix` always leads and `base` is the word the
            // affix attaches to (without this, a suffix prompt would print
            // the BASE word, e.g. "the suffix 'teach'").
            const [affix, base, whole, meaning] = usePrefix
                ? item
                : ([item[1], item[0], item[2], item[3]] as [string, string, string, string]);
            if (kind === 0) {
                return {
                    prompt: `What does the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" mean in "${whole}"?`,
                    answer: meaning
                };
            }
            if (kind === 1) {
                // MC: which word contains the affix. Distractors are whole
                // words from the opposite bank (no shared affix).
                const distractorBank = usePrefix ? SUFFIX_ITEMS : PREFIX_ITEMS;
                const options = [whole];
                let guard = 0;
                while (options.length < 3 && guard < 24) {
                    guard++;
                    const pick = rng.pick(distractorBank)[2];
                    if (!pick.includes(affix) && !options.includes(pick)) options.push(pick);
                }
                const shown = shuffleLocal(rng, options);
                return {
                    prompt: `Which word has the ${usePrefix ? 'prefix' : 'suffix'} "${affix}"? (${shown.join(', ')})`,
                    answer: whole
                };
            }
            if (kind === 2) {
                return {
                    prompt: `Add the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" to "${base}".`,
                    answer: whole
                };
            }
            // MC gloss: the right meaning beside two glosses from other items.
            const glossBank = usePrefix ? PREFIX_ITEMS : SUFFIX_ITEMS;
            const options = [meaning];
            let guard = 0;
            while (options.length < 3 && guard < 24) {
                guard++;
                const pick = rng.pick(glossBank)[3];
                if (pick !== meaning && !options.includes(pick)) options.push(pick);
            }
            const shown = shuffleLocal(rng, options);
            return {
                prompt: `What does the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" do? (${shown.join(', ')})`,
                answer: meaning
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests).
export const affixSpec: WorksheetSpec = {
    id: 'affix',
    label: 'Prefixes & Suffixes',
    icon: '±',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('affix'),
    scope: () => 'word building blocks',
    generate: generateAffix
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AffixWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(affixSpec);
}
