// ─────────────────────────────────────────────────────────────────────────────
// PREFIXES & SUFFIXES (AFFIXES) WORKSHEET — a self-contained dashboard plugin
// (upper primary: Year 3+; ACARA Y3–6 — morphemes, common prefixes and
// suffixes, AU spellings: -ise not -ize, -our forms).
//
// The dashboard loads this plugin by calling `AffixWorksheet(dashboard)` with
// its configurations + layouts (see plugins/index.ts). Within this function
// the plugin describes:
//   - its SIDEBAR LABEL ("Prefixes & Suffixes", glyph "±") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Prefixes & Suffixes worksheet without affecting the framework
// or any other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 18 rows to 8
// roomy ones. The affix banks grew from 18+20 to 39+34 items, and three new
// connected families joined: SPLIT the word into affix + base (reverse of
// adding), APPLY the word inside a curated sentence frame (only one bank word
// fits each frame), and an open-ended COMPOSE whose key gives one example and
// accepts any sensible word with the affix.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Prefix items: [prefix, base, whole word, meaning of the prefix].
// All AU spellings; meanings are the kid-level glosses taught in class.
// Grown from 18 to 39 items for T4C.
const PREFIX_ITEMS: [string, string, string, string][] = [
    ['un', 'happy', 'unhappy', 'not'],
    ['un', 'pack', 'unpack', 'reverse'],
    ['un', 'fair', 'unfair', 'not'],
    ['un', 'lock', 'unlock', 'reverse'],
    ['re', 'write', 'rewrite', 'again'],
    ['re', 'read', 'reread', 'again'],
    ['re', 'fill', 'refill', 'again'],
    ['re', 'play', 'replay', 'again'],
    ['dis', 'agree', 'disagree', 'not'],
    ['dis', 'appear', 'disappear', 'opposite'],
    ['dis', 'honest', 'dishonest', 'not'],
    ['pre', 'view', 'preview', 'before'],
    ['pre', 'heat', 'preheat', 'before'],
    ['mis', 'spell', 'misspell', 'wrongly'],
    ['mis', 'read', 'misread', 'wrongly'],
    ['over', 'cook', 'overcook', 'too much'],
    ['under', 'size', 'undersize', 'too little'],
    ['sub', 'marine', 'submarine', 'under'],
    // T4C growth: more high-frequency prefixes.
    ['un', 'kind', 'unkind', 'not'],
    ['un', 'do', 'undo', 'reverse'],
    ['re', 'use', 'reuse', 'again'],
    ['re', 'do', 'redo', 'again'],
    ['re', 'heat', 'reheat', 'again'],
    ['re', 'turn', 'return', 'again'],
    ['dis', 'like', 'dislike', 'not'],
    ['dis', 'obey', 'disobey', 'not'],
    ['mis', 'place', 'misplace', 'wrongly'],
    ['mis', 'hear', 'mishear', 'wrongly'],
    ['over', 'sleep', 'oversleep', 'too much'],
    ['under', 'cook', 'undercook', 'too little'],
    ['sub', 'way', 'subway', 'under'],
    ['pre', 'school', 'preschool', 'before'],
    ['non', 'sense', 'nonsense', 'not'],
    ['semi', 'circle', 'semicircle', 'half'],
    ['super', 'market', 'supermarket', 'beyond'],
    ['inter', 'view', 'interview', 'between'],
    ['out', 'grow', 'outgrow', 'more than'],
    ['uni', 'form', 'uniform', 'one'],
    ['tri', 'angle', 'triangle', 'three']
];

// Suffix items: [base, suffix, whole word, what the suffix does]. AU spellings
// (-ise, -our) and the doubling rule shown explicitly (run -> running).
// Grown from 20 to 34 items for T4C.
const SUFFIX_ITEMS: [string, string, string, string][] = [
    ['care', 'less', 'careless', 'without'],
    ['help', 'ful', 'helpful', 'full of'],
    ['colour', 'ful', 'colourful', 'full of'],
    ['fear', 'less', 'fearless', 'without'],
    ['quick', 'ly', 'quickly', 'in that way'],
    ['slow', 'ly', 'slowly', 'in that way'],
    ['sad', 'ly', 'sadly', 'in that way'],
    ['real', 'ise', 'realise', 'make/become'],
    ['apolog', 'ise', 'apologise', 'make/become'],
    ['organ', 'ise', 'organise', 'make/become'],
    ['teach', 'er', 'teacher', 'person who'],
    ['play', 'er', 'player', 'person who'],
    ['sing', 'er', 'singer', 'person who'],
    ['hope', 'less', 'hopeless', 'without'],
    ['run', 'ing', 'running', 'doing now'],
    ['jump', 'ing', 'jumping', 'doing now'],
    ['walk', 'ed', 'walked', 'already happened'],
    ['jump', 'ed', 'jumped', 'already happened'],
    ['wonder', 'ful', 'wonderful', 'full of'],
    ['comfort', 'able', 'comfortable', 'able to be'],
    // T4C growth: more -ful/-less/-ly/-er/-able families.
    ['help', 'less', 'helpless', 'without'],
    ['care', 'ful', 'careful', 'full of'],
    ['use', 'less', 'useless', 'without'],
    ['hope', 'ful', 'hopeful', 'full of'],
    ['peace', 'ful', 'peaceful', 'full of'],
    ['danger', 'ous', 'dangerous', 'full of'],
    ['poison', 'ous', 'poisonous', 'full of'],
    ['kind', 'ness', 'kindness', 'state of'],
    ['teach', 'ing', 'teaching', 'doing now'],
    ['read', 'er', 'reader', 'person who'],
    ['bake', 'er', 'baker', 'person who'],
    ['move', 'able', 'movable', 'able to be'],
    ['enjoy', 'able', 'enjoyable', 'able to be'],
    ['count', 'able', 'countable', 'able to be']
];

// APPLY frames (T4C new family): [answer, sentence with "__", distractors].
// Every frame has exactly ONE bank word that fits its meaning, so the MC
// answer stays deterministic while the task becomes real sentence use.
const AFFIX_SENTENCES: [string, string, string[]][] = [
    ['replay', 'Watch the goal again — the coach showed us the __ of the match.', ['rewrite', 'return']],
    ['unpack', 'After the holiday I had to __ my suitcase.', ['unlock', 'redo']],
    ['preheat', 'Remember to __ the oven before the cake goes in.', ['reheat', 'misread']],
    ['misspell', 'I always __ the word "because".', ['rewrite', 'undo']],
    ['disagree', 'My best friend and I __ about which team is best.', ['disappear', 'disobey']],
    ['disappear', 'The magician made the coin __ into thin air.', ['dislike', 'disagree']],
    ['submarine', 'The __ dived deep under the sea.', ['subway', 'semicircle']],
    ['triangle', 'Draw a __ with three straight sides.', ['semicircle', 'uniform']],
    ['supermarket', 'We buy fresh fruit at the __ near the school.', ['preschool', 'preview']],
    ['uniform', 'The cricket team wears a white __ to play.', ['semicircle', 'subway']],
    ['teacher', 'The __ taught us long division.', ['baker', 'player']],
    ['baker', 'The __ baked fresh bread every morning.', ['teacher', 'singer']],
    ['careful', 'Be __ when you carry the glass jug.', ['careless', 'colourful']],
    ['slowly', 'The snail moved __ along the fence.', ['quickly', 'loudly']],
    ['silently', 'The cat crept __ past the sleeping dog.', ['rudely', 'sweetly']]
];

// Affixes — SEVEN procedural kinds (upper primary):
//   0. written: "what does the prefix/suffix mean in '<word>'?" (gloss)
//   1. MC: which word contains the dealt prefix/suffix (3 options)
//   2. written: "add the prefix/suffix to '<base>'" (spelling answer)
//   3. MC: what does the dealt affix do (3 gloss options)
//   4. written: "split '<whole>' into affix + base" (reverse of adding)
//   5. MC APPLY: which bank word fits the curated sentence frame
//   6. open-ended COMPOSE: "write a word with the prefix/suffix X" — the key
//      gives one bank example and accepts any sensible word
//
// NON-REPEATING SAMPLING: items are dealt from decks and every question
// passes through sampleUnique keyed on the printed prompt.
function generateAffix(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const prefixDeck = localDeck(rng, PREFIX_ITEMS);
    const suffixDeck = localDeck(rng, SUFFIX_ITEMS);
    const sentenceDeck = localDeck(rng, AFFIX_SENTENCES);
    // MC kind 3 glosses drawn from the item's own bank (same affix position).
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 6);
            if (kind === 5) {
                // APPLY: the one bank word that fits the sentence frame,
                // beside two frame-specific distractors.
                const [answer, sentence, distractors] = sentenceDeck.take();
                const shown = shuffleLocal(rng, [answer, ...distractors]);
                return { prompt: `Which word fits: ${sentence} (${shown.join(', ')})`, answer };
            }
            if (kind === 6) {
                // OPEN-ENDED compose: any real word carrying the affix is
                // correct; the example comes from the bank. NOTE the tuple
                // layouts: the affix sits at index 0 for prefixes but index 1
                // for suffixes ([base, suffix, whole, meaning]).
                const usePrefix = rng.next() < 0.5;
                const bank = usePrefix ? PREFIX_ITEMS : SUFFIX_ITEMS;
                const affixIdx = usePrefix ? 0 : 1;
                const affix = rng.pick(bank)[affixIdx];
                const matches = bank.filter((i) => i[affixIdx] === affix);
                const example = matches[rng.int(0, matches.length - 1)][2];
                return {
                    prompt: `Write a word that has the ${usePrefix ? 'prefix' : 'suffix'} "${affix}".`,
                    answer: `Example: ${example} (any real word with the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" is correct)`
                };
            }
            const usePrefix = rng.next() < 0.5;
            const item = usePrefix ? prefixDeck.take() : suffixDeck.take();
            // Tuple layouts differ: PREFIX_ITEMS are [affix, base, whole,
            // meaning] while SUFFIX_ITEMS read [base, suffix, whole, meaning]
            // — normalise so `affix` always leads and `base` is the word the
            // affix attaches to (without this, a suffix prompt would print
            // the BASE word, e.g. "the suffix 'teach'").
            const [affix, base, whole, meaning] = usePrefix
                ? item
                : ([item[1], item[0], item[2], item[3]] as [string, string, string, string]);
            if (kind === 0) {
                return {
                    prompt: `What does the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" mean in "${whole}"?`,
                    answer: meaning
                };
            }
            if (kind === 1) {
                // MC: which word contains the affix. Distractors are whole
                // words from the opposite bank (no shared affix).
                const distractorBank = usePrefix ? SUFFIX_ITEMS : PREFIX_ITEMS;
                const options = [whole];
                let guard = 0;
                while (options.length < 3 && guard < 24) {
                    guard++;
                    const pick = rng.pick(distractorBank)[2];
                    if (!pick.includes(affix) && !options.includes(pick)) options.push(pick);
                }
                const shown = shuffleLocal(rng, options);
                return {
                    prompt: `Which word has the ${usePrefix ? 'prefix' : 'suffix'} "${affix}"? (${shown.join(', ')})`,
                    answer: whole
                };
            }
            if (kind === 2) {
                return {
                    prompt: `Add the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" to "${base}".`,
                    answer: whole
                };
            }
            if (kind === 4) {
                // SPLIT: reverse of adding — the child separates the morphemes.
                const parts = usePrefix ? `${affix} + ${base}` : `${base} + ${affix}`;
                return {
                    prompt: `Split "${whole}" into its ${usePrefix ? 'prefix' : 'suffix'} and base word.`,
                    answer: parts
                };
            }
            // MC gloss: the right meaning beside two glosses from other items.
            const glossBank = usePrefix ? PREFIX_ITEMS : SUFFIX_ITEMS;
            const options = [meaning];
            let guard = 0;
            while (options.length < 3 && guard < 24) {
                guard++;
                const pick = rng.pick(glossBank)[3];
                if (pick !== meaning && !options.includes(pick)) options.push(pick);
            }
            const shown = shuffleLocal(rng, options);
            return {
                prompt: `What does the ${usePrefix ? 'prefix' : 'suffix'} "${affix}" do? (${shown.join(', ')})`,
                answer: meaning
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). T4C: 8 roomy
// rows per page instead of 18.
export const affixSpec: WorksheetSpec = {
    id: 'affix',
    label: 'Prefixes & Suffixes',
    icon: '±',
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('affix'),
    scope: () => 'word building blocks',
    generate: generateAffix
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AffixWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(affixSpec);
}
