// ─────────────────────────────────────────────────────────────────────────────
// SUBJECT–VERB AGREEMENT WORKSHEET — a self-contained dashboard plugin (upper
// primary: Year 5+; ACARA Y5–6 grammar — matching verbs to singular/plural
// subjects, is/are, was/were, has/have).
//
// The dashboard loads this plugin by calling `AgreementWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Verb Agreement", glyph "≡") and which grades offer
//     it (Year 5+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Verb Agreement worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Singular subjects x predicates (is/was/has forms) and the plural pairs
// (are/were/have): [singular subject, plural subject, verb pair, tail].
// The tail completes the sentence with the singular subject; for plurals the
// tail is adjusted where needed (kept sense-neutral: "happy", "quiet"...).
const AGREEMENT_PAIRS: [string, string, [string, string, string]][] = [
    ['The dog', 'The dogs', ['is', 'are', 'barking']],
    ['My brother', 'My brothers', ['is', 'are', 'watching TV']],
    ['The teacher', 'The teachers', ['has', 'have', 'a new planner']],
    ['The player', 'The players', ['was', 'were', 'tired after training']],
    ['The baby', 'The babies', ['is', 'are', 'sleeping']],
    ['My friend', 'My friends', ['is', 'are', 'coming over']],
    ['The kitten', 'The kittens', ['was', 'were', 'hiding']],
    ['The student', 'The students', ['has', 'have', 'finished the test']],
    ['The bird', 'The birds', ['is', 'are', 'singing']],
    ['The child', 'The children', ['is', 'are', 'reading quietly']],
    ['The farmer', 'The farmers', ['was', 'were', 'harvesting wheat']],
    ['My cousin', 'My cousins', ['has', 'have', 'arrived']],
    ['The woman', 'The women', ['is', 'are', 'swimming laps']],
    ['The man', 'The men', ['was', 'were', 'mending the fence']],
    ['The mouse', 'The mice', ['is', 'are', 'sneaking about']],
    ['The goose', 'The geese', ['was', 'were', 'waddling to the pond']]
];

// Verb pairs for the is/are-family multiple choice; was/were and has/have
// each carry the same singular/plural split. One extra set (does/do) supplies
// MC distractors without touching the answer forms.
const VERB_SETS: readonly [string, string][] = [
    ['is', 'are'],
    ['was', 'were'],
    ['has', 'have'],
    ['does', 'do']
] as const;

// Subject–verb agreement — THREE procedural kinds (upper primary):
//   0. written: fill the correct verb for the printed subject
//   1. MC: which verb agrees with the printed subject (right verb beside the
//      partner form and one from another pair)
//   2. written: spot the matching subject — given the verb, name the SUBJECT
//      (from the dealt pair's singular) that fits
//
// NON-REPEATING SAMPLING: pairs AND verb sets are dealt from decks; every
// question passes through sampleUnique keyed on the printed prompt.
function generateAgreement(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const pairDeck = localDeck(rng, AGREEMENT_PAIRS);
    const verbDeck = localDeck(rng, VERB_SETS);
    return sampleUnique(
        count,
        () => {
            const [sing, plur, verbs] = pairDeck.take();
            const kind = rng.int(0, 2);
            if (kind === 0) {
                // Written: singular or plural subject -> the agreeing verb.
                const useSing = rng.next() < 0.5;
                const subject = useSing ? sing : plur;
                const answer = useSing ? verbs[0] : verbs[1];
                return { prompt: `Choose the correct verb: ${subject} __ ${verbs[2]}.`, answer };
            }
            if (kind === 1) {
                // MC: the agreeing verb beside its partner + a third form from
                // another verb set (never equal to the answer).
                const useSing = rng.next() < 0.5;
                const subject = useSing ? sing : plur;
                const answer = useSing ? verbs[0] : verbs[1];
                const other = useSing ? verbs[1] : verbs[0];
                const otherSet = rng.pick(VERB_SETS.filter(([, a]) => a !== verbs[0] && a !== verbs[1] && a !== answer));
                const extra = rng.pick(otherSet);
                const shown = shuffleLocal(rng, [answer, other, extra]);
                return { prompt: `Which verb agrees: ${subject} __ ${verbs[2]}? (${shown.join(', ')})`, answer };
            }
            // Written: given the verb form, name the fitting subject.
            const [, verbSet] = verbDeck.take();
            const useSing = rng.next() < 0.5;
            const verb = useSing ? verbSet[0] : verbSet[1];
            const answer = useSing ? sing : plur;
            return { prompt: `Which subject fits: __ ${verb} happy. (${sing} or ${plur})`, answer };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests).
export const agreementSpec: WorksheetSpec = {
    id: 'agreement',
    label: 'Verb Agreement',
    icon: '=',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('agreement'),
    scope: () => 'subjects & verbs that match',
    generate: generateAgreement
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AgreementWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(agreementSpec);
}
