// ─────────────────────────────────────────────────────────────────────────────
// ALPHABET ORDER WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `AlphabetOrderWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Alphabet Order", glyph "Az") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Alphabet Order worksheet without affecting the framework or
// any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, isEarlyCueBand, sampleUnique } from '../framework';
import { wordSet, shuffleWords } from './words';

// ── Task design (T4A) ────────────────────────────────────────────────────────
// TWENTY procedural kinds — the fifteen letter-neighbourhood / word-order
// kinds plus four deeper connected task types so a page mixes recognize /
// build / apply / CHECK work instead of one template repeated 24×:
//
//   15 APPLY    "Which letter comes between 'p' and 'r'?"          (answer q)
//   16 CHECK    "Do the letters 'b' and 'f' come in alphabetical
//               order? (yes / no)"                                  (true+false)
//   17 CHECK    "Do the words 'ant' and 'bee' come in alphabetical
//               order? (yes / no)"
//   18 BUILD    "Write in alphabetical order: (sun, ant, pen)"
//               (model answer "ant, pen, sun" — the full sorted list)
//   19 RECOGNIZE "Which is the 5th UPPERCASE letter of the alphabet?" (E)
//
// DENSITY (E2): perPage 24 -> 8.
//
// The earlier widening (3-runs, skip-2 runs, positions from either end,
// UPPERCASE variants, word order over the grade word set) is kept: the
// question space is the cross-product of letters x neighbourhoods x word
// sets, so the sheet stays fresh far past 100 pages.
//
// NON-REPEATING SAMPLING: every question passes through sampleUnique keyed on
// the printed prompt; word-order triples and task kinds are dealt from decks.
const A = 97; // 'a'
const letter = (x: number) => String.fromCharCode(A + x);
// 1st, 2nd, 3rd, 4th, ... for the position questions.
function ordinal(n: number): string {
    if (n % 100 >= 11 && n % 100 <= 13) return `${n}th`;
    return `${n}${['th', 'st', 'nd', 'rd'][n % 10] ?? 'th'}`;
}
// Three DISTINCT dealt words (decks reshuffle, so the redraw always
// terminates). Null on the unreachable guard breach — callers fall back.
function threeWords(rng: Rng, wordDeck: { take: () => string }): string[] | null {
    let w1 = wordDeck.take();
    let w2 = wordDeck.take();
    let w3 = wordDeck.take();
    let guard = 0;
    while ((w2 === w1 || w3 === w1 || w3 === w2) && guard < 48) {
        guard++;
        if (w2 === w1) w2 = wordDeck.take();
        if (w3 === w1 || w3 === w2) w3 = wordDeck.take();
    }
    if (w2 === w1 || w3 === w1 || w3 === w2) return null;
    return [w1, w2, w3];
}
// Word-order question over `pool`: three distinct dealt words, shuffled for
// printing; `first` asks for the alphabetically FIRST word, `false` the LAST.
function wordOrder(rng: Rng, wordDeck: { take: () => string }, first: boolean) {
    const words = threeWords(rng, wordDeck);
    if (!words) {
        // Practically unreachable fallback: keep the draw well-posed by
        // returning a letter question instead.
        const x = rng.int(0, 24);
        return { prompt: `Which letter comes after "${letter(x)}"?`, answer: letter(x + 1) };
    }
    const [w1, w2, w3] = words;
    const sorted = [w1, w2, w3].sort();
    const answer = first ? sorted[0] : sorted[2];
    const shown = shuffleWords(rng, [w1, w2, w3]);
    return {
        prompt: `Which word comes ${first ? 'first' : 'last'} in the alphabet? (${shown.join(', ')})`,
        answer
    };
}
// ── Tile scaffold (Y1–3, early cue band) ────────────────────────────────────
// The SEQUENCE kinds print the missing-letter slot as a bordered WRITE-BOX
// tile (PrintableSheet renders `__` as a writing box instead of a plain
// underline when tileBlanks is set) — a real writing scaffold, not decoration:
// the child sees a letter-sized box to write the missing letter into. The
// prompts themselves are unchanged, only the printed blank shape, and the
// metadata is gated on isEarlyCueBand so Prep and Years 4+ keep their legacy
// underlines.
function generateLetters(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const wordDeck = createDeck(rng, wordSet(caps.wordTier));
    // {} outside the cue band → the row object stays byte-identical to legacy.
    const boxed = isEarlyCueBand(caps) ? { tileBlanks: 'letter' as const } : {};
    const kindDeck = createDeck(rng, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]);
    return sampleUnique(
        count,
        () => {
            const kind = kindDeck.take();
            if (kind === 0) {
                // Letter AFTER x (x in a..y so an answer always exists).
                const x = rng.int(0, 24);
                return { prompt: `Which letter comes after "${letter(x)}"?`, answer: letter(x + 1) };
            }
            if (kind === 1) {
                // Letter BEFORE x (x in b..z).
                const x = rng.int(1, 25);
                return { prompt: `Which letter comes before "${letter(x)}"?`, answer: letter(x - 1) };
            }
            if (kind === 2) {
                // Forward run of two shown then the next: "a, b, __" (+ write-
                // box for the missing letter, Y1–3 only — see `boxed`).
                const x = rng.int(0, 23);
                return { prompt: `${letter(x)}, ${letter(x + 1)}, __`, answer: letter(x + 2), ...boxed };
            }
            if (kind === 3) {
                // Backward run of two shown then the next: "b, a, __".
                const x = rng.int(1, 24);
                return { prompt: `${letter(x)}, ${letter(x - 1)}, __`, answer: letter(x - 2), ...boxed };
            }
            if (kind === 4) {
                // Middle gap of a three-letter run: "a, __, c".
                const x = rng.int(0, 23);
                return { prompt: `${letter(x)}, __, ${letter(x + 2)}`, answer: letter(x + 1), ...boxed };
            }
            if (kind === 5) {
                // Forward run of THREE shown then the next: "a, b, c, __".
                const x = rng.int(0, 22);
                return { prompt: `${letter(x)}, ${letter(x + 1)}, ${letter(x + 2)}, __`, answer: letter(x + 3), ...boxed };
            }
            if (kind === 6) {
                // Backward run of three shown then the next: "d, c, b, __".
                const x = rng.int(3, 25);
                return { prompt: `${letter(x)}, ${letter(x - 1)}, ${letter(x - 2)}, __`, answer: letter(x - 3), ...boxed };
            }
            if (kind === 7) {
                // Skip-one forward: "a, c, __" continues to "e".
                const x = rng.int(0, 21);
                return { prompt: `${letter(x)}, ${letter(x + 2)}, __`, answer: letter(x + 4), ...boxed };
            }
            if (kind === 8) {
                // Skip-one backward: "e, c, __" continues to "a".
                const x = rng.int(4, 25);
                return { prompt: `${letter(x)}, ${letter(x - 2)}, __`, answer: letter(x - 4), ...boxed };
            }
            if (kind === 9) {
                // Position from the start: "Which is the 5th letter of the
                // alphabet?" (answer e).
                const n = rng.int(1, 26);
                return { prompt: `Which is the ${ordinal(n)} letter of the alphabet?`, answer: letter(n - 1) };
            }
            if (kind === 10) {
                // Position from the end: the 1st from the end is z.
                const n = rng.int(1, 26);
                return { prompt: `Which is the ${ordinal(n)} letter from the end of the alphabet?`, answer: letter(26 - n) };
            }
            if (kind === 11) {
                // UPPERCASE after: same neighbour rule, capital shapes.
                const x = rng.int(0, 24);
                const up = (c: string) => c.toUpperCase();
                return { prompt: `Which UPPERCASE letter comes after "${up(letter(x))}"?`, answer: up(letter(x + 1)) };
            }
            if (kind === 12) {
                // UPPERCASE before.
                const x = rng.int(1, 25);
                const up = (c: string) => c.toUpperCase();
                return { prompt: `Which UPPERCASE letter comes before "${up(letter(x))}"?`, answer: up(letter(x - 1)) };
            }
            if (kind === 13) {
                // Word order: which of three dealt words sorts FIRST.
                return wordOrder(rng, wordDeck, true);
            }
            if (kind === 14) {
                // Word order: which of three dealt words sorts LAST.
                return wordOrder(rng, wordDeck, false);
            }
            if (kind === 15) {
                // APPLY: the letter strictly between two neighbours.
                const x = rng.int(0, 24);
                return { prompt: `Which letter comes between "${letter(x)}" and "${letter(x + 2)}"?`, answer: letter(x + 1) };
            }
            if (kind === 16) {
                // CHECK: a yes/no judgement about letter order (both
                // polarities posed — the child cannot learn to always say yes).
                let x = rng.int(0, 25);
                let y = rng.int(0, 25);
                let guard = 0;
                while (y === x && guard < 12) {
                    guard++;
                    y = rng.int(0, 25);
                }
                if (y === x) y = (x + 1) % 26;
                return {
                    prompt: `Do the letters "${letter(x)}" and "${letter(y)}" come in alphabetical order? (yes / no)`,
                    answer: x < y ? 'yes' : 'no'
                };
            }
            if (kind === 17) {
                // CHECK: the same judgement over two dealt WORDS.
                const words = threeWords(rng, wordDeck);
                if (!words) {
                    const x = rng.int(0, 24);
                    return { prompt: `Which letter comes after "${letter(x)}"?`, answer: letter(x + 1) };
                }
                const [a, b] = [words[0], words[1]];
                return {
                    prompt: `Do the words "${a}" and "${b}" come in alphabetical order? (yes / no)`,
                    answer: a < b ? 'yes' : 'no'
                };
            }
            if (kind === 18) {
                // BUILD: sort three dealt words; the model answer is the full
                // ordered list (comma-separated — the framework's multi-value
                // answer form).
                const words = threeWords(rng, wordDeck);
                if (!words) {
                    const x = rng.int(0, 24);
                    return { prompt: `Which letter comes after "${letter(x)}"?`, answer: letter(x + 1) };
                }
                const shown = shuffleWords(rng, words);
                return {
                    prompt: `Write in alphabetical order: (${shown.join(', ')})`,
                    answer: [...shown].sort().join(', ')
                };
            }
            // RECOGNIZE: UPPERCASE position from the start of the alphabet.
            const n = rng.int(1, 26);
            return { prompt: `Which is the ${ordinal(n)} UPPERCASE letter of the alphabet?`, answer: letter(n - 1).toUpperCase() };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const lettersSpec: WorksheetSpec = {
    id: 'letters',
    label: 'Alphabet Order',
    icon: 'Az',
    // E2 density: 8 rows per A4 page.
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('letters'),
    scope: () => 'a–z order',
    generate: generateLetters
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AlphabetOrderWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(lettersSpec);
}
