// ─────────────────────────────────────────────────────────────────────────────
// ALPHABET ORDER WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `AlphabetOrderWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Alphabet Order", glyph "Az") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Alphabet Order worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Alphabet order: five question kinds — next letter after X, letter before X,
// a forward run "a, b, __", a backward run "b, a, __", and a middle gap
// "a, __, c". The alphabet is finite: 25+25+24+24+24 = 122 distinct questions,
// which sampleUnique deals out with zero repeats before the space must cycle.
function generateLetters(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const A = 97; // 'a'
    const letter = (x: number) => String.fromCharCode(A + x);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 4);
            if (kind === 0) {
                // Letter AFTER x (x in a..y so an answer always exists).
                const x = rng.int(0, 24);
                return { prompt: `Which letter comes after "${letter(x)}"?`, answer: letter(x + 1) };
            }
            if (kind === 1) {
                // Letter BEFORE x (x in b..z).
                const x = rng.int(1, 25);
                return { prompt: `Which letter comes before "${letter(x)}"?`, answer: letter(x - 1) };
            }
            if (kind === 2) {
                // Forward run of two shown then the next: "a, b, __".
                const x = rng.int(0, 23);
                return { prompt: `${letter(x)}, ${letter(x + 1)}, __`, answer: letter(x + 2) };
            }
            if (kind === 3) {
                // Backward run of two shown then the next: "b, a, __".
                const x = rng.int(1, 24);
                return { prompt: `${letter(x)}, ${letter(x - 1)}, __`, answer: letter(x - 2) };
            }
            // Middle gap of a three-letter run: "a, __, c".
            const x = rng.int(0, 23);
            return { prompt: `${letter(x)}, __, ${letter(x + 2)}`, answer: letter(x + 1) };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const lettersSpec: WorksheetSpec = {
    id: 'letters',
    label: 'Alphabet Order',
    icon: 'Az',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('letters'),
    scope: () => 'a–z order',
    generate: generateLetters
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AlphabetOrderWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(lettersSpec);
}
