// ─────────────────────────────────────────────────────────────────────────────
// APOSTROPHES WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — apostrophes of possession and contraction).
//
// The dashboard loads this plugin by calling `ApostropheWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Apostrophes", glyph "'") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Apostrophes worksheet without affecting the framework or any
// other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 16 rows to 6
// roomy prose rows. The old space was only 247 unique questions (the smallest
// in the catalogue); the banks grew from 18+18 to 44+40 items AND two whole
// new semantic areas joined: PLURAL possessives ("the students' books" — the
// apostrophe-after-s case) and a correct/incorrect CHECK family. Contraction
// EXPANSION ("write the two words for don't") adds the reverse direction.
// Every item is hand-curated, so the space is genuinely larger — not a
// cosmetic reshuffle of the same 247 lines.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Possession items: [owner, thing, sentence with "__"] — the answer is the
// possessive form printed in the options. Owners are kid-level nouns. Grown
// from 18 to 40 items; no owner ends in 's', so 's is always the right form.
const POSSESSIVE_ITEMS: [string, string, string][] = [
    ['Sam', 'bicycle', 'This is __ bicycle.'],
    ['Mia', 'pencil case', 'That is __ pencil case.'],
    ['the dog', 'kennel', 'The dog sleeps in __ kennel.'],
    ['Leo', 'hat', 'Is this __ hat?'],
    ['the teacher', 'desk', 'The books on __ desk are brand new.'],
    ['my sister', 'bike', '__ bike is red.'],
    ['Zoe', 'lunchbox', '__ lunchbox is on the shelf.'],
    ['the cat', 'bowl', 'Fill up __ bowl, please.'],
    ['Ben', 'shoes', 'Ben tied __ shoes.'],
    ['the girl', 'satchel', 'The girl carried __ satchel.'],
    ['my brother', 'ball', '__ ball is flat.'],
    ['Grandpa', 'glasses', 'These are __ glasses.'],
    ['our team', 'coach', '__ coach blew the whistle.'],
    ['the doctor', 'bag', 'The doctor packed __ bag.'],
    ['the bird', 'nest', 'The eggs are in __ nest.'],
    ['Max', 'football', 'Kick __ football over here.'],
    ['Ava', 'paintbrush', 'Ava washed __ paintbrush.'],
    ['the farmer', 'tractor', 'The farmer parked __ tractor.'],
    // T4C growth: more kid-level owners.
    ['Jack', 'skateboard', 'Jack left __ skateboard at the park.'],
    ['Ella', 'violin', 'Ella tuned __ violin.'],
    ['the spider', 'web', 'The rain damaged __ web.'],
    ['our club', 'robot', '__ robot won the competition.'],
    ['the koala', 'gum leaf', 'The koala chewed __ gum leaf.'],
    ['Nanna', 'recipe book', 'Nanna wrote it in __ recipe book.'],
    ['the horse', 'stable', 'We mucked out __ stable.'],
    ['Ivy', 'scissors', 'Ivy borrowed __ scissors.'],
    ['the chef', 'knife', 'The chef sharpened __ knife.'],
    ['my cousin', 'surfboard', 'My cousin waxed __ surfboard.'],
    ['the penguin', 'chick', 'The penguin fed __ chick.'],
    ['Dad', 'toolbox', '__ toolbox is in the shed.'],
    // T4C growth: more kid-level owners.
    ['Ruby', 'skipping rope', 'Ruby skipped __ rope.'],
    ['the pony', 'saddle', 'Brush __ saddle after riding.'],
    ['Tom', 'fishing rod', 'Tom packed __ fishing rod.'],
    ['the baby', 'pram', 'The baby slept in __ pram.'],
    ['Uncle Ben', 'ute', '__ ute is parked under the verandah.'],
    ['Grace', 'medal', 'Grace polished __ medal.'],
    ['the frog', 'pond', 'The frog dived into __ pond.'],
    ['my aunt', 'van', '__ van is parked outside.'],
    ['the witch', 'hat', 'The witch lost __ pointy hat.'],
    ['the dragon', 'cave', 'The dragon guarded __ cave.']
];

// Contractions: [sentence with "__", full expansion, contraction] — the child
// supplies the contraction (or picks it). Two-word pairs only, kid-level.
// Grown from 18 to 44 items.
const CONTRACTION_ITEMS: [string, string, string][] = [
    ['__ are my friends.', 'you are', "you're"],
    ['I __ believe it!', 'do not', "don't"],
    ['__ is going to rain.', 'it is', "it's"],
    ['We __ late for school.', 'will not', "won't"],
    ['She __ finished her homework.', 'has not', "hasn't"],
    ['They __ coming to the party.', 'are not', "aren't"],
    ['He __ eaten his lunch.', 'has not', "hasn't"],
    ['__ a great game!', 'it is', "it's"],
    ['I __ like spinach.', 'do not', "don't"],
    ['__ going to the library.', 'we are', "we're"],
    ['The dog __ stop barking.', 'did not', "didn't"],
    ['__ have a great holiday!', 'you will', "you'll"],
    ['I __ finished my book.', 'have not', "haven't"],
    ['Swimming __ allowed in the pool.', 'is not', "isn't"],
    ['She __ sing at the concert.', 'will not', "won't"],
    ['__ is time for lunch.', 'it is', "it's"],
    ['We __ seen that movie.', 'have not', "haven't"],
    ['He __ know the answer.', 'does not', "doesn't"],
    // T4C growth: more everyday contractions.
    ['__ your turn next.', 'it is', "it's"],
    ['I __ always carry an umbrella.', 'do not', "don't"],
    ['__ coming with us?', 'are they', "they're"],
    ['Mum __ made a huge cake.', 'has not', "hasn't"],
    ['__ be sunny tomorrow.', 'it will', "it'll"],
    ['We __ never late.', 'are not', "aren't"],
    ['He __ ever been there.', 'has not', "hasn't"],
    ['__ not fair!', 'that is', "that's"],
    ['__ help you carry that.', 'I will', "I'll"],
    ['She __ be six on Tuesday.', 'will not', "won't"],
    ['__ a beautiful painting!', 'that is', "that's"],
    ['You __ need a ticket.', 'do not', "don't"],
    // T4C growth: more everyday contractions.
    ['__ raining hard outside.', 'it is', "it's"],
    ['We __ going to miss it.', 'are not', "aren't"],
    ['__ my birthday next week!', 'it is', "it's"],
    ['They __ not at home.', 'are not', "aren't"],
    ['__ not a problem.', 'it is', "it's"],
    ['I __ forget.', 'will not', "won't"],
    ['He __ coming either.', 'is not', "isn't"],
    // "it's" expands to BOTH "it is" and "it has" — ambiguous for the
    // "write the two words" kind, so this line is only ever a fill-blank item.
    // Replaced with an unambiguous I've -> I have pair instead.
    ['__ never seen anything like it.', 'I have', "I've"],
    ['You __ believe this!', 'will not', "won't"],
    ['__ always her turn!', 'it is', "it's"],
    ['__ snowing in the mountains.', 'it is', "it's"],
    ['Mum __ be late tonight.', 'will not', "won't"],
    ['__ ready to go?', 'are we', "we're"],
    ['The cat __ drunk all the milk.', 'has not', "hasn't"],
    ['__ snowing tomorrow.', 'it will', "it'll"]
];

// Plural possessives (T4C new area): owners that already end in s take the
// apostrophe AFTER the s. [plural owner, sentence with "__"] — the answer is
// the owner plus the trailing apostrophe.
const POSSESSIVE_PLURAL_ITEMS: [string, string][] = [
    ['the students', 'The students forgot __ homework.'],
    ['the babies', '__ toys are scattered on the rug.'],
    ['the dogs', 'The dogs wag __ tails at the gate.'],
    ['the teachers', '__ cars are parked in the staff bay.'],
    ['the children', 'The children packed __ bags on Friday.'],
    ['my cousins', '__ dog digs huge holes in the yard.'],
    ['the chickens', '__ coop needs a new roof.'],
    ['the neighbours', '__ garden is full of sunflowers.'],
    // T4C growth: more plural owners.
    ['the goats', '__ pen leans over the creek.'],
    ['the girls', 'The girls tied __ hair back before the race.'],
    ['the horses', '__ stalls were cleaned at dawn.'],
    ['my uncles', '__ boats are moored at the jetty.']
];

// CHECK items (T4C new family): is the apostrophe used correctly? Curated
// correct and incorrect lines — the child answers "correct" or "incorrect".
const APOSTROPHE_CHECKS: [string, string][] = [
    ["Thats my lunchbox.", 'incorrect'],
    ["That's my lunchbox.", 'correct'],
    ["The dog's bowl is full.", 'correct'],
    ["Its raining outside.", 'incorrect'],
    ["It's raining outside.", 'correct'],
    ["Sams bike is red.", 'incorrect'],
    ["Sam's bike is red.", 'correct'],
    ["The students homework is late.", 'incorrect'],
    ["The students' homework is late.", 'correct'],
    ["I havent finished yet.", 'incorrect'],
    ["I haven't finished yet.", 'correct'],
    ["Shes in the next room.", 'incorrect'],
    ["She's in the next room.", 'correct'],
    ["The team's new uniform looks great.", 'correct'],
    ["We didnt see the comet.", 'incorrect'],
    ["We didn't see the comet.", 'correct'],
    // T4C growth: more classic slips.
    ["We cant find it.", 'incorrect'],
    ["We can't find it.", 'correct'],
    ["I dont like spiders.", 'incorrect'],
    ["I don't like spiders.", 'correct'],
    ["The dog chased it's tail.", 'incorrect'],
    ["The dog chased its tail.", 'correct'],
    ["Theres the bus!", 'incorrect'],
    ["There's the bus!", 'correct']
];

// Apostrophes — SEVEN procedural kinds (upper primary):
//   0. contraction written answer: "Write the contraction for 'do not'."
//   1. contraction EXPAND written answer: "Write the two words for 'don't'."
//   2. contraction MC: pick the right contraction from 3 options
//   3. possession MC: pick the correctly punctuated possessive form
//      (Sam's / Sams' / Sams)
//   4. possession written answer: fill the possessive in the sentence
//   5. plural possession written answer: fill "the students'" in the sentence
//   6. CHECK: "Is the apostrophe used correctly in ...?" correct/incorrect
//
// NON-REPEATING SAMPLING: items are dealt from decks and every question
// passes through sampleUnique keyed on the printed prompt.
function generateApostrophe(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const contractionDeck = localDeck(rng, CONTRACTION_ITEMS);
    const possessiveDeck = localDeck(rng, POSSESSIVE_ITEMS);
    const pluralDeck = localDeck(rng, POSSESSIVE_PLURAL_ITEMS);
    const checkDeck = localDeck(rng, APOSTROPHE_CHECKS);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 6);
            if (kind === 0) {
                // Written contraction: "Write the contraction for 'do not'."
                const [, full, short] = contractionDeck.take();
                return { prompt: `Write the contraction for "${full}".`, answer: short };
            }
            if (kind === 1) {
                // Reverse direction: expand the contraction into two words.
                const [, full, short] = contractionDeck.take();
                return { prompt: `Write the two words for "${short}".`, answer: full };
            }
            if (kind === 2) {
                // Contraction MC: the right contraction beside two distractors
                // formed by dropping/relocating the apostrophe.
                const [sentence, , short] = contractionDeck.take();
                const noMark = short.replace("'", '');
                const wrongMark = noMark + "'";
                const shown = shuffleLocal(rng, [short, noMark, wrongMark]);
                return { prompt: `Which contraction fits: ${sentence} (${shown.join(', ')})`, answer: short };
            }
            if (kind === 3) {
                // Possession MC: correct 's form beside the two classic
                // errors (dropped apostrophe, misplaced plural apostrophe).
                // No bank owner ends in 's', so 's is always the right form.
                const [owner] = possessiveDeck.take();
                const cap = owner[0].toUpperCase() + owner.slice(1);
                const right = `${cap}'s`;
                const wrongPlural = `${cap}s`;
                const shown = shuffleLocal(rng, [right, wrongPlural, `${cap}s'`]);
                return { prompt: `Which shows that ${cap} owns something? (${shown.join(', ')})`, answer: right };
            }
            if (kind === 4) {
                // Possession written answer: fill the possessive into the line.
                // The parenthetical names only the OWNER — the child writes the
                // possessive form themselves ("(Sam)" -> "Sam's").
                const [owner, , sentence] = possessiveDeck.take();
                const answer = `${owner}'s`;
                return { prompt: `Fill in the missing word: ${sentence} (${owner})`, answer };
            }
            if (kind === 5) {
                // Plural possession: owners ending in s take ' AFTER the s.
                const [owner, sentence] = pluralDeck.take();
                return {
                    prompt: `Fill in the missing word: ${sentence} (${owner})`,
                    answer: `${owner}'`
                };
            }
            // CHECK: correct/incorrect judgement of a curated line.
            const [sentence, verdict] = checkDeck.take();
            return {
                prompt: `Is the apostrophe used correctly in this sentence? "${sentence}"`,
                answer: verdict
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn. T4C: 6 roomy rows/page.
export const apostropheSpec: WorksheetSpec = {
    id: 'apostrophe',
    label: 'Apostrophes',
    icon: "'",
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('apostrophe'),
    scope: () => "possessives & contractions",
    generate: generateApostrophe
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ApostropheWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(apostropheSpec);
}
