// ─────────────────────────────────────────────────────────────────────────────
// APOSTROPHES WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — apostrophes of possession and contraction).
//
// The dashboard loads this plugin by calling `ApostropheWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Apostrophes", glyph "'") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Apostrophes worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Possession items: [owner, thing, sentence with "__"] — the answer is the
// possessive form printed in the options. Owners are kid-level nouns.
const POSSESSIVE_ITEMS: [string, string, string][] = [
    ['Sam', 'bicycle', 'This is __ bicycle.'],
    ['Mia', 'pencil case', 'That is __ pencil case.'],
    ['the dog', 'kennel', 'The dog sleeps in __ kennel.'],
    ['Leo', 'hat', 'Is this __ hat?'],
    ['the teacher', 'desk', "The teacher's books sit on __ desk."],
    ['my sister', 'bike', '__ bike is red.'],
    ['Zoe', 'lunchbox', '__ lunchbox is on the shelf.'],
    ['the cat', 'bowl', 'Fill up __ bowl, please.'],
    ['Ben', 'shoes', 'Ben tied __ shoes.'],
    ['the girl', 'satchel', 'The girl carried __ satchel.'],
    ['my brother', 'ball', '__ ball is flat.'],
    ['Grandpa', 'glasses', 'These are __ glasses.'],
    ['our team', 'coach', '__ coach blew the whistle.'],
    ['the doctor', 'bag', 'The doctor packed __ bag.'],
    ['the bird', 'nest', 'The eggs are in __ nest.'],
    ['Max', 'football', 'Kick __ football over here.'],
    ['Ava', 'paintbrush', 'Ava washed __ paintbrush.'],
    ['the farmer', 'tractor', 'The farmer parked __ tractor.']
];

// Contractions: [sentence with "__", full expansion, contraction] — the child
// supplies the contraction (or picks it). Two-word pairs only, kid-level.
const CONTRACTION_ITEMS: [string, string, string][] = [
    ['__ are my friends.', 'you are', "you're"],
    ['I __ believe it!', 'do not', "don't"],
    ['__ is going to rain.', 'it is', "it's"],
    ['We __ late for school.', 'will not', "won't"],
    ['She __ finished her homework.', 'has not', "hasn't"],
    ['They __ coming to the party.', 'are not', "aren't"],
    ['He __ eaten his lunch.', 'has not', "hasn't"],
    ['__ was a great game.', 'it was', "it's"],
    ['I __ like spinach.', 'do not', "don't"],
    ['__ going to the library.', 'we are', "we're"],
    ['The dog __ stop barking.', 'did not', "didn't"],
    ['__ have a great holiday!', 'you will', "you'll"],
    ['I __ finished my book.', 'have not', "haven't"],
    ['__ not allowed in the pool.', 'is', "isn't"],
    ['She __ sing at the concert.', 'will not', "won't"],
    ['__ is time for lunch.', 'it is', "it's"],
    ['We __ seen that movie.', 'have not', "haven't"],
    ['He __ know the answer.', 'does not', "doesn't"]
];

// Apostrophes — FOUR procedural kinds (upper primary):
//   0. contraction written answer: expand the contraction context
//   1. contraction MC: pick the right contraction from 3 options
//   2. possession MC: pick the correctly punctuated possessive form
//      (Sam's / Sams' / Sams)
//   3. possession written answer: fill the possessive in the sentence
//
// NON-REPEATING SAMPLING: items are dealt from decks and every question
// passes through sampleUnique keyed on the printed prompt.
function generateApostrophe(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const contractionDeck = localDeck(rng, CONTRACTION_ITEMS);
    const possessiveDeck = localDeck(rng, POSSESSIVE_ITEMS);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 3);
            if (kind === 0) {
                // Written contraction: "Write the contraction for 'do not'."
                const [, full, short] = contractionDeck.take();
                return { prompt: `Write the contraction for "${full}".`, answer: short };
            }
            if (kind === 1) {
                // Contraction MC: the right contraction beside two distractors
                // formed by dropping/relocating the apostrophe.
                const [sentence, , short] = contractionDeck.take();
                const noMark = short.replace("'", '');
                const wrongMark = noMark + "'";
                const shown = shuffleLocal(rng, [short, noMark, wrongMark]);
                return { prompt: `Which contraction fits: ${sentence} (${shown.join(', ')})`, answer: short };
            }
            if (kind === 2) {
                // Possession MC: correct 's form beside the two classic
                // errors (dropped apostrophe, misplaced plural apostrophe).
                // No bank owner ends in 's', so 's is always the right form.
                const [owner] = possessiveDeck.take();
                const cap = owner[0].toUpperCase() + owner.slice(1);
                const right = `${cap}'s`;
                const wrongPlural = `${cap}s`;
                const shown = shuffleLocal(rng, [right, wrongPlural, `${cap}s'`]);
                return { prompt: `Which shows that ${cap} owns something? (${shown.join(', ')})`, answer: right };
            }
            // Possession written answer: fill the possessive into the line.
            // The parenthetical names only the OWNER — the child writes the
            // possessive form themselves ("(Sam)" -> "Sam's").
            const [owner, , sentence] = possessiveDeck.take();
            const answer = `${owner}'s`;
            return { prompt: `Fill in the missing word: ${sentence} (${owner})`, answer };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn.
export const apostropheSpec: WorksheetSpec = {
    id: 'apostrophe',
    label: 'Apostrophes',
    icon: "'",
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('apostrophe'),
    scope: () => "possessives & contractions",
    generate: generateApostrophe
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ApostropheWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(apostropheSpec);
}
