// ─────────────────────────────────────────────────────────────────────────────
// BEGINNING SOUNDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `BeginningSoundsWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Beginning Sounds", glyph "♪") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Beginning Sounds worksheet without affecting the framework or
// any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { wordSet } from './words';

// Beginning sounds: "which letter does <word> start with?" — the phonemic
// awareness task (letter, not letter-name, kept simple at these word lengths).
//
// NON-REPEATING SAMPLING: words are dealt from a deck, so every word in the
// grade set is asked once before any repeats (the pool IS the fact space —
// ~45-61 distinct questions per tier).
function generateSounds(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = wordSet(caps.wordTier).filter((w) => w.length >= 3);
    const wordDeck = createDeck(rng, pool);
    return sampleUnique(
        count,
        () => {
            const word = wordDeck.take();
            return { prompt: `Which letter does "${word}" start with?`, answer: word[0] };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const soundsSpec: WorksheetSpec = {
    id: 'sounds',
    label: 'Beginning Sounds',
    icon: '♪',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('sounds'),
    scope: (grade: GradeConfig) => `beginnings, word set ${grade.caps.wordTier}`,
    generate: generateSounds
};

// The plugin: a function the dashboard calls with its framework bundle.
export function BeginningSoundsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(soundsSpec);
}
