// ─────────────────────────────────────────────────────────────────────────────
// BLENDING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `BlendingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Blending", glyph "ab") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Blending worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { wordSet, shuffleWords } from './words';

// Blending: see the letters, write the word. SEVEN procedural forms per word:
//   - all letters shown       ("what word is s u n?")
//   - one blank at ANY position ("finish the word: s u __")
//   - two blanks at once      ("finish the word: __ u __")
//   - scrambled letters       ("unscramble: n u s")
//   - backwards reading       ("what word is 'nus' backwards?")
// Only words of 6 letters or fewer are used so a whole line stays on one row
// in the two-column grid.
//
// The old four-form generator cycled after ~180-250 questions (forms x pool).
// Blank positions, blank pairs and scramble permutations multiply the space
// per word ~20x, so the sheet deals fresh questions past 100 pages.
//
// NON-REPEATING SAMPLING: words are dealt from a deck and every question
// passes through sampleUnique keyed on the printed prompt.
function generateBlend(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = wordSet(caps.wordTier).filter((w) => w.length >= 3 && w.length <= 6);
    const wordDeck = createDeck(rng, pool);
    // Print `letters` with every position in `blanks` replaced by "__".
    const withBlanks = (letters: string[], blanks: number[]) =>
        letters.map((ch, i) => (blanks.includes(i) ? '__' : ch)).join(' ');
    // Two distinct blank positions for the two-blank form.
    const twoBlanks = (len: number): number[] => {
        const i = rng.int(0, len - 1);
        let j = rng.int(0, len - 1);
        let guard = 0;
        while (j === i && guard < 12) {
            guard++;
            j = rng.int(0, len - 1);
        }
        if (j === i) j = (i + 1) % len;
        return [i, j];
    };
    return sampleUnique(
        count,
        () => {
            const word = wordDeck.take();
            const letters = word.split('');
            const r = rng.next();
            if (r < 0.15) {
                // All letters shown, space-separated: "What word is: s u n?"
                return { prompt: `What word is: ${letters.join(' ')}?`, answer: word };
            }
            if (r < 0.45) {
                // One blank at a random position (edges included):
                // "Finish the word: s u __".
                const pos = rng.int(0, letters.length - 1);
                return { prompt: `Finish the word: ${withBlanks(letters, [pos])}`, answer: word };
            }
            if (r < 0.65) {
                // Two blanks at once: "Finish the word: __ u __".
                return { prompt: `Finish the word: ${withBlanks(letters, twoBlanks(letters.length))}`, answer: word };
            }
            if (r < 0.8) {
                // Scrambled letters: "Unscramble the letters: n u s" — a
                // different scramble of the same word is a different question
                // (and never printed in the correct order, see shuffleWords).
                const scrambled = shuffleWords(rng, letters);
                return { prompt: `Unscramble the letters: ${scrambled.join(' ')}`, answer: word };
            }
            // Backwards reading: "What word is 'sun' spelled backwards?"
            return {
                prompt: `What word is "${word.split('').reverse().join('')}" spelled backwards?`,
                answer: word
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const blendSpec: WorksheetSpec = {
    id: 'blend',
    label: 'Blending',
    icon: 'ab',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('blend'),
    scope: (grade: GradeConfig) => `letters, word set ${grade.caps.wordTier}`,
    generate: generateBlend
};

// The plugin: a function the dashboard calls with its framework bundle.
export function BlendingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(blendSpec);
}
