// ─────────────────────────────────────────────────────────────────────────────
// BLENDING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `BlendingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Blending", glyph "ab") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Blending worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { wordSet } from './words';

// Blending: see the letters, write the word. Three forms — all letters shown
// ("what word is s u n?"), or the first/last letter left as a blank
// ("finish the word: __ u n"). Only words of 6 letters or fewer are used so a
// whole line stays on one row in the two-column grid.
function generateBlend(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const pool = wordSet(caps.wordTier).filter((w) => w.length >= 3 && w.length <= 6);
    for (let i = 0; i < count; i++) {
        const word = rng.pick(pool);
        const r = rng.next();
        if (r < 0.4) {
            // All letters shown, space-separated: "What word is: s u n?"
            out.push({ prompt: `What word is: ${word.split('').join(' ')}?`, answer: word });
        } else if (r < 0.7) {
            // First letter blanked: "Finish the word: __ u n".
            out.push({ prompt: `Finish the word: __ ${word.slice(1).split('').join(' ')}`, answer: word });
        } else {
            // Last letter blanked: "Finish the word: s u __".
            out.push({ prompt: `Finish the word: ${word.slice(0, -1).split('').join(' ')} __`, answer: word });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const blendSpec: WorksheetSpec = {
    id: 'blend',
    label: 'Blending',
    icon: 'ab',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('blend'),
    scope: (grade: GradeConfig) => `letters, word set ${grade.caps.wordTier}`,
    generate: generateBlend
};

// The plugin: a function the dashboard calls with its framework bundle.
export function BlendingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(blendSpec);
}
