// ─────────────────────────────────────────────────────────────────────────────
// CAPITAL LETTERS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `CapitalLettersWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Capital Letters", glyph "A!") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Capital Letters worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { wordSet, COMMON_WORDS } from './words';

// Capital letters: start a lower-case word with a capital letter.
//
// NON-REPEATING SAMPLING: the pool is the grade word set PLUS the common-words
// bank (~300 real words at Year 1+) dealt from a deck, so every word is
// capitalised once before any repeats.
function generateCapital(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = [...new Set([...wordSet(caps.wordTier), ...COMMON_WORDS])];
    const wordDeck = createDeck(rng, pool);
    return sampleUnique(
        count,
        () => {
            const word = wordDeck.take();
            return { prompt: `Write it with a capital letter: ${word}`, answer: `${word[0].toUpperCase()}${word.slice(1)}` };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const capitalSpec: WorksheetSpec = {
    id: 'capital',
    label: 'Capital Letters',
    icon: 'A!',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('capital'),
    scope: () => 'word starts',
    generate: generateCapital
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CapitalLettersWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(capitalSpec);
}
