// ─────────────────────────────────────────────────────────────────────────────
// COMMA LISTS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — commas to separate items in a list; AU convention:
// no comma before 'and').
//
// The dashboard loads this plugin by calling `CommaListWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Comma Lists", glyph ",") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Comma Lists worksheet without affecting the framework or any
// other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 16 rows to 6
// roomy prose rows. The themed banks grew from 6 to 10 and the openers from
// 8 to 12 (opener→theme alignment kept, so every list reads sensibly), and
// item selection moved from CONTIGUOUS slices to any theme subset — the real
// reason the old space was only 450 lines. Two new families joined: a
// COMPOSE-your-own-list task (open-ended: the key models one list and accepts
// any sensible one) and a correct/incorrect CHECK. Also FIXED: the rewrite
// answer used to lower-case the sentence opener ("at the shop I bought...")
// — the model answer now keeps the printed capitalisation.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// List-noun banks by theme — a question draws ALL items from one theme so the
// assembled list always reads sensibly ("apples, bananas and pears" not
// "apples, Tuesday and ladder"). Grown from 6 to 10 themes for T4C.
const LIST_THEMES: readonly (readonly string[])[] = [
    ['apples', 'bananas', 'pears', 'grapes', 'oranges', 'mangoes'],
    ['cricket', 'swimming', 'netball', 'soccer', 'athletics', 'tennis'],
    ['pencils', 'rulers', 'erasers', 'paintbrushes', 'scissors', 'gluesticks'],
    ['Sydney', 'Brisbane', 'Perth', 'Adelaide', 'Darwin', 'Hobart'],
    ['kangaroos', 'koalas', 'wombats', 'emus', 'possums', 'platypuses'],
    ['reading', 'writing', 'spelling', 'counting', 'singing', 'dancing'],
    ['carrots', 'potatoes', 'pumpkins', 'spinach', 'corn', 'peas'],
    ['guitars', 'pianos', 'violins', 'drums', 'flutes', 'trumpets'],
    ['red', 'blue', 'green', 'yellow', 'purple', 'orange'],
    ['nurse', 'teacher', 'farmer', 'chef', 'pilot', 'vet']
] as const;
// Kid-friendly theme labels for the open-ended compose task.
const THEME_LABELS: readonly string[] = [
    'fruits', 'sports', 'stationery', 'cities', 'native animals',
    'class activities', 'vegetables', 'instruments', 'colours', 'jobs'
] as const;

// Sentence openers that take a 3–5 item list ("At the shop I bought __").
// Grown from 8 to 12 for T4C.
const LIST_OPENERS: readonly string[] = [
    'At the shop I bought', 'In my school bag I keep', 'My favourite sports are',
    'On our holiday we visited', 'At the zoo we saw', 'In class today we practised',
    'For lunch I packed', 'In the garden we planted', 'My crayon box has',
    'In the band we play', 'My dream jobs are', 'At the party we ate'
] as const;
// Where each opener's items come from (index into LIST_THEMES), aligned.
const OPENER_THEMES: readonly number[] = [0, 2, 1, 3, 4, 5, 6, 6, 8, 7, 9, 0] as const;

// Comma lists — FIVE procedural kinds:
//   0. EDIT: "rewrite the list with commas" (items given space-separated;
//      the answer is the comma-joined line WITH the printed capitalisation)
//   1. MC: which list is punctuated correctly (commas between items, none
//      after 'and')
//   2. count: "how many items are in this list?" (comma-separated line)
//   3. CHECK: "Is this list punctuated correctly?" correct/incorrect
//   4. COMPOSE: "Write your own list of three <theme> separated by commas."
//      (open-ended — the key models one list and accepts any sensible one)
//
// NON-REPEATING SAMPLING: opener x item-SUBSET cross-products keep the space
// past 100 pages (any 3–5 of the 6 theme items, kept in theme order so the
// list reads naturally); every question passes through sampleUnique keyed on
// the printed prompt.
function generateCommaList(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    // Draw 3–5 items from one theme as a random subset (sorted back into
    // theme order) — the subset choice is the randomness, and every subset
    // of a theme reads sensibly. Index order is Fisher–Yates shuffled with
    // the shared Rng, so the draw is reproducible from the document seed.
    const drawItems = (theme: readonly string[]) => {
        const len = rng.int(3, Math.min(5, theme.length));
        const idx = theme.map((_, i) => i);
        for (let i = idx.length - 1; i > 0; i--) {
            const j = rng.int(0, i);
            [idx[i], idx[j]] = [idx[j], idx[i]];
        }
        return idx.slice(0, len).sort((a, b) => a - b).map((i) => theme[i]);
    };
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 4);
            const openerIdx = rng.int(0, LIST_OPENERS.length - 1);
            const theme = LIST_THEMES[OPENER_THEMES[openerIdx]];
            const items = drawItems(theme);
            if (kind === 0) {
                // Space-separated raw list -> the child adds the commas.
                // FIX: the answer keeps the opener's printed capitalisation
                // (it used to lower-case it, contradicting the prompt).
                const joined = items.join(', ');
                return {
                    prompt: `Rewrite with commas: ${LIST_OPENERS[openerIdx]} ${items.join(' ')}.`,
                    answer: `${LIST_OPENERS[openerIdx]} ${joined}.`
                };
            }
            if (kind === 1) {
                // MC: correct list beside two mis-punctuated variants.
                const right = `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
                const noCommas = items.join(' ');
                const extraAnd = items.join(', and ');
                const shown = shuffleLocal(rng, [right, noCommas, extraAnd]);
                return { prompt: `Which list uses commas correctly? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 2) {
                // Count the items in the printed comma list.
                const joined = items.join(', ');
                return { prompt: `How many items are in this list? ${joined}`, answer: `${items.length}` };
            }
            if (kind === 3) {
                // CHECK: half the printed lists are punctuated correctly, half
                // carry the classic missing-comma error.
                const correct = rng.next() < 0.5;
                const line = correct
                    ? `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`
                    : items.join(' ');
                return {
                    prompt: `Is this list punctuated correctly? "${line}"`,
                    answer: correct ? 'correct' : 'incorrect'
                };
            }
            // OPEN-ENDED compose: the key models one list from the theme and
            // explicitly accepts any sensible list of three.
            const themeIdx = rng.int(0, LIST_THEMES.length - 1);
            const example = drawItems(LIST_THEMES[themeIdx]).slice(0, 3);
            return {
                prompt: `Write your own list of three ${THEME_LABELS[themeIdx]} separated by commas.`,
                answer: `Example: ${example.slice(0, -1).join(', ')} and ${example[example.length - 1]} (any sensible list is correct)`
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn. T4C: 6 roomy rows/page.
export const commaSpec: WorksheetSpec = {
    id: 'comma',
    label: 'Comma Lists',
    icon: ',',
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('comma'),
    scope: () => 'commas in lists',
    generate: generateCommaList
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CommaListWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(commaSpec);
}
