// ─────────────────────────────────────────────────────────────────────────────
// COMMA LISTS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — commas to separate items in a list, serial comma
// before 'and' introduced in Y3, reinforced through Y6).
//
// The dashboard loads this plugin by calling `CommaListWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Comma Lists", glyph ",") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Comma Lists worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// List-noun banks by theme — a question draws ALL items from one theme so the
// assembled list always reads sensibly ("apple, banana and pear" not
// "apple, Tuesday and ladder").
const LIST_THEMES: readonly (readonly string[])[] = [
    ['apples', 'bananas', 'pears', 'grapes', 'oranges', 'mangoes'],
    ['cricket', 'swimming', 'netball', 'soccer', 'athletics', 'tennis'],
    ['pencils', 'rulers', 'erasers', 'paintbrushes', 'scissors', 'gluesticks'],
    ['Sydney', 'Brisbane', 'Perth', 'Adelaide', 'Darwin', 'Hobart'],
    ['kangaroos', 'koalas', 'wombats', 'emus', 'possums', 'platypuses'],
    ['reading', 'writing', 'spelling', 'counting', 'singing', 'dancing']
] as const;

// Sentence openers that take a 3–5 item list ("At the shop I bought __").
const LIST_OPENERS: readonly string[] = [
    'At the shop I bought', 'In my school bag I keep', 'My favourite sports are',
    'On our holiday we visited', 'At the zoo we saw', 'In class today we practised',
    'For lunch I packed', 'In the garden we planted'
] as const;
// Where each opener's items come from (index into LIST_THEMES), aligned.
const OPENER_THEMES: readonly number[] = [0, 2, 1, 3, 4, 5, 0, 5] as const;

// Comma lists — THREE procedural kinds:
//   0. written answer: "rewrite the list with commas" (items given space-
//      separated; the answer is the comma-joined serial form)
//   1. MC: which list is punctuated correctly (commas between items, none
//      after 'and')
//   2. count: "how many items are in this list?" (comma-separated line)
//
// NON-REPEATING SAMPLING: opener x item-subset cross-products keep the space
// past 100 pages; every question passes through sampleUnique keyed on prompt.
function generateCommaList(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 2);
            // 3–5 items drawn from one theme, in theme order (lists read
            // naturally); the subset choice is the randomness.
            const openerIdx = rng.int(0, LIST_OPENERS.length - 1);
            const theme = LIST_THEMES[OPENER_THEMES[openerIdx]];
            const listLen = rng.int(3, Math.min(5, theme.length));
            const start = rng.int(0, theme.length - listLen);
            const items = theme.slice(start, start + listLen);
            if (kind === 0) {
                // Space-separated raw list -> the child adds the commas.
                const joined = items.join(', ');
                return {
                    prompt: `Rewrite with commas: ${LIST_OPENERS[openerIdx]} ${items.join(' ')}.`,
                    answer: `${LIST_OPENERS[openerIdx].toLowerCase()} ${joined}`
                };
            }
            if (kind === 1) {
                // MC: correct serial list beside two mis-punctuated variants.
                const right = `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
                const noCommas = items.join(' ');
                const extraAnd = items.join(', and ');
                const shown = shuffleLocal(rng, [right, noCommas, extraAnd]);
                return { prompt: `Which list uses commas correctly? (${shown.join(' / ')})`, answer: right };
            }
            // Count the items in the printed comma list.
            const joined = items.join(', ');
            return { prompt: `How many items are in this list? ${joined}`, answer: `${items.length}` };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn.
export const commaSpec: WorksheetSpec = {
    id: 'comma',
    label: 'Comma Lists',
    icon: ',',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('comma'),
    scope: () => 'commas in lists',
    generate: generateCommaList
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CommaListWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(commaSpec);
}
