// ─────────────────────────────────────────────────────────────────────────────
// READING COMPREHENSION WORKSHEET — a self-contained dashboard plugin
// (upper primary: Year 3–6; ACARA v9-informed — Y3 AC9E3LY05/LE03,
// Y4 AC9E4LY05/LE03, Y5 AC9E5LY04/LY05/LE03, Y6 AC9E6LY03/LY04/LY05/LE03).
//
// The dashboard loads this plugin by calling `ComprehensionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Reading Comprehension", glyph "☰") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Reading Comprehension worksheet without affecting the framework
// or any other plugin.
//
// T5 DESIGN NOTES (the strong deficit this family fills):
//   * ORIGINAL passages only — hand-written, Australian settings, respectful
//     references (no fabricated Indigenous stories, no attributed authors).
//   * PASSAGE + QUESTIONS PRINT AS ONE BLOCK (single problem row): the
//     passage stays physically with its questions on the page, and because
//     each row is a DIFFERENT deck-dealt passage, the same misleading text is
//     never repeated above every question.
//   * Every passage carries exactly three questions in a scaffolded order:
//     a) LITERAL (find it), b) INFER (read between the lines), c) EVIDENCE /
//     EVALUATE (quote or judge). The inferential answer is marking guidance
//     ("any sensible answer supported by the text is accepted") — never a
//     false single correct answer.
//   * YEAR PROGRESSION is EXPLICIT via caps.level (framework/grades.ts): each
//     year draws its OWN passage bank — Y3 short narratives/facts, Y4
//     visualise-predict-evaluate, Y5 scan-compare-evaluate + viewpoint,
//     Y6 analyse style/bias/compare sources. Year 5 and Year 6 banks are
//     different texts, not a re-skin.
//   * A4-SAFE: perPage = 1 — one full passage task per page (the framework
//     grid stretches the single row to the page), so long Y6 passages can
//     never overflow, and each question gets a real ruled writing line
//     (a run of "__" blanks renders on its own line — see types.ts).
//   * Student print is answer-free by default; the teacher answer key
//     (session.answerKey) prints the a/b/c guidance lines.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// One comprehension question. `kind` documents the scaffold step for the
// next agent: literal = find, infer = read between the lines, evidence =
// quote/judge. `a` is the model answer; for infer questions the generator
// appends the acceptance note.
type CompQuestion = { q: string; a: string; kind: 'literal' | 'infer' | 'evidence' };

// A passage block: title + text + its three scaffolded questions. The whole
// block prints as ONE problem row so the passage never separates from (or
// repeats for) its questions.
type Passage = { title: string; text: string; questions: [CompQuestion, CompQuestion, CompQuestion] };

// A ruled WRITING line: ten "__" tokens render as ten connected fill-in
// blanks on one baseline (PrintableSheet PromptText splits prompts on "__").
const RULE = '__ __ __ __ __ __ __ __ __ __';

// ── Year 3 bank (AC9E3LY05 literal/inferred; AC9E3LE03 character & setting) ──
// Short concrete narratives + one information text; literal answer is always
// findable word-for-word, infer answers stay text-supported.
const PASSAGES_Y3: readonly Passage[] = [
    {
        title: "Sam's Sandcastle",
        text: 'Sam dug a big hole in the sand at Broadbeach. He packed wet sand into a bucket and turned it over to make a tower. Just as he placed the last shell on top, a wave rushed in and knocked the tower down. Sam laughed and reached for his bucket again.',
        questions: [
            { q: 'Where did Sam build his sandcastle?', a: 'At Broadbeach.', kind: 'literal' },
            { q: 'How did Sam feel when the wave knocked his tower down? How do you know?', a: 'Cheerful or undaunted — the text says he laughed and started again', kind: 'infer' },
            { q: 'Which words show the wave arrived suddenly?', a: '"a wave rushed in and knocked the tower down"', kind: 'evidence' }
        ]
    },
    {
        title: 'The Class Hamster',
        text: 'Our class hamster is called Peanut. Every Monday we fill her food bowl and change her water. On Fridays we let her run around the classroom for twenty minutes. She always hides under the reading-corner mat, where it is dark and quiet.',
        questions: [
            { q: 'On which day does Peanut run around the classroom?', a: 'On Fridays.', kind: 'literal' },
            { q: 'Why do you think Peanut hides under the mat?', a: 'It feels safe there — the mat is dark and quiet', kind: 'infer' },
            { q: 'Which words tell you the class looks after Peanut every week?', a: '"Every Monday" and "On Fridays"', kind: 'evidence' }
        ]
    },
    {
        title: 'Why Wombats Dig',
        text: 'Wombats are small, strong animals that dig long tunnels under the ground. Their tunnels stay cool in the hot Australian summer and warm on cold nights. Wombats dig with their sharp claws and push the soil aside with their tough noses.',
        questions: [
            { q: 'What do wombats use to dig with?', a: 'Their sharp claws.', kind: 'literal' },
            { q: 'Why is it useful that the tunnels stay cool and warm?', a: 'The tunnels keep wombats comfortable through hot days and cold nights', kind: 'infer' },
            { q: 'Which words show the tunnels help in BOTH heat and cold?', a: '"cool in the hot Australian summer and warm on cold nights"', kind: 'evidence' }
        ]
    },
    {
        title: 'Biscuit Learns a Trick',
        text: 'Grandma threw the ball and her dog Biscuit raced after it. "Bring it back!" she called. Biscuit picked up the ball, trotted to the water tank and dropped it in. Grandma giggled. "Good try, Biscuit," she said.',
        questions: [
            { q: 'What did Biscuit do with the ball?', a: 'He dropped it in the water tank.', kind: 'literal' },
            { q: 'Was Grandma angry at the end? How do you know?', a: 'No — she giggled and said "Good try"', kind: 'infer' },
            { q: 'Which words show Biscuit really tried to help?', a: '"raced after it" and "picked up the ball"', kind: 'evidence' }
        ]
    },
    {
        title: 'The School Garden',
        text: 'In Term 2 our year planted tomato seedlings in the school garden. We dug small holes, dropped in each seedling and patted the soil around it. Every lunchtime one student from each class watered them. By Week 8 we were picking tomatoes for our sandwiches.',
        questions: [
            { q: 'What did the class plant in the garden?', a: 'Tomato seedlings.', kind: 'literal' },
            { q: 'What made the seedlings grow into tomatoes by Week 8?', a: 'The students watered them every lunchtime', kind: 'infer' },
            { q: 'Which words show the hard work paid off?', a: '"By Week 8 we were picking tomatoes for our sandwiches"', kind: 'evidence' }
        ]
    },
    {
        title: 'Rain Over the Range',
        text: 'Dark clouds gathered over the range after lunch. First a cool wind turned the leaves of the gum trees silver. Then fat drops of rain began to patter on the tin roof of the shed. Within minutes the dry creek bed was running brown and fast.',
        questions: [
            { q: 'Where were the clouds gathering?', a: 'Over the range.', kind: 'literal' },
            { q: 'Why was the creek bed running brown and fast?', a: 'The heavy rain washed soil into the dry creek bed', kind: 'infer' },
            { q: 'Which words let you HEAR the rain?', a: '"fat drops of rain began to patter"', kind: 'evidence' }
        ]
    }
] as const;

// ── Year 4 bank (AC9E4LY05 visualise/predict/monitor/evaluate evidence;
//    AC9E4LE03 plot tension) ──────────────────────────────────────────────────
// Longer narratives with a turning point + staged information texts; evidence
// questions ask for the detail that justifies a judgement.
const PASSAGES_Y4: readonly Passage[] = [
    {
        title: 'The Lost Bumper Sticker',
        text: 'Zoe checked her bike basket three times. The bright orange "Share the Path" sticker was gone. She retraced her ride — the bridge, the park, the shops — asking each person she passed. At the café her mum pointed at the strap of Zoe\'s backpack. The sticker had flapped all the way home, stuck there, and kept its colour in the sun.',
        questions: [
            { q: 'What colour was the sticker?', a: 'Bright orange.', kind: 'literal' },
            { q: 'Why did Zoe retrace her ride?', a: 'To work out where the sticker could have fallen off', kind: 'infer' },
            { q: 'Which words show the sticker survived the whole ride?', a: '"flapped all the way home, stuck there, and kept its colour"', kind: 'evidence' }
        ]
    },
    {
        title: 'How Bees Make Honey',
        text: 'A honeybee gathers nectar from flowers and stores it in a special honey stomach. Back at the hive, worker bees pass the nectar from bee to bee, then spread it in thin cells and fan it with their wings. As the water evaporates, the nectar thickens into honey, which the bees seal under a lid of wax.',
        questions: [
            { q: 'Where does a honeybee store the nectar it gathers?', a: 'In a special honey stomach.', kind: 'literal' },
            { q: 'Why do the bees fan the nectar with their wings?', a: 'Fanning evaporates the water so the nectar thickens into honey', kind: 'infer' },
            { q: 'Which words show the honey is stored safely?', a: '"seal under a lid of wax"', kind: 'evidence' }
        ]
    },
    {
        title: 'Under the Ghost Gum',
        text: 'Camp was quiet except for the crackle of the fire. High in the ghost gum, a kookaburra let out its laughing call, and the darkness seemed bigger afterwards. I pulled my swag tighter. Then Mum began to play her concertina, and one by one we crept closer to the light and the music.',
        questions: [
            { q: 'What sound did the kookaburra make?', a: 'Its laughing call.', kind: 'literal' },
            { q: 'How do the writer\'s feelings change during the passage?', a: 'From uneasy (pulling the swag tighter) to comforted by the family and music', kind: 'infer' },
            { q: 'Which words build the uneasy mood at the start?', a: '"quiet except for the crackle of the fire" and "the darkness seemed bigger"', kind: 'evidence' }
        ]
    },
    {
        title: 'The Silver Balloon',
        // T9: the price is now an explicit literal fact ("Two dollars"), so
        // the a) question has one unambiguous findable answer (the old "One
        // more dollar and it's yours" + "exactly enough" pair was ambiguous).
        text: 'At the school fete a silver balloon bobbed on the end of a string beside Raj\'s hand. "Two dollars and it\'s yours," said the stallholder. Raj counted his coins twice — he had exactly two dollars. As he reached for the string, a gust snatched the balloon up, up, and over the oval fence. Raj watched it shrink to a silver dot, then turned back to the stall. "I\'ll save for the next one," he said.',
        questions: [
            { q: 'How much did the stallholder ask for the balloon?', a: 'Two dollars.', kind: 'literal' },
            { q: 'What does Raj\'s last sentence show about him?', a: 'He is resilient and hopeful — he plans to try again instead of giving up', kind: 'infer' },
            { q: 'Which words show the balloon was lost very quickly?', a: '"a gust snatched the balloon up, up, and over the oval fence"', kind: 'evidence' }
        ]
    },
    {
        title: 'Life on a Wheat Farm',
        text: 'On a wheat farm in the Western District, the year turns around the seasons. In autumn the paddocks are ploughed and seeded. Winter rain keeps the young wheat green until the hot, dry days of summer, when harvesters roll through the golden paddocks day and night. After harvest the stubble rests, and the cycle begins again.',
        questions: [
            { q: 'When are the paddocks ploughed and seeded?', a: 'In autumn.', kind: 'literal' },
            { q: 'Why do the harvesters work day and night in summer?', a: 'The dry harvesting window is short, so the wheat must be cut quickly', kind: 'infer' },
            { q: 'Which words show the farm year repeats itself?', a: '"the cycle begins again"', kind: 'evidence' }
        ]
    },
    {
        title: 'Kite Day at the Reserve',
        text: 'The wind was perfect for kites. Mei\'s dragon kite climbed wobbly, then caught a strong gust and soared. "Let out more string!" called her brother from the hill. The string hummed. Suddenly the line went slack — the kite had looped into a neighbouring tree. It took a football, a jump and a polite apology to free it.',
        questions: [
            { q: 'What happened to the kite suddenly?', a: 'It looped into a neighbouring tree.', kind: 'literal' },
            { q: 'What does "the string hummed" tell the reader?', a: 'The kite was pulling hard, flying high in strong wind', kind: 'infer' },
            { q: 'Which words show getting the kite down needed more than one person?', a: '"It took a football, a jump and a polite apology"', kind: 'evidence' }
        ]
    }
] as const;

// ── Year 5 bank (AC9E5LY04 skimming/scanning, LY05 evaluate/compare;
//    AC9E5LE03 first/third-person viewpoint) ─────────────────────────────────
// Persuasive, informational and first-person viewpoint texts; literal
// questions demand scanning, evidence questions ask for the phrase that
// carries a judgement.
const PASSAGES_Y5: readonly Passage[] = [
    {
        title: 'Should Students Have a Longer Recess?',
        text: 'Students rush through lunch when recess is short. A longer recess would give everyone time to eat properly, move around and sort out playground squabbles before class. Some teachers worry that more play means less learning time, but research on brain breaks suggests the opposite: students concentrate better after real breaks. Our school council should trial a thirty-minute recess for one term and measure the difference.',
        questions: [
            { q: 'Scan the text: what length of recess does the writer suggest?', a: 'A thirty-minute recess (for one term).', kind: 'literal' },
            // T9: was a second LITERAL question (breaking the literal→infer→
            // evidence scaffold); now genuinely inferential — the answer is
            // implied by the trial-and-measure wording, not quoted.
            { q: 'Why does the writer suggest a TRIAL rather than changing recess permanently right away?', a: 'A trial lets the school test the idea and measure the difference before committing to a permanent change', kind: 'infer' },
            { q: 'Does the writer support or oppose the trial, and what evidence do they use?', a: 'Support — they cite research on brain breaks showing students concentrate better after real breaks', kind: 'evidence' }
        ]
    },
    {
        title: 'The Snowy River',
        text: 'The Snowy River begins as snow high in the Australian Alps. Through spring it gathers speed down granite slopes, forcing through gorges it has carved over thousands of years. Downstream, part of its water has been turned into electricity by human engineering — a fact that still sparks debate between those who value wild rivers and those who value the power they provide.',
        questions: [
            { q: 'Where does the Snowy River begin?', a: 'As snow high in the Australian Alps.', kind: 'literal' },
            { q: 'What debate does the river spark?', a: 'Between keeping rivers wild and using their water for electricity', kind: 'infer' },
            { q: 'Which words show the river shaped its own valley?', a: '"gorges it has carved over thousands of years"', kind: 'evidence' }
        ]
    },
    {
        title: 'Designing a Bushfire-Resistant Town',
        text: 'Planners who design new towns in bushfire zones think in layers. First, wide spaces called asset protection zones separate houses from dense bush. Next, roads are laid out so fire trucks can enter from two directions. Finally, houses use non-flammable cladding and fine mesh over every vent. No single measure is perfect, but together they give a town a fighting chance.',
        questions: [
            { q: 'List the three layers in the order the text gives them.', a: 'Asset protection zones; two-way roads for fire trucks; non-flammable cladding and mesh over vents.', kind: 'literal' },
            { q: 'Why are two-way roads important in a bushfire town?', a: 'If one route is blocked by fire, trucks can still get in another way', kind: 'infer' },
            { q: 'Which sentence shows the writer is being realistic rather than over-promising?', a: '"No single measure is perfect, but together they give a town a fighting chance."', kind: 'evidence' }
        ]
    },
    {
        title: "My Grandma's Wireless",
        text: 'Every Sunday my grandma polished her wireless with a soft cloth, as if it were a jewel. She tuned it slowly, listening past the crackle until the voices came clear. "Patience finds the signal," she told me. When she passed the cloth to my hands one afternoon, I understood that the radio was never really about the news. It was about the hour we shared.',
        questions: [
            { q: 'What did Grandma do every Sunday?', a: 'She polished her wireless and tuned it slowly.', kind: 'literal' },
            { q: 'What did the radio really mean to the writer?', a: 'The shared time with Grandma, not the news itself', kind: 'infer' },
            { q: 'Which words show Grandma treated the wireless with great care?', a: '"polished her wireless with a soft cloth, as if it were a jewel"', kind: 'evidence' }
        ]
    },
    {
        title: 'The Platypus Puzzle',
        text: 'When Europeans first saw a platypus specimen, naturalists suspected a hoax — a duck\'s beak sewn onto a furry body. It is no hoax: the platypus lays eggs, sweats milk (it has no teats) and hunts by electroreception, sensing the tiny electric fields of its prey. Australia\'s oddities remind us that nature writes the field guide, not people.',
        questions: [
            { q: 'What did the early naturalists suspect about the specimen?', a: 'That it was a hoax — a beak sewn onto a furry body.', kind: 'literal' },
            { q: 'What does "nature writes the field guide, not people" mean?', a: 'Animals can surprise human categories — our rules about nature are not the final word', kind: 'infer' },
            // T9: was a third LITERAL question (list the three facts), which
            // broke the literal→infer→evidence scaffold; now an evidence
            // question quoting the text.
            { q: 'Which words show the platypus looked so strange that experts doubted it was real?', a: '"naturalists suspected a hoax — a duck\'s beak sewn onto a furry body"', kind: 'evidence' }
        ]
    },
    {
        title: 'Buses, Bikes and Footpaths',
        text: 'Our street council claims the new bike lane will "transform travel". Look at the numbers: bus patronage fell the year the lane was built, because buses were stuck in the same traffic the lane was meant to escape. A bike lane helps when it joins a connected network; painted alone onto a jammed road, it is a promise nobody can keep.',
        questions: [
            { q: 'According to the numbers, what happened to bus patronage?', a: 'It fell the year the lane was built.', kind: 'literal' },
            { q: 'What condition does the writer set for a bike lane to actually help?', a: 'It must join a connected network of lanes', kind: 'infer' },
            { q: 'Which phrase shows the writer doubts the council, and why?', a: '"a promise nobody can keep" (or the quoted "transform travel") — it frames the council\'s claim as unrealistic', kind: 'evidence' }
        ]
    }
] as const;

// ── Year 6 bank (AC9E6LY03 audience influence/text analysis, LY04 select/
//    navigate/evaluate, LY05 compare sources; AC9E6LE03 author's style,
//    LE04 sound & imagery) ───────────────────────────────────────────────────
// Analysis-grade texts: bias, tone, two-source comparison and original
// poetry. Questions appraise HOW a text works, not just what it says.
const PASSAGES_Y6: readonly Passage[] = [
    {
        title: 'The Price of a Reef Visit',
        text: 'Tour operators on the Great Barrier Reef insist that every visitor dollar funds conservation. That claim deserves scrutiny. Monitoring fees do reach research programs, yet marketing budgets often grow faster than restoration grants. The fairer question is not whether tourists should pay, but how their money is spent — and whether the companies charging the most are the ones giving the reef the best chance.',
        questions: [
            { q: 'What claim is the writer examining?', a: 'The operators\' claim that every visitor dollar funds conservation.', kind: 'literal' },
            { q: 'What bias might a tour operator have about visitor spending?', a: 'Operators profit from high visitor numbers, so they may overstate how much goes to conservation', kind: 'infer' },
            { q: 'Which words show the writer\'s measured, careful tone?', a: '"deserves scrutiny" and "The fairer question is not... but..."', kind: 'evidence' }
        ]
    },
    {
        title: 'Reading the Night Sky',
        text: 'For thousands of years, First Nations peoples of this continent read the dark spaces between stars as well as the stars themselves — the Emu in the Sky, for example, is shaped by dust lanes in the Milky Way. Colonial star charts named what they could navigate and trade by. Two skies, then: one of story and law, one of navigation. Both reward careful looking.',
        questions: [
            { q: 'What shapes the "Emu in the Sky"?', a: 'Dust lanes (dark spaces) in the Milky Way.', kind: 'literal' },
            { q: 'What does "Two skies, then" mean?', a: 'The same sky can be seen and used in two very different ways', kind: 'infer' },
            { q: 'Which phrase contrasts the two traditions directly?', a: '"one of story and law, one of navigation"', kind: 'evidence' }
        ]
    },
    {
        title: 'The Old Telegraph Station',
        text: 'The stone walls of the telegraph station still stand, though the wires are long gone. In its day, messages travelled through this building at the speed of electricity, shrinking a continent. Today, volunteers in period waistcoats tap out Morse code for school groups. Whether such re-enactments teach history or merely entertain it is a fair debate — but the laughter of children in that courtyard is hard to argue with.',
        questions: [
            { q: 'What do the volunteers do for school groups?', a: 'They tap out Morse code (wearing period waistcoats).', kind: 'literal' },
            { q: 'What debate does the writer raise in the last two sentences?', a: 'Whether re-enactments actually teach history or just entertain visitors', kind: 'infer' },
            { q: 'Which words show how important the station once was?', a: '"messages travelled... at the speed of electricity, shrinking a continent"', kind: 'evidence' }
        ]
    },
    {
        title: 'Should Advertising Be Banned at School?',
        text: 'Schools are for learning, so advertisers have no business on school grounds. This argument sounds tidy but ignores reality: sponsorships fund sports gear and laptops that budgets no longer cover. The honest answer is regulation, not bans — no junk-food logos, no collection of student data, and every contract published for parents to read. Principles are easy to shout; trade-offs are harder to manage.',
        questions: [
            { q: 'What does the writer suggest instead of a ban?', a: 'Regulation: no junk-food logos, no student data collection, published contracts.', kind: 'literal' },
            { q: 'What "trade-off" is the writer describing?', a: 'Sponsorship money schools need versus commercial pressure on students', kind: 'infer' },
            { q: 'Which sentence shows the writer rejects a too-simple argument?', a: '"This argument sounds tidy but ignores reality"', kind: 'evidence' }
        ]
    },
    {
        title: "Poem: 'Windy Season'",
        text: 'The wind combs the paddock,\nbends the old fence post,\ntucks dust under the door\nand will not stay host.\n\nIt rattles the rain tank,\nit hums through the wire,\nthen off to the coast\ncarrying kites higher and higher.',
        questions: [
            { q: 'Which two objects does the wind rattle and hum through?', a: 'The rain tank and the wire.', kind: 'literal' },
            { q: 'What does the poem suggest about the wind\'s character?', a: 'It is restless and powerful — it uses everything and moves on', kind: 'infer' },
            { q: 'Which words let you HEAR the wind in the second verse?', a: '"rattles the rain tank" and "hums through the wire"', kind: 'evidence' }
        ]
    },
    {
        title: 'Two Reviews of the Same Play',
        text: 'Review A calls the school production of "The Liars" "a triumph of timing", praising its "sharp, well-rehearsed ensemble". Review B, watching the same performance, found it "over-rehearsed to the point of lifelessness", with "actors reciting rather than acting". The plots match; the verdicts do not. Before you pick a side, ask each reviewer the same question: what did you hope a school play should be?',
        questions: [
            { q: 'What does Review A praise?', a: 'The timing and the sharp, well-rehearsed ensemble.', kind: 'literal' },
            { q: 'What do the two reviews prove about opinions?', a: 'The same performance can be judged oppositely depending on what each reviewer expects', kind: 'infer' },
            { q: 'What advice does the writer give readers at the end?', a: 'Ask each reviewer what they hoped a school play would be (before choosing a side)', kind: 'evidence' }
        ]
    }
] as const;

// Explicit year-level routing (T5): the caps.level knob selects the bank —
// no fragile wordTier/sentenceLen inference. Unknown levels clamp to Y3 so a
// misconfigured grade can never crash the generator.
const BANKS: Record<3 | 4 | 5 | 6, readonly Passage[]> = { 3: PASSAGES_Y3, 4: PASSAGES_Y4, 5: PASSAGES_Y5, 6: PASSAGES_Y6 };

// Render one passage as a single multi-line prompt + its marking answer.
// Layout (printed): title, passage text, blank line, instruction, then the
// three scaffolded questions a/b/c, each followed by a ruled writing line.
function renderPassage(p: Passage): RawProblem {
    const [q1, q2, q3] = p.questions;
    const prompt = [
        p.title,
        p.text,
        '',
        'Answer the questions in full sentences.',
        `a) ${q1.q}`,
        RULE,
        `b) ${q2.q}`,
        RULE,
        `c) ${q3.q}`,
        RULE
    ].join('\n');
    // Marking guidance, not a false single key: the inferential answer states
    // a text-supported sample and accepts any sensible alternative; the
    // evidence answer quotes the detail and accepts other accurate quotes.
    const answer = [
        `a) ${q1.a}`,
        `b) ${q2.a} (any sensible answer supported by the text is accepted)`,
        `c) ${q3.a} (other accurate quotes/details are accepted)`
    ].join('\n');
    return { prompt, answer };
}

// Generator: deal the year's passage bank without repeats (deck), collect
// distinct blocks via sampleUnique keyed on the printed prompt. The space is
// the bank size (6 per year) — long documents re-deal whole passages, which
// is by design for reading tasks (a fresh passage each time, never the same
// passage repeated above every question).
function generateComprehension(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const level = Math.min(Math.max(caps.level, 3), 6) as 3 | 4 | 5 | 6;
    const deck = localDeck(rng, BANKS[level]);
    return sampleUnique(
        count,
        () => renderPassage(deck.take()),
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// Per-year scope line (shown in the toolbar subtitle + sheet subtitle) —
// exposes the comprehension focus that deepens with caps.level.
const SCOPE_BY_LEVEL: Record<number, string> = {
    3: 'Year 3 passages — find it, read between the lines, quote it',
    4: 'Year 4 passages — visualise, predict, evaluate the evidence',
    5: 'Year 5 texts — scan, compare, evaluate the viewpoint',
    6: 'Year 6 texts — analyse style, tone and bias, compare sources'
};

// The plugin's declarative spec (exported for its own tests). One passage
// task per A4 page (perPage 1, single column) — the safest A4 budget for the
// longest Y6 block, and every question gets a full ruled writing line.
export const comprehensionSpec: WorksheetSpec = {
    id: 'comprehension',
    label: 'Reading Comprehension',
    icon: '☰',
    perPage: 1,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('comprehension'),
    scope: (grade: GradeConfig) => SCOPE_BY_LEVEL[grade.caps.level] ?? SCOPE_BY_LEVEL[3],
    generate: generateComprehension
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ComprehensionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(comprehensionSpec);
}
