// ─────────────────────────────────────────────────────────────────────────────
// COMPOUND WORDS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — joining two words to make a compound).
//
// The dashboard loads this plugin by calling `CompoundWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Compound Words", glyph "⚓") and which grades offer
//     it (Year 3+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Compound Words worksheet without affecting the framework or any
// other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 18 rows to 8
// roomy ones. The bank grew from 30 to 48 closed compounds, and two new
// families joined: APPLY (which compound fits a curated sentence frame) and
// an open-ended COMPOSE (the key models one compound and accepts any real
// one). CRITICAL FIX: the old "which one is a real compound word?" MC built
// its fakes by cross-joining bank halves with only a not-in-bank check — so
// real English words like "someone", "snowball", "playroom" and "cupboard"
// could appear as "fake" options, making the question unanswerable. Fakes are
// now cross-joins filtered through a curated blocklist of real words the
// halves can form, so every fake is genuinely not a word.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Compound items: [first, second, compound]. All closed (unspaced) compounds
// a Y3–6 student spells and reads. Grown from 30 to 48 for T4C.
const COMPOUND_ITEMS: [string, string, string][] = [
    ['sun', 'flower', 'sunflower'],
    ['rain', 'bow', 'rainbow'],
    ['tooth', 'brush', 'toothbrush'],
    ['foot', 'ball', 'football'],
    ['book', 'shop', 'bookshop'],
    ['bed', 'room', 'bedroom'],
    ['snow', 'man', 'snowman'],
    ['sea', 'shell', 'seashell'],
    ['cup', 'cake', 'cupcake'],
    ['note', 'book', 'notebook'],
    ['play', 'ground', 'playground'],
    ['water', 'fall', 'waterfall'],
    ['butter', 'fly', 'butterfly'],
    ['star', 'fish', 'starfish'],
    ['lamp', 'post', 'lamppost'],
    ['hair', 'brush', 'hairbrush'],
    ['lawn', 'mower', 'lawnmower'],
    ['dish', 'washer', 'dishwasher'],
    ['key', 'board', 'keyboard'],
    ['black', 'board', 'blackboard'],
    ['day', 'dream', 'daydream'],
    ['grand', 'parent', 'grandparent'],
    ['under', 'ground', 'underground'],
    ['out', 'side', 'outside'],
    ['some', 'thing', 'something'],
    ['every', 'one', 'everyone'],
    ['birth', 'day', 'birthday'],
    ['sand', 'pit', 'sandpit'],
    ['tree', 'house', 'treehouse'],
    ['wind', 'mill', 'windmill'],
    // T4C growth: more everyday closed compounds.
    ['sun', 'set', 'sunset'],
    ['book', 'worm', 'bookworm'],
    ['fire', 'fly', 'firefly'],
    ['rain', 'coat', 'raincoat'],
    ['tooth', 'paste', 'toothpaste'],
    ['pan', 'cake', 'pancake'],
    ['air', 'port', 'airport'],
    ['post', 'man', 'postman'],
    ['mail', 'box', 'mailbox'],
    ['gold', 'fish', 'goldfish'],
    ['snow', 'flake', 'snowflake'],
    ['water', 'melon', 'watermelon'],
    ['bed', 'time', 'bedtime'],
    ['home', 'work', 'homework'],
    ['class', 'room', 'classroom'],
    ['back', 'pack', 'backpack'],
    ['any', 'one', 'anyone'],
    ['under', 'water', 'underwater']
];

// Real English words that the bank's halves CAN cross-join but that are NOT
// in the compound bank. The fake-distractor generator must never produce one
// of these, or a "which one is a real compound word?" question would have
// more than one right answer (the exact bug this list fixes).
const REAL_WORDS_OUTSIDE_BANK: ReadonlySet<string> = new Set([
    'someone', 'someday', 'sometime', 'everyday', 'anything', 'anytime',
    'onesome', 'sunday', 'sunroom', 'snowball', 'snowboard', 'buttercup',
    'playroom', 'flowerbed', 'blackout', 'shellfish', 'pitfall', 'fallout',
    'rainwater', 'cupboard', 'ballroom', 'ballpit', 'seaside', 'fisherman',
    'mailman', 'housework', 'firework', 'fireball', 'daytime', 'postbox',
    'sandbox', 'outback', 'background', 'seaport', 'airmail',
    // Found by auditing generated fakes against real vocabulary: these are
    // real words the halves can cross-join, so they must never be fakes.
    'bedpan', 'daybed', 'starboard', 'setback', 'outset', 'workshop',
    'classwork', 'groundwork', 'watermill'
]);

// APPLY frames (T4C new family): [answer, sentence with "__", distractors].
// Distractors are OTHER real bank compounds that do not fit the frame's
// meaning, so the task doubles as genuine vocabulary checking.
const COMPOUND_SENTENCES: [string, string, string[]][] = [
    ['football', 'We kicked the __ into the goal.', ['toothbrush', 'notebook']],
    ['toothbrush', 'I clean my teeth with a __.', ['playground', 'sandpit']],
    ['notebook', 'Write the new words in your __.', ['mailbox', 'raincoat']],
    ['rainbow', 'After the storm we saw a __ in the sky.', ['firefly', 'snowflake']],
    ['sunflower', 'The tall __ turned its face towards the sun.', ['waterfall', 'bookshop']],
    ['playground', 'We played tag in the __ at lunchtime.', ['toothpaste', 'keyboard']],
    ['sandpit', 'The kids built a castle in the __.', ['blackboard', 'lamppost']],
    ['waterfall', 'The river tumbled over the __.', ['cupcake', 'hairbrush']],
    ['butterfly', 'A __ landed on the lavender.', ['snowman', 'sandpit']],
    ['snowman', 'We rolled a huge __ in the yard.', ['sunflower', 'playground']],
    ['keyboard', 'Type your name on the __.', ['lawnmower', 'dishwasher']],
    ['dishwasher', 'We loaded the __ after dinner.', ['keyboard', 'treehouse']],
    ['lawnmower', 'Dad pushed the __ across the lawn.', ['mailbox', 'toothbrush']],
    ['mailbox', 'Post the letter in the __.', ['notebook', 'football']],
    ['hairbrush', 'She combed the tangles out with a __.', ['windmill', 'starfish']]
];

// Compound words — SIX procedural kinds (upper primary):
//   0. written: "join these two words" (spelling answer)
//   1. MC: which compound is made from the dealt pair (3 options, two fakes
//      assembled from other compounds' halves)
//   2. reverse: "which two words make up '<compound>'?" (written "a + b")
//   3. MC: which of the three IS a real compound word (the compound beside
//      two cross-join fakes that pass the real-word blocklist)
//   4. MC APPLY: which bank compound fits the curated sentence frame
//   5. open-ended COMPOSE: "write your own compound word" — the key models
//      one and accepts any real compound
//
// NON-REPEATING SAMPLING: items are dealt from a deck and every question
// passes through sampleUnique keyed on the printed prompt.
function generateCompound(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, COMPOUND_ITEMS);
    const sentenceDeck = localDeck(rng, COMPOUND_SENTENCES);
    // Fakes join only the TWO-WORD halves (never a whole compound), so they
    // read as plausible child errors ("sunball") rather than triple mush.
    const halves = COMPOUND_ITEMS.flatMap(([first, second]) => [first, second]);
    // A cross-join is a usable FAKE only when it is neither a bank compound
    // nor a real English word the halves happen to form (see blocklist).
    const isFake = (word: string) =>
        !COMPOUND_ITEMS.some(([, , c]) => c === word) && !REAL_WORDS_OUTSIDE_BANK.has(word);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 5);
            if (kind === 4) {
                // APPLY: the one bank compound that fits the sentence.
                const [answer, sentence, distractors] = sentenceDeck.take();
                const shown = shuffleLocal(rng, [answer, ...distractors]);
                return { prompt: `Which compound word fits: ${sentence} (${shown.join(', ')})`, answer };
            }
            if (kind === 5) {
                // OPEN-ENDED compose: any real compound word is correct.
                const example = itemDeck.take()[2];
                return {
                    prompt: 'Write your own compound word (two words joined into one).',
                    answer: `Example: ${example} (any real compound word is correct)`
                };
            }
            const [first, second, compound] = itemDeck.take();
            if (kind === 0) {
                return { prompt: `Join into one word: ${first} + ${second}`, answer: compound };
            }
            if (kind === 1) {
                // MC: the compound beside two fake joins from other halves.
                // Only the dealt pair forms the answer, so real-word fakes
                // cannot make this question ambiguous — but the blocklist
                // keeps the fakes clearly non-words anyway.
                const options = [compound];
                let guard = 0;
                while (options.length < 3 && guard < 48) {
                    guard++;
                    const h1 = rng.pick(halves);
                    const h2 = rng.pick(halves);
                    const fake = `${h1}${h2}`;
                    if (isFake(fake) && !options.includes(fake) && fake !== compound) {
                        options.push(fake);
                    }
                }
                const shown = shuffleLocal(rng, options);
                return { prompt: `Which word is made from "${first}" and "${second}"? (${shown.join(', ')})`, answer: compound };
            }
            if (kind === 2) {
                return { prompt: `Which two words make up "${compound}"?`, answer: `${first} + ${second}` };
            }
            // MC: pick the real compound from three candidates. The fakes are
            // blocklist-filtered cross-joins, so exactly ONE option is a word.
            const fakes: string[] = [];
            let guard = 0;
            while (fakes.length < 2 && guard < 48) {
                guard++;
                const h1 = rng.pick(halves);
                const h2 = rng.pick(halves);
                const fake = `${h1}${h2}`;
                if (isFake(fake) && !fakes.includes(fake) && fake !== compound) {
                    fakes.push(fake);
                }
            }
            const shown = shuffleLocal(rng, [compound, ...fakes]);
            return { prompt: `Which one is a real compound word? (${shown.join(', ')})`, answer: compound };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). T4C: 8 roomy
// rows per page instead of 18.
export const compoundSpec: WorksheetSpec = {
    id: 'compound',
    label: 'Compound Words',
    icon: '⚓',
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('compound'),
    scope: () => 'two words, one word',
    generate: generateCompound
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CompoundWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(compoundSpec);
}
