// ─────────────────────────────────────────────────────────────────────────────
// COMPOUND WORDS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — joining two words to make a compound).
//
// The dashboard loads this plugin by calling `CompoundWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Compound Words", glyph "⚓") and which grades offer
//     it (Year 3+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Compound Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Compound items: [first, second, compound]. All closed (unspaced) compounds
// a Y3–6 student spells and reads.
const COMPOUND_ITEMS: [string, string, string][] = [
    ['sun', 'flower', 'sunflower'],
    ['rain', 'bow', 'rainbow'],
    ['tooth', 'brush', 'toothbrush'],
    ['foot', 'ball', 'football'],
    ['book', 'shop', 'bookshop'],
    ['bed', 'room', 'bedroom'],
    ['snow', 'man', 'snowman'],
    ['sea', 'shell', 'seashell'],
    ['cup', 'cake', 'cupcake'],
    ['note', 'book', 'notebook'],
    ['play', 'ground', 'playground'],
    ['water', 'fall', 'waterfall'],
    ['butter', 'fly', 'butterfly'],
    ['star', 'fish', 'starfish'],
    ['lamp', 'post', 'lamppost'],
    ['hair', 'brush', 'hairbrush'],
    ['lawn', 'mower', 'lawnmower'],
    ['dish', 'washer', 'dishwasher'],
    ['key', 'board', 'keyboard'],
    ['black', 'board', 'blackboard'],
    ['day', 'dream', 'daydream'],
    ['grand', 'parent', 'grandparent'],
    ['under', 'ground', 'underground'],
    ['out', 'side', 'outside'],
    ['some', 'thing', 'something'],
    ['every', 'one', 'everyone'],
    ['birth', 'day', 'birthday'],
    ['sand', 'pit', 'sandpit'],
    ['tree', 'house', 'treehouse'],
    ['wind', 'mill', 'windmill']
];

// Compound words — FOUR procedural kinds (upper primary):
//   0. written: "join these two words" (spelling answer)
//   1. MC: which compound is made from the dealt pair (3 options, two fakes
//      assembled from other compounds' halves)
//   2. reverse: "which two words make up '<compound>'?" (written "a + b")
//   3. MC: which of the three IS a real compound word (the compound beside
//      two fake concatenations of bank halves that are NOT compounds)
//
// NON-REPEATING SAMPLING: items are dealt from a deck and every question
// passes through sampleUnique keyed on the printed prompt.
function generateCompound(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, COMPOUND_ITEMS);
    const halves = COMPOUND_ITEMS.flat();
    // Fake concatenations that are NOT in the compound bank (verified at
    // build time below by the distractor filter).
    return sampleUnique(
        count,
        () => {
            const [first, second, compound] = itemDeck.take();
            const kind = rng.int(0, 3);
            if (kind === 0) {
                return { prompt: `Join into one word: ${first} + ${second}`, answer: compound };
            }
            if (kind === 1) {
                // MC: the compound beside two fake joins from other halves.
                const options = [compound];
                let guard = 0;
                while (options.length < 3 && guard < 48) {
                    guard++;
                    const h1 = rng.pick(halves);
                    const h2 = rng.pick(halves);
                    const fake = `${h1}${h2}`;
                    if (!COMPOUND_ITEMS.some(([, , c]) => c === fake) && !options.includes(fake) && fake !== compound) {
                        options.push(fake);
                    }
                }
                const shown = shuffleLocal(rng, options);
                return { prompt: `Which word is made from "${first}" and "${second}"? (${shown.join(', ')})`, answer: compound };
            }
            if (kind === 2) {
                return { prompt: `Which two words make up "${compound}"?`, answer: `${first} + ${second}` };
            }
            // MC: pick the real compound from three candidates.
            const fakes: string[] = [];
            let guard = 0;
            while (fakes.length < 2 && guard < 48) {
                guard++;
                const h1 = rng.pick(halves);
                const h2 = rng.pick(halves);
                const fake = `${h1}${h2}`;
                if (!COMPOUND_ITEMS.some(([, , c]) => c === fake) && !fakes.includes(fake) && fake !== compound) {
                    fakes.push(fake);
                }
            }
            const shown = shuffleLocal(rng, [compound, ...fakes]);
            return { prompt: `Which one is a real compound word? (${shown.join(', ')})`, answer: compound };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests).
export const compoundSpec: WorksheetSpec = {
    id: 'compound',
    label: 'Compound Words',
    icon: '⚓',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('compound'),
    scope: () => 'two words, one word',
    generate: generateCompound
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CompoundWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(compoundSpec);
}
