// ─────────────────────────────────────────────────────────────────────────────
// CONJUNCTIONS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — joining clauses with and/but/or/so/because/when/if/
// before).
//
// The dashboard loads this plugin by calling `ConjunctionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Conjunctions", glyph "+") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Conjunctions worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// ── Combinatorial sentence banks ─────────────────────────────────────────────
// Clause slots assemble thousands of grammatical lines; each CONJUNCTION item
// pairs a left clause, a conjunction and a right clause whose meanings fit.
// Slots are cross-multiplied per item so the question space is the
// cross-product (hundreds per conjunction) instead of a fixed list.
const FIRST_CLAUSES: readonly string[] = [
    'I wanted to play outside', 'We packed our bags', 'Mia finished her book',
    'The rain poured down', 'Sam ate all his lunch', 'The dog barked loudly',
    'Our team scored a goal', 'Dad lit the barbecue', 'I lost my pencil case',
    'The bell rang'
] as const;
// Right clauses per conjunction — semantically compatible continuations.
const RIGHT_BECAUSE: readonly string[] = [
    'it was raining', 'I was tired', 'the shop was closed', 'we were hungry',
    'she loves stories', 'he felt sick', 'it was my birthday', 'the bus was late'
] as const;
const RIGHT_SO: readonly string[] = [
    'we stayed inside', 'I went to bed early', 'we ate together', 'she read another one',
    'we waited for the next one', 'I asked for a spare', 'he had a rest', 'we cheered'
] as const;
const RIGHT_BUT: readonly string[] = [
    'it was too wet', 'I forgot my hat', 'nobody was home', 'the gate was locked',
    'we missed the bus', 'my bike had a flat tyre', 'the pool was closed', 'I felt shy'
] as const;
const RIGHT_AND: readonly string[] = [
    'we played cricket', 'she drank her milk', 'he laughed loudly', 'they sang a song',
    'I drew a picture', 'we ate some fruit', 'the cat fell asleep', 'mum made dinner'
] as const;
// When/if question kinds: choose the conjunction that fits the blank.
const WHEN_IF_SENTENCES: readonly [string, string][] = [
    ['Wash your hands __ you eat dinner.', 'before'],
    ['We go to the pool __ it is hot.', 'when'],
    ['__ you finish your homework, you can watch TV.', 'if'],
    ['__ I grow up, I want to be a vet.', 'when'],
    ['Take a jacket __ it gets cold.', 'if'],
    ['We always visit Nanna __ Sunday.', 'when'],
    ['__ the fire alarm sounds, we line up quietly.', 'when'],
    ['You cannot ride __ you wear a helmet.', 'if'],
    ['Brush your teeth __ you go to bed.', 'before'],
    ['__ it snows, school closes early.', 'if'],
    ['I wave goodbye __ the bus leaves.', 'before'],
    ['__ the light turns red, the cars stop.', 'when']
] as const;

// Conjunctions — THREE procedural kinds:
//   0. fill the blank with the fitting conjunction (3 options, one correct)
//   1. MC "which conjunction fits best?" over an assembled because/so/but line
//   2. written answer: "join these clauses with __" (and/because pairs)
//
// NON-REPEATING SAMPLING: every question passes through sampleUnique keyed on
// the printed prompt; slot cross-products keep the space past 100 pages.
function generateConjunction(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeckData = [
        ...FIRST_CLAUSES.flatMap((left): [string, readonly string[], string][] => [
            [left, RIGHT_BECAUSE, 'because'],
            [left, RIGHT_SO, 'so'],
            [left, RIGHT_BUT, 'but'],
            [left, RIGHT_AND, 'and']
        ])
    ];
    const whenDeck = createLocalDeck(rng, WHEN_IF_SENTENCES);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 2);
            if (kind === 0) {
                // When/if/before blank: pick the fitting word (3 options).
                const [sentence, answer] = whenDeck.take();
                const options = shuffleLocal(rng, [answer, 'but', 'or']);
                return { prompt: `${sentence} (${options.join(', ')})`, answer };
            }
            // Assembled clause pair. Kind 1 = MC; kind 2 = written join.
            const [left, rights, answer] = itemDeckData[
                rng.int(0, itemDeckData.length - 1)
            ];
            const right = rng.pick(rights);
            const line = `${left} __ ${right}`;
            if (kind === 1) {
                // MC: the answer beside two other conjunctions.
                const others = ['because', 'so', 'but', 'and'].filter((c) => c !== answer);
                const o1 = rng.pick(others);
                let o2 = rng.pick(others);
                if (o2 === o1) o2 = others[(others.indexOf(o1) + 1) % others.length];
                const shown = shuffleLocal(rng, [answer, o1, o2]);
                return { prompt: `Which conjunction fits best: ${line} (${shown.join(', ')})`, answer };
            }
            return { prompt: `Join with the best conjunction: ${line}`, answer };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function createLocalDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Gap sentences
// are prose — single-column via singleColumn.
export const conjunctionSpec: WorksheetSpec = {
    id: 'conjunction',
    label: 'Conjunctions',
    icon: '+',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('conjunction'),
    scope: () => 'and, but, or, so, because',
    generate: generateConjunction
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ConjunctionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(conjunctionSpec);
}
