// ─────────────────────────────────────────────────────────────────────────────
// CONJUNCTIONS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — joining clauses with and/but/or/so/because/when/if/
// before).
//
// The dashboard loads this plugin by calling `ConjunctionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Conjunctions", glyph "+") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Conjunctions worksheet without affecting the framework or any
// other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 16 rows to 6
// roomy prose rows (these are full-sentence tasks — they need space).
// SEMANTIC FIX: the old generator cross-multiplied ANY left clause with ANY
// right clause of a conjunction, which produced broken logic — "Our team
// scored a goal because it was raining". The banks are CURATED
// [left, right] pairs per conjunction family, each pair verified to carry
// that conjunction's real logic (cause for because, consequence for so,
// contrast for but, addition for and). T5E review: the first rework cut the
// SEMANTIC space below the old (invalid) one (346 vs 1223 measured), so the
// banks grew 16 → 24 pairs per family and the when/if bank 20 → 28 lines —
// the space now clears the 100-page ask with VALID questions only.
// New families: an explicit JOIN-AS-EDIT task (deterministic answer) and an
// open-ended COMPOSE whose key gives one example and accepts any sensible
// sentence.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// ── Curated clause-pair banks ────────────────────────────────────────────────
// Each pair carries its conjunction's logic. 24 pairs per family (T5E).
const BECAUSE_PAIRS: readonly [string, string][] = [
    ['We stayed inside', 'it was raining'],
    ['I went to bed early', 'I was tired'],
    ['Mia read another book', 'she loves stories'],
    ['We ate the whole cake', 'we were hungry'],
    ['He had a long rest', 'he felt sick'],
    ['We celebrated at home', 'it was my birthday'],
    ['We waited in the sun', 'the bus was late'],
    ['I asked to borrow a pencil', 'I lost my pencil case'],
    ['We walked to the shop', 'the car would not start'],
    ['She drank a big glass of water', 'she was very thirsty'],
    ['The class practised daily', 'the competition was near'],
    ['Grandma baked two pies', 'the visitors were coming'],
    ['I wore my gumboots', 'the yard was muddy'],
    ['We packed our bags at dawn', 'the camp was tomorrow'],
    ['The dog barked loudly', 'a stranger walked past'],
    ['Our team cheered loudly', 'they had won the game'],
    // T5E pool expansion (E3): the curated bank grew 16 → 24 pairs per
    // family so the SEMANTIC space (not just the printed one) clears the
    // 100-page ask. Every added pair carries the family's real logic.
    ['She forgot her glasses', 'she could not read the board'],
    ['We left early', 'the show started at six'],
    ['He wore his coat', 'it was cold outside'],
    ['I yawned all morning', 'I stayed up late'],
    ['We took an umbrella', 'the sky looked grey'],
    ['Sam laughed and laughed', 'the joke was very funny'],
    ['The kids ran inside', 'the storm was coming'],
    ['The garden needs water', 'it has not rained for weeks']
] as const;
const SO_PAIRS: readonly [string, string][] = [
    ['It was raining', 'we stayed inside'],
    ['I was tired', 'I went to bed early'],
    ['Mia finished her book', 'she read another one'],
    ['We were hungry', 'we ate together'],
    ['He felt sick', 'he had a rest'],
    ['The bus was late', 'we waited for the next one'],
    ['I lost my pencil case', 'I asked for a spare'],
    ['Our team scored a goal', 'we cheered'],
    ['The rain poured down', 'the match was called off'],
    ['The bell rang', 'the students lined up'],
    ['Zoe forgot her sports bag', 'she sat out the game'],
    ['We trained every weekend', 'we won the grand final'],
    ['The power went out', 'we lit candles'],
    ['I practised the song daily', 'it sounded perfect'],
    ['Sam finished his lunch early', 'he played outside'],
    ['Dad lit the barbecue', 'mum set the table'],
    // T5E pool expansion — consequence pairs (16 → 24).
    ['It was cold outside', 'we wore our coats'],
    ['The show started at six', 'we left early'],
    ['She could not read the board', 'she moved to the front'],
    ['We stayed up late', 'we yawned in class'],
    ['The plants were dry', 'we watered them nightly'],
    ['The sky turned grey', 'we grabbed our umbrellas'],
    ['Sam told a funny joke', 'the whole table laughed'],
    ['The storm was coming', 'the kids ran inside']
] as const;
const BUT_PAIRS: readonly [string, string][] = [
    ['I wanted to play outside', 'it was too wet'],
    ['We packed our bags', 'we missed the bus'],
    ['Mia finished her book', 'the last page was missing'],
    ['The rain poured down', 'the match went ahead'],
    ['Sam ate all his lunch', 'he was still hungry'],
    ['The dog barked loudly', 'the stranger walked on'],
    ['Our team scored a goal', 'we lost the game'],
    ['Dad lit the barbecue', 'the gas ran out'],
    ['I lost my pencil case', 'the teacher found it later'],
    ['The bell rang', 'nobody moved'],
    ['The bus was late again', 'we still made it'],
    ['Zoe forgot her sports bag', 'she played anyway'],
    ['We trained every weekend', 'we did not win'],
    ['Grandma baked a pumpkin pie', 'it vanished in minutes'],
    ['The power went out', 'we read by torchlight'],
    ['I practised the song daily', 'my voice still wobbled'],
    // T5E pool expansion — contrast pairs (16 → 24).
    ['She forgot her glasses', 'the teacher helped her read'],
    ['It was cold outside', 'we still rode our bikes'],
    ['The show started late', 'the hall was already full'],
    ['We took an umbrella', 'it never rained'],
    ['The plants were dry', 'nobody had a hose'],
    ['Sam told a joke', 'nobody laughed'],
    ['The storm was coming', 'the match went ahead'],
    ['I stayed up late', 'I still finished my project']
] as const;
// 'and' pairs are deliberately NON-causal additions, so 'so' can never also
// "fit best" an and-line (the ambiguity the old cross-product created).
const AND_PAIRS: readonly [string, string][] = [
    ['Dad lit the barbecue', 'mum made dinner'],
    ['The bell rang', 'the students sang a song'],
    ['We finished early', 'the bell rang'],
    ['Mia finished her book', 'Jack finished his'],
    ['The rain poured down', 'the wind howled'],
    ['Sam ate all his lunch', 'he drank his milk too'],
    ['The dog barked', 'the cat purred'],
    ['Our team scored a goal', 'the other team kicked off'],
    ['I lost my pencil case', 'my ruler went missing too'],
    ['We packed our bags', 'we checked the map'],
    ['Zoe forgot her sports bag', 'Ben forgot his boots'],
    ['We trained every weekend', 'we cheered for each other'],
    ['Grandma baked a pumpkin pie', 'Grandpa grilled the sausages'],
    ['The power went out', 'the candles were in the drawer'],
    ['I practised the song daily', 'my friends practised theirs'],
    ['The birds sang at dawn', 'the sun came up'],
    // T5E pool expansion — non-causal additions (16 → 24); none may read as
    // a cause/effect pair, or 'so' would compete with 'and' in the MC kind.
    ['I packed my bag', 'my sister packed hers'],
    ['Dad washed the car', 'mum watered the garden'],
    ['The kids ran inside', 'the dog followed them'],
    ['Sam laughed at the joke', 'his sister smiled too'],
    ['We took an umbrella', 'we packed torches as well'],
    ['She likes reading', 'her brother likes drawing'],
    ['I yawned a lot', 'my friend yawned too'],
    ['The sky looked grey', 'the wind picked up']
] as const;
// 'or' pairs: choices and warnings — curated [left, right] so every line reads.
const OR_PAIRS: readonly [string, string][] = [
    ['Hurry up', 'you will miss the bus'],
    ['Put on your coat', 'you will be cold'],
    ['We can walk to the park', 'we can ride our bikes'],
    ['Finish your vegetables', 'you will not grow big and strong'],
    ['Read the instructions first', 'you will build it wrong'],
    ['Share the snacks now', 'there will be none left later'],
    ['Water the seedlings daily', 'they will dry out'],
    ['We can play cricket', 'we can play soccer']
] as const;
// When/if/before question kinds: choose the conjunction that fits the blank.
// Grown from 12 to 20 lines for T4C.
const WHEN_IF_SENTENCES: readonly [string, string][] = [
    ['Wash your hands __ you eat dinner.', 'before'],
    ['We go to the pool __ it is hot.', 'when'],
    ['__ you finish your homework, you can watch TV.', 'if'],
    ['__ I grow up, I want to be a vet.', 'when'],
    ['Take a jacket __ it gets cold.', 'if'],
    ['We always visit Nanna __ Sunday.', 'when'],
    ['__ the fire alarm sounds, we line up quietly.', 'when'],
    ['You cannot ride __ you wear a helmet.', 'if'],
    ['Brush your teeth __ you go to bed.', 'before'],
    ['__ it snows, school closes early.', 'if'],
    ['I wave goodbye __ the bus leaves.', 'before'],
    ['__ the light turns red, the cars stop.', 'when'],
    ['__ you water the plants, they grow faster.', 'if'],
    ['Check the map __ you leave the house.', 'before'],
    ['__ the bell rings, the students line up.', 'when'],
    ['__ we finish early, we will play a game.', 'if'],
    ['Tie your shoes __ you run the race.', 'before'],
    ['__ the sky turns dark, we head home.', 'when'],
    ['__ you feel thirsty, drink some water.', 'if'],
    ['Wash the fruit __ you eat it.', 'before'],
    // T5E pool expansion — when/if/before lines (20 → 28).
    ['__ you save your money, you can buy the game.', 'if'],
    ['We stay inside __ it rains.', 'when'],
    ['__ you have finished, you may play.', 'when'],
    ['Clap your hands __ the music stops.', 'when'],
    ['__ the dog sees a cat, it runs.', 'when'],
    ['Wear a hat __ the sun is strong.', 'when'],
    ['__ you feel cold, ask for a blanket.', 'if'],
    ['Turn off the lights __ you leave the room.', 'before']
] as const;

// Conjunctions — FIVE procedural kinds:
//   0. fill the blank with the fitting when/if/before (3 options, one correct)
//   1. MC "which conjunction fits best?" over a curated clause pair
//   2. written answer: "join these clauses with __"
//   3. EDIT: "Join the two sentences with '<conj>'." (deterministic answer)
//   4. open-ended COMPOSE: "Write a sentence using '<conj>'." (the key gives
//      one example and accepts any sensible sentence)
//
// NON-REPEATING SAMPLING: every question passes through sampleUnique keyed on
// the printed prompt; pair x prompt-form x MC-option-order keeps the space
// past 100 pages.
function generateConjunction(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    // One flat deck of [left, right, conjunction] triples over the curated
    // pairs, so coverage travels the whole bank before any repeat.
    const pairDeck = createLocalDeck(rng, [
        ...BECAUSE_PAIRS.map((p): [string, string, string] => [p[0], p[1], 'because']),
        ...SO_PAIRS.map((p): [string, string, string] => [p[0], p[1], 'so']),
        ...BUT_PAIRS.map((p): [string, string, string] => [p[0], p[1], 'but']),
        ...AND_PAIRS.map((p): [string, string, string] => [p[0], p[1], 'and'])
    ]);
    const whenDeck = createLocalDeck(rng, WHEN_IF_SENTENCES);
    const orDeck = createLocalDeck(rng, OR_PAIRS);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 4);
            if (kind === 0) {
                // When/if/before blank: pick the fitting word (3 options).
                const [sentence, answer] = whenDeck.take();
                const options = shuffleLocal(rng, [answer, 'but', 'or']);
                return { prompt: `${sentence} (${options.join(', ')})`, answer };
            }
            if (kind === 4) {
                // OPEN-ENDED compose: the example is a curated pair for that
                // conjunction, so it always reads; any sensible sentence using
                // the conjunction is correct.
                const conj = rng.pick(['because', 'so', 'but', 'and', 'when', 'if']);
                let example: string;
                if (conj === 'when' || conj === 'if') {
                    const matches = WHEN_IF_SENTENCES.filter(([, a]) => a === conj);
                    const [sentence] = matches[rng.int(0, matches.length - 1)];
                    // Capitalise the sentence-initial conjunction in the example.
                    const filled = sentence.replace('__', conj);
                    example = filled[0].toUpperCase() + filled.slice(1);
                } else {
                    const pairs = conj === 'because' ? BECAUSE_PAIRS : conj === 'so' ? SO_PAIRS : conj === 'but' ? BUT_PAIRS : AND_PAIRS;
                    const [left, right] = pairs[rng.int(0, pairs.length - 1)];
                    example = `${left} ${conj} ${right}.`;
                }
                return {
                    prompt: `Write a sentence that uses the joining word "${conj}".`,
                    answer: `Example: ${example} (any sensible sentence using "${conj}" is correct)`
                };
            }
            // Kinds 1–3 work on one curated clause pair.
            const [left, right, answer] = pairDeck.take();
            const line = `${left} __ ${right}`;
            if (kind === 1) {
                // MC: the answer beside two other conjunctions.
                const others = ['because', 'so', 'but', 'and'].filter((c) => c !== answer);
                const o1 = rng.pick(others);
                let o2 = rng.pick(others);
                if (o2 === o1) o2 = others[(others.indexOf(o1) + 1) % others.length];
                const shown = shuffleLocal(rng, [answer, o1, o2]);
                return { prompt: `Which conjunction fits best: ${line} (${shown.join(', ')})`, answer };
            }
            if (kind === 2) {
                return { prompt: `Join with the best conjunction: ${line}`, answer };
            }
            // EDIT: join two printed sentences with a NAMED conjunction. The
            // pair is drawn from that conjunction's own bank, so the joined
            // line always reads and the answer is exactly determined.
            // The right half is banked lowercase (it continues the joined
            // sentence); capitalise it only for its display as a quote.
            const rightShown = right[0].toUpperCase() + right.slice(1);
            return {
                prompt: `Join the two sentences with "${answer}": "${left}." "${rightShown}."`,
                answer: `${left} ${answer} ${right}.`
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function createLocalDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Gap sentences
// are prose — single-column via singleColumn. T4C: 6 roomy rows per page.
export const conjunctionSpec: WorksheetSpec = {
    id: 'conjunction',
    label: 'Conjunctions',
    icon: '+',
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('conjunction'),
    scope: () => 'and, but, or, so, because',
    generate: generateConjunction
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ConjunctionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(conjunctionSpec);
}
