// ─────────────────────────────────────────────────────────────────────────────
// CRAFTING SENTENCES WORKSHEET — a self-contained dashboard plugin
// (upper primary: Year 3–6; ACARA v9-informed — Y3 AC9E3LA06/LY06,
// Y4 AC9E4LA06/LA08/LY06, Y5 AC9E5LA05/LA06, Y6 AC9E6LA05/LA06/LA09).
//
// The dashboard loads this plugin by calling `CraftWorksheet(dashboard)` with
// its configurations + layouts (see plugins/index.ts). Within this function
// the plugin describes:
//   - its SIDEBAR LABEL ("Crafting Sentences", glyph "⤴") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Crafting Sentences worksheet without affecting the framework
// or any other plugin.
//
// T5 DESIGN NOTES (sentence/paragraph crafting — the "grow the writer" gap):
//   * Five task kinds form an explicit SCAFFOLD → CORE → STAIRCASE within
//     every year: REORDER (support: parts given) → EXPAND / JOIN (core:
//     guided production) → MC ANALYSE (practise: judge quality) → COMPOSE
//     (stretch: open-ended with an example + acceptance note).
//   * YEAR PROGRESSION is EXPLICIT via caps.level: Y3 orders and joins
//     simple sentences with and/but/or/so/because/when; Y4 combines with
//     subordinate conjunctions and adds adverbial/prepositional detail; Y5
//     builds complex sentences for reason/purpose/condition/concession with
//     fronted-clause rewrites; Y6 embeds relative clauses, varies openers
//     and shifts TONE (formal/objective). Year 5 and Year 6 banks are
//     genuinely different tasks, not the same list at deeper caps.
//   * Deterministic answers where the task has one right form (reorder,
//     join, MC); open production answers are "Example: ... (any sensible
//     ... is correct)" — marking guidance, never a false single key.
//   * Every written row prints a ruled WRITING LINE (a run of "__" blanks)
//     under the task so there is real space to craft.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// A ruled WRITING line (see PrintableSheet PromptText: "__" tokens render as
// connected fill-in blanks on one baseline).
const RULE = '__ __ __ __ __ __ __ __ __ __';

// ── Item shapes (shared across the four year banks) ─────────────────────────
// EXPAND: [base sentence, detail to add, model expanded sentence, style?].
// Default style = the detail is a LITERAL PHRASE to place ("Add the detail
// \"loudly\"..."). T9: Year 5 details are WRITING INSTRUCTIONS ("which
// teacher and how they spoke") — those items carry style 'instruction' so
// the generator prints a descriptive-rewrite stem/rubric instead of the
// nonsensical "placement of <instruction>" rubric.
type ExpandItem = [string, string, string, 'instruction'?];
// JOIN: [main clause, subordinate clause, named conjunction, model joined].
type JoinItem = [string, string, string, string];
// MC: stem + optional base sentence + options + the one correct option
// (options joined with " / " so sentence-length options containing commas
// stay parseable).
type McItem = { stem: string; base?: string; options: string[]; answer: string };
// REWRITE: instruction + shown source + answer; `open` marks tone/production
// rewrites whose answer is a model (accept any sensible equivalent).
type RewriteItem = { instruction: string; shown: string; answer: string; open: boolean };
// COMPOSE: open-ended stretch task + example.
type ComposeItem = { prompt: string; example: string };

// One bank per year level (routed explicitly by caps.level below).
type CraftBank = {
    expand: readonly ExpandItem[];
    join: readonly JoinItem[];
    mc: readonly McItem[];
    rewrite: readonly RewriteItem[];
    compose: readonly ComposeItem[];
};

// ── Year 3 (AC9E3LA06 clause/subject-verb; AC9E3LY06 compound sentences) ────
// Support-first: reorder given parts; core: add one detail / join two
// sentences with a named word; stretch: compose with that word.
const BANK_Y3: CraftBank = {
    expand: [
        ['The kookaburra laughed', 'loudly', 'The kookaburra laughed loudly.'],
        ['The dog barked', 'at the mailman', 'The dog barked at the mailman.'],
        ['Mum drove the ute', 'carefully', 'Mum drove the ute carefully.'],
        ['We ate the watermelon', 'in the shade', 'We ate the watermelon in the shade.'],
        ['The train rumbled past', 'slowly', 'The train rumbled past slowly.'],
        ['A magpie followed the tractor', 'curiously', 'A magpie followed the tractor curiously.']
    ],
    join: [
        ['We stayed inside', 'it was raining', 'because', 'We stayed inside because it was raining.'],
        ['Grandma waved', 'the bus pulled away', 'when', 'Grandma waved when the bus pulled away.'],
        ['The lights went out', 'we lit candles', 'so', 'The lights went out so we lit candles.'],
        ['I wanted to swim', 'the water was too cold', 'but', 'I wanted to swim but the water was too cold.'],
        ['We can ride bikes', 'we can walk', 'or', 'We can ride bikes or we can walk.'],
        ['Dad grilled the sausages', 'mum set the table', 'and', 'Dad grilled the sausages and mum set the table.']
    ],
    mc: [
        { stem: 'Which detail best tells HOW?', base: 'The bus rumbled on.', options: ['slowly', 'three', 'yesterday'], answer: 'slowly' },
        { stem: 'Which detail best tells WHERE?', base: 'We found the lost kite.', options: ['in the tree', 'quickly', 'then'], answer: 'in the tree' },
        { stem: 'Which detail best tells WHEN?', base: 'The show begins.', options: ['at dusk', 'loudly', 'under the seat'], answer: 'at dusk' },
        { stem: 'Which detail best tells HOW?', base: 'She answered the question.', options: ['quietly', 'three', 'outside'], answer: 'quietly' }
    ],
    rewrite: [
        { instruction: 'Put the parts in order to make one sentence:', shown: '"at the park"  "we played"  "and laughed"', answer: 'We played and laughed at the park.', open: false },
        { instruction: 'Put the parts in order to make one sentence:', shown: '"before lunch"  "practised"  "the teams"', answer: 'The teams practised before lunch.', open: false },
        { instruction: 'Put the parts in order to make one sentence:', shown: '"under the gum tree"  "we sat"  "and shared our lunch"', answer: 'We sat under the gum tree and shared our lunch.', open: false },
        { instruction: 'Put the parts in order to make one sentence:', shown: '"in the cool water"  "the kids splashed"', answer: 'The kids splashed in the cool water.', open: false },
        { instruction: 'Put the parts in order to make one sentence:', shown: '"every Saturday morning"  "we water the garden"', answer: 'Every Saturday morning we water the garden.', open: false },
        { instruction: 'Put the parts in order to make one sentence:', shown: '"with a shiny new helmet"  "she rode her bike"', answer: 'She rode her bike with a shiny new helmet.', open: false }
    ],
    compose: [
        { prompt: 'Write a sentence that tells WHEN something happened.', example: 'After lunch, the teams raced down the oval.' },
        { prompt: 'Write a sentence that tells WHERE you saw a bird.', example: 'A rosella perched on the school fence.' },
        { prompt: 'Write a sentence using "because" to give a reason.', example: 'We packed our swags because we were going camping.' },
        { prompt: 'Write a sentence using "and" to add two actions.', example: 'The wind rose and the kite soared.' }
    ]
};

// ── Year 4 (AC9E4LA06 complex clauses; AC9E4LA08 adverb/prepositional groups;
//    AC9E4LY06 linked ideas) ──────────────────────────────────────────────────
const BANK_Y4: CraftBank = {
    expand: [
        ['The storm rolled in', 'across the plain', 'The storm rolled in across the plain.'],
        ['Children cheered', 'along the fence line', 'Children cheered along the fence line.'],
        ['The ferry glided', 'through the harbour fog', 'The ferry glided through the harbour fog.'],
        ['She noted the time', 'on the library sign', 'She noted the time on the library sign.'],
        ['The concertina sounded', 'from the campfire', 'The concertina sounded from the campfire.'],
        ['Rain drummed', 'on the tin roof', 'Rain drummed on the tin roof.']
    ],
    join: [
        ['The kids ran inside', 'the storm arrived', 'as soon as', 'The kids ran inside as soon as the storm arrived.'],
        ['We still hiked to the lookout', 'the wind was strong', 'although', 'We still hiked to the lookout although the wind was strong.'],
        ['The dog barked', 'a stranger walked past', 'when', 'The dog barked when a stranger walked past.'],
        ['Mum kept reading', 'the train hummed on', 'while', 'Mum kept reading while the train hummed on.'],
        ['You must fasten your seatbelt', 'the car moves', 'before', 'You must fasten your seatbelt before the car moves.'],
        ['The class fell silent', 'the principal arrived', 'when', 'The class fell silent when the principal arrived.']
    ],
    mc: [
        { stem: 'Which detail best tells HOW the match ended?', base: 'The final whistle blew.', options: ['abruptly', 'tomorrow', 'at the oval'], answer: 'abruptly' },
        { stem: 'Which detail best tells WHEN?', base: 'We left the campsite.', options: ['at dawn', 'happily', 'near the river'], answer: 'at dawn' },
        { stem: 'Which detail best tells WHERE?', base: 'The flock wheeled.', options: ['above the gully', 'silently', 'yesterday'], answer: 'above the gully' },
        { stem: 'Which detail best tells HOW?', base: 'She folded the map.', options: ['neatly', 'three', 'outside'], answer: 'neatly' }
    ],
    rewrite: [
        { instruction: 'Join the three sentences into ONE sentence:', shown: '"The rain stopped."  "We unpacked the picnic."  "The sun came out."', answer: 'Example: After the rain stopped, we unpacked the picnic while the sun came out. (any sensible single sentence joining all three ideas is correct)', open: true },
        { instruction: 'Join the three sentences into ONE sentence:', shown: '"Ben forgot his lunch."  "Mia shared hers."  "Ben said thanks."', answer: 'Example: When Ben forgot his lunch, Mia shared hers, so Ben said thanks. (any sensible single sentence joining all three ideas is correct)', open: true },
        { instruction: 'Join the three sentences into ONE sentence:', shown: '"The kites rose."  "The wind picked up."  "Everyone cheered."', answer: 'Example: As the wind picked up, the kites rose and everyone cheered. (any sensible single sentence joining all three ideas is correct)', open: true },
        { instruction: 'Join the three sentences into ONE sentence:', shown: '"We planted the seeds."  "We watered them."  "We labelled the pots."', answer: 'Example: We planted the seeds, watered them and labelled the pots. (any sensible single sentence joining all three ideas is correct)', open: true }
    ],
    compose: [
        { prompt: 'Write a sentence that starts with "After the bell,".', example: 'After the bell, the students lined up quietly.' },
        { prompt: 'Write a sentence using "although" to show a surprise.', example: 'Although the trail was steep, we reached the lookout.' },
        { prompt: 'Write a sentence that starts with an "-ing" word.', example: 'Carrying the firewood, we hurried back to camp.' },
        { prompt: 'Write a sentence using "while" to show two things happening at once.', example: 'While Dad grilled, mum folded the chairs.' }
    ]
};

// ── Year 5 (AC9E5LA05 reason/purpose/condition/concession; AC9E5LA06
//    expanded noun groups) ───────────────────────────────────────────────────
const BANK_Y5: CraftBank = {
    expand: [
        ['The bird sang.', 'a detail about the bird AND its song', 'The bright yellow robin sang a cheerful song.', 'instruction'],
        ['The crowd cheered.', 'which crowd and how they cheered', 'The home crowd cheered wildly.', 'instruction'],
        ['A boat appeared.', 'what kind of boat and where it appeared', 'A small fishing boat appeared on the horizon.', 'instruction'],
        ['The teacher spoke.', 'which teacher and how they spoke', 'The science teacher spoke calmly.', 'instruction'],
        ['Storm clouds gathered.', 'what kind of clouds and where', 'Dark storm clouds gathered over the ranges.', 'instruction'],
        ['The old building stood empty.', 'which building and where', 'The old telegraph station stood empty.', 'instruction']
    ],
    join: [
        ['We set off before dawn', 'we would not miss the ferry', 'so that', 'We set off before dawn so that we would not miss the ferry.'],
        ['The picnic will be cancelled', 'the rain stops', 'unless', 'The picnic will be cancelled unless the rain stops.'],
        ['She still smiled', 'she had lost the race', 'although', 'She still smiled although she had lost the race.'],
        ['Plants grow faster here', 'the soil is rich', 'because', 'Plants grow faster here because the soil is rich.'],
        ['Turn off the tap', 'you leave the room', 'before', 'Turn off the tap before you leave the room.'],
        ['Keep your voice down', 'the movie is playing', 'while', 'Keep your voice down while the movie is playing.']
    ],
    mc: [
        { stem: 'Which sentence is COMPLEX (it contains a subordinate clause)?', options: ['Because the wind dropped, the sails went slack.', 'The wind dropped and the sails went slack.', 'The wind dropped suddenly.'], answer: 'Because the wind dropped, the sails went slack.' },
        { stem: 'Which sentence uses "unless" correctly?', options: ['Unless you hurry, you will miss the bus.', 'Unless you hurry, you will never hurry.', 'You will miss the bus unless you run fastly.'], answer: 'Unless you hurry, you will miss the bus.' },
        { stem: 'Which sentence shows a PURPOSE?', options: ['We practised twice more so that the finale was perfect.', 'We practised twice more because we were late.', 'We practised twice more and finished early.'], answer: 'We practised twice more so that the finale was perfect.' },
        { stem: 'Which sentence has a subject–verb AGREEMENT error?', options: ['The dogs barks at strangers.', 'The dogs bark at strangers.', 'The dog barks at strangers.'], answer: 'The dogs barks at strangers.' }
    ],
    rewrite: [
        { instruction: 'Rewrite starting with the words in [brackets]:', shown: '"The children ran inside when the storm came."  [When the storm came]', answer: 'When the storm came, the children ran inside.', open: false },
        { instruction: 'Rewrite starting with the words in [brackets]:', shown: '"She packed her bag and hurried to the bus."  [Packing her bag]', answer: 'Packing her bag, she hurried to the bus.', open: false },
        { instruction: 'Rewrite starting with the words in [brackets]:', shown: '"We ate breakfast before we walked to the lookout."  [Before we walked to the lookout]', answer: 'Before we walked to the lookout, we ate breakfast.', open: false },
        { instruction: 'Rewrite starting with the words in [brackets]:', shown: '"The concert started when the lights dimmed."  [When the lights dimmed]', answer: 'When the lights dimmed, the concert started.', open: false }
    ],
    compose: [
        { prompt: 'Write a complex sentence that gives a REASON for an action.', example: 'We filled the water bottles because the hike would be long.' },
        { prompt: 'Write a complex sentence that shows a PURPOSE (use "so that").', example: 'We left early so that we could catch the first ferry.' },
        { prompt: 'Write a complex sentence that states a CONDITION (use "unless").', example: 'The fireworks will go ahead unless the wind turns.' },
        { prompt: 'Write a complex sentence that concedes a point (use "although").', example: 'Although the queue was long, the ride was worth it.' }
    ]
};

// ── Year 6 (AC9E6LA05 embedded clauses; AC9E6LA06 precise verbs/adverbs;
//    AC9E6LA01 formality; AC9E6LA09 commas for clauses) ──────────────────────
const BANK_Y6: CraftBank = {
    expand: [
        // T9: three items were re-worded away from the Conjunction EMBED
        // bank's near-verbatim sentences (coach/twenty years, volunteer/
        // planted garden, fence/broken in the storm) — same embedded-clause
        // skill, different content so the two sheets don't echo each other.
        ['The curator smiled.', 'the curator had found the fossil first', 'The curator, who had found the fossil first, smiled.'],
        ['The footpath closed.', 'the footpath ran beside the creek', 'The footpath, which ran beside the creek, closed.'],
        ['A volunteer thanked the students.', 'the students had cleaned the creek', 'A volunteer thanked the students, who had cleaned the creek.'],
        ['The sign warned swimmers.', 'the sign had faded in the sun', 'The sign, which had faded in the sun, warned swimmers.'],
        ['My uncle repaired the fence.', 'the fence had been hit by a ute', 'My uncle repaired the fence, which had been hit by a ute.'],
        ['The old cinema reopened.', 'the cinema had closed in 1988', 'The old cinema, which had closed in 1988, reopened.']
    ],
    join: [
        ['The proposal was popular', 'the council rejected it', 'although', 'Although the proposal was popular, the council rejected it.'],
        ['Renewables are falling in cost', 'fossil fuels remain common', 'while', 'While renewables are falling in cost, fossil fuels remain common.'],
        ['The conclusion was sound', 'the data was incomplete', 'even though', 'Even though the data was incomplete, the conclusion was sound.'],
        ['Advertising targets children', 'they cannot judge persuasive intent', 'because', 'Advertising targets children because they cannot judge persuasive intent.'],
        ['A bike lane helps', 'it joins a connected network', 'only when', 'A bike lane helps only when it joins a connected network.'],
        ['The plan may work', 'funding continues', 'provided', 'The plan may work provided funding continues.']
    ],
    mc: [
        { stem: 'Which sentence contains an EMBEDDED clause?', options: ['The guide, who led our group, knew every trail.', 'The guide led our group and knew every trail.', 'The guide knew every trail.'], answer: 'The guide, who led our group, knew every trail.' },
        { stem: 'Which sentence is the most FORMAL?', options: ['The council made an error.', 'The council stuff-ups were bad.', 'The council really messed up.'], answer: 'The council made an error.' },
        { stem: 'Which sentence shows BIAS?', options: ['Our team played the best game ever.', 'The match finished 10 to 8.', 'Both teams scored early.'], answer: 'Our team played the best game ever.' },
        { stem: 'Which sentence uses a comma correctly after a fronted clause?', options: ['After the rain stopped, we set off.', 'After the rain, stopped we set off.', 'After the rain stopped we, set off.'], answer: 'After the rain stopped, we set off.' }
    ],
    rewrite: [
        { instruction: 'Rewrite in a FORMAL tone:', shown: '"The council stuff-ups cost us heaps."', answer: 'Example: The council\'s mistakes cost the community a great deal. (any sensible formal wording is correct)', open: true },
        { instruction: 'Rewrite PRECISELY (replace vague words):', shown: '"A lot of people reckoned the show was pretty good."', answer: 'Example: Many reviewers considered the show a success. (any sensible precise wording is correct)', open: true },
        { instruction: 'Remove the BIAS:', shown: '"Nobody in their right mind supports the new rule."', answer: 'Example: Some community members oppose the new rule. (any sensible neutral wording is correct)', open: true },
        { instruction: 'Rewrite in an OBJECTIVE tone:', shown: '"The terrible new footpath is a total waste."', answer: 'Example: The new footpath cost more than expected. (any sensible objective wording is correct)', open: true }
    ],
    compose: [
        { prompt: 'Write a complex sentence with an EMBEDDED clause (who/which/that) about a person or place you know.', example: 'The librarian, who remembers every student\'s name, recommended the book.' },
        { prompt: 'Write a FORMAL sentence reporting someone\'s opinion (use "according to" or an embedded clause).', example: 'According to the principal, the kitchen garden improved attendance.' },
        { prompt: 'Write a sentence that concedes a counter-argument (use "although" or "even though").', example: 'Although the excursion costs more, teachers say the learning is worth it.' },
        { prompt: 'Write an OBJECTIVE sentence summarising two opposing views.', example: 'Some families support the bike lane, while others prefer more parking.' }
    ]
};

// Explicit year-level routing via caps.level (T5) — clamp defensively so an
// unexpected level can never crash the generator.
const BANKS: Record<3 | 4 | 5 | 6, CraftBank> = { 3: BANK_Y3, 4: BANK_Y4, 5: BANK_Y5, 6: BANK_Y6 };

// Generator — FIVE kinds per year, same slots every year so the PROGRESSION
// is the bank, not the task type (learn/support → practise/core → stretch):
//   0 REORDER/REWRITE (scaffolded production, deterministic or model)
//   1 EXPAND (core: add detail / widen / embed)
//   2 JOIN (core: combine with a named conjunction)
//   3 MC ANALYSE (practise: judge the best option)
//   4 COMPOSE (stretch: open-ended, example + acceptance note)
function generateCraft(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const level = Math.min(Math.max(caps.level, 3), 6) as 3 | 4 | 5 | 6;
    const bank = BANKS[level];
    const expandDeck = localDeck(rng, bank.expand);
    const joinDeck = localDeck(rng, bank.join);
    const mcDeck = localDeck(rng, bank.mc);
    const rewriteDeck = localDeck(rng, bank.rewrite);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 4);
            if (kind === 4) {
                // STRETCH compose: example + acceptance (no false single key).
                const c = rng.pick(bank.compose);
                return {
                    prompt: `${c.prompt}\n${RULE}`,
                    answer: `Example: ${c.example} (any sensible sentence meeting the task is correct)`
                };
            }
            if (kind === 3) {
                // MC analyse: options joined with " / " (sentence options
                // contain commas, so ", " would be ambiguous). When the item
                // carries a base sentence, it prints before the option list.
                const m = mcDeck.take();
                const shown = shuffleLocal(rng, m.options);
                const stem = m.base ? `${m.stem} "${m.base}"` : m.stem;
                return { prompt: `${stem} (${shown.join(' / ')})`, answer: m.answer };
            }
            if (kind === 2) {
                const [main, sub, conj, joined] = joinDeck.take();
                return {
                    prompt: `Join the two sentences with "${conj}" to make one sentence:\n"${main}."  "${sub}."\n${RULE}`,
                    answer: joined
                };
            }
            if (kind === 1) {
                const [base, detail, expanded, style] = expandDeck.take();
                if (style === 'instruction') {
                    // T9: the "detail" is a WRITING INSTRUCTION (Y5 expanded
                    // noun groups), not a literal phrase — the stem asks for a
                    // descriptive rewrite and the rubric accepts any sensible
                    // descriptive wording (a "placement" rubric would be
                    // nonsensical for an instruction).
                    return {
                        prompt: `Make the sentence more descriptive — add ${detail}:\n"${base}"\n${RULE}`,
                        answer: `Example: ${expanded} (any sensible descriptive wording that covers the instruction is correct)`
                    };
                }
                return {
                    prompt: `Add the detail "${detail}" to the sentence. Write your new sentence:\n"${base}"\n${RULE}`,
                    answer: `Example: ${expanded} (any sensible placement of "${detail}" is correct)`
                };
            }
            // kind 0 — scaffolded rewrite/reorder. Deterministic answers for
            // reorders/openers; tone rewrites already carry their
            // "Example: ... (any sensible ... is correct)" guidance in the
            // bank itself (open: true items).
            const r = rewriteDeck.take();
            return { prompt: `${r.instruction}\n${r.shown}\n${RULE}`, answer: r.answer };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// Per-year scope line — exposes the sentence-crafting focus of each level.
const SCOPE_BY_LEVEL: Record<number, string> = {
    3: 'reorder, add detail, join with and/but/or/so/because',
    4: 'combine with when/while/although, add adverbial detail',
    5: 'complex sentences — reason, purpose, condition, concession',
    6: 'embedded clauses, varied openers, formal and objective tone'
};

// The plugin's declarative spec (exported for its own tests). Prose rows —
// single column, 4 rows per A4 page (task + ruled writing line each). T12:
// 6 rows exceeded the printable grid budget on keyed Y4–Y6 pages. T15: the
// corrected capacity model (PER-LINE wrapping at 45 chars/line honouring
// forced '\n' breaks, +16px inter-row gaps, +4px answer-key margins) showed
// 5 rows still left only ~14px headroom on keyed Craft Y6 pages at realistic
// metrics and clipped under the conservative 45ch stress — 4 rows restores a
// safe margin in BOTH metrics (see print-capacity.test.ts worst-page pins).
export const craftSpec: WorksheetSpec = {
    id: 'craft',
    label: 'Crafting Sentences',
    icon: '⤴',
    perPage: 4,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('craft'),
    scope: (grade: GradeConfig) => SCOPE_BY_LEVEL[grade.caps.level] ?? SCOPE_BY_LEVEL[3],
    generate: generateCraft
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CraftWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(craftSpec);
}
