// ─────────────────────────────────────────────────────────────────────────────
// EDITING & PROOFREADING WORKSHEET — a self-contained dashboard plugin
// (upper primary: Year 3–6; ACARA v9-informed — Y3 AC9E3LA11/LY09,
// Y4 AC9E4LA12/LY09, Y5 AC9E5LA09, Y6 AC9E6LA01/LA02/LA09).
//
// The dashboard loads this plugin by calling `EditingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Editing & Proofreading", glyph "✓") and which
//     grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Editing & Proofreading worksheet without affecting the
// framework or any other plugin.
//
// T5 DESIGN NOTES (editing/proofreading — the "spot and fix" companion to
// the crafting/writing families):
//   * Three deterministic kinds + one stretch kind, per year:
//       0 FIX    — correct the printed sentence (ruled rewrite line; the
//                  curated answer is the corrected sentence, or an
//                  "Example: ... (any sensible ... is accepted)" model for
//                  open rewordings);
//       1 SPOT   — name the KIND of error (multiple choice: capitalisation /
//                  punctuation / spelling / word choice / grammar);
//       2 CHOOSE — pick the one correct sentence among two buggy twins
//                  (CLOSED single-correct items only — T9; options joined
//                  with " / " because sentences contain commas);
//       3 IMPROVE (Year 5+ stretch) — rewrite more formally/precisely;
//                  marking guidance, never a false single key.
//   * YEAR PROGRESSION is explicit via caps.level: Y3 capital letters + end
//     punctuation; Y4 speech marks, AU spelling and commonly confused words
//     (its/it's, their/there); Y5 REQUIRED punctuation (list commas,
//     contraction apostrophes) + subject–verb agreement (T12: optional-style
//     commas — fronted adverbials, ambiguous defining/non-defining relatives —
//     are not keyed as errors); Y6 formality, precision and bias.
//     Year 5 and Year 6 banks are different error inventories.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// A ruled WRITING line for the rewrite answer.
const RULE = '__ __ __ __ __ __ __ __ __ __';

// One proofreading item: the buggy sentence, its curated correction, the
// error category, and `open` when the correction is a model rewording
// (answer key then prints "Example: ... (any sensible ... is accepted)").
type EditItem = { buggy: string; correct: string; category: 'capitalisation' | 'punctuation' | 'spelling' | 'word choice' | 'grammar'; open?: boolean };

// The five error categories (SPOT options are drawn from this list).
const CATEGORIES = ['capitalisation', 'punctuation', 'spelling', 'word choice', 'grammar'] as const;

// ── Year 3 (AC9E3LA11 sentence capitalisation/end punctuation basics) ───────
// T9: every SPOT example carries EXACTLY ONE error category — 'did you pack
// your lunchbox' and 'what a goal that was' originally mixed a lowercase
// opener with a missing end mark, making the "kind of mistake" key
// ambiguous; their buggy forms now carry only the flagged error.
const ITEMS_Y3: readonly EditItem[] = [
    { buggy: 'the dog ran home.', correct: 'The dog ran home.', category: 'capitalisation' },
    { buggy: 'We saw a kookaburra at dawn', correct: 'We saw a kookaburra at dawn.', category: 'punctuation' },
    { buggy: 'my sister and i rode our bikes.', correct: 'My sister and I rode our bikes.', category: 'capitalisation' },
    { buggy: 'Did you pack your lunchbox', correct: 'Did you pack your lunchbox?', category: 'punctuation' },
    { buggy: 'mum drove us to the show.', correct: 'Mum drove us to the show.', category: 'capitalisation' },
    { buggy: 'What a goal that was', correct: 'What a goal that was!', category: 'punctuation' },
    { buggy: 'we ate pancakes on sunday.', correct: 'We ate pancakes on Sunday.', category: 'capitalisation' },
    { buggy: 'Look out for the steps', correct: 'Look out for the steps.', category: 'punctuation' }
] as const;

// ── Year 4 (AC9E4LA12 dialogue punctuation; AC9E4LY09 unstressed vowels;
//    AC9E4LY11 homophones) ───────────────────────────────────────────────────
const ITEMS_Y4: readonly EditItem[] = [
    { buggy: 'Where is my hat said Jack.', correct: '"Where is my hat?" said Jack.', category: 'punctuation' },
    { buggy: 'My favorit colour is blue.', correct: 'My favourite colour is blue.', category: 'spelling' },
    { buggy: 'The dog wagged it\'s tail.', correct: 'The dog wagged its tail.', category: 'word choice' },
    { buggy: 'I love swimming said Mei.', correct: '"I love swimming," said Mei.', category: 'punctuation' },
    { buggy: 'We saw a flock of galahs at there place.', correct: 'We saw a flock of galahs at their place.', category: 'word choice' },
    { buggy: 'The train arrived late again', correct: 'The train arrived late again.', category: 'punctuation' },
    { buggy: 'My brother realy likes reptiles.', correct: 'My brother really likes reptiles.', category: 'spelling' },
    { buggy: 'Where do you live asked the tourist.', correct: '"Where do you live?" asked the tourist.', category: 'punctuation' }
] as const;

// ── Year 5 (AC9E5LA09 commas, prepositions, plural possessives; agreement) ──
// T12: two items replaced — a comma after a FRONTED ADVERBIAL ('After the
// storm passed…') is OPTIONAL style in Australian English, and a relative
// clause can be read as DEFINING ('My uncle who fixes bikes…' = which uncle),
// so neither sentence is unambiguously wrong. They are swapped for REQUIRED
// punctuation: list commas and a contraction apostrophe.
const ITEMS_Y5: readonly EditItem[] = [
    { buggy: 'We packed the torches the snacks and the map.', correct: 'We packed the torches, the snacks and the map.', category: 'punctuation' },
    { buggy: 'The dogs barks at strangers.', correct: 'The dogs bark at strangers.', category: 'grammar' },
    { buggy: 'Mum bought flour butter sugar and vanilla.', correct: 'Mum bought flour, butter, sugar and vanilla.', category: 'punctuation' },
    { buggy: 'Each of the students have a locker.', correct: 'Each of the students has a locker.', category: 'grammar' },
    { buggy: 'We couldnt find the southern lights.', correct: "We couldn't find the southern lights.", category: 'punctuation' },
    { buggy: 'The geese was swimming across the billabong.', correct: 'The geese were swimming across the billabong.', category: 'grammar' },
    { buggy: 'Bring the net I will hold the torch.', correct: 'Bring the net, and I will hold the torch.', category: 'punctuation', open: true },
    { buggy: 'Their going to love the display.', correct: 'They\'re going to love the display.', category: 'word choice' }
] as const;

// ── Year 6 (AC9E6LA01 formality; AC9E6LA02 bias; AC9E6LA09 commas/clauses) ──
// T9: three CLOSED (single-correct) comma items were added so the CHOOSE
// kind — now restricted to closed items (see generateEditing) — keeps a
// printed pool above the 500-question bar (T12: perPage 5 × 100 pages)
// despite dropping the open style/bias rewrites from multiple choice.
// T12: the two collective-noun twins ('The class were…', 'The committee
// have…') were re-worded to singular PERSONAL subjects — Australian English
// allows plural agreement with collectives by meaning ("the class were" is
// defensible), so a keyed "correct" sentence must not hinge on it. The
// flagged error in these items is the stray comma, now paired with an
// agreement-unambiguous subject.
const ITEMS_Y6: readonly EditItem[] = [
    { buggy: 'The council reckons the new pool will be heaps good.', correct: 'The council expects the new pool to be a great addition.', category: 'word choice', open: true },
    { buggy: 'Everyone knows the footy finals are the best event ever.', correct: 'Many people consider the football finals the highlight of the year.', category: 'word choice', open: true },
    { buggy: 'The report which was twelve pages long arrived late.', correct: 'The report, which was twelve pages long, arrived late.', category: 'punctuation' },
    { buggy: 'The old man, who was super old, crossed the road.', correct: 'The elderly man crossed the road.', category: 'word choice', open: true },
    { buggy: 'Neither of the answers are correct.', correct: 'Neither of the answers is correct.', category: 'grammar' },
    { buggy: 'We was late because the train broke down.', correct: 'We were late because the train broke down.', category: 'grammar' },
    { buggy: 'The new policy is pretty much a total disaster.', correct: 'The new policy has several serious drawbacks.', category: 'word choice', open: true },
    { buggy: 'The study proves, without any doubt, that recess should be longer.', correct: 'The study suggests that recess could be longer.', category: 'word choice', open: true },
    { buggy: 'Aisha was excited, when the bus arrived.', correct: 'Aisha was excited when the bus arrived.', category: 'punctuation' },
    { buggy: 'The principal released, the final report.', correct: 'The principal released the final report.', category: 'punctuation' },
    { buggy: 'The research shows, that the reef is warming.', correct: 'The research shows that the reef is warming.', category: 'punctuation' }
] as const;

// Stretch IMPROVE prompts (Year 5+): [instruction, source, model answer].
const IMPROVE_Y5: readonly [string, string, string][] = [
    ['Rewrite more PRECISELY (replace the vague words):', 'The show was pretty good and stuff.', 'Example: The show was entertaining and well organised. (any sensible precise wording is accepted)'],
    ['Rewrite with a FORMAL tone:', 'Mum reckons the canteen food is rubbish.', 'Example: My mother believes the canteen food is poor quality. (any sensible formal wording is accepted)'],
    ['Rewrite to remove the exaggeration:', 'Literally everyone hates the new uniform.', 'Example: Many students dislike the new uniform. (any sensible measured wording is accepted)'],
    ['Rewrite using technical vocabulary:', 'Plants grow better when farmers mix ash into the dirt after a fire.', 'Example: Plants germinate more successfully when nutrients from ash enrich the soil after a bushfire. (any sensible technical wording is accepted)']
] as const;

const IMPROVE_Y6: readonly [string, string, string][] = [
    ['Rewrite in a FORMAL, objective register:', 'The councillor\'s plan is a total joke, end of story.', 'Example: The councillor\'s plan has significant weaknesses that require further debate. (any sensible formal, objective wording is accepted)'],
    ['Rewrite to remove BIAS:', 'Only lazy commuters support the new bus lane.', 'Example: Some commuters support the new bus lane. (any sensible unbiased wording is accepted)'],
    ['Rewrite PRECISELY (replace vague language):', 'The project cost a lot but it is doing good things for the area.', 'Example: The project was expensive, but it has benefited the local community. (any sensible precise wording is accepted)'],
    ['Rewrite as a formal concession:', 'Yeah the trip costs more, but it is worth it and that is that.', 'Example: Although the excursion costs more, its educational value justifies the expense. (any sensible formal concession is accepted)']
] as const;

// Explicit year-level routing via caps.level (T5) — clamp defensively.
const BANKS: Record<3 | 4 | 5 | 6, readonly EditItem[]> = { 3: ITEMS_Y3, 4: ITEMS_Y4, 5: ITEMS_Y5, 6: ITEMS_Y6 };
const IMPROVE: Record<number, readonly [string, string, string][]> = { 5: IMPROVE_Y5, 6: IMPROVE_Y6 };

// Generator — kinds 0–2 every year, kind 3 (IMPROVE) from Year 5:
function generateEditing(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const level = Math.min(Math.max(caps.level, 3), 6) as 3 | 4 | 5 | 6;
    const bank = BANKS[level];
    const deck = localDeck(rng, bank);
    // T9: CHOOSE is restricted to CLOSED (single-correct) items — an "open"
    // item's correction is a style rewording, so its buggy twin is merely
    // informal/biased, not wrong, and "Which sentence is correct?" would
    // have several defensible answers. Open items stay in FIX (with
    // Example guidance) and IMPROVE.
    const closed = bank.filter((i) => !i.open);
    const closedDeck = localDeck(rng, closed);
    const maxKind = level >= 5 ? 3 : 2;
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, maxKind);
            if (kind === 3) {
                // STRETCH improve: open rewording with model + acceptance.
                const [instruction, source, model] = rng.pick(IMPROVE[level]);
                return { prompt: `${instruction}\n"${source}"\n${RULE}`, answer: model };
            }
            if (kind === 2) {
                // CHOOSE: the one correct sentence among the dealt closed
                // item's correction and two buggy twins from OTHER closed
                // items (options joined " / " — sentences contain commas).
                const item = closedDeck.take();
                const distractors = closed.filter((i) => i.buggy !== item.buggy);
                const d1 = rng.pick(distractors);
                let d2 = rng.pick(distractors);
                if (d2.buggy === d1.buggy) d2 = distractors[(distractors.indexOf(d1) + 1) % distractors.length];
                const shown = shuffleLocal(rng, [item.correct, d1.buggy, d2.buggy]);
                return { prompt: `Which sentence is correct? (${shown.join(' / ')})`, answer: item.correct };
            }
            const item = deck.take();
            if (kind === 0) {
                // FIX: rewrite the sentence. Open items (rewordings) print
                // their model + acceptance note; deterministic fixes print
                // the exact corrected sentence.
                const answer = item.open
                    ? `Example: ${item.correct} (any sensible corrected sentence is accepted)`
                    : item.correct;
                return { prompt: `Correct this sentence:\n"${item.buggy}"\n${RULE}`, answer };
            }
            // SPOT: name the error kind (category + two other categories).
            // Every bank sentence carries exactly ONE error category, so the
            // named kind is never ambiguous.
            const others = CATEGORIES.filter((c) => c !== item.category);
            const o1 = rng.pick(others);
            let o2 = rng.pick(others);
            if (o2 === o1) o2 = others[(others.indexOf(o1) + 1) % others.length];
            const shown = shuffleLocal(rng, [item.category, o1, o2]);
            return { prompt: `What kind of mistake is in this sentence?\n"${item.buggy}" (${shown.join(', ')})`, answer: item.category };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// Per-year scope line — exposes the editing-focus progression.
const SCOPE_BY_LEVEL: Record<number, string> = {
    3: 'capital letters and end punctuation',
    4: 'speech marks, spelling and commonly confused words',
    5: 'commas and subject–verb agreement',
    6: 'formality, precision and bias'
};

// The plugin's declarative spec (exported for its own tests). Prose rows —
// single column, 5 rows per A4 page (buggy sentence + rewrite line). T12:
// 6 rows exceeded the 915px printable grid budget on keyed pages (analytical
// model: 45 chars/line, 30px prompt line, 18.2px answer line); 5 rows keeps
// every grade inside the budget with the key ON.
export const editingSpec: WorksheetSpec = {
    id: 'editing',
    label: 'Editing & Proofreading',
    icon: '✓',
    perPage: 5,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('editing'),
    scope: (grade: GradeConfig) => SCOPE_BY_LEVEL[grade.caps.level] ?? SCOPE_BY_LEVEL[3],
    generate: generateEditing
};

// The plugin: a function the dashboard calls with its framework bundle.
export function EditingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(editingSpec);
}
