// ─────────────────────────────────────────────────────────────────────────────
// FIGURATIVE LANGUAGE WORKSHEET — a self-contained dashboard plugin (upper
// primary: Year 4+; ACARA Y4–6 — similes, metaphors, personification and
// alliteration in texts).
//
// The dashboard loads this plugin by calling `FigurativeWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Figurative Language", glyph "≋") and which grades
//     offer it (listed for Years 3–6 in the upper-primary catalogue — the
//     ACARA material itself is Y4–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Figurative Language worksheet without affecting the framework
// or any other plugin.
//
// DENSITY (distribution quality pass): perPage dropped 18 → 8 — the written
// families (explain a meaning, complete a phrase, write your own) need real
// writing room the 18-row grid never gave.
//
// TASK VARIETY: SIX connected families — interpret (name the technique,
// explain what the figure means, pick the example of a technique), apply
// (complete the conventional phrase, write your own figure), compare (same
// or different technique across two lines). Families are dealt from a KIND
// DECK so task types spread evenly down a page.
//
// ANSWER VALIDITY: every bank line is a single unambiguous technique with a
// curated plain-English meaning and the KEY word/phrase used for the
// completion family. "Write your own" rows are legitimately open-ended, so
// their answer field carries an "Example:" model answer.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Curated examples: [example line, technique, plain meaning, key word]. The
// key is the word/phrase the completion family masks; it always occurs in
// the example. For alliteration the "meaning" names the repeated sound (that
// is what the explain family asks about).
// (Exported for the plugin's own tests — the answer-correctness invariants
// re-derive expected answers straight from this bank.)
export const FIGURES: [string, string, string, string][] = [
    // Similes — comparisons with "like" or "as".
    ['as busy as a bee', 'simile', 'very busy', 'bee'],
    ['as brave as a lion', 'simile', 'very brave', 'lion'],
    ['as light as a feather', 'simile', 'very light', 'feather'],
    ['as cool as a cucumber', 'simile', 'very calm', 'cucumber'],
    ['runs like the wind', 'simile', 'runs very fast', 'wind'],
    ['sings like an angel', 'simile', 'sings beautifully', 'angel'],
    ['eats like a horse', 'simile', 'eats a lot', 'horse'],
    ['shines like a torch', 'simile', 'shines very brightly', 'torch'],
    ['quiet as a mouse', 'simile', 'very quiet', 'mouse'],
    ['smooth as glass', 'simile', 'very smooth', 'glass'],
    // Metaphors — saying one thing IS another.
    ['the classroom was a zoo', 'metaphor', 'the classroom was wild and noisy', 'zoo'],
    ['her smile is sunshine', 'metaphor', 'her smile makes everything feel warm and happy', 'sunshine'],
    ['the test was a breeze', 'metaphor', 'the test was very easy', 'breeze'],
    ['time is a thief', 'metaphor', 'time passes quickly before you notice', 'thief'],
    ['his heart is gold', 'metaphor', 'he is very kind', 'gold'],
    ['the world is a stage', 'metaphor', 'life is like a performance', 'stage'],
    ['my room is a disaster zone', 'metaphor', 'my room is very messy', 'disaster zone'],
    ['the baby is a little angel', 'metaphor', 'the baby is very good', 'angel'],
    ['the playground was a magnet', 'metaphor', 'the playground drew everyone in', 'magnet'],
    ['a sea of faces filled the hall', 'metaphor', 'a huge crowd of people', 'sea'],
    // Personification — things doing human things.
    ['the wind whispered through the trees', 'personification', 'the wind made a soft rustling sound', 'whispered'],
    ['the sun smiled down on us', 'personification', 'the sun felt warm and friendly', 'smiled'],
    ['the flowers danced in the breeze', 'personification', 'the flowers swayed about', 'danced'],
    ['the old car groaned up the hill', 'personification', 'the old car made a low straining sound', 'groaned'],
    ['the thunder growled all night', 'personification', 'the thunder rumbled loudly', 'growled'],
    ['the waves clapped on the shore', 'personification', 'the waves crashed noisily on the beach', 'clapped'],
    ['the clock glared at me', 'personification', 'the clock seemed to stare warningly', 'glared'],
    ['the stars winked above us', 'personification', 'the stars twinkled on and off', 'winked'],
    ['my tummy rumbled at lunchtime', 'personification', 'my tummy made a hungry sound', 'rumbled'],
    ['the trees waved at the passing cars', 'personification', 'the trees seemed to wave hello', 'waved'],
    // Alliteration — repeated beginning sounds.
    ['six sizzling sausages', 'alliteration', 'the s sound is repeated', 'sausages'],
    ['the big brown bear', 'alliteration', 'the b sound is repeated', 'bear'],
    ['wild and windy weather', 'alliteration', 'the w sound is repeated', 'weather'],
    ['quietly the quick quoll', 'alliteration', 'the q sound is repeated', 'quoll'],
    ['bright blue butterflies', 'alliteration', 'the b sound is repeated', 'butterflies'],
    ['the slippery snake slid silently', 'alliteration', 'the s sound is repeated', 'silently'],
    ['Peter Piper picked a peck', 'alliteration', 'the p sound is repeated', 'peck'],
    ['three thrifty thin thieves', 'alliteration', 'the th sound is repeated', 'thieves'],
    ['a fleet of flying fireflies', 'alliteration', 'the f sound is repeated', 'fireflies'],
    ['merry mice making music', 'alliteration', 'the m sound is repeated', 'music']
];

// Write-your-own prompts: [technique, topic, model example]. Each model is a
// bank line that genuinely illustrates the technique AND fits the topic, so
// the "Example:" answer is a valid sample of exactly what was asked.
const WRITE_OWN: [string, string, string][] = [
    ['simile', 'a fast runner', 'runs like the wind'],
    ['simile', 'a very busy day', 'as busy as a bee'],
    ['simile', 'a very quiet child', 'quiet as a mouse'],
    ['metaphor', 'a noisy classroom', 'the classroom was a zoo'],
    ['metaphor', 'an easy win', 'the test was a breeze'],
    ['metaphor', 'a very kind person', 'his heart is gold'],
    ['personification', 'a stormy night', 'the thunder growled all night'],
    ['personification', 'an old, noisy car', 'the old car groaned up the hill'],
    ['personification', 'a sunny morning', 'the sun smiled down on us'],
    ['alliteration', 'a snake', 'the slippery snake slid silently'],
    ['alliteration', 'cooking breakfast', 'six sizzling sausages'],
    ['alliteration', 'fireflies', 'a fleet of flying fireflies']
];

const TECHNIQUES = ['simile', 'metaphor', 'personification', 'alliteration'] as const;

// Figurative language — SIX connected families (upper primary):
//   0. MC technique (interpret): which technique does the printed line use
//   1. written meaning (interpret): explain what the figure means in plain
//      words (open-ended → "Example:" model from the curated bank)
//   2. MC example-of (interpret): which printed line is a <technique>
//   3. written complete (apply): fill the KEY word of the figurative phrase
//   4. MC same/different (compare): do two lines use the same technique?
//   5. written write-your-own (apply): compose an original figure on a topic
//      (open-ended → "Example:" model)
//
// NON-REPEATING SAMPLING: examples AND families are dealt from decks; every
// question passes through sampleUnique keyed on the printed prompt.
function generateFigurative(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, FIGURES);
    const kindDeck = localDeck(rng, [0, 1, 2, 3, 4, 5] as const);
    const ownDeck = localDeck(rng, WRITE_OWN);
    return sampleUnique(
        count,
        () => {
            const [example, technique, meaning, key] = itemDeck.take();
            const kind = kindDeck.take();
            if (kind === 0) {
                // MC technique: the answer beside the three other techniques.
                const others = TECHNIQUES.filter((t) => t !== technique);
                const shown = shuffleLocal(rng, [technique, ...others]);
                return { prompt: `Which technique is used: "${example}"? (${shown.join(', ')})`, answer: technique };
            }
            if (kind === 1) {
                // Written meaning: alliteration asks which sound repeats;
                // the other techniques ask for the plain-English sense.
                const ask = technique === 'alliteration'
                    ? `Which sound is repeated: "${example}"`
                    : `What does "${example}" mean? Write it in your own words.`;
                return { prompt: ask, answer: `Example: ${meaning}` };
            }
            if (kind === 2) {
                // MC example-of: one example of the asked technique beside two
                // examples of OTHER techniques (never the same line twice).
                const asked = rng.pick([...TECHNIQUES]);
                const right = rng.pick(FIGURES.filter(([, t]) => t === asked))[0];
                const wrongBank = FIGURES.filter(([, t]) => t !== asked);
                const wrongs: string[] = [];
                let guard = 0;
                while (wrongs.length < 2 && guard < 24) {
                    guard++;
                    const pick = rng.pick(wrongBank)[0];
                    if (pick !== right && !wrongs.includes(pick)) wrongs.push(pick);
                }
                const shown = shuffleLocal(rng, [right, ...wrongs]);
                // "an alliteration" — article agrees with the technique word.
                const article = asked === 'alliteration' ? 'an' : 'a';
                return { prompt: `Which example is ${article} ${asked}? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 3) {
                // Written complete: mask the curated KEY of the phrase — the
                // conventional word the child must supply.
                const masked = example.replace(key, '__');
                return { prompt: `Complete the figurative phrase: "${masked}"`, answer: key };
            }
            if (kind === 4) {
                // MC compare: same or different technique across two lines.
                // Half the pairs share the technique so BOTH answers occur.
                const sameWanted = rng.next() < 0.5;
                const pool = sameWanted
                    ? FIGURES.filter(([, t]) => t === technique)
                    : FIGURES.filter(([, t]) => t !== technique);
                let partner = rng.pick(pool)[0];
                let guard = 0;
                while (partner === example && guard < 24) {
                    guard++;
                    partner = rng.pick(pool)[0];
                }
                const answer = partner === example || sameWanted ? 'the same technique' : 'different techniques';
                const shown = shuffleLocal(rng, ['the same technique', 'different techniques']);
                return {
                    prompt: `Do these two use the same technique or different techniques: "${example}" and "${partner}"? (${shown.join(' / ')})`,
                    answer
                };
            }
            // Written write-your-own: original composition on a curated
            // topic; the answer field is a LABELED example, not the only
            // possible answer.
            const [ownTechnique, topic, model] = ownDeck.take();
            return {
                prompt: `Write your own ${ownTechnique} about ${topic}.`,
                answer: `Example: ${model}`
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). perPage 8:
// low density so the written families have real writing room.
export const figurativeSpec: WorksheetSpec = {
    id: 'figurative',
    label: 'Figurative Language',
    icon: '≋',
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('figurative'),
    scope: () => 'simile, metaphor, personification, alliteration',
    generate: generateFigurative
};

// The plugin: a function the dashboard calls with its framework bundle.
export function FigurativeWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(figurativeSpec);
}
