// ─────────────────────────────────────────────────────────────────────────────
// FIGURATIVE LANGUAGE WORKSHEET — a self-contained dashboard plugin (upper
// primary: Year 4+; ACARA Y4–6 — similes, metaphors, personification and
// alliteration in texts).
//
// The dashboard loads this plugin by calling `FigurativeWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Figurative Language", glyph "≋") and which grades
//     offer it (listed for Years 3–6 in the upper-primary catalogue — the
//     ACARA material itself is Y4–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Figurative Language worksheet without affecting the framework
// or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Curated examples with their technique: [example line, technique].
// Every line is a single technique, unambiguous for Y4–6.
const FIGURES: [string, string][] = [
    ['as busy as a bee', 'simile'],
    ['as brave as a lion', 'simile'],
    ['as light as a feather', 'simile'],
    ['as cool as a cucumber', 'simile'],
    ['runs like the wind', 'simile'],
    ['sings like an angel', 'simile'],
    ['eats like a horse', 'simile'],
    ['shines like a torch', 'simile'],
    ['the classroom was a zoo', 'metaphor'],
    ['her smile is sunshine', 'metaphor'],
    ['the test was a breeze', 'metaphor'],
    ['time is a thief', 'metaphor'],
    ['his heart is gold', 'metaphor'],
    ['the world is a stage', 'metaphor'],
    ['my room is a disaster zone', 'metaphor'],
    ['the wind whispered through the trees', 'personification'],
    ['the sun smiled down on us', 'personification'],
    ['the flowers danced in the breeze', 'personification'],
    ['the old car groaned up the hill', 'personification'],
    ['the thunder growled all night', 'personification'],
    ['the waves clapped on the shore', 'personification'],
    ['the clock glared at me', 'personification'],
    ['the stars winked above', 'personification'],
    ['six sizzling sausages', 'alliteration'],
    ['the big brown bear', 'alliteration'],
    ['wild and windy weather', 'alliteration'],
    ['quietly the quick quoll', 'alliteration'],
    ['bright blue butterflies', 'alliteration'],
    ['the slippery snake slid silently', 'alliteration'],
    ['Peter Piper picked a peck', 'alliteration']
];

// Figurative language — THREE procedural kinds (upper primary):
//   0. MC: which technique is the printed example (simile/metaphor/
//      personification/alliteration, one correct + 3 others)
//   1. written: name the technique of the printed example
//   2. MC: which of the three printed lines is a <technique> (one of the
//      four banks per question, others drawn from different techniques)
//
// NON-REPEATING SAMPLING: examples are dealt from a deck and every question
// passes through sampleUnique keyed on the printed prompt.
function generateFigurative(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, FIGURES);
    const TECHNIQUES = ['simile', 'metaphor', 'personification', 'alliteration'] as const;
    return sampleUnique(
        count,
        () => {
            const [example, technique] = itemDeck.take();
            const kind = rng.int(0, 2);
            if (kind === 0) {
                // MC technique: the answer beside three other techniques.
                const others = TECHNIQUES.filter((t) => t !== technique);
                const shown = shuffleLocal(rng, [technique, ...others]);
                return { prompt: `Which technique is used: "${example}"? (${shown.join(', ')})`, answer: technique };
            }
            if (kind === 1) {
                return { prompt: `Name the technique: "${example}"`, answer: technique };
            }
            // MC by technique: one example of the asked technique beside two
            // examples of OTHER techniques.
            const asked = rng.pick([...TECHNIQUES]);
            const right = rng.pick(FIGURES.filter(([, t]) => t === asked))[0];
            const wrongBank = FIGURES.filter(([, t]) => t !== asked);
            const wrongs: string[] = [];
            let guard = 0;
            while (wrongs.length < 2 && guard < 24) {
                guard++;
                const pick = rng.pick(wrongBank)[0];
                if (pick !== right && !wrongs.includes(pick)) wrongs.push(pick);
            }
            const shown = shuffleLocal(rng, [right, ...wrongs]);
            return { prompt: `Which example is a ${asked}? (${shown.join(' / ')})`, answer: right };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests).
export const figurativeSpec: WorksheetSpec = {
    id: 'figurative',
    label: 'Figurative Language',
    icon: '≋',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('figurative'),
    scope: () => 'simile, metaphor, personification, alliteration',
    generate: generateFigurative
};

// The plugin: a function the dashboard calls with its framework bundle.
export function FigurativeWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(figurativeSpec);
}
