// ─────────────────────────────────────────────────────────────────────────────
// HOMOGRAPHS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 4+ — words spelled the same with different meanings; ACARA Y4–6
// vocabulary: "bat", "light", "wave" …).
//
// The dashboard loads this plugin by calling `HomographWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Homographs", glyph "⚭") and which grades offer it
//     (listed for Years 3–6 in the upper-primary catalogue — the ACARA
//     material itself is Y4–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Homographs worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Homograph items: [word, meaning A sentence, meaning B sentence] — the word
// fits BOTH sentences; the child matches word -> meaning.
const HOMOGRAPH_ITEMS: [string, string, string][] = [
    ['bat', 'A __ flew out of the cave at dusk.', 'Pick up the __ and hit the ball.'],
    ['light', 'The room felt dark until she turned on the __ .', 'This bag is very __ to carry.'],
    ['wave', 'The surfer rode a huge __ .', 'Give your friend a friendly __ goodbye.'],
    ['ring', 'The boxer stepped into the __ .', 'Grandma wears a gold __ .'],
    ['bank', 'We had a picnic on the river __ .', 'I keep my savings in the __ .'],
    ['match', 'The two teams played a close __ .', 'Use a __ to light the candle.'],
    ['palm', 'A tall __ tree shaded the beach.', 'The __ of my hand itched.'],
    ['trunk', 'The elephant sprayed water from its __ .', 'We packed the car boot and the __ .'],
    ['band', 'A rubber __ held the letters together.', 'The school __ played at assembly.'],
    ['bark', 'The dog gave a loud __ .', 'The __ of the tree is rough.'],
    ['watch', '__ the baby birds until they fly.', 'I checked my __ for the time.'],
    ['play', 'The children __ in the park.', 'We saw a __ at the theatre.'],
    ['letter', 'I posted a __ to my cousin.', 'Every __ of the alphabet has a shape.'],
    ['seal', 'A __ flopped onto the rocks.', 'She pressed a __ on the envelope.'],
    ['crane', 'A __ bird waded through the shallows.', 'The building __ lifted the steel beams.'],
    ['current', 'The river __ pulled the canoe sideways.', 'Electric __ flows through the wire.'],
    ['file', 'Keep the papers in a __ .', 'The carpenter smoothed the edge with a __ .'],
    ['fly', 'A __ buzzed around the kitchen.', 'The birds __ south for winter.'],
    ['rock', 'The boat bumped against a __ .', 'Guitars, drums and a singer make a __ band.'],
    ['spring', 'Water bubbled from a natural __ .', 'The mattress __ creaked under him.']
];

// Homographs — THREE procedural kinds (upper primary):
//   0. MC: "which meaning fits '<word>'?" (two meaning glosses + one from
//      another word; keyed on the sentence pairs)
//   1. written: "write a sentence-sense for '<word>' — animal, thing or
//      action?" (the child names the class of the drawn sense)
//   2. MC: which word completes BOTH kinds of sentence (the homograph beside
//      two bank words that fit neither)
//
// NON-REPEATING SAMPLING: items AND sense direction are dealt from decks and
// every question passes through sampleUnique keyed on the printed prompt.
function generateHomograph(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, HOMOGRAPH_ITEMS);
    const bankWords = HOMOGRAPH_ITEMS.map(([w]) => w);
    return sampleUnique(
        count,
        () => {
            const [word, senseA, senseB] = itemDeck.take();
            const kind = rng.int(0, 2);
            if (kind === 0) {
                // MC: pick the sentence where the word fits (both do! — so we
                // ask for the OTHER bank word instead; simpler: ask which
                // bank word fits a given sentence).
                const [, sA, sB] = HOMOGRAPH_ITEMS.find(([w]) => w === word)!;
                const target = rng.next() < 0.5 ? [word, sA] : [word, sB];
                const others = shuffleLocal(rng, bankWords.filter((w) => w !== word)).slice(0, 2);
                const shown = shuffleLocal(rng, [target[0], ...others]);
                return { prompt: `Which word fits the gap: ${target[1]} (${shown.join(', ')})`, answer: target[0] };
            }
            if (kind === 1) {
                // Sense class: does the word mean an animal, a thing or an
                // action in the printed sentence? (Curated per item sense.)
                const sense = rng.next() < 0.5 ? senseA : senseB;
                return { prompt: `What does "${word}" mean in this sentence? ${sense}`, answer: HOMOGRAPH_SENSE[`${word}|${sense}`] ?? 'thing' };
            }
            // MC: which bank word can have BOTH printed meanings?
            const others = shuffleLocal(rng, bankWords.filter((w) => w !== word)).slice(0, 2);
            const shown = shuffleLocal(rng, [word, ...others]);
            return {
                prompt: `Which word fits both sentences: "${senseA}" and "${senseB}"? (${shown.join(', ')})`,
                answer: word
            };
        },
        (p) => p.prompt
    );
}

// Sense-class gloss keyed by "word|sentence" — hand-curated for each item
// sense (kind 1 above). Any unlisted key falls back to 'thing'.
const HOMOGRAPH_SENSE: Record<string, string> = {
    'bat|A __ flew out of the cave at dusk.': 'an animal',
    'bat|Pick up the __ and hit the ball.': 'a thing',
    'light|The room felt dark until she turned on the __ .': 'a thing',
    'light|This bag is very __ to carry.': 'a describing word',
    'wave|The surfer rode a huge __ .': 'a thing',
    'wave|Give your friend a friendly __ goodbye.': 'an action',
    'ring|The boxer stepped into the __ .': 'a place',
    'ring|Grandma wears a gold __ .': 'a thing',
    'bank|We had a picnic on the river __ .': 'a place',
    'bank|I keep my savings in the __ .': 'a place',
    'match|The two teams played a close __ .': 'an event',
    'match|Use a __ to light the candle.': 'a thing',
    'palm|A tall __ tree shaded the beach.': 'a plant',
    'palm|The __ of my hand itched.': 'a body part',
    'trunk|The elephant sprayed water from its __ .': 'a body part',
    'trunk|We packed the car boot and the __ .': 'a thing',
    'band|A rubber __ held the letters together.': 'a thing',
    'band|The school __ played at assembly.': 'a group',
    'bark|The dog gave a loud __ .': 'a sound',
    'bark|The __ of the tree is rough.': 'a thing',
    'watch|__ the baby birds until they fly.': 'an action',
    'watch|I checked my __ for the time.': 'a thing',
    'play|The children __ in the park.': 'an action',
    'play|We saw a __ at the theatre.': 'an event',
    'letter|I posted a __ to my cousin.': 'a thing',
    'letter|Every __ of the alphabet has a shape.': 'a symbol',
    'seal|A __ flopped onto the rocks.': 'an animal',
    'seal|She pressed a __ on the envelope.': 'a thing',
    'crane|A __ bird waded through the shallows.': 'an animal',
    'crane|The building __ lifted the steel beams.': 'a machine',
    'current|The river __ pulled the canoe sideways.': 'a flow',
    'current|Electric __ flows through the wire.': 'a flow',
    'file|Keep the papers in a __ .': 'a thing',
    'file|The carpenter smoothed the edge with a __ .': 'a tool',
    'fly|A __ buzzed around the kitchen.': 'an insect',
    'fly|The birds __ south for winter.': 'an action',
    'rock|The boat bumped against a __ .': 'a thing',
    'rock|Guitars, drums and a singer make a __ band.': 'music',
    'spring|Water bubbled from a natural __ .': 'a place',
    'spring|The mattress __ creaked under him.': 'a thing'
};

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests).
export const homographSpec: WorksheetSpec = {
    id: 'homograph',
    label: 'Homographs',
    icon: '⚭',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('homograph'),
    scope: () => 'same spelling, new meaning',
    generate: generateHomograph
};

// The plugin: a function the dashboard calls with its framework bundle.
export function HomographWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(homographSpec);
}
