// ─────────────────────────────────────────────────────────────────────────────
// HOMOGRAPHS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 4+ — words spelled the same with different meanings; ACARA Y4–6
// vocabulary: "bat", "light", "wave" …).
//
// The dashboard loads this plugin by calling `HomographWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Homographs", glyph "⚭") and which grades offer it
//     (listed for Years 3–6 in the upper-primary catalogue — the ACARA
//     material itself is Y4–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Homographs worksheet without affecting the framework or any
// other plugin.
//
// DENSITY (distribution quality pass): perPage dropped 18 → 8. Eight rows on
// the A4 grid (framework PrintableSheet `gridAutoRows: 1fr`) gives every task
// real writing room — several families ask the child to write a sentence or
// explain a meaning, which an 18-row page cannot accommodate.
//
// TASK VARIETY: SIX connected families instead of three MC-heavy kinds —
// interpret (gap, meaning-in-sentence, meaning-choice), compare (fits-both),
// edit (spot-and-replace a misused word) and apply (write-your-own). Families
// are dealt from a KIND DECK so a page never clumps into one task type.
//
// ANSWER VALIDITY: every multiple-choice distractor is CURATED per item
// (fields d1/d2) — a bank word that fits NEITHER of the item's sense
// sentences — so each MCQ has exactly one defensible answer. Written sense
// answers come from the per-sense gloss (no fallback guesses). Open-ended
// "write your own" rows carry an "Example:" model answer in the answer field
// so the teacher key is clearly a sample, not the only right answer.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Homograph items: [word, sense A sentence, sense A gloss, sense B sentence,
// sense B gloss, distractor word 1, distractor word 2]. The word fits BOTH
// sense sentences; d1/d2 are bank words that fit NEITHER (curated, so the MC
// families are unambiguous). Sentences print the gap as "__".
// (Exported for the plugin's own tests — the answer-correctness invariants
// re-derive expected answers straight from this bank.)
export const HOMOGRAPH_ITEMS: [string, string, string, string, string, string, string][] = [
    ['bat', 'A __ flew out of the cave at dusk.', 'a night-flying animal', 'Pick up the __ and hit the ball.', 'a stick for hitting a ball', 'seal', 'ring'],
    ['light', 'The room was dark until she turned on the __ .', 'a bright lamp or glow', 'This bag is very __ to carry.', 'not heavy', 'trunk', 'crane'],
    ['wave', 'The surfer rode a huge __ to the shore.', 'a moving ridge of sea water', 'Give your friend a friendly __ goodbye.', 'a greeting with your hand', 'file', 'stamp'],
    ['ring', 'The boxer stepped into the __ .', 'the roped area for a fight', 'Grandma wears a gold __ on her finger.', 'a band worn on a finger', 'bank', 'palm'],
    ['bank', 'We had a picnic on the river __ .', 'the land beside a river', 'I keep my savings in the __ .', 'a place that keeps money', 'bat', 'wave'],
    ['match', 'The two teams played a close __ .', 'a game between two sides', 'Strike a __ to light the candle.', 'a small stick that makes fire', 'mouse', 'organ'],
    ['palm', 'A tall __ tree shaded the beach.', 'a tropical tree with fronds', 'The __ of my hand itched.', 'the middle of your hand', 'ring', 'bat'],
    ['trunk', 'The elephant sprayed water from its __ .', "an elephant's long nose", 'We packed the __ in the car boot for the trip.', 'a large suitcase', 'light', 'seal'],
    ['band', 'A rubber __ held the letters together.', 'a stretchy strip', 'The school __ played at assembly.', 'a group of musicians', 'wave', 'file'],
    ['bark', 'The dog gave a loud __ at the stranger.', 'the sharp sound a dog makes', 'The __ of the tree is rough.', 'the outer covering of a tree', 'match', 'palm'],
    ['watch', '__ the baby birds until they fly.', 'to look at for a while', 'I checked my __ for the time.', 'a small clock you wear', 'spring', 'tail'],
    ['play', 'The children __ in the park after lunch.', 'to take part in a game', 'We saw a __ at the theatre.', 'a show on a stage', 'ring', 'bat'],
    ['letter', 'I posted a __ to my cousin.', 'a message in an envelope', 'Every __ of the alphabet has a shape.', 'a symbol of the alphabet', 'wave', 'bank'],
    ['seal', 'A __ flopped onto the rocks.', 'a flippered sea animal', 'She pressed a wax __ on the envelope.', 'a stamp that closes a letter', 'light', 'match'],
    ['crane', 'A __ bird waded through the shallows.', 'a long-legged, long-necked bird', 'The building __ lifted the steel beams.', 'a machine that lifts heavy loads', 'palm', 'trunk'],
    ['current', 'The river __ pulled the canoe sideways.', 'a moving flow of water', "She is the __ champion, not last year's winner.", 'of right now', 'bat', 'seal'],
    ['file', 'Keep the papers in a __ .', 'a folder for papers', 'The carpenter smoothed the edge with a __ .', 'a tool for smoothing wood or metal', 'wave', 'band'],
    ['fly', 'A __ buzzed around the kitchen.', 'a small winged insect', 'The birds __ south for winter.', 'to travel through the air', 'ring', 'current'],
    ['rock', 'The boat bumped against a __ .', 'a large piece of stone', 'Guitars, drums and a singer make a __ band.', 'a style of loud music', 'file', 'light'],
    ['spring', 'Water bubbled from a natural __ .', 'a place where water rises from the ground', 'The mattress __ creaked under him.', 'a coiled ring that bounces', 'watch', 'bank'],
    ['date', 'A __ is a sweet fruit that grows on tall palms.', 'a sweet brown fruit', 'Check the __ on the invitation to see when the show starts.', 'a day on the calendar', 'bat', 'wave'],
    ['minute', 'Wait one __ and I will be ready.', 'sixty seconds', 'The crack in the wall was almost __ .', 'very small', 'seal', 'rock'],
    ['park', 'We played football in the __ after school.', 'a public green area', 'Dad had to __ the car twice to find a space.', 'to stop and leave a vehicle', 'ring', 'bat'],
    ['well', 'The village drew water from the old __ .', 'a deep hole that holds water', 'The choir sang __ at the concert.', 'in a good way', 'light', 'wave'],
    ['mouse', 'A __ squeaked behind the cupboard.', 'a small grey animal', 'Click the __ to open the file.', 'a hand-held computer pointer', 'palm', 'crane'],
    ['organ', 'The heart is an __ that pumps blood.', 'a part of a living body', 'The __ music filled the church hall.', 'a large keyboard instrument', 'bat', 'match'],
    ['head', 'The boy bumped his __ on the low branch.', 'the top part of a body', 'The __ of the line waved at the teacher.', 'the person in charge', 'file', 'band'],
    ['tail', 'The dog wagged its __ happily.', 'the tail end of an animal', 'The police decided to __ the suspect.', 'to follow secretly', 'light', 'seal']
];

// All sense glosses (the meaning pool for the MC-meaning family's third
// option). Every gloss string is unique across the bank, so a foreign gloss
// can never equal the item's own two senses.
const ALL_GLOSSES: string[] = HOMOGRAPH_ITEMS.flatMap(([, , gA, , gB]) => [gA, gB]);

// Homographs — SIX connected families (upper primary):
//   0. MC gap (interpret): which bank word fits the printed sense sentence
//   1. written sense (interpret): what does the word mean in this sentence
//   2. MC meaning (interpret): which gloss fits the word in this sentence
//      (the item's other-sense gloss + one foreign gloss as distractors)
//   3. MC edit (edit): a misused word in a sentence — which word replaces it
//   4. written apply (apply): write your own sentence for a given sense
//      (open-ended → the answer field carries an "Example:" model)
//   5. MC both (compare): which word fits BOTH sense sentences
//
// NON-REPEATING SAMPLING: items AND families are dealt from decks (the kind
// deck spreads task types evenly across a page) and every question passes
// through sampleUnique keyed on the printed prompt.
function generateHomograph(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, HOMOGRAPH_ITEMS);
    const kindDeck = localDeck(rng, [0, 1, 2, 3, 4, 5] as const);
    return sampleUnique(
        count,
        () => {
            const [word, senseA, glossA, senseB, glossB, d1, d2] = itemDeck.take();
            const kind = kindDeck.take();
            if (kind === 0) {
                // MC gap: one sense sentence, the word beside its two curated
                // non-fitting distractors.
                const [sense] = rng.next() < 0.5 ? [senseA] : [senseB];
                const shown = shuffleLocal(rng, [word, d1, d2]);
                return { prompt: `Which word fits the gap: ${sense} (${shown.join(', ')})`, answer: word };
            }
            if (kind === 1) {
                // Written sense: the printed sentence's gloss is the exact
                // answer (curated per sense — never a fallback guess).
                const useA = rng.next() < 0.5;
                const sense = useA ? senseA : senseB;
                return { prompt: `What does "${word}" mean in this sentence? ${sense}`, answer: useA ? glossA : glossB };
            }
            if (kind === 2) {
                // MC meaning: the correct gloss beside the word's OTHER-sense
                // gloss (wrong for this sentence) and one foreign gloss.
                const useA = rng.next() < 0.5;
                const sense = useA ? senseA : senseB;
                const right = useA ? glossA : glossB;
                const own = useA ? glossB : glossA;
                const foreign = pickForeignGloss(rng, glossA, glossB);
                const shown = shuffleLocal(rng, [right, own, foreign]);
                return { prompt: `Which meaning fits "${word}" in "${sense}"? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 3) {
                // MC edit: Mia wrote the sentence with a word that fits
                // neither sense — the child names the replacement.
                const useA = rng.next() < 0.5;
                const sense = useA ? senseA : senseB;
                const wrong = useA ? d1 : d2;
                const other = useA ? d2 : d1;
                const edited = sense.replace('__', wrong);
                const shown = shuffleLocal(rng, [word, wrong, other]);
                return { prompt: `Mia wrote: "${edited}" Which word should replace "${wrong}"? (${shown.join(', ')})`, answer: word };
            }
            if (kind === 4) {
                // Written apply: open-ended sentence writing. The answer
                // field is a LABELED example (the item's own sense sentence),
                // so the key shows one valid model without claiming to be the
                // only correct response.
                const useA = rng.next() < 0.5;
                const gloss = useA ? glossA : glossB;
                const sense = useA ? senseA : senseB;
                return { prompt: `Write your own sentence using "${word}" to mean ${gloss}.`, answer: `Example: ${sense.replace('__', word)}` };
            }
            // MC both (compare): the homograph beside its two non-fitting
            // distractors — only the homograph completes BOTH sentences.
            const shown = shuffleLocal(rng, [word, d1, d2]);
            return {
                prompt: `Which word fits both sentences: "${senseA}" and "${senseB}"? (${shown.join(', ')})`,
                answer: word
            };
        },
        (p) => p.prompt
    );
}

// Pick a gloss from another item (never the dealt item's own two senses) —
// the third option for the MC-meaning family. Guarded loop: the pool is far
// larger than the two excluded glosses, so it always resolves.
function pickForeignGloss(rng: Rng, ownA: string, ownB: string): string {
    for (let guard = 0; guard < 24; guard++) {
        const g = rng.pick(ALL_GLOSSES);
        if (g !== ownA && g !== ownB) return g;
    }
    return ALL_GLOSSES.find((g) => g !== ownA && g !== ownB) as string;
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). perPage 8:
// low density so the written/apply families have real writing room.
export const homographSpec: WorksheetSpec = {
    id: 'homograph',
    label: 'Homographs',
    icon: '⚭',
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('homograph'),
    scope: () => 'same spelling, new meaning',
    generate: generateHomograph
};

// The plugin: a function the dashboard calls with its framework bundle.
export function HomographWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(homographSpec);
}
