// ─────────────────────────────────────────────────────────────────────────────
// IDIOMS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 5+; ACARA Y5–6 vocabulary — figurative idioms and their real meaning).
//
// The dashboard loads this plugin by calling `IdiomWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Idioms", glyph "☁") and which grades offer it
//     (listed for Years 3–6 in the upper-primary catalogue — the ACARA
//     material itself is Y5–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Idioms worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Idiom items: [idiom, real meaning, distractor meaning A, distractor B].
// Distractors are literal-ish readings — the classic trap the worksheet
// teaches children to avoid.
const IDIOM_ITEMS: [string, string, string, string][] = [
    ['raining cats and dogs', 'raining very heavily', 'pets falling from the sky', 'a rain storm with animals'],
    ['piece of cake', 'very easy', 'a slice of dessert', 'a small part of a cake'],
    ['under the weather', 'feeling unwell', 'standing in the rain', 'feeling cold outside'],
    ['spill the beans', 'reveal a secret', 'drop the dinner', 'lose your temper'],
    ['hit the sack', 'go to bed', 'punch a pillow', 'pack up the camping gear'],
    ['pull your socks up', 'try harder', 'get dressed faster', 'tidy your room'],
    ['cold feet', 'nervous about something', 'feeling chilly', 'standing on ice'],
    ['in hot water', 'in trouble', 'having a bath', 'swimming at the beach'],
    ['big cheese', 'the person in charge', 'a large block from the deli', 'a popular snack'],
    ['in a pickle', 'in a tricky situation', 'eating sandwiches', 'in a jar'],
    ['on cloud nine', 'extremely happy', 'flying a plane', 'dreaming at night'],
    ['over the moon', 'delighted', 'in outer space', 'on a trampoline'],
    ['hold your horses', 'be patient', 'gallop away', 'hug your pet'],
    ['butterflies in your tummy', 'feeling nervous', 'a caterpillar home', 'feeling hungry'],
    ['break the ice', 'start a conversation', 'crack frozen water', 'chill the drinks'],
    ['head in the clouds', 'daydreaming', 'being very tall', 'watching the sky'],
    ['keep your eyes peeled', 'stay alert and watch', 'rub your eyes', 'take off your glasses'],
    ['the last straw', 'the final problem that breaks patience', 'a drinking tube', 'the end of harvest']
];

// Idioms — THREE procedural kinds (upper primary):
//   0. MC: what does the idiom really mean (answer beside 2 curated
//      distractors)
//   1. MC: which sentence uses the idiom correctly (the sense sentence
//      beside two misused senses)
//   2. written: complete the idiom ("raining ___ and ___")
//
// NON-REPEATING SAMPLING: items are dealt from a deck and every question
// passes through sampleUnique keyed on the printed prompt.
function generateIdiom(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, IDIOM_ITEMS);
    return sampleUnique(
        count,
        () => {
            const [idiom, meaning, d1, d2] = itemDeck.take();
            const kind = rng.int(0, 2);
            if (kind === 0) {
                const shown = shuffleLocal(rng, [meaning, d1, d2]);
                return { prompt: `What does it mean to be "${idiom}"? (${shown.join(' / ')})`, answer: meaning };
            }
            if (kind === 1) {
                // MC: which sentence uses the idiom with its REAL sense. The
                // two wrong sentences read the idiom literally.
                const right = `When the party was cancelled, Sam was "${idiom}" - ${meaning}.`;
                const wrong1 = `Jake looked outside and saw "${idiom}" - ${d1}.`;
                const wrong2 = `Miss Lee said "${idiom}" because ${d2}.`;
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return { prompt: `Which sentence uses the idiom "${idiom}" correctly? (${shown.join(' / ')})`, answer: right };
            }
            // Written: complete the idiom's missing words.
            const words = idiom.split(' ');
            const masked = words
                .map((w, i) => (i % 2 === 0 ? '__' : w))
                .join(' ');
            return { prompt: `Complete the idiom: ${masked}`, answer: idiom };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn.
export const idiomSpec: WorksheetSpec = {
    id: 'idiom',
    label: 'Idioms',
    icon: '☁',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('idiom'),
    scope: () => 'sayings & their meanings',
    generate: generateIdiom
};

// The plugin: a function the dashboard calls with its framework bundle.
export function IdiomWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(idiomSpec);
}
