// ─────────────────────────────────────────────────────────────────────────────
// IDIOMS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 5+; ACARA Y5–6 vocabulary — figurative idioms and their real meaning).
//
// The dashboard loads this plugin by calling `IdiomWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Idioms", glyph "☁") and which grades offer it
//     (listed for Years 3–6 in the upper-primary catalogue — the ACARA
//     material itself is Y5–6);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Idioms worksheet without affecting the framework or any other
// plugin.
//
// DENSITY (distribution quality pass): perPage dropped 16 → 6 (single
// column). Idioms are the writing-heavy sheet — explaining, completing and
// composing sentences needs full-width rows with room to write.
//
// SEMANTIC VARIETY (the old sheet's core flaw): the previous generator built
// every "which sentence uses it correctly" row from ONE fixed frame ("When
// the party was cancelled, Sam was ...") for all 18 idioms — high option
// churn, near-zero context variety. Now EVERY idiom carries its OWN curated
// correct-usage sentence plus two literal-misreading sentences across varied
// contexts (classroom, farm, kitchen, sport, weather, travel …), and the
// bank grew 18 → 24 idioms.
//
// TASK VARIETY: SIX connected families — interpret (real meaning, correct
// sentence), apply (complete the idiom, write your own), compare/justify
// (which idiom matches this meaning; explain WHY a literal reading misuses
// it). Families are dealt from a KIND DECK for even spread.
//
// ANSWER VALIDITY: meanings, distractors and usage sentences are curated per
// idiom, so every MCQ has exactly one defensible answer. Open-ended rows
// carry an "Example:" model answer in the answer field.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Idiom items: [idiom, real meaning, literal distractor A, literal
// distractor B, correct-usage sentence, literal-misuse sentence A,
// literal-misuse sentence B]. The two misuse sentences read the idiom
// literally — the classic trap the worksheet teaches children to avoid —
// each in its OWN context (no shared frame).
// (Exported for the plugin's own tests — the answer-correctness invariants
// re-derive expected answers straight from this bank.)
export const IDIOM_ITEMS: [string, string, string, string, string, string, string][] = [
    ['raining cats and dogs', 'raining very heavily', 'pets falling from the sky', 'a storm with animals in it',
        'We got soaked walking home because it was raining cats and dogs.',
        'Maya saw raining cats and dogs fall into the garden.',
        'The zoo announced a new display of raining cats and dogs.'],
    ['piece of cake', 'very easy', 'a slice of dessert', 'a small part of a cake',
        'The spelling quiz was a piece of cake for Priya.',
        'At the picnic, Ben ate a piece of cake and saved the rest.',
        'The baker cut the piece of cake into eight slices.'],
    ['under the weather', 'feeling unwell', 'standing in the rain', 'feeling cold outside',
        'Ari stayed home because he was feeling under the weather.',
        'The hikers hid under the weather to avoid the hail.',
        'The forecast said under the weather would arrive by noon.'],
    ['spill the beans', 'reveal a secret', 'drop the dinner', 'lose your temper',
        'Who spilled the beans about the surprise party?',
        'The cook spilled the beans all over the kitchen floor.',
        'Be careful not to spill the beans at the picnic.'],
    ['hit the sack', 'go to bed', 'punch a pillow', 'pack up the camping gear',
        'After the long trip, we were ready to hit the sack.',
        'At the campsite, the boy hit the sack with a stick.',
        'Please hit the sack before we load the car.'],
    ['pull your socks up', 'try harder and improve', 'get dressed faster', 'tidy your room',
        'Mr Lee told the team to pull their socks up before the final.',
        'The baby laughed as Dad pulled his socks up.',
        'Pull your socks up before the inspector checks the bedroom.'],
    ['cold feet', 'nervous about something', 'feeling chilly', 'standing on ice',
        'Before the big speech, Tessa got cold feet but stepped on stage anyway.',
        'In the snow, the boy complained about his cold feet.',
        'The penguin was famous for its cold feet.'],
    ['in hot water', 'in trouble', 'having a bath', 'swimming at the beach',
        'The boys were in hot water after breaking the window.',
        'Mum sat in hot water to relax after work.',
        'The lifeguard warned us about swimming in hot water.'],
    ['big cheese', 'the person in charge', 'a large block of cheese', 'a popular snack',
        'The new manager is the big cheese of the company.',
        'The mouse admired the big cheese in the pantry.',
        'We ordered the big cheese with our salad.'],
    ['in a pickle', 'in a tricky situation', 'eating sandwiches', 'sitting in a jar',
        'Losing my homework put me in a pickle.',
        'The veggie was stored in a pickle for winter.',
        'The children sat in a pickle at the picnic.'],
    ['on cloud nine', 'extremely happy', 'flying a plane', 'dreaming at night',
        'Winning the award left her on cloud nine.',
        'The pilot flew the plane up on cloud nine.',
        'On a cloudy night, the baby slept on cloud nine.'],
    ['over the moon', 'delighted', 'in outer space', 'on a trampoline',
        'Nina was over the moon about her exam result.',
        'The rocket travelled over the moon at dawn.',
        'The kids bounced over the moon at the park.'],
    ['hold your horses', 'be patient', 'gallop away', 'hug your pet',
        'Hold your horses — the results will be read out soon.',
        'At the stables, the rider held her horses tightly.',
        'The farmer held his horses until the gate opened.'],
    ['butterflies in your tummy', 'feeling nervous', 'a caterpillar home', 'feeling hungry',
        'Before the concert, I had butterflies in my tummy.',
        'The doctor found real butterflies in the boy\'s tummy.',
        'The chef served butterflies in a tummy-shaped bowl.'],
    ['break the ice', 'start a conversation', 'crack frozen water', 'chill the drinks',
        'A funny story helped break the ice at the new club.',
        'The sailor broke the ice with an axe.',
        'Please break the ice before pouring the juice.'],
    ['head in the clouds', 'daydreaming', 'being very tall', 'watching the sky',
        'Pay attention — you have your head in the clouds again.',
        'The giraffe walked with its head in the clouds.',
        'The pilot kept his head in the clouds during the flight.'],
    ['keep your eyes peeled', 'stay alert and watch', 'rub your eyes', 'take off your glasses',
        'Keep your eyes peeled for the turning as we drive.',
        'The chef kept his eyes peeled like a potato.',
        'The doctor asked the patient to keep his eyes peeled carefully.'],
    ['the last straw', 'the final problem that breaks patience', 'a drinking tube', 'the end of harvest',
        'Missing the bus was the last straw after such a bad week.',
        'The farmer counted the last straw in the barn.',
        'She stirred her drink with the last straw from the box.'],
    ['once in a blue moon', 'very rarely', 'seeing the moon once', 'a blue mooncake',
        'Uncle Ray visits us once in a blue moon.',
        'The astronomer photographed once in a blue moon hanging in the sky.',
        'The baker baked a cake called once in a blue moon.'],
    ['a hard nut to crack', 'a difficult problem', 'a strong shell', 'a broken tooth',
        'This riddle is a hard nut to crack.',
        'The squirrel found a hard nut to crack open.',
        'The dentist warned about a hard nut cracking a tooth.'],
    ['cost an arm and a leg', 'very expensive', 'lose your limbs', 'a cut of meat',
        'The new bike cost an arm and a leg.',
        'The accident cost the sailor an arm and a leg.',
        'The recipe costs an arm and a leg of lamb.'],
    ['let the cat out of the bag', 'reveal a secret', 'free a pet', 'a heavy bag',
        'Who let the cat out of the bag about the play?',
        'The farmer let the cat out of the bag at the market.',
        'Please let the cat out of the bag before we sit down.'],
    ['on the ball', 'alert and competent', 'bouncing a ball', 'standing at the game',
        'The goalie was on the ball for the whole match.',
        'The child stood on the ball at the playground.',
        'The coach placed the players on the ball.'],
    ['the ball is in your court', 'it is your turn to decide', 'a ball game', 'a ball in your yard',
        'I have made my offer, so the ball is in your court.',
        'The referee rolled the ball into the court.',
        'The neighbours put the ball in their court for the match.']
];

// Idioms — SIX connected families (upper primary):
//   0. MC meaning (interpret): what does the idiom really mean
//   1. MC use (interpret): which sentence uses the idiom correctly (the
//      curated real-sense sentence beside two literal misreadings)
//   2. written complete (apply): fill the missing words of the idiom
//   3. MC idiom-for-meaning (compare): which idiom matches this meaning
//   4. written apply (apply): write your own sentence with the idiom
//      (open-ended → "Example:" model from the curated usage sentence)
//   5. written justify (justify): explain WHY the literal sentence misuses
//      the idiom (open-ended → "Example:" explanation)
//
// NON-REPEATING SAMPLING: idioms AND families are dealt from decks; every
// question passes through sampleUnique keyed on the printed prompt.
function generateIdiom(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, IDIOM_ITEMS);
    const kindDeck = localDeck(rng, [0, 1, 2, 3, 4, 5] as const);
    const idiomNames = IDIOM_ITEMS.map(([idiom]) => idiom);
    return sampleUnique(
        count,
        () => {
            const [idiom, meaning, d1, d2, useRight, useWrong1, useWrong2] = itemDeck.take();
            const kind = kindDeck.take();
            if (kind === 0) {
                const shown = shuffleLocal(rng, [meaning, d1, d2]);
                return { prompt: `What does the idiom "${idiom}" really mean? (${shown.join(' / ')})`, answer: meaning };
            }
            if (kind === 1) {
                // MC use: per-idiom curated sentences — the real-sense usage
                // beside two literal misreadings, each in its own context.
                const shown = shuffleLocal(rng, [useRight, useWrong1, useWrong2]);
                return { prompt: `Which sentence uses "${idiom}" correctly? (${shown.join(' / ')})`, answer: useRight };
            }
            if (kind === 2) {
                // Written complete: mask alternating words of the idiom.
                const words = idiom.split(' ');
                const masked = words.map((w, i) => (i % 2 === 0 ? '__' : w)).join(' ');
                return { prompt: `Complete the idiom: ${masked}`, answer: idiom };
            }
            if (kind === 3) {
                // MC idiom-for-meaning: reverse direction — the meaning is
                // printed, the child picks the idiom (two other idioms as
                // distractors; every idiom has a distinct meaning).
                const others = shuffleLocal(rng, idiomNames.filter((n) => n !== idiom)).slice(0, 2);
                const shown = shuffleLocal(rng, [idiom, ...others]);
                return { prompt: `Which idiom means "${meaning}"? (${shown.join(', ')})`, answer: idiom };
            }
            if (kind === 4) {
                // Written apply: open-ended composition; the answer field is
                // a LABELED example (the curated usage sentence).
                return { prompt: `Write your own sentence using the idiom "${idiom}".`, answer: `Example: ${useRight}` };
            }
            // Written justify: the child explains the literal misreading.
            // Answer = a labeled model explanation naming the real sense.
            return {
                prompt: `This sentence misuses "${idiom}": "${useWrong1}" Explain in your own words what the idiom really means.`,
                answer: `Example: it reads "${idiom}" literally — it really means ${meaning}.`
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn; perPage 6 keeps the
// writing-heavy sheet low-density.
export const idiomSpec: WorksheetSpec = {
    id: 'idiom',
    label: 'Idioms',
    icon: '☁',
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('idiom'),
    scope: () => 'sayings & their meanings',
    generate: generateIdiom
};

// The plugin: a function the dashboard calls with its framework bundle.
export function IdiomWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(idiomSpec);
}
