// ─────────────────────────────────────────────────────────────────────────────
// LETTER TRACING WORKSHEET — a self-contained dashboard plugin (Prep
// handwriting: trace each letter A–Z).
//
// The dashboard loads this plugin by calling
// `LetterTracingWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Letter Tracing", glyph "⌗") and which grades offer
//     it (Prep only — tracing is a Prep skill);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Letter Tracing worksheet without affecting the framework or any
// other plugin.
//
// DETERMINISM: the generator deliberately draws NO random numbers — the sheet
// content is the fixed ordered set A–Z, which is exactly what letter-shape
// practice needs. "Randomize" is a no-op for this type by design; multi-page
// documents repeat the same ordered set (repeated practice runs).
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Uppercase alphabet in order (the shapes traced on letter pages).
const TRACE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

// Letter tracing: "look at the model, then trace the letter three times",
// one ordered row per letter A–Z (26 rows = exactly one page; extra pages
// repeat A–Z from the top). The model exemplar + dashed trace target switch
// the row to the tracing layout in the framework's PrintableSheet.
function generateLetterTrace(_rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const letter = TRACE_ALPHABET[i % TRACE_ALPHABET.length];
        out.push({
            prompt: `Trace the letter "${letter}"`,
            answer: letter,
            model: letter,
            trace: `${letter} ${letter} ${letter}`
        });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const letterTraceSpec: WorksheetSpec = {
    id: 'letterTrace',
    label: 'Letter Tracing',
    icon: '⌗',
    perPage: 26,
    offered: (grade: GradeConfig) => grade.available.includes('letterTrace'),
    scope: () => 'A–Z letter shapes',
    generate: generateLetterTrace
};

// The plugin: a function the dashboard calls with its framework bundle.
export function LetterTracingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(letterTraceSpec);
}
