// ─────────────────────────────────────────────────────────────────────────────
// LETTER TRACING WORKSHEET — a self-contained dashboard plugin (Prep
// handwriting: tracing letter shapes).
//
// The dashboard loads this plugin by calling
// `LetterTracingWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Letter Tracing", glyph "⌗") and which grades offer
//     it (Prep only — tracing is a Prep skill);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Letter Tracing worksheet without affecting the framework or any
// other plugin.
//
// PRACTICE DESIGN (quality over quantity): the old sheet flooded all 26
// letters onto one page in a frozen A–Z order and every extra page repeated
// that same sheet. Handwriting practice wants the opposite: a SMALL group of
// letters per page (8 = 4 rows × 2 columns) written at the enlarged
// writable scale of PrintableSheet's tracing layout, and a DIFFERENT group /
// order on every page. The letters now come from a seeded DECK over the
// alphabet (createDeck, framework/sampling.ts): each letter is dealt exactly
// once per cycle, the deck reshuffles between cycles, and the cycle-boundary
// guard stops the same letter being dealt twice back-to-back. The alphabet
// is finite, so long documents repeat letters by nature — the deck spreads
// those repeats evenly instead of re-printing a frozen A–Z sheet.
//
// DETERMINISM (unchanged contract): the deck draws from the document's ONE
// seeded Rng stream (seed = seedFrom([grade, id, refresh]), seed packing
// untouched), so the same seed always yields the same document and preview
// and print can never disagree. "Randomize" now genuinely re-rolls the
// practice grouping — which is the point of the button.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck } from '../framework';

// Uppercase alphabet — the deck pool for letter-shape practice.
const TRACE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

// Letter tracing: "look at the model, then trace the letter three times",
// one row per dealt letter. The model exemplar + dashed trace target switch
// the row to the tracing layout in the framework's PrintableSheet.
function generateLetterTrace(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    // Seeded deck: every page is a fresh group, and one full cycle (26
    // rows) covers every letter exactly once — no fabricated capacity.
    const deck = createDeck(rng, TRACE_ALPHABET);
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const letter = deck.take();
        out.push({
            prompt: `Trace the letter "${letter}"`,
            answer: letter,
            model: letter,
            trace: `${letter} ${letter} ${letter}`
        });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const letterTraceSpec: WorksheetSpec = {
    id: 'letterTrace',
    label: 'Letter Tracing',
    icon: '⌗',
    // 8 rows (4 per column) at the enlarged tracing scale: generous
    // writing space per letter instead of a 26-row wall.
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('letterTrace'),
    scope: () => 'A–Z letter shapes',
    generate: generateLetterTrace
};

// The plugin: a function the dashboard calls with its framework bundle.
export function LetterTracingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(letterTraceSpec);
}
