// ─────────────────────────────────────────────────────────────────────────────
// NOUNS & VERBS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `NounsVerbsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Nouns & Verbs", glyph "&") and which grades offer
//     it (Year 2 only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Nouns & Verbs worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Noun / verb word lists for the Year 2 parts-of-speech type. Grown from 8+8
// to 20+20 words; the combined list is dealt from a single deck, so every
// word is classified once before any repeats.
const NOUN_WORDS = [
    'cat', 'book', 'tree', 'ball', 'school', 'house', 'dog', 'apple',
    'fish', 'bird', 'chair', 'table', 'tiger', 'train', 'plane', 'grass',
    'rabbit', 'window', 'garden', 'button'
] as const;
const VERB_WORDS = [
    'run', 'jump', 'eat', 'read', 'sleep', 'sing', 'kick', 'draw',
    'walk', 'play', 'swim', 'hop', 'clap', 'write', 'drive', 'drink',
    'fly', 'cry', 'wash', 'open'
] as const;

// Nouns & verbs (Year 2 only): classify a word as a thing or an action.
//
// NON-REPEATING SAMPLING: the combined 40-word bank is the whole fact space —
// a deck guarantees every word (noun AND verb) appears before any repeats.
function generateGrammar(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    // Deal [word, isNoun] pairs so the classification travels with the word.
    const deck = createDeck(rng, [
        ...NOUN_WORDS.map((w): [string, boolean] => [w, true]),
        ...VERB_WORDS.map((w): [string, boolean] => [w, false])
    ]);
    return sampleUnique(
        count,
        () => {
            const [w, isNoun] = deck.take();
            return {
                prompt: `Is the word "${w}" a noun (thing) or a verb (action)?`,
                answer: isNoun ? 'noun' : 'verb'
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const grammarSpec: WorksheetSpec = {
    id: 'grammar',
    label: 'Nouns & Verbs',
    icon: '&',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('grammar'),
    scope: () => 'noun (thing) vs verb (action)',
    generate: generateGrammar
};

// The plugin: a function the dashboard calls with its framework bundle.
export function NounsVerbsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(grammarSpec);
}
