// ─────────────────────────────────────────────────────────────────────────────
// NOUNS & VERBS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `NounsVerbsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Nouns & Verbs", glyph "&") and which grades offer
//     it (Year 2 and up — Y2 lists it in the extended set, Y3–6 in the
//     upper-primary catalogue);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Nouns & Verbs worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// LEARNING VISUALS (Y1–3 cue band — isEarlyCueBand = word tiers 2..4, and the
// two early-branch gates below): the WRITTEN-CLASSIFY kind ("Is 'cat' a noun
// or a verb?") carries a scaffold cue — the noun's own picture, an action
// glyph for verbs, a sparkle for adjectives, an action glyph for adverbs. The
// answer is the CLASS NAME ("noun"/"verb"/"adjective"/"adverb"), never the
// depicted word, so the cue is safe. The MC and sentence-find kinds stay
// text-only: a pictured option there WOULD reveal the answer. Prep (tier 1)
// and Y4+ (tiers 5-6) print legacy markup.
function earlyPicture(caps: Caps, key: string): string | undefined {
    return isEarlyCueBand(caps) && hasVisual(key) ? key : undefined;
}

// Noun / verb word lists for the Year 2 parts-of-speech type. Grown from
// 20+20 to 28+28 words.
const NOUN_WORDS = [
    'cat', 'book', 'tree', 'ball', 'school', 'house', 'dog', 'apple',
    'fish', 'bird', 'chair', 'table', 'tiger', 'train', 'plane', 'grass',
    'rabbit', 'window', 'garden', 'button',
    'kitten', 'pencil', 'flower', 'robot', 'rocket', 'monkey', 'river', 'cloud'
] as const;
const VERB_WORDS = [
    'run', 'jump', 'eat', 'read', 'sleep', 'sing', 'kick', 'draw',
    'walk', 'play', 'swim', 'hop', 'clap', 'write', 'drive', 'drink',
    'fly', 'cry', 'wash', 'open',
    'climb', 'carry', 'smile', 'push', 'pull', 'paint', 'dance', 'crawl'
] as const;

// Third-person -s form of a verb ("run" -> "runs", "wash" -> "washes",
// "cry" -> "cries") for the sentence-find kinds.
function verbSForm(verb: string): string {
    if (/(s|sh|ch|x|z)$/.test(verb)) return `${verb}es`;
    if (/[^aeiou]y$/.test(verb)) return `${verb.slice(0, -1)}ies`;
    return `${verb}s`;
}

// Sentence-subject nouns: only ANIMATE nouns can sensibly DO every action in
// the verb bank ("the cloud sings" would read broken). The sentence-find kind
// draws its subject from this subset; the MC kinds still use the full banks.
const ANIMATE_NOUNS = [
    'cat', 'dog', 'fish', 'bird', 'tiger', 'rabbit', 'kitten', 'monkey',
    'boy', 'girl', 'dad', 'mum', 'baby', 'frog'
] as const;

// Upper-primary (Year 3+) word-class extension: ACARA Y3–6 grammar adds
// ADJECTIVES (describing words) and ADVERBS (how/when/where words) to the
// noun/verb split. The senior kinds below classify these two classes only —
// they never mix with the noun/verb banks, which keep their Y2 shape.
const ADJECTIVE_WORDS = [
    'bright', 'brave', 'calm', 'cheerful', 'gentle', 'gloomy', 'greedy',
    'honest', 'lazy', 'polite', 'proud', 'quiet', 'rude', 'silly',
    'tidy', 'wise', 'curious', 'generous', 'patient', 'loyal'
] as const;
const ADVERB_WORDS = [
    'quickly', 'slowly', 'loudly', 'softly', 'gently', 'kindly', 'bravely',
    'happily', 'sadly', 'anxiously', 'carefully', 'carelessly', 'eagerly',
    'neatly', 'politely', 'rudely', 'silently', 'sweetly', 'wisely', 'proudly'
] as const;

// Nouns & verbs — FOUR procedural kinds (Year 2); Year 3+ (wordTier 4)
// switches to the adjective/adverb classify kinds below:
//   0. "Is the word X a noun or a verb?"        (the written classify base)
//   1. "Which word is a noun?"                  (3 options: 1 noun, 2 verbs)
//   2. "Which word is a verb?"                  (3 options: 1 verb, 2 nouns)
//   3. "Find the noun / verb: The cat sleeps."  (assembled sentence)
//
// The old classify-only generator cycled after the 40-word bank; the MC and
// sentence kinds make the space options x words x sentence slots — deep
// enough for 100 pages.
//
// NON-REPEATING SAMPLING: [word, isNoun] pairs and sentence slots are dealt
// from decks and every question passes through sampleUnique keyed on the
// printed prompt.
function generateGrammar(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // Upper-primary gate: wordTier 4 (Year 3+) switches to the ACARA Y3–6
    // word-class work — adjectives vs adverbs (MC + written classify).
    if (caps.wordTier >= 4) {
        const adjDeck = createDeck(rng, ADJECTIVE_WORDS);
        const advDeck = createDeck(rng, ADVERB_WORDS);
        return sampleUnique(
            count,
            () => {
                const kind = rng.int(0, 2);
                if (kind === 0) {
                    // Written classify: is the dealt word an adjective or an adverb?
                    const isAdj = rng.next() < 0.5;
                    const word = isAdj ? adjDeck.take() : advDeck.take();
                    return {
                        prompt: `Is the word "${word}" an adjective (describes a thing) or an adverb (tells how)?`,
                        answer: isAdj ? 'adjective' : 'adverb',
                        // Year 3 scaffold: adjectives get the sparkle glyph,
                        // adverbs the action glyph (tells-HOW = a how-motion).
                        visual: earlyPicture(caps, isAdj ? 'sparkle' : 'action')
                    };
                }
                // MC: one adjective beside two adverbs (kind 1), or one adverb
                // beside two adjectives (kind 2).
                const wantAdj = kind === 1;
                const answer = wantAdj ? adjDeck.take() : advDeck.take();
                const otherDeck = wantAdj ? advDeck : adjDeck;
                const options = [answer];
                let guard = 0;
                while (options.length < 3 && guard < 24) {
                    guard++;
                    const pick = otherDeck.take();
                    if (!options.includes(pick)) options.push(pick);
                }
                const shown = shuffleWords(rng, options);
                return {
                    prompt: `Which word is an ${wantAdj ? 'adjective (describes a thing)' : 'adverb (tells how)'}? (${shown.join(', ')})`,
                    answer
                };
            },
            (p) => p.prompt
        );
    }
    // Deal [word, isNoun] pairs so the classification travels with the word.
    const pairDeck = createDeck(rng, [
        ...NOUN_WORDS.map((w): [string, boolean] => [w, true]),
        ...VERB_WORDS.map((w): [string, boolean] => [w, false])
    ]);
    const nounDeck = createDeck(rng, NOUN_WORDS);
    const verbDeck = createDeck(rng, VERB_WORDS);
    // Build a 3-option set: the answer plus two words of the OPPOSITE class,
    // printed shuffled.
    const choiceSet = (answer: string, isNoun: boolean) => {
        const otherDeck = isNoun ? verbDeck : nounDeck;
        const options = [answer];
        let guard = 0;
        while (options.length < 3 && guard < 24) {
            guard++;
            const pick = otherDeck.take();
            if (!options.includes(pick)) options.push(pick);
        }
        return shuffleWords(rng, options);
    };
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 3);
            if (kind === 0) {
                // Base kind: classify a dealt word.
                const [w, isNoun] = pairDeck.take();
                return {
                    prompt: `Is the word "${w}" a noun (thing) or a verb (action)?`,
                    answer: isNoun ? 'noun' : 'verb',
                    // Year 2 scaffold: the noun's own picture (if it has one)
                    // or the action glyph for verbs. Answer is the class name,
                    // so the picture never reveals it.
                    visual: earlyPicture(caps, isNoun ? w : 'action')
                };
            }
            if (kind === 1 || kind === 2) {
                // MC: pick the noun (kind 1) or the verb (kind 2) of three.
                const isNoun = kind === 1;
                const answer = isNoun ? nounDeck.take() : verbDeck.take();
                const shown = choiceSet(answer, isNoun);
                return { prompt: `Which word is a ${isNoun ? 'noun (thing)' : 'verb (action)'}? (${shown.join(', ')})`, answer };
            }
            // Sentence find: "The cat sleeps." — find the noun or the verb.
            // Subjects come from the animate subset so every line reads.
            const noun = rng.pick(ANIMATE_NOUNS);
            const verb = verbDeck.take();
            const line = `The ${noun} ${verbSForm(verb)}.`;
            const findNoun = rng.next() < 0.5;
            return findNoun
                ? { prompt: `Find the noun: ${line}`, answer: noun }
                : { prompt: `Find the verb: ${line}`, answer: verbSForm(verb) };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const grammarSpec: WorksheetSpec = {
    id: 'grammar',
    label: 'Nouns & Verbs',
    icon: '&',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('grammar'),
    scope: (grade: GradeConfig) =>
        grade.caps.wordTier >= 4 ? 'adjectives vs adverbs' : 'noun (thing) vs verb (action)',
    generate: generateGrammar
};

// The plugin: a function the dashboard calls with its framework bundle.
export function NounsVerbsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(grammarSpec);
}
