// ─────────────────────────────────────────────────────────────────────────────
// NOUNS & VERBS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `NounsVerbsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Nouns & Verbs", glyph "&") and which grades offer
//     it (Year 2 only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Nouns & Verbs worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Noun / verb word lists for the Year 2 parts-of-speech type.
const NOUN_WORDS = ['cat', 'book', 'tree', 'ball', 'school', 'house', 'dog', 'apple'] as const;
const VERB_WORDS = ['run', 'jump', 'eat', 'read', 'sleep', 'sing', 'kick', 'draw'] as const;

// Nouns & verbs (Year 2 only): classify a word as a thing or an action.
function generateGrammar(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        if (rng.next() < 0.5) {
            const w = rng.pick(NOUN_WORDS);
            out.push({ prompt: `Is the word "${w}" a noun (thing) or a verb (action)?`, answer: 'noun' });
        } else {
            const w = rng.pick(VERB_WORDS);
            out.push({ prompt: `Is the word "${w}" a noun (thing) or a verb (action)?`, answer: 'verb' });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const grammarSpec: WorksheetSpec = {
    id: 'grammar',
    label: 'Nouns & Verbs',
    icon: '&',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('grammar'),
    scope: () => 'noun (thing) vs verb (action)',
    generate: generateGrammar
};

// The plugin: a function the dashboard calls with its framework bundle.
export function NounsVerbsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(grammarSpec);
}
