// ─────────────────────────────────────────────────────────────────────────────
// NUMBER TRACING WORKSHEET — a self-contained dashboard plugin (Prep
// handwriting: trace the numbers 0–9).
//
// The dashboard loads this plugin by calling
// `NumberTracingWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Number Tracing", glyph "12") and which grades offer
//     it (Prep only — tracing is a Prep skill);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Number Tracing worksheet without affecting the framework or any
// other plugin.
//
// DETERMINISM: the generator deliberately draws NO random numbers — the sheet
// content is the fixed ordered set 0–9, which is exactly what number-shape
// practice needs. "Randomize" is a no-op for this type by design; multi-page
// documents repeat the same ordered set (repeated practice runs).
//
// LAYOUT: numberTrace runs single-column — number rows print on long
// full-width writing lines ("0 0 0"), which suits number shapes (letter/word
// tracing stays two-column).
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// The numbers traced on number pages, in counting order.
const TRACE_NUMBERS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];

// Number tracing: "look at the model, then trace the number three times",
// one ordered row per digit 0–9 (10 rows = exactly one page; extra pages
// repeat 0–9 from the top). The model exemplar + dashed trace target switch
// the row to the tracing layout in the framework's PrintableSheet.
function generateNumberTrace(_rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const n = TRACE_NUMBERS[i % TRACE_NUMBERS.length];
        out.push({
            prompt: `Trace the number "${n}"`,
            answer: n,
            model: n,
            trace: `${n} ${n} ${n}`
        });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const numberTraceSpec: WorksheetSpec = {
    id: 'numberTrace',
    label: 'Number Tracing',
    icon: '12',
    perPage: 10,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('numberTrace'),
    scope: () => '0–9 number shapes',
    generate: generateNumberTrace
};

// The plugin: a function the dashboard calls with its framework bundle.
export function NumberTracingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(numberTraceSpec);
}
