// ─────────────────────────────────────────────────────────────────────────────
// OPPOSITE WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `OppositeWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Opposite Words", glyph "⇄") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Opposite Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Opposite (antonym) pairs: tier1 = the six kindest pairs; tier 2+ = all 30.
// (No word may anchor TWO pairs — "hard" only pairs with "easy", never also
// with "soft" — so a prompt word always has exactly one correct answer.)
const OPPOSITE_PAIRS: [string, string][] = [
    ['hot', 'cold'],
    ['big', 'small'],
    ['up', 'down'],
    ['fast', 'slow'],
    ['happy', 'sad'],
    ['long', 'short'],
    ['in', 'out'],
    ['open', 'shut'],
    ['new', 'old'],
    ['heavy', 'light'],
    ['early', 'late'],
    ['easy', 'hard'],
    // Year 1+ extras (30 pairs => 60 written-answer questions before the
    // multiple-choice variant multiplies the space past a thousand)
    ['day', 'night'],
    ['come', 'go'],
    ['push', 'pull'],
    ['full', 'empty'],
    ['wet', 'dry'],
    ['loud', 'quiet'],
    ['first', 'last'],
    ['give', 'take'],
    ['laugh', 'cry'],
    ['sweet', 'sour'],
    ['above', 'below'],
    ['front', 'back'],
    ['win', 'lose'],
    ['clean', 'dirty'],
    ['strong', 'weak'],
    ['under', 'over'],
    ['near', 'far']
];

// Upper-primary (Year 3+) antonym extension: ACARA Y3–6 vocabulary. The
// no-word-anchors-two-pairs rule still holds — none of these words appears in
// any other pair, so every prompt word has exactly one correct answer.
const OPPOSITE_UPPER: [string, string][] = [
    ['accept', 'refuse'],
    ['arrive', 'depart'],
    ['ancient', 'modern'],
    ['brave', 'cowardly'],
    ['expand', 'shrink'],
    ['generous', 'selfish'],
    ['humble', 'proud'],
    ['include', 'exclude'],
    ['increase', 'decrease'],
    ['loyal', 'disloyal'],
    ['patient', 'impatient'],
    ['polite', 'rude'],
    ['praise', 'criticise'],
    ['succeed', 'fail'],
    ['temporary', 'permanent'],
    ['tidy', 'messy'],
    ['transparent', 'opaque'],
    ['victory', 'defeat'],
    ['wisdom', 'foolishness'],
    ['ascending', 'descending']
];

// Opposite words: name the antonym of a word from the pair bank, either as a
// written answer or (40% of questions) as a three-option multiple choice.
//
// NON-REPEATING SAMPLING: pair AND direction are dealt from decks (each of
// the 60 "what is the opposite of X?" forms appears before any repeats), and
// the whole question passes through sampleUnique keyed on the printed prompt —
// the multiple-choice variant's distractor sets multiply the space beyond a
// thousand unique questions.
function generateOpposite(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // Tier 1 offers the six most concrete pairs; tier 2+ the full set; the
    // upper-primary pairs join from wordTier 4 (Year 3+).
    const pairs =
        caps.wordTier >= 4
            ? [...OPPOSITE_PAIRS, ...OPPOSITE_UPPER]
            : caps.wordTier >= 2
              ? OPPOSITE_PAIRS
              : OPPOSITE_PAIRS.slice(0, 6);
    const pairDeck = createDeck(rng, pairs);
    // Every bank word except the prompt word and its answer is a legal
    // multiple-choice distractor.
    const words = pairs.flat();
    return sampleUnique(
        count,
        () => {
            const [a, b] = pairDeck.take();
            // Random direction: ask for a's opposite or b's opposite.
            const useAsk = rng.next() < 0.5;
            const word = useAsk ? a : b;
            const answer = useAsk ? b : a;
            if (rng.next() < 0.6) {
                return { prompt: `What is the opposite of "${word}"?`, answer };
            }
            // Multiple choice: two distractor words from unrelated pairs.
            const options = [answer];
            let guard = 0;
            while (options.length < 3 && guard < 24) {
                guard++;
                const pick = rng.pick(words);
                if (!options.includes(pick) && pick !== word) options.push(pick);
            }
            const shown = shuffleWords(rng, options);
            return { prompt: `Which word means the opposite of "${word}"? (${shown.join(', ')})`, answer };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const oppositeSpec: WorksheetSpec = {
    id: 'opposite',
    label: 'Opposite Words',
    icon: '⇄',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('opposite'),
    scope: (grade: GradeConfig) =>
        grade.caps.wordTier >= 4 ? 'antonyms' : grade.caps.wordTier >= 2 ? 'common opposites' : 'starter opposites',
    generate: generateOpposite
};

// The plugin: a function the dashboard calls with its framework bundle.
export function OppositeWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(oppositeSpec);
}
