// ─────────────────────────────────────────────────────────────────────────────
// OPPOSITE WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `OppositeWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Opposite Words", glyph "⇄") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Opposite Words worksheet without affecting the framework or any
// other plugin.
//
// T4B REWORK (quality over quantity):
//   - DENSITY: perPage 24 → 8. Eight roomy rows per A4 page give the child
//     real writing space instead of a packed grid of near-identical items.
//   - TASK MIX (four genuine formats, not option shuffling):
//       1. written antonym            "What is the opposite of "hot"?"
//       2. three-option antonym MCQ   "Which word means the opposite of …?"
//       3. CONTEXT cloze              a curated contrast sentence whose blank
//                                     is the antonym IN USE ("A mouse is small;
//                                     an elephant is __.") — semantic depth;
//       4. PAIR-FIND                  "Which two words are opposites?" — the
//                                     child identifies the antonym PAIR among
//                                     three words (answer metadata lists both
//                                     words, comma-separated).
//   - BANKS: local curated vocabulary expanded 30→40 basic pairs and 20→33
//     upper pairs, plus 20+8 curated context sentences. words.ts is read-only
//     shared data this wave, so every new word lives in THIS file.
//   - ANSWER SAFETY: the no-word-anchors-two-pairs rule still holds across
//     both banks (checked below), so every prompt word has exactly ONE
//     correct opposite and every pair-find distractor is guaranteed not to
//     form a second opposite pair.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// LEARNING VISUALS (Y1–3 only — the early cue band, isEarlyCueBand = word
// tiers 2..4): concrete pair words carry a CONCEPT picture so "hot" prints
// beside a flame and "big" beside an elephant. The map covers both members of
// each concrete pair — since the answer is always the OTHER word, the picture
// never reveals it. Abstract or unmapped words (and the Prep / Year 4+
// sheets) print plain (legacy markup).
const OPPOSITE_VISUAL: Record<string, string> = {
    // concrete property pairs
    hot: 'fire', cold: 'ice',
    big: 'elephant', small: 'ant',
    long: 'barLong', short: 'barShort',
    heavy: 'weight', light: 'feather',
    fast: 'bolt', slow: 'snail',
    wet: 'drop', dry: 'sun',
    full: 'cupFull', empty: 'cupEmpty',
    clean: 'sparkle', dirty: 'xmark',
    sweet: 'honey', sour: 'lemon',
    loud: 'speaker', quiet: 'zzz',
    // feelings & times
    happy: 'smile', sad: 'cry',
    day: 'sun', night: 'night',
    early: 'clock', late: 'clock',
    // space & order
    up: 'arrowUp', down: 'arrowDown',
    above: 'arrowUp', below: 'arrowDown',
    first: 'trophy', last: 'xmark',
    // strength & outcomes
    strong: 'weight', weak: 'feather',
    win: 'trophy', lose: 'xmark',
    // T4B additions (only where a PICS key already exists — visuals.tsx is
    // framework-owned and untouched this wave):
    top: 'arrowUp', bottom: 'arrowDown',
    asleep: 'zzz'
};
function oppPicture(caps: Caps, word: string): string | undefined {
    const key = OPPOSITE_VISUAL[word];
    return key && isEarlyCueBand(caps) && hasVisual(key) ? key : undefined;
}

// Opposite (antonym) pairs: tier1 = the six kindest pairs; tier 2+ = all 40.
// (No word may anchor TWO pairs — "hard" only pairs with "easy", never also
// with "soft" — so a prompt word always has exactly one correct answer.)
const OPPOSITE_PAIRS: [string, string][] = [
    ['hot', 'cold'],
    ['big', 'small'],
    ['up', 'down'],
    ['fast', 'slow'],
    ['happy', 'sad'],
    ['long', 'short'],
    ['in', 'out'],
    ['open', 'shut'],
    ['new', 'old'],
    ['heavy', 'light'],
    ['early', 'late'],
    ['easy', 'hard'],
    // Year 1+ extras
    ['day', 'night'],
    ['come', 'go'],
    ['push', 'pull'],
    ['full', 'empty'],
    ['wet', 'dry'],
    ['loud', 'quiet'],
    ['first', 'last'],
    ['give', 'take'],
    ['laugh', 'cry'],
    ['sweet', 'sour'],
    ['above', 'below'],
    ['front', 'back'],
    ['win', 'lose'],
    ['clean', 'dirty'],
    ['strong', 'weak'],
    ['under', 'over'],
    ['near', 'far'],
    // T4B basic extension — concrete, grade-fit Y1–Y2 opposites. None of
    // these words appears in any other pair (verified by the anchor check in
    // the tests), so answers stay unique.
    ['top', 'bottom'],
    ['start', 'finish'],
    ['begin', 'end'],
    ['buy', 'sell'],
    ['inside', 'outside'],
    ['love', 'hate'],
    ['always', 'never'],
    ['before', 'after'],
    ['awake', 'asleep'],
    ['safe', 'dangerous']
];

// Upper-primary (Year 3+) antonym extension: ACARA Y3–6 vocabulary. The
// no-word-anchors-two-pairs rule still holds — none of these words appears in
// any other pair, so every prompt word has exactly one correct answer.
const OPPOSITE_UPPER: [string, string][] = [
    ['accept', 'refuse'],
    ['arrive', 'depart'],
    ['ancient', 'modern'],
    ['brave', 'cowardly'],
    ['expand', 'shrink'],
    ['generous', 'selfish'],
    ['humble', 'proud'],
    ['include', 'exclude'],
    ['increase', 'decrease'],
    ['loyal', 'disloyal'],
    ['patient', 'impatient'],
    ['polite', 'rude'],
    ['praise', 'criticise'],
    ['succeed', 'fail'],
    ['temporary', 'permanent'],
    ['tidy', 'messy'],
    ['transparent', 'opaque'],
    ['victory', 'defeat'],
    ['wisdom', 'foolishness'],
    ['ascending', 'descending'],
    // T4B upper extension — grade-fit Y3–6 antonyms, no anchor clashes.
    ['wide', 'narrow'],
    ['deep', 'shallow'],
    ['smooth', 'rough'],
    ['thick', 'thin'],
    ['careful', 'careless'],
    ['possible', 'impossible'],
    ['appear', 'disappear'],
    ['agree', 'disagree'],
    ['useful', 'useless'],
    ['beautiful', 'ugly'],
    ['rich', 'poor'],
    ['forward', 'backward'],
    ['straight', 'curved']
];

// CONTEXT cloze bank: [sentence with one "__", answer]. Each sentence states
// an explicit CONTRAST between the pair, so the blank has exactly one fitting
// antonym ("A mouse is small; an elephant is __." → big). Sentences are
// curated, grade-fit and use only pair-bank words as answers.
const OPPOSITE_CONTEXT_BASIC: [string, string][] = [
    ['From the fridge the juice was cold; in the sun it grew __ .', 'hot'],
    ['An elephant is big; a mouse is __ .', 'small'],
    ['A cheetah runs fast; a snail moves __ .', 'slow'],
    ['A ruler is long; an eraser is __ .', 'short'],
    ['A rock is heavy; a feather is __ .', 'light'],
    ['Winning made her happy; losing made her __ .', 'sad'],
    ['The towel soaked the water up and the floor became __ .', 'dry'],
    ['She drank all her milk; the glass was __ .', 'empty'],
    ['After washing the shirts were clean; before they were __ .', 'dirty'],
    ['The band played loud; the library was __ .', 'quiet'],
    ['Cake is sweet; a lemon is __ .', 'sour'],
    ['A lion is strong; a kitten is __ .', 'weak'],
    ['The first bell rang early; the last bell rang __ .', 'late'],
    ['The sun shines by day; the moon shines by __ .', 'night'],
    ['The kite flew up; the leaf floated __ .', 'down'],
    ['Tom finished first; Ben finished __ .', 'last'],
    ['The gate is near; the hill is __ .', 'far'],
    ['When the score is best you win; when it is worst you __ .', 'lose'],
    ['A mountain is high at the top; the valley is __ .', 'low'],
    ['The kettle is hot; the ice cream is __ .', 'cold']
];
const OPPOSITE_CONTEXT_UPPER: [string, string][] = [
    ['A castle is ancient; a glass tower is __ .', 'modern'],
    ['A generous child shares; a __ child keeps everything.', 'selfish'],
    ['Glass is transparent; wood is __ .', 'opaque'],
    ['The brave firefighter ran in; the __ child hid.', 'cowardly'],
    ['A wide road fits many cars; a __ lane fits one.', 'narrow'],
    ['The pool is deep; the paddling pool is __ .', 'shallow'],
    ['Sandpaper is rough; the glass is __ .', 'smooth'],
    ['A careful reader checks; a __ reader guesses.', 'careless']
];

// Opposite words: name the antonym of a word from the pair bank (written or
// multiple choice), place it in a contrast sentence, or spot the antonym pair
// among three words.
//
// NON-REPEATING SAMPLING: pair AND direction are dealt from decks (each of
// the 80 "what is the opposite of X?" forms appears before any repeats), the
// context sentences run on their own deck, and the whole question passes
// through sampleUnique keyed on the printed prompt — the multiple-choice and
// pair-find distractor sets multiply the space beyond several thousand
// unique questions.
function generateOpposite(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // Tier 1 offers the six most concrete pairs; tier 2+ the full set; the
    // upper-primary pairs join from wordTier 4 (Year 3+).
    const pairs =
        caps.wordTier >= 4
            ? [...OPPOSITE_PAIRS, ...OPPOSITE_UPPER]
            : caps.wordTier >= 2
              ? OPPOSITE_PAIRS
              : OPPOSITE_PAIRS.slice(0, 6);
    const pairDeck = createDeck(rng, pairs);
    // Context pool follows the same gate; Prep (tier 1) has no context deck.
    const contextPool =
        caps.wordTier >= 4
            ? [...OPPOSITE_CONTEXT_BASIC, ...OPPOSITE_CONTEXT_UPPER]
            : caps.wordTier >= 2
              ? OPPOSITE_CONTEXT_BASIC
              : [];
    const contextDeck = contextPool.length > 0 ? createDeck(rng, contextPool) : null;
    // Every bank word except the prompt word and its answer is a legal
    // multiple-choice distractor.
    const words = pairs.flat();
    return sampleUnique(
        count,
        () => {
            const [a, b] = pairDeck.take();
            // Random direction: ask for a's opposite or b's opposite.
            const useAsk = rng.next() < 0.5;
            const word = useAsk ? a : b;
            const answer = useAsk ? b : a;
            // Concept picture for the PROMPT word only (the answer is the
            // other word, so the cue is a scaffold, never a give-away).
            const pic = oppPicture(caps, word);
            const roll = rng.next();
            if (roll < 0.35) {
                // Format 1 — written antonym.
                return { prompt: `What is the opposite of "${word}"?`, answer, visual: pic };
            }
            if (roll < 0.6) {
                // Format 2 — multiple choice: two distractor words from
                // unrelated pairs.
                const options = [answer];
                let guard = 0;
                while (options.length < 3 && guard < 24) {
                    guard++;
                    const pick = rng.pick(words);
                    if (!options.includes(pick) && pick !== word) options.push(pick);
                }
                const shown = shuffleWords(rng, options);
                return {
                    prompt: `Which word means the opposite of "${word}"? (${shown.join(', ')})`,
                    answer,
                    visual: pic
                };
            }
            if (roll < 0.85 && contextDeck) {
                // Format 3 — context cloze. NO cue here: the answer word is
                // the blank itself, so any picture could give it away.
                const [sentence, ctxAnswer] = contextDeck.take();
                return { prompt: `Complete the sentence: ${sentence}`, answer: ctxAnswer };
            }
            // Format 4 — pair-find: the dealt pair plus one distractor from
            // ANOTHER pair. Because pairs are DISJOINT (the no-word-anchors-
            // two-pairs rule), any bank word outside {a, b} belongs to a
            // different pair AND its partner is outside {a, b} too — so the
            // line shows exactly one opposite pair and the distractor can
            // never complete a second one. Answer metadata lists both words
            // in bank order.
            let distractor = '';
            let guard = 0;
            while (guard < 24) {
                guard++;
                const pick = rng.pick(words);
                if (pick !== a && pick !== b) {
                    distractor = pick;
                    break;
                }
            }
            if (!distractor) distractor = words.find((w) => w !== a && w !== b) ?? 'yes';
            const shown = shuffleWords(rng, [a, b, distractor]);
            return {
                prompt: `Which two words are opposites? (${shown.join(', ')})`,
                answer: `${a}, ${b}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const oppositeSpec: WorksheetSpec = {
    id: 'opposite',
    label: 'Opposite Words',
    icon: '⇄',
    // T4B density: 8 roomy rows per page (was 24) — quality over quantity.
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('opposite'),
    scope: (grade: GradeConfig) =>
        grade.caps.wordTier >= 4 ? 'antonyms' : grade.caps.wordTier >= 2 ? 'common opposites' : 'starter opposites',
    generate: generateOpposite
};

// The plugin: a function the dashboard calls with its framework bundle.
export function OppositeWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(oppositeSpec);
}
