// ─────────────────────────────────────────────────────────────────────────────
// OPPOSITE WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `OppositeWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Opposite Words", glyph "⇄") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Opposite Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Opposite (antonym) pairs: tier1 = the six kindest pairs; tier 2+ = all.
const OPPOSITE_PAIRS: [string, string][] = [
    ['hot', 'cold'],
    ['big', 'small'],
    ['up', 'down'],
    ['fast', 'slow'],
    ['happy', 'sad'],
    ['long', 'short'],
    ['in', 'out'],
    ['open', 'shut'],
    ['new', 'old'],
    ['heavy', 'light'],
    ['early', 'late'],
    ['easy', 'hard']
];

// Opposite words: name the antonym of a word from the pair bank.
function generateOpposite(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    // Tier 1 offers the six most concrete pairs; tier 2+ the full set.
    const pairs = caps.wordTier >= 2 ? OPPOSITE_PAIRS : OPPOSITE_PAIRS.slice(0, 6);
    for (let i = 0; i < count; i++) {
        const [a, b] = rng.pick(pairs);
        // Random direction: ask for a's opposite or b's opposite.
        const ask = rng.next() < 0.5;
        out.push({ prompt: `What is the opposite of "${ask ? a : b}"?`, answer: ask ? b : a });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const oppositeSpec: WorksheetSpec = {
    id: 'opposite',
    label: 'Opposite Words',
    icon: '⇄',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('opposite'),
    scope: (grade: GradeConfig) => (grade.caps.wordTier >= 2 ? 'common opposites' : 'starter opposites'),
    generate: generateOpposite
};

// The plugin: a function the dashboard calls with its framework bundle.
export function OppositeWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(oppositeSpec);
}
