// ─────────────────────────────────────────────────────────────────────────────
// PAST TENSE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PastTenseWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Past Tense", glyph "→") and which grades offer it
//     (Year 2 and up — Y2 lists it in the extended set, Y3–6 in the
//     upper-primary catalogue);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Past Tense worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Past-tense pairs [base, past], Year 2 and up. Grown from 14 to 32 pairs —
// 18 added regular pairs (-ed/double-consonant) on top of the original 14
// (4 regular, 10 irregular).
const TENSE_PAIRS: [string, string][] = [
    ['walk', 'walked'],
    ['play', 'played'],
    ['jump', 'jumped'],
    ['kick', 'kicked'],
    ['sit', 'sat'],
    ['run', 'ran'],
    ['eat', 'ate'],
    ['see', 'saw'],
    ['go', 'went'],
    ['swim', 'swam'],
    ['take', 'took'],
    ['make', 'made'],
    ['drive', 'drove'],
    ['write', 'wrote'],
    ['help', 'helped'],
    ['want', 'wanted'],
    ['look', 'looked'],
    ['open', 'opened'],
    ['call', 'called'],
    ['need', 'needed'],
    ['wash', 'washed'],
    ['ask', 'asked'],
    ['point', 'pointed'],
    ['smile', 'smiled'],
    ['use', 'used'],
    ['live', 'lived'],
    ['love', 'loved'],
    ['like', 'liked'],
    ['hop', 'hopped'],
    ['stop', 'stopped'],
    ['clap', 'clapped'],
    ['grab', 'grabbed']
];

// Past tense (Year 2 and up): the past form of a base verb, either as a written
// answer or (40% of questions) as a three-option multiple choice whose
// distractor past forms come from other pairs — that option-combination space
// pushes the worksheet past a thousand unique questions.
//
// NON-REPEATING SAMPLING: bases are dealt from a deck (every verb is asked
// before any repeats) and the question passes through sampleUnique keyed on
// the printed prompt.
function generateTense(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const baseDeck = createDeck(rng, TENSE_PAIRS);
    const pastForms = TENSE_PAIRS.map(([, past]) => past);
    return sampleUnique(
        count,
        () => {
            const [base, past] = baseDeck.take();
            if (rng.next() < 0.6) {
                return { prompt: `What is the past tense of "${base}"?`, answer: past };
            }
            // Multiple choice: the answer beside two past forms from other verbs.
            const options = [past];
            let guard = 0;
            while (options.length < 3 && guard < 24) {
                guard++;
                const pick = rng.pick(pastForms);
                if (!options.includes(pick)) options.push(pick);
            }
            const shown = shuffleWords(rng, options);
            return { prompt: `What is the past tense of "${base}"? (${shown.join(', ')})`, answer: past };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const tenseSpec: WorksheetSpec = {
    id: 'tense',
    label: 'Past Tense',
    icon: '→',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('tense'),
    scope: () => 'past forms',
    generate: generateTense
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PastTenseWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(tenseSpec);
}
