// ─────────────────────────────────────────────────────────────────────────────
// PAST TENSE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PastTenseWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Past Tense", glyph "→") and which grades offer it
//     (Year 2 only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Past Tense worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Past-tense pairs [base, past], Year 2 only.
const TENSE_PAIRS: [string, string][] = [
    ['walk', 'walked'],
    ['play', 'played'],
    ['jump', 'jumped'],
    ['kick', 'kicked'],
    ['sit', 'sat'],
    ['run', 'ran'],
    ['eat', 'ate'],
    ['see', 'saw'],
    ['go', 'went'],
    ['swim', 'swam'],
    ['take', 'took'],
    ['make', 'made'],
    ['drive', 'drove'],
    ['write', 'wrote']
];

// Past tense (Year 2 only): the past form of a base verb.
function generateTense(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const [base, past] = rng.pick(TENSE_PAIRS);
        out.push({ prompt: `What is the past tense of "${base}"?`, answer: past });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const tenseSpec: WorksheetSpec = {
    id: 'tense',
    label: 'Past Tense',
    icon: '→',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('tense'),
    scope: () => 'past forms',
    generate: generateTense
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PastTenseWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(tenseSpec);
}
