// ─────────────────────────────────────────────────────────────────────────────
// PAST TENSE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PastTenseWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Past Tense", glyph "→") and which grades offer it
//     (Year 2 and up — Y2 lists it in the extended set, Y3–6 in the
//     upper-primary catalogue);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Past Tense worksheet without affecting the framework or any
// other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 24 cramped rows
// to 8 roomy ones. The verb bank grew from 32 to 52 pairs (more irregulars —
// the hard ones Y2–Y6 actually stumble on), and the sheet now mixes five
// connected families: written recall, multiple choice, REWRITE A WHOLE
// SENTENCE (apply), a true/false CHECK of the past form, and an open-ended
// COMPOSE whose key models one sentence and accepts any sensible one.
// Sentence rewrites are combinatorial (subject × verb frame) but every frame
// is curated per verb, so every line reads.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Past-tense pairs [base, past], Year 2 and up. Grown from 32 to 52 pairs —
// 20 added (12 more irregulars: sing/sang, fly/flew, thought, caught...;
// 8 more regulars incl. -ied and doubled-consonant forms). Every form
// re-verified for correct AU-classroom spelling.
const TENSE_PAIRS: [string, string][] = [
    ['walk', 'walked'],
    ['play', 'played'],
    ['jump', 'jumped'],
    ['kick', 'kicked'],
    ['sit', 'sat'],
    ['run', 'ran'],
    ['eat', 'ate'],
    ['see', 'saw'],
    ['go', 'went'],
    ['swim', 'swam'],
    ['take', 'took'],
    ['make', 'made'],
    ['drive', 'drove'],
    ['write', 'wrote'],
    ['help', 'helped'],
    ['want', 'wanted'],
    ['look', 'looked'],
    ['open', 'opened'],
    ['call', 'called'],
    ['need', 'needed'],
    ['wash', 'washed'],
    ['ask', 'asked'],
    ['point', 'pointed'],
    ['smile', 'smiled'],
    ['use', 'used'],
    ['live', 'lived'],
    ['love', 'loved'],
    ['like', 'liked'],
    ['hop', 'hopped'],
    ['stop', 'stopped'],
    ['clap', 'clapped'],
    ['grab', 'grabbed'],
    // T4C growth: more irregulars (the tricky core of Y2–Y6 tense work).
    ['sing', 'sang'],
    ['ring', 'rang'],
    ['drink', 'drank'],
    ['begin', 'began'],
    ['fly', 'flew'],
    ['grow', 'grew'],
    ['know', 'knew'],
    ['throw', 'threw'],
    ['teach', 'taught'],
    ['catch', 'caught'],
    ['buy', 'bought'],
    ['bring', 'brought'],
    ['think', 'thought'],
    ['feel', 'felt'],
    ['keep', 'kept'],
    ['sleep', 'slept'],
    ['leave', 'left'],
    ['say', 'said'],
    ['tell', 'told'],
    ['find', 'found'],
    ['fall', 'fell'],
    ['hear', 'heard'],
    // T4C growth: more regulars (-ed, doubled consonant, -ied).
    ['watch', 'watched'],
    ['finish', 'finished'],
    ['start', 'started'],
    ['dance', 'danced'],
    ['plant', 'planted'],
    ['plan', 'planned'],
    ['drop', 'dropped'],
    ['cry', 'cried'],
    ['try', 'tried'],
    ['study', 'studied']
];

// Sentence frames for the REWRITE kind: [base, tail] where the tail is a
// phrase that grammatically fits THAT verb ("walk to school", "sang a song").
// Subjects come from a bank that all take the BASE verb form (no -s), so the
// present-tense line is always correct and the rewrite only swaps the verb.
const VERB_FRAMES: [string, string][] = [
    ['walk', 'to school'], ['run', 'in the race'], ['eat', 'a big lunch'],
    ['see', 'a great movie'], ['go', 'to the park'], ['swim', 'in the pool'],
    ['take', 'the bus'], ['make', 'a card'], ['drive', 'the tractor'],
    ['write', 'a story'], ['sit', 'on the mat'], ['jump', 'over the log'],
    ['kick', 'the ball'], ['help', 'Mum'], ['look', 'out of the window'],
    ['open', 'the gate'], ['call', 'the office'], ['wash', 'the dishes'],
    ['ask', 'a question'], ['point', 'at the map'], ['use', 'the computer'],
    ['love', 'ice cream'], ['like', 'the new book'], ['hop', 'across the yard'],
    ['stop', 'the bus'], ['grab', 'the rope'], ['sing', 'a song'],
    ['ring', 'the bell'], ['drink', 'some water'], ['begin', 'the race'],
    ['fly', 'a kite'], ['grow', 'tall sunflowers'], ['know', 'the answer'],
    ['throw', 'the ball'], ['teach', 'the class'], ['catch', 'the ball'],
    ['buy', 'some fruit'], ['bring', 'my jacket'], ['think', 'about it'],
    ['feel', 'happy'], ['keep', 'the secret'], ['sleep', 'through the night'],
    ['leave', 'home early'], ['say', 'thank you'], ['tell', 'a joke'],
    ['find', 'a lost coin'], ['fall', 'off the chair'], ['hear', 'a noise'],
    ['watch', 'a film'], ['finish', 'my homework'], ['start', 'the game'],
    ['dance', 'at the party'], ['plant', 'some seeds'], ['drop', 'my glove'],
    ['cry', 'all night'], ['try', 'the hard one'], ['study', 'the spelling list'],
    ['want', 'a drink'], ['need', 'a rest'], ['smile', 'at the photo'],
    ['live', 'in a big house'], ['clap', 'our hands'], ['hop', 'like a frog']
];

// Subjects that take the base verb form ("I walk", "They walk") — never
// third-person -s, so the present line is always grammatical.
const REWRITE_SUBJECTS = ['I', 'We', 'They', 'You', 'The children', 'My friends'] as const;

// Past tense (Year 2 and up) — FIVE procedural kinds:
//   0. "What is the past tense of X?"           (written recall)
//   1. same ask with 3 past-form options        (MC identify)
//   2. "Rewrite in the past tense: <sentence>"  (apply — whole sentence)
//   3. "True or false: the past tense of X is Y." (check — classic errors)
//   4. "Write about yesterday using '<past>'."  (open-ended compose —
//      the key models one sentence and accepts any sensible one)
//
// NON-REPEATING SAMPLING: bases are dealt from a deck (every verb is asked
// before any repeats) and the question passes through sampleUnique keyed on
// the printed prompt.
function generateTense(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const baseDeck = createDeck(rng, TENSE_PAIRS);
    const frameDeck = createDeck(rng, VERB_FRAMES);
    const pastForms = TENSE_PAIRS.map(([, past]) => past);
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 4);
            const [base, past] = baseDeck.take();
            if (kind === 0) {
                return { prompt: `What is the past tense of "${base}"?`, answer: past };
            }
            if (kind === 1) {
                // Multiple choice: the answer beside two past forms from other verbs.
                const options = [past];
                let guard = 0;
                while (options.length < 3 && guard < 24) {
                    guard++;
                    const pick = rng.pick(pastForms);
                    if (!options.includes(pick)) options.push(pick);
                }
                const shown = shuffleWords(rng, options);
                return { prompt: `What is the past tense of "${base}"? (${shown.join(', ')})`, answer: past };
            }
            if (kind === 2) {
                // APPLY: rewrite a whole present-tense sentence in the past.
                // The frame is curated for THIS verb, so only the verb swaps.
                // If the dealt base has no frame, draw a framed verb instead.
                const frame = VERB_FRAMES.find(([b]) => b === base) ?? frameDeck.take();
                const subject = rng.pick(REWRITE_SUBJECTS);
                return {
                    prompt: `Rewrite in the past tense: "${subject} ${frame[0]} ${frame[1]}."`,
                    answer: `${subject} ${TENSE_PAIRS.find(([b]) => b === frame[0])?.[1] ?? past} ${frame[1]}.`
                };
            }
            if (kind === 3) {
                // CHECK: half the claims are right, half are the classic
                // over-regularisation ("goed") or the uninflected base.
                const irregular = base !== past;
                const truthful = rng.next() < 0.5;
                let claim: string;
                if (truthful) claim = past;
                else if (irregular) claim = `${base}ed`; // goed / runned / eated
                else claim = base; // "walk" claimed as its own past tense
                return {
                    prompt: `True or false: the past tense of "${base}" is "${claim}".`,
                    answer: claim === past ? 'true' : 'false'
                };
            }
            // OPEN-ENDED compose: the key models one yesterday-sentence with
            // the dealt verb's frame and explicitly accepts any sensible one.
            const frame = VERB_FRAMES.find(([b]) => b === base);
            const subject = rng.pick(REWRITE_SUBJECTS);
            const example = frame ? `${subject} ${past} ${frame[1]}.` : `Yesterday, ${subject.toLowerCase()} ${past}.`;
            return {
                prompt: `Write a sentence about something that happened yesterday. Use "${past}".`,
                answer: `Example: ${example} (any sensible sentence using "${past}" is correct)`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests). T4C: 8 roomy
// rows per page instead of 24 cramped ones.
export const tenseSpec: WorksheetSpec = {
    id: 'tense',
    label: 'Past Tense',
    icon: '→',
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('tense'),
    scope: () => 'past forms',
    generate: generateTense
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PastTenseWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(tenseSpec);
}
