// ─────────────────────────────────────────────────────────────────────────────
// PLURALS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PluralsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Plurals", glyph "s") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Plurals worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// LEARNING VISUALS (Y1–3 only — the early cue band, isEarlyCueBand = word
// tiers 2..4): QUANTITY CONTRAST — "What is the plural of 'cat'?" prints ONE
// cat, "What is the singular of 'cats'?" prints THREE cats. Counting the
// pictures IS the lesson. The answer word is never printed, so the contrast
// is purely visual. Bank words without a registered pictogram (and the Prep /
// Year 4+ tiers) print plain (legacy markup).
function picture(caps: Caps, word: string): string | undefined {
    return isEarlyCueBand(caps) && hasVisual(word) ? word : undefined;
}

// Plural pairs [singular, plural]. Regular -s/-es endings (always on) — grown
// from 15 to 29 pairs; the irregular set is Year-2 (tricky) only.
const PLURAL_REGULAR: [string, string][] = [
    ['cat', 'cats'],
    ['dog', 'dogs'],
    ['kid', 'kids'],
    ['bird', 'birds'],
    ['cup', 'cups'],
    ['map', 'maps'],
    ['pen', 'pens'],
    ['pig', 'pigs'],
    ['boat', 'boats'],
    ['ball', 'balls'],
    ['star', 'stars'],
    ['door', 'doors'],
    ['bus', 'buses'],
    ['box', 'boxes'],
    ['watch', 'watches'],
    ['hat', 'hats'],
    ['moon', 'moons'],
    ['book', 'books'],
    ['tree', 'trees'],
    ['frog', 'frogs'],
    ['fan', 'fans'],
    ['net', 'nets'],
    ['pot', 'pots'],
    ['top', 'tops'],
    ['bag', 'bags'],
    ['jam', 'jams'],
    ['leg', 'legs'],
    ['log', 'logs'],
    ['wig', 'wigs']
];
const PLURAL_IRREGULAR: [string, string][] = [
    ['child', 'children'],
    ['man', 'men'],
    ['woman', 'women'],
    ['foot', 'feet'],
    ['tooth', 'teeth'],
    ['mouse', 'mice'],
    ['goose', 'geese'],
    ['ox', 'oxen'],
    ['person', 'people']
];

// Plurals: "what is the plural of X?" / "what is the singular of X?" over the
// regular set, extended with the irregular set for Year 2 (tricky). 60% of
// questions are written-answer; 40% offer three options (the right form plus
// two forms from other pairs) — that option-combination space pushes the
// worksheet past a thousand unique questions.
//
// NON-REPEATING SAMPLING: pairs AND direction are dealt from decks, and the
// whole question passes through sampleUnique keyed on the printed prompt.
function generatePlural(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool: [string, string][] = caps.tricky
        ? [...PLURAL_REGULAR, ...PLURAL_IRREGULAR]
        : PLURAL_REGULAR;
    const pairDeck = createDeck(rng, pool);
    // Direction deck: plural-ask and singular-ask alternate evenly.
    const askDeck = createDeck(rng, [true, false]);
    const forms = pool.flat();
    return sampleUnique(
        count,
        () => {
            const [sing, pl] = pairDeck.take();
            const pluralAsk = askDeck.take();
            // Quantity-contrast cue of the SINGULAR concept: one picture when
            // the child must pluralise, three when they must singularise.
            const pic = picture(caps, sing);
            const picCount = pluralAsk ? 1 : 3;
            if (rng.next() < 0.6) {
                // Written answer, random direction.
                return pluralAsk
                    ? { prompt: `What is the plural of "${sing}"?`, answer: pl, visual: pic, visualCount: picCount }
                    : { prompt: `What is the singular of "${pl}"?`, answer: sing, visual: pic, visualCount: picCount };
            }
            // Multiple choice: the answer beside two forms from other pairs.
            const answer = pluralAsk ? pl : sing;
            const options = [answer];
            let guard = 0;
            while (options.length < 3 && guard < 24) {
                guard++;
                const pick = rng.pick(forms);
                if (!options.includes(pick)) options.push(pick);
            }
            const shown = shuffleWords(rng, options);
            return {
                prompt: pluralAsk
                    ? `What is the plural of "${sing}"? (${shown.join(', ')})`
                    : `What is the singular of "${pl}"? (${shown.join(', ')})`,
                answer,
                visual: pic,
                visualCount: picCount
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const pluralSpec: WorksheetSpec = {
    id: 'plural',
    label: 'Plurals',
    icon: 's',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('plural'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'regular & irregular' : 'regular -s endings'),
    generate: generatePlural
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PluralsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(pluralSpec);
}
