// ─────────────────────────────────────────────────────────────────────────────
// PLURALS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PluralsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Plurals", glyph "s") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Plurals worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Plural pairs [singular, plural]. Regular -s/-es endings (always on); the
// irregular set is Year-2 (tricky) only.
const PLURAL_REGULAR: [string, string][] = [
    ['cat', 'cats'],
    ['dog', 'dogs'],
    ['kid', 'kids'],
    ['bird', 'birds'],
    ['cup', 'cups'],
    ['map', 'maps'],
    ['pen', 'pens'],
    ['pig', 'pigs'],
    ['boat', 'boats'],
    ['ball', 'balls'],
    ['star', 'stars'],
    ['door', 'doors'],
    ['bus', 'buses'],
    ['box', 'boxes'],
    ['watch', 'watches']
];
const PLURAL_IRREGULAR: [string, string][] = [
    ['child', 'children'],
    ['man', 'men'],
    ['woman', 'women'],
    ['foot', 'feet'],
    ['tooth', 'teeth'],
    ['mouse', 'mice'],
    ['goose', 'geese'],
    ['ox', 'oxen'],
    ['person', 'people']
];

// Plurals: "what is the plural of X?" / "what is the singular of X?" over the
// regular set, extended with the irregular set for Year 2 (tricky).
function generatePlural(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const pool: [string, string][] = caps.tricky
        ? [...PLURAL_REGULAR, ...PLURAL_IRREGULAR]
        : PLURAL_REGULAR;
    for (let i = 0; i < count; i++) {
        const [sing, pl] = rng.pick(pool);
        if (rng.next() < 0.5) {
            out.push({ prompt: `What is the plural of "${sing}"?`, answer: pl });
        } else {
            out.push({ prompt: `What is the singular of "${pl}"?`, answer: sing });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const pluralSpec: WorksheetSpec = {
    id: 'plural',
    label: 'Plurals',
    icon: 's',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('plural'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'regular & irregular' : 'regular -s endings'),
    generate: generatePlural
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PluralsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(pluralSpec);
}
