// ─────────────────────────────────────────────────────────────────────────────
// PLURALS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PluralsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Plurals", glyph "s") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Plurals worksheet without affecting the framework or any other
// plugin.
//
// T4B REWORK (quality over quantity):
//   - DENSITY: perPage 24 → 8 roomy rows.
//   - TASK MIX (five genuine formats beyond option shuffling):
//       1. written plural/singular (quantity-contrast cue)
//       2. three-option plural/singular MCQ
//       3. SENTENCE cloze — the correct form inside a real sentence
//          ("The __ ran fast." child/children) — grammar in use;
//       4. ENDING RULE — which suffix makes the word plural (-s / -es / -ies)
//          — the spelling pattern itself is the answer;
//       5. FORM SPELLING — pick the correctly spelled plural beside two
//          curated wrong forms (childs / childrens) — targets the tricky
//          irregular and -es spellings directly.
//   - BANKS: local curated pairs expanded 29→46 regular and 9→14 irregular,
//     plus 20 curated sentence items and 16 curated form-spelling items.
//     words.ts is read-only shared data this wave; new words live HERE.
//   - ANSWER SAFETY: every pair is disjoint (no word in two pairs); the
//     ending-rule answer is derived from the word's own ending (deterministic
//     function, asserted in the tests); -f→-ves words are excluded from the
//     ending rule so it never asks an irregular question.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// LEARNING VISUALS (Y1–3 only — the early cue band, isEarlyCueBand = word
// tiers 2..4): QUANTITY CONTRAST — "What is the plural of 'cat'?" prints ONE
// cat, "What is the singular of 'cats'?" prints THREE cats. Counting the
// pictures IS the lesson. The answer word is never printed, so the contrast
// is purely visual. Bank words without a registered pictogram (and the Prep /
// Year 4+ tiers) print plain (legacy markup).
function picture(caps: Caps, word: string): string | undefined {
    return isEarlyCueBand(caps) && hasVisual(word) ? word : undefined;
}

// Plural pairs [singular, plural]. Regular -s/-es endings (always on); the
// irregular set is Year-2 (tricky) only.
const PLURAL_REGULAR: [string, string][] = [
    ['cat', 'cats'],
    ['dog', 'dogs'],
    ['kid', 'kids'],
    ['bird', 'birds'],
    ['cup', 'cups'],
    ['map', 'maps'],
    ['pen', 'pens'],
    ['pig', 'pigs'],
    ['boat', 'boats'],
    ['ball', 'balls'],
    ['star', 'stars'],
    ['door', 'doors'],
    ['bus', 'buses'],
    ['box', 'boxes'],
    ['watch', 'watches'],
    ['hat', 'hats'],
    ['moon', 'moons'],
    ['book', 'books'],
    ['tree', 'trees'],
    ['frog', 'frogs'],
    ['fan', 'fans'],
    ['net', 'nets'],
    ['pot', 'pots'],
    ['top', 'tops'],
    ['bag', 'bags'],
    ['jam', 'jams'],
    ['leg', 'legs'],
    ['log', 'logs'],
    ['wig', 'wigs'],
    // T4B regular extension — grade-fit Y1 nouns (bed/duck/orange/flower also
    // carry PICS cues automatically via picture()).
    ['egg', 'eggs'],
    ['car', 'cars'],
    ['van', 'vans'],
    ['bed', 'beds'],
    ['duck', 'ducks'],
    ['hen', 'hens'],
    ['bee', 'bees'],
    ['orange', 'oranges'],
    ['grape', 'grapes'],
    ['flower', 'flowers'],
    ['fox', 'foxes'],
    ['dish', 'dishes'],
    ['brush', 'brushes'],
    ['sandwich', 'sandwiches'],
    ['peach', 'peaches'],
    ['tomato', 'tomatoes'],
    ['potato', 'potatoes']
];
const PLURAL_IRREGULAR: [string, string][] = [
    ['child', 'children'],
    ['man', 'men'],
    ['woman', 'women'],
    ['foot', 'feet'],
    ['tooth', 'teeth'],
    ['mouse', 'mice'],
    ['goose', 'geese'],
    ['ox', 'oxen'],
    ['person', 'people'],
    // T4B irregular extension — the -ves plurals and -oes (Y2 tricky).
    ['leaf', 'leaves'],
    ['life', 'lives'],
    ['knife', 'knives'],
    ['half', 'halves'],
    ['hero', 'heroes']
];

// SENTENCE cloze items: [sentence with one "__", singular, plural, answer].
// The sentence context (numerals, verbs, articles) makes exactly one form
// correct — grammar in use, not just form recall.
const PLURAL_SENTENCE: [string, string, string, string][] = [
    ['The __ ran fast across the yard.', 'child', 'children', 'children'],
    ['One __ and two mice.', 'mouse', 'mice', 'mouse'],
    ['Three __ live in our garden.', 'bird', 'birds', 'birds'],
    ['I have two __ on my feet.', 'foot', 'feet', 'feet'],
    ['The dentist counted my __.', 'tooth', 'teeth', 'teeth'],
    ['The farmer has ten __.', 'pig', 'pigs', 'pigs'],
    ['Look at the baby __!', 'child', 'children', 'children'],
    ['We saw six __ in the pond.', 'frog', 'frogs', 'frogs'],
    ['Mum bought fresh __ at the market.', 'egg', 'eggs', 'eggs'],
    ['My brother counts the __ at night.', 'star', 'stars', 'stars'],
    ['We planted three __ in spring.', 'tree', 'trees', 'trees'],
    ['The __ hopped across the yard.', 'hen', 'hens', 'hens'],
    ['I ate two __ at lunch.', 'orange', 'oranges', 'oranges'],
    ['The __ flew south for winter.', 'goose', 'geese', 'geese'],
    ['The __ make honey in the hive.', 'bee', 'bees', 'bees'],
    ['We eat with __ and forks.', 'knife', 'knives', 'knives'],
    ['The __ fell off the trees in autumn.', 'leaf', 'leaves', 'leaves'],
    ['The story has three __.', 'hero', 'heroes', 'heroes'],
    ['A __ lives in a hive.', 'bee', 'bees', 'bee']
];

// FORM SPELLING items: [correct plural, wrong form A, wrong form B, prompt
// word]. Curated so each wrong form is a real child error pattern (dropped
// -e, doubled plural, -s on an irregular).
const PLURAL_FORMS: [string, string, string, string][] = [
    ['children', 'childs', 'childrens', 'child'],
    ['feet', 'foots', 'feets', 'foot'],
    ['teeth', 'tooths', 'teeths', 'tooth'],
    ['mice', 'mouses', 'mices', 'mouse'],
    ['geese', 'gooses', 'geeses', 'goose'],
    ['men', 'mans', 'mens', 'man'],
    ['women', 'womans', 'womens', 'woman'],
    ['oxen', 'oxes', 'oxens', 'ox'],
    ['leaves', 'leafs', 'leafes', 'leaf'],
    ['knives', 'knifes', 'kives', 'knife'],
    ['halves', 'halvs', 'halfs', 'half'],
    ['heroes', 'heros', 'heroies', 'hero'],
    ['tomatoes', 'tomatos', 'tomateos', 'tomato'],
    ['potatoes', 'potatos', 'potateos', 'potato'],
    ['buses', 'bus', 'busies', 'bus'],
    ['boxes', 'boxs', 'boxies', 'box'],
    ['watches', 'watchs', 'watchies', 'watch'],
    ['dishes', 'dishs', 'dishies', 'dish']
];

// The -es rule for the ENDING format: s/x/z/ch/sh (and the -o nouns in the
// bank) take -es; everything else takes -s. -f→-ves irregulars are excluded
// from this format entirely, so the rule never meets an exception.
function esEnding(word: string): boolean {
    return /(s|x|z|ch|sh|o)$/.test(word);
}

// Plurals: "what is the plural of X?" / "what is the singular of X?" over the
// regular set, extended with the irregular set for Year 2 (tricky), plus the
// sentence-cloze, ending-rule and form-spelling formats.
//
// NON-REPEATING SAMPLING: pairs AND direction are dealt from decks, sentence
// and form items run on their own decks, and the whole question passes
// through sampleUnique keyed on the printed prompt — the option-combination
// space pushes the worksheet past several thousand unique questions.
function generatePlural(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool: [string, string][] = caps.tricky
        ? [...PLURAL_REGULAR, ...PLURAL_IRREGULAR]
        : PLURAL_REGULAR;
    const pairDeck = createDeck(rng, pool);
    // Direction deck: plural-ask and singular-ask alternate evenly.
    const askDeck = createDeck(rng, [true, false]);
    // Sentence items: irregular answers only appear when tricky is on.
    const sentencePool = caps.tricky
        ? PLURAL_SENTENCE
        : PLURAL_SENTENCE.filter(([, sing]) => PLURAL_REGULAR.some(([s]) => s === sing));
    const sentenceDeck = createDeck(rng, sentencePool);
    // Form items: irregular ones gated by tricky.
    const formsPool = caps.tricky
        ? PLURAL_FORMS
        : PLURAL_FORMS.filter((f) => PLURAL_REGULAR.some(([s]) => s === f[3]));
    const formsDeck = createDeck(rng, formsPool);
    const forms = pool.flat();
    return sampleUnique(
        count,
        () => {
            const [sing, pl] = pairDeck.take();
            const pluralAsk = askDeck.take();
            // Quantity-contrast cue of the SINGULAR concept: one picture when
            // the child must pluralise, three when they must singularise.
            const pic = picture(caps, sing);
            const picCount = pluralAsk ? 1 : 3;
            const roll = rng.next();
            if (roll < 0.3) {
                // Format 1 — written answer, random direction.
                return pluralAsk
                    ? { prompt: `What is the plural of "${sing}"?`, answer: pl, visual: pic, visualCount: picCount }
                    : { prompt: `What is the singular of "${pl}"?`, answer: sing, visual: pic, visualCount: picCount };
            }
            if (roll < 0.55) {
                // Format 2 — multiple choice: the answer beside two forms from
                // other pairs.
                const answer = pluralAsk ? pl : sing;
                const options = [answer];
                let guard = 0;
                while (options.length < 3 && guard < 24) {
                    guard++;
                    const pick = rng.pick(forms);
                    if (!options.includes(pick)) options.push(pick);
                }
                const shown = shuffleWords(rng, options);
                return {
                    prompt: pluralAsk
                        ? `What is the plural of "${sing}"? (${shown.join(', ')})`
                        : `What is the singular of "${pl}"? (${shown.join(', ')})`,
                    answer,
                    visual: pic,
                    visualCount: picCount
                };
            }
            if (roll < 0.8) {
                // Format 3 — sentence cloze. Cue follows the same quantity
                // rule: answer is the plural form → ONE picture of the
                // singular concept; answer is the singular → THREE.
                const [sentence, s2, p2, answer] = sentenceDeck.take();
                const pic2 = picture(caps, s2);
                const count2 = answer === p2 ? 1 : 3;
                const shown = shuffleWords(rng, [s2, p2]);
                return {
                    prompt: `Choose the right word: ${sentence} (${shown.join(', ')})`,
                    answer,
                    visual: pic2,
                    visualCount: count2
                };
            }
            if (roll < 0.9) {
                // Format 4 — ending rule. IRREGULAR stems (mouse, child, the
                // -ves and -oes forms) never enter this format: their plural
                // is not built by a suffix choice, so the question would be
                // misleading. They fall back to a safe written ask instead.
                const stem = sing;
                if (PLURAL_IRREGULAR.some(([s]) => s === stem)) {
                    return pluralAsk
                        ? { prompt: `What is the plural of "${sing}"?`, answer: pl, visual: pic, visualCount: picCount }
                        : { prompt: `What is the singular of "${pl}"?`, answer: sing, visual: pic, visualCount: picCount };
                }
                const answer = esEnding(stem) ? '-es' : '-s';
                return {
                    prompt: `Which ending makes "${stem}" plural? (-s, -es, -ies)`,
                    answer
                };
            }
            // Format 5 — form spelling: pick the correctly spelled plural.
            const [right, wrongA, wrongB, word] = formsDeck.take();
            const shown = shuffleWords(rng, [right, wrongA, wrongB]);
            return {
                prompt: `Which is the plural of "${word}" spelled correctly? (${shown.join(', ')})`,
                answer: right
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const pluralSpec: WorksheetSpec = {
    id: 'plural',
    label: 'Plurals',
    icon: 's',
    // T4B density: 8 roomy rows per page (was 24).
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('plural'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'regular & irregular' : 'regular -s endings'),
    generate: generatePlural
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PluralsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(pluralSpec);
}
