// ─────────────────────────────────────────────────────────────────────────────
// PRONOUNS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — personal and possessive pronouns replacing nouns).
//
// The dashboard loads this plugin by calling `PronounWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Pronouns", glyph "⊙") and which grades offer it
//     (Year 3+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Pronouns worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Subject/possessive pronoun replacement items: [noun phrase, subject
// pronoun, possessive pronoun, sentence with "__" (subject slot)].
const PRONOUN_ITEMS: [string, string, string, string][] = [
    ['Mia', 'she', 'her', '__ plays netball on Saturdays.'],
    ['Sam', 'he', 'his', '__ fed the chickens.'],
    ['the children', 'they', 'their', '__ caught the bus home.'],
    ['my brother and I', 'we', 'our', '__ built a sandcastle.'],
    ['Grandpa', 'he', 'his', '__ told a long story.'],
    ['Zoe and Ben', 'they', 'their', '__ swam at the beach.'],
    ['the teacher', 'she', 'her', '__ read the class a book.'],
    ['my dog', 'it', 'its', '__ buried a bone in the yard.'],
    ['Ava', 'she', 'her', '__ painted a picture of the harbour.'],
    ['Leo', 'he', 'his', '__ lost a tooth at school.'],
    ['the students', 'they', 'their', '__ planted seedlings in the garden.'],
    ['my cousin and I', 'we', 'our', '__ rode our bikes to the shop.'],
    ['Dad', 'he', 'his', '__ cooked dinner on Friday.'],
    ['the twins', 'they', 'their', '__ sang in the choir.'],
    ['Mum', 'she', 'her', '__ drove us to training.'],
    ['the cat', 'it', 'its', '__ chased a butterfly.'],
    ['Ella', 'she', 'her', '__ won the running race.'],
    ['Jack', 'he', 'his', '__ wrote a story about space.']
];

// Pronouns — FOUR procedural kinds (upper primary):
//   0. written: replace the noun phrase with the SUBJECT pronoun
//   1. MC: which pronoun replaces the noun phrase (subject pronoun beside
//      two other subject pronouns)
//   2. written: replace the noun phrase with the POSSESSIVE pronoun ("my
//      sister's" -> "her")
//   3. fill-the-blank: the printed sentence's "__" takes which pronoun (MC)
//
// NON-REPEATING SAMPLING: items are dealt from a deck and every question
// passes through sampleUnique keyed on the printed prompt.
function generatePronoun(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, PRONOUN_ITEMS);
    const subjectPronouns = ['he', 'she', 'it', 'they', 'we'] as const;
    return sampleUnique(
        count,
        () => {
            const [noun, subject, possessive, sentence] = itemDeck.take();
            const kind = rng.int(0, 3);
            if (kind === 0) {
                return { prompt: `Replace "${noun}" with a pronoun: ${noun} did something kind.`, answer: subject };
            }
            if (kind === 1) {
                // MC: the right subject pronoun beside two other subjects.
                const others = subjectPronouns.filter((p) => p !== subject);
                const o1 = rng.pick(others);
                let o2 = rng.pick(others);
                if (o2 === o1) o2 = others[(others.indexOf(o1) + 1) % others.length];
                const shown = shuffleLocal(rng, [subject, o1, o2]);
                return { prompt: `Which pronoun can replace "${noun}"? (${shown.join(', ')})`, answer: subject };
            }
            if (kind === 2) {
                return {
                    prompt: `Which possessive pronoun shows what belongs to ${noun}? ("${noun}'s book")`,
                    answer: possessive
                };
            }
            // Fill the blank: which pronoun completes the printed sentence.
            // The two distractors are distinct and never the answer.
            const others = subjectPronouns.filter((p) => p !== subject);
            const o1 = rng.pick(others);
            let o2 = rng.pick(others);
            if (o2 === o1) o2 = others[(others.indexOf(o1) + 1) % others.length];
            const shown = shuffleLocal(rng, [subject, o1, o2]);
            return { prompt: `Fill in the missing pronoun: ${sentence} (${shown.join(', ')})`, answer: subject };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests).
export const pronounSpec: WorksheetSpec = {
    id: 'pronoun',
    label: 'Pronouns',
    icon: '⊙',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('pronoun'),
    scope: () => 'pronouns replace nouns',
    generate: generatePronoun
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PronounWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(pronounSpec);
}
