// ─────────────────────────────────────────────────────────────────────────────
// PRONOUNS WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — personal and possessive pronouns replacing nouns).
//
// The dashboard loads this plugin by calling `PronounWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Pronouns", glyph "⊙") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Pronouns worksheet without affecting the framework or any other
// plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 18 rows to 8
// roomy ones. Two correctness FIXES: the old replace kind printed the filler
// template "<noun> did something kind." (a broken, meaningless line), and the
// old possessive kind built "'<noun>'s book" — producing ungrammatical
// "my brother and I's book". Items now carry their OWN curated subject and
// possessive sentences, so every line reads. OBJECT pronouns (him/her/them/
// us/it) and a correct/incorrect CHECK family join the subject/possessive
// work, plus an open-ended COMPOSE. The bank grew from 18 to 30 items.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Subject/possessive pronoun replacement items:
//   [noun phrase, subject pronoun, possessive pronoun,
//    subject sentence with "__" (subject slot), possessive sentence with "__"].
// Every sentence is curated for its noun, so no assembled line can read
// broken (the old "my brother and I's book" bug is impossible now).
// Grown from 18 to 30 items for T4C.
const PRONOUN_ITEMS: [string, string, string, string, string][] = [
    ['Mia', 'she', 'her', '__ plays netball on Saturdays.', '__ bag is on the chair.'],
    ['Sam', 'he', 'his', '__ fed the chickens.', '__ bike is red.'],
    ['the children', 'they', 'their', '__ caught the bus home.', '__ bags are in the hall.'],
    ['my brother and I', 'we', 'our', '__ built a sandcastle.', '__ sandcastle was huge.'],
    ['Grandpa', 'he', 'his', '__ told a long story.', '__ glasses are on the table.'],
    ['Zoe and Ben', 'they', 'their', '__ swam at the beach.', '__ towels were blue.'],
    ['the teacher', 'she', 'her', '__ read the class a book.', '__ desk is tidy.'],
    ['my dog', 'it', 'its', '__ buried a bone in the yard.', '__ bowl is empty.'],
    ['Ava', 'she', 'her', '__ painted a picture of the harbour.', '__ brush is new.'],
    ['Leo', 'he', 'his', '__ lost a tooth at school.', '__ toothbrush is pink.'],
    ['the students', 'they', 'their', '__ planted seedlings in the garden.', '__ project won first prize.'],
    ['my cousin and I', 'we', 'our', '__ rode bikes to the shop.', '__ helmets were shiny.'],
    ['Dad', 'he', 'his', '__ cooked dinner on Friday.', '__ toolbox is in the shed.'],
    ['the twins', 'they', 'their', '__ sang in the choir.', '__ voices were loud.'],
    ['Mum', 'she', 'her', '__ drove us to training.', '__ car is parked outside.'],
    ['the cat', 'it', 'its', '__ chased a butterfly.', '__ favourite spot is the windowsill.'],
    ['Ella', 'she', 'her', '__ won the running race.', '__ medal shines.'],
    ['Jack', 'he', 'his', '__ wrote a story about space.', '__ rocket model is huge.'],
    ['the koalas', 'they', 'their', '__ slept in the big gum.', '__ fur was grey.'],
    ['Nanna', 'she', 'her', '__ baked a pumpkin pie.', '__ recipe book is old.'],
    ['Max and Ivy', 'they', 'their', '__ trained the puppy.', '__ new puppy is playful.'],
    ['the spider', 'it', 'its', '__ spun a huge web.', '__ web sparkled with dew.'],
    ['Mrs Chen', 'she', 'her', '__ taught us long division.', '__ class is fun.'],
    ['the farmers', 'they', 'their', '__ harvested the crops.', '__ tractor is brand new.'],
    ['Ben', 'he', 'his', '__ kicked the penalty goal.', '__ boots are muddy.'],
    ['the baby', 'she', 'her', '__ giggled at peekaboo.', '__ blanket is soft.'],
    ['the birds', 'they', 'their', '__ nested in the fig.', '__ songs woke us.'],
    ['Ellie', 'she', 'her', '__ recited a poem.', '__ voice was clear.'],
    ['the robot', 'it', 'its', '__ swept the floor.', '__ battery needs charging.'],
    ['my friends', 'they', 'their', '__ came over after school.', '__ bikes were rainbow-coloured.']
];

// Object-pronoun items (T4C new area): [noun phrase, object pronoun,
// sentence containing the noun phrase in OBJECT position].
const OBJECT_ITEMS: [string, string, string][] = [
    ['the children', 'them', 'The teacher praised the children.'],
    ['Mia', 'her', 'We waved at Mia.'],
    ['Sam', 'him', 'Grandpa called Sam.'],
    ['the dog', 'it', 'Sarah fed the dog.'],
    ['my brother and I', 'us', 'Mum drove my brother and I home.'],
    ['Ava and Zoe', 'them', 'I invited Ava and Zoe to the party.'],
    ['the teacher', 'her', 'The students thanked the teacher.'],
    ['Dad', 'him', 'We watched Dad cook breakfast.'],
    ['the koalas', 'them', 'We saw the koalas at the sanctuary.'],
    ['Nanna', 'her', 'Ben hugged Nanna.']
];

// CHECK items (T4C new family): curated sentences judged correct/incorrect —
// the classic subject/object mix-ups children make.
const PRONOUN_CHECKS: [string, string][] = [
    ['Him went to the shop.', 'incorrect'],
    ['She finished her lunch.', 'correct'],
    ['Them played together.', 'incorrect'],
    ['They played together.', 'correct'],
    ['Us rode our bikes.', 'incorrect'],
    ['We rode our bikes.', 'correct'],
    ['He gave her the book.', 'correct'],
    ['Her gave him the book.', 'incorrect'],
    ['The class liked they.', 'incorrect'],
    ['The class liked them.', 'correct'],
    ['They finished their project.', 'correct'],
    ['She sang her song.', 'correct']
];

// Pronouns — SEVEN procedural kinds (upper primary):
//   0. written: replace the noun phrase with the SUBJECT pronoun (in the
//      item's own curated sentence)
//   1. MC: which pronoun replaces the noun phrase (subject pronoun beside
//      two other subject pronouns)
//   2. written: fill the POSSESSIVE pronoun into the item's own sentence
//   3. fill-the-blank: the printed sentence's "__" takes which pronoun (MC)
//   4. written: replace the noun phrase with the OBJECT pronoun
//   5. CHECK: "Does this sentence use the pronoun correctly?" correct/incorrect
//   6. open-ended COMPOSE: "write a sentence that starts with a pronoun" —
//      the key models one and accepts any sensible sentence
//
// NON-REPEATING SAMPLING: items are dealt from decks and every question
// passes through sampleUnique keyed on the printed prompt.
function generatePronoun(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const itemDeck = localDeck(rng, PRONOUN_ITEMS);
    const objectDeck = localDeck(rng, OBJECT_ITEMS);
    const checkDeck = localDeck(rng, PRONOUN_CHECKS);
    const subjectPronouns = ['he', 'she', 'it', 'they', 'we'] as const;
    // Capitalise a sentence-initial word (the "__" slot sits at the start of
    // every curated sentence, so the replacement must be capitalised).
    const cap = (s: string) => s[0].toUpperCase() + s.slice(1);
    // Two DISTINCT distractor subject pronouns beside the answer.
    const distractors = (subject: string) => {
        const others = subjectPronouns.filter((p) => p !== subject);
        const o1 = rng.pick(others);
        let o2 = rng.pick(others);
        if (o2 === o1) o2 = others[(others.indexOf(o1) + 1) % others.length];
        return [o1, o2];
    };
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 6);
            if (kind === 4) {
                // OBJECT replacement in a curated sentence.
                const [noun, object, sentence] = objectDeck.take();
                return { prompt: `Replace "${noun}" with a pronoun: ${sentence}`, answer: object };
            }
            if (kind === 5) {
                // CHECK: correct/incorrect judgement of a curated line.
                const [sentence, verdict] = checkDeck.take();
                return {
                    prompt: `Does this sentence use the pronoun correctly? "${sentence}"`,
                    answer: verdict
                };
            }
            if (kind === 6) {
                // OPEN-ENDED compose: any sensible pronoun-initial sentence.
                return {
                    prompt: 'Write a sentence that starts with a pronoun.',
                    answer: 'Example: They rode their bikes after school. (any sensible sentence starting with a pronoun is correct)'
                };
            }
            const [noun, subject, possessive, subjectSentence, possessiveSentence] = itemDeck.take();
            if (kind === 0) {
                // FIX: the old template ("<noun> did something kind.") is
                // gone — the line is the item's own curated sentence with the
                // noun printed (capitalised at the line start), and the child
                // rewrites it with the pronoun.
                const line = cap(subjectSentence.replace('__', noun));
                return {
                    prompt: `Replace "${noun}" with a pronoun: ${line}`,
                    answer: cap(subject)
                };
            }
            if (kind === 1) {
                // MC: the right subject pronoun beside two other subjects.
                const [o1, o2] = distractors(subject);
                const shown = shuffleLocal(rng, [subject, o1, o2]);
                return { prompt: `Which pronoun can replace "${noun}"? (${shown.join(', ')})`, answer: subject };
            }
            if (kind === 2) {
                // FIX: possessive now fills the item's OWN sentence — no more
                // "'my brother and I's book" style constructions.
                return {
                    prompt: `Fill in the missing word: ${possessiveSentence} (${noun})`,
                    answer: cap(possessive)
                };
            }
            // Fill the blank: which pronoun completes the printed sentence.
            // The referent noun is printed in the task line so exactly ONE of
            // the three options is correct (without it, "she/he/it" all fit
            // "__ won the running race." — the ambiguity this fixes).
            const [o1, o2] = distractors(subject);
            const shown = shuffleLocal(rng, [subject, o1, o2]);
            return { prompt: `Fill in the missing pronoun for "${noun}": ${subjectSentence} (${shown.join(', ')})`, answer: subject };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// The plugin's declarative spec (exported for its own tests). T4C: 8 roomy
// rows per page instead of 18.
export const pronounSpec: WorksheetSpec = {
    id: 'pronoun',
    label: 'Pronouns',
    icon: '⊙',
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('pronoun'),
    scope: () => 'pronouns replace nouns',
    generate: generatePronoun
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PronounWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(pronounSpec);
}
