// ─────────────────────────────────────────────────────────────────────────────
// PUNCTUATION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PunctuationWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Punctuation", glyph "?") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Punctuation worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Punctuation pools: statements take ".", questions "?", exclamations "!".
const PUNCT_SAY = [
    'The cat is sleeping',
    'I like school',
    'The sun is up',
    'We eat lunch',
    'The dog is happy',
    'Mia has a red hat'
] as const;
const PUNCT_ASK = [
    'Where is the dog',
    'What is your name',
    'How are you',
    'Who is that girl',
    'Why is the sky blue'
] as const;
const PUNCT_EXCLAIM = [
    'I love ice cream',
    'What a big dog',
    'Look at that bird',
    'We won the game'
] as const;

// Punctuation: add the right mark at the end — "." statement, "?" question,
// "!" exclamation.
function generatePunct(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const kind = rng.int(0, 2);
        if (kind === 0) {
            out.push({ prompt: `Add the right punctuation: ${rng.pick(PUNCT_SAY)} __`, answer: '.' });
        } else if (kind === 1) {
            out.push({ prompt: `Add the right punctuation: ${rng.pick(PUNCT_ASK)} __`, answer: '?' });
        } else {
            out.push({ prompt: `Add the right punctuation: ${rng.pick(PUNCT_EXCLAIM)} __`, answer: '!' });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const punctSpec: WorksheetSpec = {
    id: 'punct',
    label: 'Punctuation',
    icon: '?',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('punct'),
    scope: () => '. ? ! marks',
    generate: generatePunct
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PunctuationWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(punctSpec);
}
