// ─────────────────────────────────────────────────────────────────────────────
// PUNCTUATION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PunctuationWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Punctuation", glyph "?") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Punctuation worksheet without affecting the framework or any
// other plugin.
//
// T4B REWORK (quality over quantity):
//   - DENSITY: perPage 24 → 8 (roomier rows with writing lines).
//   - BANKS: statements 18x20 → 28x30 slots, questions 8x18 → 14x26,
//     exclamations 34 → 50 curated lines.
//   - TASK MIX (four genuine formats instead of two prompt forms of one):
//       1. add the end mark (written answer);
//       2. which end mark fits (. ? ! choice);
//       3. REWRITE the sentence with its capital start AND end mark —
//          combines capitals + punctuation, the deepest format;
//       4. sentence-kind MCQ: statement / question / exclamation —
//          metalanguage recognition, not mark-fitting.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Punctuation pools — assembled from grammar slots so the line spaces are
// cross-products instead of hand-written lists:
//   statements:  28 subjects x 30 predicates = 840 lines ("The cat is sleeping")
//   questions:   14 openers  x 26 noun phrases = 364 lines ("Where is the dog")
//   exclamations: 50 curated lines ("I love ice cream")
// Each line is asked in up to FOUR prompt forms (written mark, mark choice,
// rewrite, sentence-kind MCQ), so the question space runs to several
// thousand distinct questions — dozens of pages before anything can repeat.
const PUNCT_SUBJECTS = [
    'The cat', 'The dog', 'My dad', 'My mom', 'The baby', 'The teacher', 'My friend', 'The bird',
    'The boy', 'The girl', 'My sister', 'My brother', 'The frog', 'The duck', 'The horse', 'My cousin',
    'The lion', 'The rabbit', 'The spider', 'The kookaburra', 'Grandma', 'The class', 'Our team', 'The train',
    'The moon', 'My puppy', 'The farmer', 'The koala'
] as const;
const PUNCT_PREDICATES = [
    'is sleeping', 'is happy', 'likes school', 'runs fast', 'is hungry', 'sings loudly', 'is here',
    'found the ball', 'is tired', 'plays outside', 'reads a book', 'drinks milk', 'is friendly',
    'paints pictures', 'walks home', 'eats lunch', 'is noisy', 'helps my dad', 'watches TV', 'rides a bike',
    'jumps high', 'digs in the garden', 'waits for the bell', 'chases the ball', 'is lost', 'feels sick',
    'sells fresh bread', 'cleans the classroom', 'flies south', 'brings the mail'
] as const;
const PUNCT_OPENERS = [
    'Where is', 'Who is', 'Can you see', 'Do you have', 'What is', 'Have you seen', 'Is that', 'Can I have',
    'When does', 'Why is', 'How many', 'Did you feed', 'Will we visit', 'Would you like'
] as const;
const PUNCT_THINGS = [
    'the dog', 'the cat', 'a pencil', 'my hat', 'the ball', 'your book', 'a bird', 'the milk',
    'my shoe', 'the door', 'a flower', 'my lunch', 'the moon', 'a cookie', 'your bag', 'the star',
    'my coat', 'the kite', 'the postman', 'a map', 'the farm', 'your glasses', 'the seeds', 'a torch',
    'the whiteboard', 'my sneakers'
] as const;
const PUNCT_EXCLAIM = [
    'I love ice cream', 'What a big dog', 'Look at that bird', 'We won the game',
    'What a fast car', 'I love this book', 'Look at the moon', 'We did it',
    'What a sunny day', 'I am so hungry', 'What a great idea', 'The fire is hot',
    'What a tall tree', 'What a red kite', 'I love my bike', 'What a messy room',
    'Look at that frog', 'We can go now', 'What a lovely song', 'I am so happy',
    'What a funny clown', 'Look at the stars', 'What a shiny bell', 'I love my puppy',
    'What a rainy day', 'What a huge fish', 'Look at the ducks', 'What a sweet kitten',
    'I am so tired', 'What a fun game', 'Look at the ponies', 'What a cosy den',
    'I love my grandma', 'What a bright light',
    // T4B extension — more exclamatory lines.
    'What a loud thunderclap', 'Look at that rainbow', 'We finished the puzzle', 'What a cold day',
    'I love this song', 'What a clever fox', 'Look at the fireworks', 'What a long queue',
    'I am so excited', 'What a beautiful shell'
] as const;

// Sentence-kind labels for the MCQ format (kind 3): the child names the
// FUNCTION of the sentence — the metalanguage the end marks encode.
const PUNCT_KINDS = ['a statement', 'a question', 'an exclamation'] as const;

// Punctuation: add the right mark at the end — "." statement, "?" question,
// "!" exclamation — asked in four forms: a plain written-answer line, a
// "which end mark fits" choice line (fixed mark order), a full REWRITE
// (capital start + end mark), and a sentence-kind choice.
//
// NON-REPEATING SAMPLING: slot decks spread coverage evenly across a long
// document and every question passes through sampleUnique keyed on the
// printed prompt.
function generatePunct(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const subjectDeck = createDeck(rng, PUNCT_SUBJECTS);
    const predicateDeck = createDeck(rng, PUNCT_PREDICATES);
    const openerDeck = createDeck(rng, PUNCT_OPENERS);
    const thingDeck = createDeck(rng, PUNCT_THINGS);
    const exclaimDeck = createDeck(rng, PUNCT_EXCLAIM);
    return sampleUnique(
        count,
        () => {
            // Pick the line type first (statement / question / exclamation),
            // then the prompt format — so every line type appears in every
            // format over a long sheet.
            const kind = rng.int(0, 2);
            const format = rng.int(0, 3);
            let line: string;
            let mark: string;
            let kindLabel: string;
            if (kind === 0) {
                line = `${subjectDeck.take()} ${predicateDeck.take()}`;
                mark = '.';
                kindLabel = PUNCT_KINDS[0];
            } else if (kind === 1) {
                line = `${openerDeck.take()} ${thingDeck.take()}`;
                mark = '?';
                kindLabel = PUNCT_KINDS[1];
            } else {
                line = exclaimDeck.take();
                mark = '!';
                kindLabel = PUNCT_KINDS[2];
            }
            if (format === 0) {
                // Format 1 — written end mark.
                return { prompt: `Add the right punctuation: ${line} __`, answer: mark };
            }
            if (format === 1) {
                // Format 2 — end-mark choice (fixed mark order).
                return { prompt: `Which end mark fits: ${line} __ (. ? !)`, answer: mark };
            }
            if (format === 2) {
                // Format 3 — rewrite with capital start + end mark. The line
                // banks are stored lower-case mid-sentence with a capital
                // start; the rewrite prompt prints the WHOLE line lower-case
                // so the child restores both the start capital and the mark.
                const answer = `${line}${mark}`;
                return { prompt: `Rewrite this sentence with the correct start letter and end mark: ${line.toLowerCase()}`, answer };
            }
            // Format 4 — sentence-kind MCQ (metalanguage recognition).
            const options = shuffleWords(rng, [kindLabel, ...PUNCT_KINDS.filter((k) => k !== kindLabel)]);
            return { prompt: `What kind of sentence is this: "${line}${mark}" (${options.join(', ')})`, answer: kindLabel };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const punctSpec: WorksheetSpec = {
    id: 'punct',
    label: 'Punctuation',
    icon: '?',
    // T4B density: 8 rows per page (was 24).
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('punct'),
    scope: () => '. ? ! marks',
    generate: generatePunct
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PunctuationWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(punctSpec);
}
