// ─────────────────────────────────────────────────────────────────────────────
// RHYMING WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `RhymingWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Rhyming Words", glyph "≈") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Rhyming Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// LEARNING VISUALS (Y1–3 only — the early cue band, isEarlyCueBand = word
// tiers 2..4): the base word ("Which word rhymes with 'cat'?") carries its
// picture cue. The base is never the answer (the child must pick the RHYME),
// so the picture is a safe scaffold; Prep (tier 1) and Years 4+ print plain
// (legacy markup).
function picture(caps: Caps, word: string): string | undefined {
    return isEarlyCueBand(caps) && hasVisual(word) ? word : undefined;
}

// Rhyme families: base word -> words that rhyme with it. Tiers 2/3 add the
// "-ight" and long-vowel families.
const RHIME_BANK: Record<string, string[]> = {
    cat: ['hat', 'bat', 'mat'],
    dog: ['log', 'hog'],
    sun: ['fun', 'run'],
    cup: ['up', 'pup'],
    pen: ['hen', 'ten'],
    pig: ['big', 'dig', 'wig'],
    bed: ['red', 'fed'],
    hat: ['cat', 'mat', 'bat'],
    fan: ['pan', 'can', 'man'],
    top: ['hop', 'mop', 'lop'],
    red: ['bed', 'fed', 'led'],
    pin: ['tin', 'fin', 'bin'],
    pot: ['hot', 'got', 'cot'],
    rat: ['fat', 'vat'],
    // Tier 2+ families
    night: ['light', 'sight', 'flight'],
    chair: ['hair', 'pair'],
    light: ['night', 'sight', 'flight'],
    green: ['clean', 'mean', 'screen'],
    // Tier 3+ families
    apple: ['happy', 'maple']
};
// Non-rhyme distractor pool: checked against every rhyme family above, so a
// distractor can never accidentally rhyme with the base word. Grown from 10
// to 19 members — with two distinct distractors drawn per question the
// combination space (base x rhyme x C(19,2) option sets) clears a thousand
// unique questions many times over.
const RHYME_DISTRACT = [
    'fish', 'tree', 'bird', 'milk', 'king', 'star', 'door', 'duck', 'leaf', 'rock',
    'moon', 'spoon', 'hand', 'corn', 'nest', 'gift', 'cloud', 'west', 'sand'
] as const;
// Which families a tier offers: tier1 = the short families; tier2 adds
// night/chair/light/green; tier3 adds apple.
function rhymeBases(tier: number): readonly string[] {
    const all: readonly string[] = ['cat', 'dog', 'sun', 'cup', 'pen', 'pig', 'bed', 'hat', 'fan', 'top', 'red', 'pin', 'pot', 'rat'];
    const t2: readonly string[] = [...all, 'night', 'chair', 'light', 'green'];
    const t3: readonly string[] = [...t2, 'apple'];
    if (tier >= 3) return t3;
    if (tier >= 2) return t2;
    return all;
}

// Rhyming words: one rhyme from the base's family plus two non-rhyming
// distractors, shuffled; the child picks the rhyme.
//
// NON-REPEATING SAMPLING: bases are dealt from a deck (every family appears
// before any repeats) and each question is collected through sampleUnique
// keyed on the printed prompt, so distinct distractor pairs on the same base
// are distinct questions.
function generateRhyme(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const bases = rhymeBases(caps.wordTier);
    const baseDeck = createDeck(rng, bases);
    return sampleUnique(
        count,
        () => {
            const base = baseDeck.take();
            // Picture cue for the base word (the answer is the rhyme it picks,
            // so the base's picture is a scaffold, not a give-away).
            const pic = picture(caps, base);
            const rhyme = rng.pick(RHIME_BANK[base]);
            // Two distinct non-rhyme distractors (the pool never rhymes with any
            // base — see RHYME_DISTRACT).
            const d1 = rng.pick(RHYME_DISTRACT);
            let d2 = rng.pick(RHYME_DISTRACT);
            if (d2 === d1) d2 = rng.pick(RHYME_DISTRACT.filter((w) => w !== d1));
            const options = shuffleWords(rng, [rhyme, d1, d2]);
            return {
                prompt: `Which word rhymes with "${base}"? (${options.join(', ')})`,
                answer: rhyme,
                visual: pic
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const rhymeSpec: WorksheetSpec = {
    id: 'rhyme',
    label: 'Rhyming Words',
    icon: '≈',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('rhyme'),
    scope: () => 'rhyme families',
    generate: generateRhyme
};

// The plugin: a function the dashboard calls with its framework bundle.
export function RhymingWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(rhymeSpec);
}
