// ─────────────────────────────────────────────────────────────────────────────
// RHYMING WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `RhymingWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Rhyming Words", glyph "≈") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Rhyming Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// ── Task design (T4A) ────────────────────────────────────────────────────────
// SIX materially different connected rhyme tasks over a much deeper local
// family bank, dealt evenly from a kind deck:
//
//   0 RECOGNIZE "Which word rhymes with 'cat'? (hat, fish, rock)"
//   1 BUILD     "Write a word that rhymes with 'cat'."  (open slot; the model
//               answer lists the whole family — any member is correct)
//   2 CHECK     "Do 'cat' and 'hat' rhyme? (yes / no)"  (true AND false pairs)
//   3 CHECK     "Which word does NOT rhyme? (hat, cat, dog)"  odd-one-out
//   4 APPLY     "Choose the word that rhymes to fill the gap: The cat sat on
//               the __. (mat, dog, cup)"  — use the rhyme in a sentence
//   5 RECOGNIZE "Which word rhymes with the picture?"   (base PICTURED, not
//               printed — Y1–Y3 band only)
//
// DENSITY (E2): perPage 18 -> 8.
//
// FAMILY BANK (E1/E3): grown from 15 to ~60 curated bases across the rimes
// -at -og -un -en -ig -ed -an -op -ot -in -ug -ap -ip -et -ight -air -een
// -oon -ouse -ing plus the syllabic -appy family. Every member is a
// KNOWN_WORD_SET word (words.ts stays read-only; the plugin tests assert it).
//
// RHYME TRUTH (E4): distractors and odd-ones-out are screened by a local
// rime() ending test (substring from the last vowel — conservative, it only
// ever REJECTS a candidate, never mislabels a rhyme) AND family membership,
// so a "does NOT rhyme" answer can never accidentally rhyme with the pair.

// LEARNING VISUALS (Y1–3 only — the early cue band, isEarlyCueBand = word
// tiers 2..4): the base word ("Which word rhymes with 'cat'?") carries its
// picture cue. The base is never the answer (the child must pick the RHYME),
// so the picture is a safe scaffold; Prep (tier 1) and Years 4+ print plain
// (legacy markup).
function picture(caps: Caps, word: string): string | undefined {
    return isEarlyCueBand(caps) && hasVisual(word) ? word : undefined;
}

// Rhyme families: base word -> words that rhyme with it. Tiers gate which
// bases are offered (see rhymeBases). All members are KNOWN_WORD_SET words.
// Exported (with rhymes() below) so the tests can verify every printed row
// against the authoritative family data, not a heuristic guess.
export const RHIME_BANK: Record<string, string[]> = {
    // ── short rimes (every tier) ────────────────────────────────────────────
    cat: ['hat', 'bat', 'mat', 'sat', 'rat', 'fat'],
    hat: ['cat', 'bat', 'mat', 'sat', 'rat', 'fat'],
    bat: ['cat', 'hat', 'mat', 'sat'],
    mat: ['cat', 'hat', 'bat', 'sat'],
    sat: ['cat', 'hat', 'bat', 'mat', 'rat', 'fat'],
    rat: ['fat', 'cat', 'hat', 'sat'],
    fat: ['rat', 'cat', 'hat', 'sat'],
    dog: ['log', 'hog', 'frog'],
    log: ['dog', 'hog', 'frog'],
    hog: ['dog', 'log', 'frog'],
    frog: ['dog', 'log', 'hog'],
    sun: ['fun', 'run', 'bun'],
    fun: ['sun', 'run', 'bun'],
    run: ['sun', 'fun', 'bun'],
    bun: ['sun', 'fun', 'run'],
    cup: ['up', 'pup'],
    up: ['cup', 'pup'],
    pup: ['cup', 'up'],
    pen: ['hen', 'ten', 'men'],
    hen: ['pen', 'ten', 'men'],
    ten: ['pen', 'hen', 'men'],
    men: ['pen', 'hen', 'ten'],
    pig: ['big', 'dig', 'wig'],
    big: ['pig', 'dig', 'wig'],
    dig: ['pig', 'big', 'wig'],
    wig: ['pig', 'big', 'dig'],
    bed: ['red', 'fed', 'led'],
    red: ['bed', 'fed', 'led'],
    fed: ['bed', 'red', 'led'],
    led: ['bed', 'red', 'fed'],
    fan: ['pan', 'can', 'man'],
    pan: ['fan', 'can', 'man'],
    can: ['fan', 'pan', 'man'],
    man: ['fan', 'pan', 'can'],
    top: ['hop', 'mop', 'lop'],
    hop: ['top', 'mop', 'lop'],
    mop: ['top', 'hop', 'lop'],
    lop: ['top', 'hop', 'mop'],
    pot: ['hot', 'got', 'cot'],
    hot: ['pot', 'got', 'cot'],
    got: ['pot', 'hot', 'cot'],
    cot: ['pot', 'hot', 'got'],
    pin: ['tin', 'fin', 'bin'],
    tin: ['pin', 'fin', 'bin'],
    fin: ['pin', 'tin', 'bin'],
    bin: ['pin', 'tin', 'fin'],
    bug: ['tug', 'hug', 'jug'],
    tug: ['bug', 'hug', 'jug'],
    hug: ['bug', 'tug', 'jug'],
    jug: ['bug', 'tug', 'hug'],
    map: ['cap', 'nap', 'tap', 'gap', 'lap'],
    cap: ['map', 'nap', 'tap', 'gap', 'lap'],
    nap: ['map', 'cap', 'tap', 'gap', 'lap'],
    tap: ['map', 'cap', 'nap', 'gap', 'lap'],
    gap: ['map', 'cap', 'nap', 'lap', 'tap'],
    lap: ['map', 'cap', 'nap', 'gap', 'tap'],
    sip: ['dip', 'lip', 'hip', 'skip'],
    dip: ['sip', 'lip', 'hip', 'skip'],
    lip: ['sip', 'dip', 'hip', 'skip'],
    hip: ['sip', 'dip', 'lip', 'skip'],
    skip: ['sip', 'dip', 'lip', 'hip'],
    net: ['jet', 'bet', 'pet', 'set', 'wet', 'get'],
    jet: ['net', 'bet', 'pet', 'set', 'wet', 'get'],
    bet: ['net', 'jet', 'pet', 'set', 'wet', 'get'],
    pet: ['net', 'jet', 'bet', 'set', 'wet', 'get'],
    set: ['net', 'jet', 'bet', 'pet', 'wet', 'get'],
    wet: ['net', 'jet', 'bet', 'pet', 'set', 'get'],
    get: ['net', 'jet', 'bet', 'pet', 'set', 'wet'],
    // ── tier 2+ rimes ───────────────────────────────────────────────────────
    night: ['light', 'sight', 'flight'],
    light: ['night', 'sight', 'flight'],
    sight: ['night', 'light', 'flight'],
    flight: ['night', 'light', 'sight'],
    chair: ['hair', 'pair'],
    hair: ['chair', 'pair'],
    pair: ['chair', 'hair'],
    green: ['clean', 'mean', 'screen'],
    clean: ['green', 'mean', 'screen'],
    mean: ['green', 'clean', 'screen'],
    screen: ['green', 'clean', 'mean'],
    // -oon family: every member is a KNOWN_WORD_SET word ('spoon' is NOT —
    // it must never be printed, so the family uses noon/soon instead).
    moon: ['noon', 'soon'],
    noon: ['moon', 'soon'],
    soon: ['moon', 'noon'],
    house: ['mouse'],
    mouse: ['house'],
    king: ['sing', 'ring', 'thing', 'bring'],
    sing: ['king', 'ring', 'thing', 'bring'],
    ring: ['king', 'sing', 'thing', 'bring'],
    thing: ['king', 'sing', 'ring', 'bring'],
    bring: ['king', 'sing', 'ring', 'thing'],
    // ── tier 3+ syllabic family ─────────────────────────────────────────────
    // NOTE: 'apple'/'happy' do NOT rhyme (different unstressed endings) and
    // 'maple' is not a KNOWN_WORD_SET word — the syllabic family is -unny.
    sunny: ['funny'],
    funny: ['sunny']
};

// Which bases a tier offers: tier1 = the short rimes; tier2 adds the -ight
// /-air/-een/-oon/-ouse/-ing families; tier3 adds the syllabic -appy family.
const T1_BASES = Object.keys(RHIME_BANK).filter((b) => ['night', 'light', 'sight', 'flight', 'chair', 'hair', 'pair', 'green', 'clean', 'mean', 'screen', 'moon', 'noon', 'soon', 'house', 'mouse', 'king', 'sing', 'ring', 'thing', 'bring', 'sunny', 'funny'].indexOf(b) === -1);
const T2_BASES = T1_BASES.filter((b) => !['sunny', 'funny'].includes(b));
function rhymeBases(tier: number): readonly string[] {
    if (tier >= 3) return Object.keys(RHIME_BANK);
    if (tier >= 2) return T2_BASES;
    return T1_BASES;
}

// The word's RIME (ending from its last vowel) — a conservative rhyme test
// used only to REJECT distractors that would accidentally rhyme with a base
// (pin vs "spin", moon vs "spoon"). Silent-e words collapse to 'e', which
// over-rejects (safe direction).
function rime(word: string): string {
    for (let i = word.length - 1; i >= 0; i--) {
        if ('aeiou'.includes(word[i])) return word.slice(i);
    }
    return word;
}

// True when a and b rhyme: same curated family (authoritative) or equal rime
// (heuristic catch for words outside the bank). Exported for the tests.
export function rhymes(a: string, b: string): boolean {
    if (RHIME_BANK[a]?.includes(b) || RHIME_BANK[b]?.includes(a)) return true;
    return rime(a) === rime(b);
}

// Distractor candidates: real KNOWN words screened PER QUESTION against the
// base (rhymes() above), so a distractor can never accidentally rhyme.
const RHYME_DISTRACT = [
    'fish', 'tree', 'bird', 'milk', 'star', 'door', 'duck', 'leaf', 'rock',
    'moon', 'hand', 'corn', 'nest', 'gift', 'west', 'sand',
    'book', 'sun', 'cup', 'hat', 'pen', 'top', 'map', 'net', 'pig', 'dog',
    'bed', 'pin', 'pot', 'fan', 'bus', 'bag', 'box', 'red', 'wig'
] as const;

// Curated sentence frames for the APPLY kind: the frame carries a rhyme cue
// (cat/sat -> mat) and exactly one option completes BOTH the meaning and the
// rhyme. All frame words are KNOWN_WORD_SET members (asserted by tests).
// Exported so the tests can pin every gap-fill row to a curated pair.
export type RhymeFrame = { text: string; answer: string; wrong: string[] };
export const RHYME_FRAMES: readonly RhymeFrame[] = [
    { text: 'The cat sat on the __.', answer: 'mat', wrong: ['dog', 'cup'] },
    { text: 'The big pig wore a __.', answer: 'wig', wrong: ['cap', 'map'] },
    { text: 'The hen found ten __.', answer: 'pen', wrong: ['cup', 'fish'] },
    { text: 'The rat wore a __.', answer: 'hat', wrong: ['dog', 'log'] },
    { text: 'The sun was great __.', answer: 'fun', wrong: ['bed', 'pen'] },
    { text: 'The pin is in the __.', answer: 'tin', wrong: ['bag', 'bus'] },
    { text: 'The pot is very __.', answer: 'hot', wrong: ['big', 'bed'] },
    { text: 'The man has a __.', answer: 'pan', wrong: ['cup', 'bed'] },
    { text: 'The dog sat on a __.', answer: 'log', wrong: ['pen', 'sun'] },
    { text: 'The king can __.', answer: 'sing', wrong: ['eat', 'sleep'] },
    { text: 'The green board was __.', answer: 'clean', wrong: ['hot', 'sad'] }
];

// Rhyming words — the six kinds above over the family bank.
//
// NON-REPEATING SAMPLING: bases are dealt from a deck (every family appears
// before any repeats) and each question is collected through sampleUnique
// keyed on the printed prompt, so distinct distractor pairs on the same base
// are distinct questions.
function generateRhyme(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const bases = rhymeBases(caps.wordTier);
    const baseDeck = createDeck(rng, bases);
    const kindDeck = createDeck(rng, [0, 1, 2, 3, 4, 5]);
    const frameDeck = createDeck(rng, RHYME_FRAMES);
    // Two distinct distractors that do NOT rhyme with `base`.
    const distractors = (base: string, exclude: string[]): string[] => {
        const out: string[] = [];
        let guard = 0;
        while (out.length < 2 && guard < 60) {
            guard++;
            const cand = rng.pick(RHYME_DISTRACT);
            if (cand === base || exclude.includes(cand) || out.includes(cand)) continue;
            if (rhymes(cand, base)) continue;
            out.push(cand);
        }
        return out;
    };
    return sampleUnique(
        count,
        () => {
            const base = baseDeck.take();
            const kind = kindDeck.take();
            // Picture cue for the base word (the answer is the rhyme it picks
            // or a family member, so the base's picture is a scaffold, not a
            // give-away). Kinds 3/4 print no cue: their answer/odd-one sits
            // among printed words and a picture could point at it.
            const pic = picture(caps, base);
            const family = RHIME_BANK[base];
            if (kind === 0) {
                // RECOGNIZE: one rhyme + two non-rhyming distractors. If the
                // guard cannot supply two safe distractors, fall back to the
                // written BUILD form (never a degenerate 2-option row).
                const rhyme = rng.pick(family);
                const ds = distractors(base, [rhyme]);
                if (ds.length < 2) {
                    return { prompt: `Write a word that rhymes with "${base}".`, answer: family.join(', '), visual: pic };
                }
                const options = shuffleWords(rng, [rhyme, ...ds]);
                return { prompt: `Which word rhymes with "${base}"? (${options.join(', ')})`, answer: rhyme, visual: pic };
            }
            if (kind === 1) {
                // BUILD: write any rhyme; the model answer lists the family.
                return {
                    prompt: `Write a word that rhymes with "${base}".`,
                    answer: family.join(', '),
                    visual: pic
                };
            }
            if (kind === 2) {
                // CHECK: a true or false rhyme judgement about a word pair.
                const trueAsk = rng.next() < 0.5;
                if (trueAsk) {
                    const other = rng.pick(family);
                    return { prompt: `Do "${base}" and "${other}" rhyme? (yes / no)`, answer: 'yes', visual: pic };
                }
                const ds = distractors(base, []);
                if (ds.length < 1) {
                    // No safe non-rhyme for this base — fall back to BUILD.
                    return { prompt: `Write a word that rhymes with "${base}".`, answer: family.join(', '), visual: pic };
                }
                const other = ds[0];
                const [a, b] = rng.next() < 0.5 ? [base, other] : [other, base];
                return { prompt: `Do "${a}" and "${b}" rhyme? (yes / no)`, answer: 'no', visual: picture(caps, a) };
            }
            if (kind === 3) {
                // CHECK: odd one out — two family rhymes + one non-rhyme.
                // Needs a family of at least TWO members (moon/spoon and
                // house/mouse are pairs, never triples) — otherwise BUILD.
                if (family.length < 2) {
                    return { prompt: `Write a word that rhymes with "${base}".`, answer: family.join(', '), visual: pic };
                }
                const w1 = rng.pick(family);
                const w2 = rng.pick(family.filter((w) => w !== w1));
                const ds = distractors(base, [w1, w2]);
                const odd = ds.find((d) => !rhymes(d, w1) && !rhymes(d, w2));
                if (!odd) {
                    return { prompt: `Write a word that rhymes with "${base}".`, answer: family.join(', '), visual: pic };
                }
                const shown = shuffleWords(rng, [w1, w2, odd]);
                return { prompt: `Which word does NOT rhyme? (${shown.join(', ')})`, answer: odd };
            }
            if (kind === 4) {
                // APPLY: rhyme-cue gap fill from the curated frame bank.
                const frame = frameDeck.take();
                const options = shuffleWords(rng, [frame.answer, ...frame.wrong]);
                return {
                    prompt: `Choose the word that rhymes to fill the gap: ${frame.text} (${options.join(', ')})`,
                    answer: frame.answer
                };
            }
            // RECOGNIZE from the PICTURE (kind 5): the base is depicted, not
            // printed. Band-only (needs the cue); otherwise fall back to the
            // written MC form (kind 0).
            if (!isEarlyCueBand(caps) || !hasVisual(base)) {
                const rhyme = rng.pick(family);
                const ds = distractors(base, [rhyme]);
                const options = shuffleWords(rng, [rhyme, ...ds]);
                return { prompt: `Which word rhymes with "${base}"? (${options.join(', ')})`, answer: rhyme, visual: pic };
            }
            const rhyme = rng.pick(family);
            const ds = distractors(base, [rhyme]);
            if (ds.length < 2) {
                const options = shuffleWords(rng, [rhyme, ...ds]);
                return { prompt: `Which word rhymes with "${base}"? (${options.join(', ')})`, answer: rhyme, visual: pic };
            }
            const options = shuffleWords(rng, [rhyme, ...ds]);
            return { prompt: `Which word rhymes with the picture? (${options.join(', ')})`, answer: rhyme, visual: base };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const rhymeSpec: WorksheetSpec = {
    id: 'rhyme',
    label: 'Rhyming Words',
    icon: '≈',
    // E2 density: 8 rows per A4 page.
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('rhyme'),
    scope: () => 'rhyme families',
    generate: generateRhyme
};

// The plugin: a function the dashboard calls with its framework bundle.
export function RhymingWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(rhymeSpec);
}
