// ─────────────────────────────────────────────────────────────────────────────
// SENTENCE BUILDING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `SentenceBuildingWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Sentence Building", glyph "¶") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Sentence Building worksheet without affecting the framework or
// any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { shuffleWords } from './words';

// Sentence-building templates: fixed word lines, shortest (Prep) to longest
// (Year 2). Sentence lines are filtered by the grade's `sentenceLen` cap.
const SENTENCES_TIER1: string[] = ['Sam runs', 'Ben reads', 'Sue sings', 'Mia skips', 'Leo paints', 'Zoe draws'];
const SENTENCES_TIER2_EXTRA: string[] = [
    'The dog barks',
    'Sam has two cats',
    'The sun shines',
    'Ben sees a bird',
    'Sue reads a book',
    'Mia eats an apple',
    'Sam kicks the ball'
];
const SENTENCES_TIER3_EXTRA: string[] = [
    'The teacher reads a story',
    'My brother kicks the ball',
    'The little dog sleeps',
    'The cat chases the mouse'
];

// Sentence building: a template line is scrambled and printed as "put the
// words in the correct order: __, __, ...". Lines longer than the grade's
// sentenceLen cap are filtered out; a tier with no eligible lines falls back
// to its shortest line so the generator can never run dry.
function generateSentence(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const tierOk = (w: number) => w <= caps.sentenceLen;
    let pool: readonly string[] = SENTENCES_TIER1;
    if (caps.wordTier >= 2) pool = [...SENTENCES_TIER1, ...SENTENCES_TIER2_EXTRA];
    if (caps.wordTier >= 3) pool = [...pool, ...SENTENCES_TIER3_EXTRA];
    let eligible = pool.filter((s) => s.split(' ').length <= Math.max(2, caps.sentenceLen));
    if (eligible.length === 0) eligible = pool.slice().sort((a, b) => a.length - b.length).slice(0, Math.max(1, Math.min(3, pool.length)));
    for (let i = 0; i < count; i++) {
        const words = rng.pick(eligible).split(' ');
        const shown = shuffleWords(rng, words);
        const blanks = words.map(() => '__').join(', ');
        out.push({ prompt: `Put the words in the correct order: ${blanks}.  (${shown.join(', ')})`, answer: words.join(' ') });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn.
export const sentenceSpec: WorksheetSpec = {
    id: 'sentence',
    label: 'Sentence Building',
    icon: '¶',
    perPage: 12,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('sentence'),
    scope: (grade: GradeConfig) => `up to ${Math.max(2, grade.caps.sentenceLen)} words`,
    generate: generateSentence
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SentenceBuildingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(sentenceSpec);
}
