// ─────────────────────────────────────────────────────────────────────────────
// SIGHT & REAL WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SightWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Sight & Real Words", glyph "A") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Sight & Real Words worksheet without affecting the framework or
// any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { wordSet, KNOWN_WORD_SET, shuffleWords, inventNonWord } from './words';

// ── Task design (T4A) ────────────────────────────────────────────────────────
// The old sheet was ONE template ("Which is a real word?") repeated 18×/page.
// The plugin now rotates FOUR materially different but connected early-
// literacy task kinds over the same word knowledge, dealt evenly from a kind
// deck so a page mixes recognize / check / attend / apply work:
//
//   0 RECOGNIZE  "Which is a real word?"      1 real + 3 fake words
//   1 CHECK      "Which is NOT a real word?"  3 real + 1 fake word
//   2 ATTEND     "Which one is exactly 'X'?"  the word + look-alike words
//                (letter-order attention — the classic sight-word confusion
//                was/saw, here/there)
//   3 APPLY      "Fill the gap: The __ barks."  a curated sentence frame with
//                one sensible word from the bank (meaning, not form)
//
// DENSITY (E2): perPage 18 -> 6. Every row carries a four-option list, so six
// rows per A4 give the child real reading room per question.
//
// NO PICTURE CUES on this sheet at any grade (the answers ARE words — a
// picture would give them away; see visuals-sheets contract).
//
// NON-REPEATING SAMPLING: words are dealt from decks and every question is
// collected through sampleUnique keyed on the printed prompt, so a 100-page
// document contains no duplicate questions.

// Extra real-word blocklist (LOCAL, additive): common little words that are
// NOT in words.ts KNOWN_WORD_SET but a child would recognise as real. A fake
// distractor must not collide with these either, otherwise a "which is a real
// word?" row would print two real words. words.ts is shared/read-only in this
// wave, so the guard lives here.
// T5E review: single-letter mutations of bank words (jam→jim, pan→pam,
// net→nat, inn→ian, yap→yan, box→bob, bag→bad…) can wander into FIRST
// NAMES a child recognises (Jim, Tim, Sam, Bob, Pam, Ian, Nat…). Those are
// not in KNOWN_WORD_SET but must never print as a "not a real word" fake —
// a RECOGNIZE row with a name among its fakes would have two defensible
// answers. Found by sampling the actual 100-page fake census per grade.
const EXTRA_REAL_WORDS = new Set([
    'cit', 'pix', 'bub', 'boob', 'sis', 'bro', 'fam', 'nana', 'loll',
    'jim', 'tim', 'sam', 'bob', 'pam', 'jem', 'ian', 'nat', 'yan', 'ted',
    'bel', 'mal', 'gus', 'ron', 'dan', 'leo', 'ray'
]);

// Is the string genuinely a NON-word for this distribution? (KNOWN_WORD_SET
// plus the local blocklist above.)
function isFake(word: string): boolean {
    return !KNOWN_WORD_SET.has(word) && !EXTRA_REAL_WORDS.has(word);
}

// Invent a plausible non-word from a real base using one of three phonotactic
// mutations (substitution / vowel swap / consonant doubling). Deterministic on
// the rng stream. Falls back to the shared words.ts inventor if every draw
// wanders into a real word (rare).
function makeFake(rng: Rng, base: string): string {
    for (let guard = 0; guard < 40; guard++) {
        const strategy = rng.int(0, 2);
        let candidate = '';
        if (strategy === 0) {
            // Substitute one letter for a different random one.
            const i = rng.int(0, base.length - 1);
            const sub = String.fromCharCode(97 + rng.int(0, 25));
            if (sub === base[i]) continue;
            candidate = base.slice(0, i) + sub + base.slice(i + 1);
        } else if (strategy === 1) {
            // Swap one vowel for a different vowel (keeps the shape of a word).
            const vIdx = [...base].map((c, i) => ('aeiou'.includes(c) ? i : -1)).filter((i) => i >= 0);
            if (vIdx.length === 0) continue;
            const i = rng.pick(vIdx);
            const others = 'aeiou'.replace(base[i], '');
            const sub = others[rng.int(0, others.length - 1)];
            candidate = base.slice(0, i) + sub + base.slice(i + 1);
        } else {
            // Double one consonant (catt, sunn — wrong but word-shaped).
            const cIdx = [...base].map((c, i) => (!'aeiou'.includes(c) && i > 0 ? i : -1)).filter((i) => i >= 0);
            if (cIdx.length === 0) continue;
            const i = rng.pick(cIdx);
            candidate = base.slice(0, i) + base[i] + base.slice(i);
        }
        if (candidate !== base && isFake(candidate)) return candidate;
    }
    // Deterministic words.ts fallback, then a last-resort KNOWN-safety check.
    const fallback = inventNonWord(base);
    return isFake(fallback) ? fallback : `${base}z`;
}

// One look-alike real word for the "exactly X?" rows: a single-letter
// substitution that is itself a KNOWN real word (was→saw, here→there is
// beyond single-sub, but cat→hat/bat/mat covers the bank). Returns null when
// 60 random draws find none (very rare for these banks).
function lookAlike(rng: Rng, word: string): string | null {
    for (let guard = 0; guard < 60; guard++) {
        const i = rng.int(0, word.length - 1);
        const sub = String.fromCharCode(97 + rng.int(0, 25));
        if (sub === word[i]) continue;
        const cand = word.slice(0, i) + sub + word.slice(i + 1);
        if (KNOWN_WORD_SET.has(cand)) return cand;
    }
    return null;
}

// Curated sentence frames for the APPLY kind (local bank — words.ts is read-
// only this wave). Every frame has exactly ONE sensible answer among the
// printed options; the wrong options are real bank words that cannot fit the
// meaning ("The __ barks." with (dog, fish, bird) — only dog barks). All
// frame words are KNOWN_WORD_SET members (asserted by the plugin tests).
// Exported so the tests can pin that every gap-fill row is one of these
// curated (frame, answer) pairs — the semantic truth table of the kind.
export type ClozeFrame = { text: string; answer: string; wrong: string[] };
export const CLOZE_FRAMES: readonly ClozeFrame[] = [
    { text: 'The __ barks.', answer: 'dog', wrong: ['fish', 'bird'] },
    { text: 'Fish live in __.', answer: 'water', wrong: ['fire', 'rock'] },
    { text: 'You read a __.', answer: 'book', wrong: ['cup', 'hat'] },
    { text: 'The __ shines at night.', answer: 'moon', wrong: ['hat', 'pot'] },
    { text: 'Bees make __.', answer: 'honey', wrong: ['rock', 'sun'] },
    { text: 'Birds can __.', answer: 'fly', wrong: ['read', 'write'] },
    { text: 'You wear a __ in the rain.', answer: 'coat', wrong: ['cup', 'ball'] },
    { text: 'The cat drinks __.', answer: 'milk', wrong: ['rock', 'hat'] },
    { text: 'I eat soup with a __.', answer: 'spoon', wrong: ['shoe', 'hat'] },
    { text: 'You sleep in a __.', answer: 'bed', wrong: ['cup', 'hat'] },
    { text: 'The __ is in the sky.', answer: 'sun', wrong: ['fish', 'rock'] },
    { text: 'A __ has leaves.', answer: 'tree', wrong: ['dog', 'cup'] },
    { text: 'Snow is __.', answer: 'cold', wrong: ['hot', 'happy'] },
    { text: 'You write with a __.', answer: 'pen', wrong: ['hat', 'fish'] }
];

function generateSight(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = wordSet(caps.wordTier);
    const realDeck = createDeck(rng, pool);
    const fakeDeck = createDeck(rng, pool);
    // Kind + frame decks spread every task kind and every sentence frame
    // evenly across a long document (no kind or frame clusters).
    const kindDeck = createDeck(rng, [0, 1, 2, 3]);
    const frameDeck = createDeck(rng, CLOZE_FRAMES);
    return sampleUnique(
        count,
        () => {
            const kind = kindDeck.take();
            if (kind === 0) {
                // RECOGNIZE: one real word beside three plausible non-words.
                const real = realDeck.take();
                const fakes: string[] = [];
                let guard = 0;
                while (fakes.length < 3 && guard < 48) {
                    guard++;
                    const fake = makeFake(rng, fakeDeck.take());
                    if (fake !== real && !fakes.includes(fake)) fakes.push(fake);
                }
                const options = shuffleWords(rng, [real, ...fakes]);
                return { prompt: `Which is a real word? (${options.join(', ')})`, answer: real };
            }
            if (kind === 1) {
                // CHECK: three real words and the one fake among them.
                const reals: string[] = [];
                let guard = 0;
                while (reals.length < 3 && guard < 48) {
                    guard++;
                    const w = realDeck.take();
                    if (!reals.includes(w)) reals.push(w);
                }
                let fake = makeFake(rng, fakeDeck.take());
                guard = 0;
                while (reals.includes(fake) && guard < 24) {
                    guard++;
                    fake = makeFake(rng, fakeDeck.take());
                }
                const options = shuffleWords(rng, [...reals, fake]);
                return { prompt: `Which is NOT a real word? (${options.join(', ')})`, answer: fake };
            }
            if (kind === 2) {
                // ATTEND: find the exact same word among look-alikes. Only the
                // target itself equals the target, so the answer is unique.
                const target = realDeck.take();
                const others: string[] = [];
                let guard = 0;
                while (others.length < 3 && guard < 60) {
                    guard++;
                    const near = lookAlike(rng, target) ?? makeFake(rng, target);
                    if (near !== target && !others.includes(near)) others.push(near);
                }
                const options = shuffleWords(rng, [target, ...others]);
                return { prompt: `Which one is exactly the word "${target}"? (${options.join(', ')})`, answer: target };
            }
            // APPLY: meaning-based gap fill from the curated frame bank.
            const frame = frameDeck.take();
            const options = shuffleWords(rng, [frame.answer, ...frame.wrong]);
            return { prompt: `Fill the gap: ${frame.text} (${options.join(', ')})`, answer: frame.answer };
        },
        // Fingerprint = the full printed line (question + its exact options).
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const sightSpec: WorksheetSpec = {
    id: 'sight',
    label: 'Sight & Real Words',
    icon: 'A',
    // E2 density: four-option rows need reading room — 6 per A4 page.
    perPage: 6,
    offered: (grade: GradeConfig) => grade.available.includes('sight'),
    scope: (grade: GradeConfig) => `word set ${grade.caps.wordTier}`,
    generate: generateSight
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SightWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(sightSpec);
}
