// ─────────────────────────────────────────────────────────────────────────────
// SIGHT & REAL WORDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SightWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Sight & Real Words", glyph "A") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Sight & Real Words worksheet without affecting the framework or
// any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { wordSet, KNOWN_WORD_SET, shuffleWords, inventNonWord } from './words';

// Sight & real words: "which of these is a real word?" — one real word from
// the grade's word set beside three plausible non-words, shuffled.
function generateSight(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const pool = wordSet(caps.wordTier);
    for (let i = 0; i < count; i++) {
        const real = rng.pick(pool);
        // Build three DISTINCT non-words: keep drawing base words (possibly
        // the real word itself — its near-miss misspelling is the best
        // distractor) until three unique, real-word-safe fakes are collected.
        const fakes: string[] = [];
        let base = rng.pick(pool);
        let guard = 0;
        while (fakes.length < 3 && guard < 24) {
            guard++;
            const fake = inventNonWord(base);
            if (fake !== real && !fakes.includes(fake) && !KNOWN_WORD_SET.has(fake)) fakes.push(fake);
            base = rng.pick(pool);
        }
        const options = shuffleWords(rng, [real, ...fakes]);
        out.push({ prompt: `Which is a real word? (${options.join(', ')})`, answer: real });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const sightSpec: WorksheetSpec = {
    id: 'sight',
    label: 'Sight & Real Words',
    icon: 'A',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('sight'),
    scope: (grade: GradeConfig) => `word set ${grade.caps.wordTier}`,
    generate: generateSight
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SightWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(sightSpec);
}
