// ─────────────────────────────────────────────────────────────────────────────
// SIMILAR WORDS (SYNONYMS) WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `SimilarWordsWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Similar Words", glyph "≡") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Similar Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Similar (synonym) tuples: [target, synonym, distractor A, distractor B].
// Grown from 14 to 17 tuples; Year 2 (tricky) adds the extended set.
const SIMILAR_TIER2: [string, string, string, string][] = [
    ['happy', 'glad', 'sad', 'angry'],
    ['big', 'large', 'small', 'new'],
    ['small', 'tiny', 'big', 'new'],
    ['fast', 'quick', 'slow', 'cold'],
    ['cold', 'chilly', 'hot', 'warm'],
    ['hot', 'warm', 'cold', 'cool'],
    ['good', 'nice', 'bad', 'sad'],
    ['sad', 'unhappy', 'happy', 'tired'],
    ['small', 'little', 'big', 'tall'],
    ['look', 'see', 'hear', 'walk'],
    ['loud', 'noisy', 'quiet', 'still']
];
const SIMILAR_TIER3_EXTRA: [string, string, string, string][] = [
    ['angry', 'cross', 'happy', 'calm'],
    ['tired', 'sleepy', 'awake', 'happy'],
    ['quiet', 'silent', 'loud', 'noisy'],
    ['scared', 'afraid', 'brave', 'calm'],
    ['strong', 'mighty', 'weak', 'tiny'],
    ['easy', 'simple', 'hard', 'tricky']
];

// Similar words (synonyms): multiple-choice on word meaning — the target's
// synonym beside two words that do NOT mean the same. Distractors are drawn
// from the whole bank (minus the target's own tuple), so each distinct
// distractor pair is a distinct question — the combination space clears a
// thousand unique questions many times over.
//
// NON-REPEATING SAMPLING: targets are dealt from a deck (every word gets its
// turn before any repeats) and the question passes through sampleUnique keyed
// on the printed prompt.
function generateSimilar(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // The similar-word bank exists from Year 1; tiers 2 and 3 share it, with
    // the extra tuples gated by tricky (Y2) — mirrors the pattern of
    // degrading to the smallest usable pool instead of failing.
    const pool = (caps.wordTier >= 3 && caps.tricky ? [...SIMILAR_TIER2, ...SIMILAR_TIER3_EXTRA] : SIMILAR_TIER2);
    const targetDeck = createDeck(rng, pool);
    // Global distractor pool: every word in the bank, any tuple.
    const bankWords = pool.flat();
    // A word may anchor several tuples (e.g. "small" -> tiny AND little); a
    // distractor must never be ANY of the target's synonyms, or the question
    // would have two correct options.
    const synonyms = new Map<string, Set<string>>();
    for (const [target, syn] of pool) {
        if (!synonyms.has(target)) synonyms.set(target, new Set());
        synonyms.get(target)!.add(syn);
    }
    return sampleUnique(
        count,
        () => {
            const tuple = targetDeck.take();
            const [target, syn] = tuple;
            const wrongSynonyms = synonyms.get(target)!;
            // Two distractors from other tuples (own-tuple words would give
            // away the answer or clash with the synonym).
            const options = [syn];
            let guard = 0;
            while (options.length < 3 && guard < 24) {
                guard++;
                const pick = rng.pick(bankWords);
                if (pick === target || wrongSynonyms.has(pick)) continue;
                if (!options.includes(pick)) options.push(pick);
            }
            const shown = shuffleWords(rng, options);
            return { prompt: `Which word means the same as "${target}"? (${shown.join(', ')})`, answer: syn };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const similarSpec: WorksheetSpec = {
    id: 'similar',
    label: 'Similar Words',
    icon: '≡',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('similar'),
    scope: () => 'word meanings',
    generate: generateSimilar
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SimilarWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(similarSpec);
}
