// ─────────────────────────────────────────────────────────────────────────────
// SIMILAR WORDS (SYNONYMS) WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling
// `SimilarWordsWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Similar Words", glyph "≡") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Similar Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { shuffleWords } from './words';

// Similar (synonym) quadruples: [target, synonym, distractor A, distractor B].
const SIMILAR_TIER2: [string, string, string, string][] = [
    ['happy', 'glad', 'sad', 'angry'],
    ['big', 'large', 'small', 'new'],
    ['small', 'tiny', 'big', 'new'],
    ['fast', 'quick', 'slow', 'cold'],
    ['cold', 'chilly', 'hot', 'warm'],
    ['hot', 'warm', 'cold', 'cool'],
    ['good', 'nice', 'bad', 'sad'],
    ['sad', 'unhappy', 'happy', 'tired']
];
const SIMILAR_TIER3_EXTRA: [string, string, string, string][] = [
    ['angry', 'cross', 'happy', 'calm'],
    ['tired', 'sleepy', 'awake', 'happy'],
    ['quiet', 'silent', 'loud', 'noisy'],
    ['scared', 'afraid', 'brave', 'calm'],
    ['strong', 'mighty', 'weak', 'tiny'],
    ['easy', 'simple', 'hard', 'tricky']
];

// Similar words (synonyms): multiple-choice on word meaning — the target's
// synonym plus two unrelated words from the curated quadruples.
function generateSimilar(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    // The similar-word bank exists from Year 1; tiers 2 and 3 share it, with
    // the extra quadruples gated by tricky (Y2) — mirrors the pattern of
    // degrading to the smallest usable pool instead of failing.
    const pool = (caps.wordTier >= 3 && caps.tricky ? [...SIMILAR_TIER2, ...SIMILAR_TIER3_EXTRA] : SIMILAR_TIER2);
    for (let i = 0; i < count; i++) {
        const [target, syn, d1, d2] = rng.pick(pool);
        const options = shuffleWords(rng, [syn, d1, d2]);
        out.push({ prompt: `Which word means the same as "${target}"? (${options.join(', ')})`, answer: syn });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const similarSpec: WorksheetSpec = {
    id: 'similar',
    label: 'Similar Words',
    icon: '≡',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('similar'),
    scope: () => 'word meanings',
    generate: generateSimilar
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SimilarWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(similarSpec);
}
