// ─────────────────────────────────────────────────────────────────────────────
// DIRECT SPEECH WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — quotation marks and reporting clauses around direct
// speech; AU classroom convention: double quotes, comma before the quote).
//
// The dashboard loads this plugin by calling `SpeechWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Direct Speech", glyph "❝") and which grades offer
//     it (Year 3+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Direct Speech worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Question/exclamation speech lines (they take '?'/'!' INSIDE the quotes, no
// trailing comma) vs statement lines (comma inside, none after the quote).
const SPEECH_QUESTIONS: readonly string[] = [
    'Who left the gate open', 'Where are my runners', 'Can we go to the beach today',
    'Is the canteen still open', 'Whose turn is it to set the table', 'What time is the bus coming'
] as const;
const SPEECH_EXCLAIMS: readonly string[] = [
    'Look out below', 'We won the grand final', 'That was so close',
    'What a brilliant idea', 'Help, a spider', 'My plane actually flew'
] as const;
const SPEECH_STATEMENTS: readonly string[] = [
    'I brought the sports kit', 'The movie starts at six', 'Dinner is nearly ready',
    'We are going to the museum', 'My project is on volcanoes', 'Training is cancelled today'
] as const;
// Reporters, split by the line type they can carry: question speech rides
// with "asked X" reporters; statements/exclamations with "said X". This keeps
// every assembled line semantically consistent ("asked" + statement reads
// broken).
const REPORTERS_ASK: readonly string[] = ['asked Sam', 'asked Zoe', 'asked Ava', 'asked Jack'] as const;
const REPORTERS_SAY: readonly string[] = ['said Mia', 'said Leo', 'said Ben', 'said Ella'] as const;
// Subject-verb lines for the is-it-direct-speech MC kind.
const PLAIN_SENTENCES: readonly string[] = [
    'The dog ran across the park', 'We caught the ferry to the city',
    'Mum baked a batch of scones', 'The library closes at five'
] as const;

// Direct speech — FOUR procedural kinds (upper primary):
//   0. report-first written answer: 'Mia said, "…."' / 'Sam asked, "…?"'
//   1. speech-first written answer: '"…," said Mia.' / '"…?" asked Sam.'
//   2. MC: which sentence has the marks/commas in the right places
//   3. identify: "is this direct speech or plain writing?"
//
// PUNCTUATION CONVENTION (AU classrooms, double quotes):
//   statement  -> comma INSIDE the quotes, then the reporter, then '.'
//   ? / !      -> mark INSIDE the quotes, NO comma, then the reporter, then '.'
//
// NON-REPEATING SAMPLING: line x reporter cross-products keep the space past
// 100 pages; every question passes through sampleUnique keyed on prompt.
function generateSpeech(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 3);
            // Draw a (line, terminal mark) pair: question (?), exclamation (!)
            // or statement (,). The reporter always matches the line type.
            const r = rng.next();
            const ask = r < 0.4;
            const exclaim = !ask && r < 0.65;
            const line = ask
                ? rng.pick(SPEECH_QUESTIONS)
                : exclaim
                  ? rng.pick(SPEECH_EXCLAIMS)
                  : rng.pick(SPEECH_STATEMENTS);
            const end = ask ? '?' : exclaim ? '!' : '.';
            const reporter = ask ? rng.pick(REPORTERS_ASK) : rng.pick(REPORTERS_SAY);
            if (kind === 0) {
                // Report first: Mia said, "…." — the prompt prints the bare
                // line; the answer carries the full punctuation.
                const Name = reporter[0].toUpperCase() + reporter.slice(1);
                const right = `${Name}, "${line}${end}"`;
                return { prompt: `Add the speech marks and commas: ${Name} ${line}`, answer: right };
            }
            if (kind === 1) {
                // Speech first: "…," said Mia. / "…?" asked Sam.
                const right = ask || exclaim ? `"${line}${end}" ${reporter}.` : `"${line}," ${reporter}.`;
                return { prompt: `Add the speech marks and commas: ${line}. ${reporter}.`, answer: right };
            }
            if (kind === 2) {
                // MC: correct placement beside two classic errors — a comma
                // after ?/! that never belongs there, or a dropped/relocated
                // mark for statements.
                const right = ask || exclaim ? `"${line}${end}" ${reporter}.` : `"${line}," ${reporter}.`;
                const wrong1 = ask || exclaim ? `"${line}${end}", ${reporter}.` : `"${line}." ${reporter}.`;
                const wrong2 = ask || exclaim ? `"${line}"${end} ${reporter}.` : `"${line}", ${reporter}.`;
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return { prompt: `Which sentence shows the speech correctly? (${shown.join(' / ')})`, answer: right };
            }
            // Identify: direct speech vs plain sentence.
            const isSpeech = rng.next() < 0.5;
            const candidate = isSpeech
                ? (ask || exclaim ? `"${line}${end}" ${reporter}.` : `"${line}," ${reporter}.`)
                : `${rng.pick(PLAIN_SENTENCES)}.`;
            return {
                prompt: `Is this direct speech (someone speaking) or plain writing? ${candidate}`,
                answer: isSpeech ? 'direct speech' : 'plain writing'
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn.
export const speechSpec: WorksheetSpec = {
    id: 'speech',
    label: 'Direct Speech',
    icon: '❝',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('speech'),
    scope: () => 'speech marks & reporting',
    generate: generateSpeech
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SpeechWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(speechSpec);
}
