// ─────────────────────────────────────────────────────────────────────────────
// DIRECT SPEECH WORKSHEET — a self-contained dashboard plugin (upper primary:
// Year 3+; ACARA Y3–6 — quotation marks and reporting clauses around direct
// speech; AU classroom convention: double quotes, comma before the quote).
//
// The dashboard loads this plugin by calling `SpeechWorksheet(dashboard)` with
// its configurations + layouts (see plugins/index.ts). Within this function
// the plugin describes:
//   - its SIDEBAR LABEL ("Direct Speech", glyph "❝") and which grades offer
//     it (Year 3+ only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Direct Speech worksheet without affecting the framework or any
// other plugin.
//
// T4C REDESIGN (quality over quantity): the page shrank from 16 rows to 6
// roomy prose rows. CRITICAL FIX: the old report-first kind capitalised the
// reporter string ("said Mia" -> "Said Mia"), so prompts printed broken lines
// like `Said Mia I brought the sports kit` and the model answer repeated the
// error. Reporters are now structured [name, verb] and every assembled line
// reads correctly. The line banks roughly doubled, and three new families
// joined: WHO IS SPEAKING (identify), a correct/incorrect punctuation CHECK,
// and an open-ended COMPOSE whose key models one correctly punctuated line
// and accepts any other correctly punctuated one.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Question/exclamation speech lines (they take '?'/'!' INSIDE the quotes, no
// trailing comma) vs statement lines (comma inside, none after the quote).
// Grown from 6/6/6 to 12/12/14 lines for T4C.
const SPEECH_QUESTIONS: readonly string[] = [
    'Who left the gate open', 'Where are my runners', 'Can we go to the beach today',
    'Is the canteen still open', 'Whose turn is it to set the table', 'What time is the bus coming',
    'Did you feed the chickens', 'Which way did the comet go', 'Shall we enter the carnival',
    'Have you seen my glove', 'Why is the sky orange', 'When does the movie start'
] as const;
const SPEECH_EXCLAIMS: readonly string[] = [
    'Look out below', 'We won the grand final', 'That was so close',
    'What a brilliant idea', 'Help, a spider', 'My plane actually flew',
    'What a huge wave', 'We made it to the top', 'The rocket actually launched',
    'What a beautiful painting', 'We found a fossil', 'The koala is awake'
] as const;
const SPEECH_STATEMENTS: readonly string[] = [
    'I brought the sports kit', 'The movie starts at six', 'Dinner is nearly ready',
    'We are going to the museum', 'My project is on volcanoes', 'Training is cancelled today',
    'The canteen sells pineapple slices', 'Our team wears blue jumpers', 'Grandma brought seedlings',
    'The library closes at five', 'Tomorrow is the incursion', 'I lost a tooth at lunch',
    'The wetlands are full of birds', 'Saturday is the cross-country'
] as const;
// Reporters, split by the line type they can carry: question speech rides
// with "asked X" reporters; statements/exclamations with "said X". This keeps
// every assembled line semantically consistent ("asked" + statement reads
// broken). Grown from 4+4 to 8+8 names for T4C; stored as [name, verb] so the
// name never gets mid-string capitalised (the old report-first bug).
const REPORTERS_ASK: readonly [string, string][] = [
    ['Sam', 'asked'], ['Zoe', 'asked'], ['Ava', 'asked'], ['Jack', 'asked'],
    ['Mia', 'asked'], ['Leo', 'asked'], ['Ellie', 'asked'], ['Max', 'asked']
] as const;
const REPORTERS_SAY: readonly [string, string][] = [
    ['Mia', 'said'], ['Leo', 'said'], ['Ben', 'said'], ['Ella', 'said'],
    ['Sam', 'said'], ['Zoe', 'said'], ['Dad', 'said'], ['Mrs Chen', 'said']
] as const;
// Plain (no speech) sentences for the is-it-direct-speech identify kind.
// Grown from 4 to 8 for T4C.
const PLAIN_SENTENCES: readonly string[] = [
    'The dog ran across the park', 'We caught the ferry to the city',
    'Mum baked a batch of scones', 'The library closes at five',
    'Rain drummed on the tin roof', 'The class lined up quietly',
    'Cicadas sang in the big fig', 'We raked the leaves into a pile'
] as const;

// Direct speech — SEVEN procedural kinds (upper primary):
//   0. report-first written answer: Mia said, "…." / Sam asked, "…?"
//   1. speech-first written answer: "…," said Mia. / "…?" asked Sam.
//   2. MC: which sentence has the marks/commas in the right places
//   3. identify: "is this direct speech or plain writing?"
//   4. identify: "who is speaking in this sentence?" (answer = reporter name)
//   5. CHECK: "Is the speech punctuation correct?" correct/incorrect
//   6. open-ended COMPOSE: write your own direct-speech sentence with a named
//      reporter — the key models one and accepts any correctly punctuated one
//
// PUNCTUATION CONVENTION (AU classrooms, double quotes):
//   statement  -> comma INSIDE the quotes, then the reporter, then '.'
//   ? / !      -> mark INSIDE the quotes, NO comma, then the reporter, then '.'
//
// NON-REPEATING SAMPLING: line x reporter cross-products keep the space past
// 100 pages; every question passes through sampleUnique keyed on prompt.
function generateSpeech(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    return sampleUnique(
        count,
        () => {
            const kind = rng.int(0, 6);
            // Draw a (line, terminal mark) pair: question (?), exclamation (!)
            // or statement (,). The reporter always matches the line type.
            const r = rng.next();
            const ask = r < 0.4;
            const exclaim = !ask && r < 0.65;
            const line = ask
                ? rng.pick(SPEECH_QUESTIONS)
                : exclaim
                  ? rng.pick(SPEECH_EXCLAIMS)
                  : rng.pick(SPEECH_STATEMENTS);
            const end = ask ? '?' : exclaim ? '!' : '.';
            const [name, verb] = ask ? rng.pick(REPORTERS_ASK) : rng.pick(REPORTERS_SAY);
            // The three canonical punctuations of this (line, reporter) pair:
            // `right` is the correctly punctuated sentence; `wrong1`/`wrong2`
            // are the classic errors (stray comma after ?/!, comma or full
            // stop outside the quotes).
            const right = ask || exclaim ? `"${line}${end}" ${name} ${verb}.` : `"${line}," ${name} ${verb}.`;
            const wrong1 = ask || exclaim ? `"${line}${end}", ${name} ${verb}.` : `"${line}." ${name} ${verb}.`;
            const wrong2 = ask || exclaim ? `"${line}"${end} ${name} ${verb}.` : `"${line}", ${name} ${verb}.`;
            if (kind === 0) {
                // Report first: Mia said, "…." — the prompt prints the line
                // WITH its own end mark, so the child only adds speech marks
                // and the comma (the task promise matches the answer).
                return { prompt: `Add the speech marks and commas: ${name} ${verb} ${line}${end}`, answer: right };
            }
            if (kind === 1) {
                // Speech first: "…," said Mia. / "…?" asked Sam. Same rule:
                // the end mark is printed, never asked for.
                return { prompt: `Add the speech marks and commas: ${line}${end} ${name} ${verb}.`, answer: right };
            }
            if (kind === 2) {
                // MC: correct placement beside the two classic errors.
                const shown = shuffleLocal(rng, [right, wrong1, wrong2]);
                return { prompt: `Which sentence shows the speech correctly? (${shown.join(' / ')})`, answer: right };
            }
            if (kind === 3) {
                // Identify: direct speech vs plain sentence.
                const isSpeech = rng.next() < 0.5;
                const candidate = isSpeech ? right : `${rng.pick(PLAIN_SENTENCES)}.`;
                return {
                    prompt: `Is this direct speech (someone speaking) or plain writing? ${candidate}`,
                    answer: isSpeech ? 'direct speech' : 'plain writing'
                };
            }
            if (kind === 4) {
                // Identify: WHO is speaking — the reporting clause names them.
                return { prompt: `Who is speaking in: ${right}`, answer: name };
            }
            if (kind === 5) {
                // CHECK: half the printed sentences are punctuated correctly,
                // half carry one of the two classic speech-mark errors.
                const correct = rng.next() < 0.5;
                const candidate = correct ? right : rng.next() < 0.5 ? wrong1 : wrong2;
                return {
                    prompt: `Is the speech punctuation correct? ${candidate}`,
                    answer: correct ? 'correct' : 'incorrect'
                };
            }
            // OPEN-ENDED compose: the key models one correctly punctuated
            // sentence with the named reporter and accepts any other that is
            // correctly punctuated.
            return {
                prompt: `Write a sentence of direct speech that uses "${name} ${verb}".`,
                answer: `Example: ${right} (any correctly punctuated direct-speech sentence is correct)`
            };
        },
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Prose lines run
// single-column (full page width) via singleColumn. T4C: 6 roomy rows/page.
export const speechSpec: WorksheetSpec = {
    id: 'speech',
    label: 'Direct Speech',
    icon: '❝',
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('speech'),
    scope: () => 'speech marks & reporting',
    generate: generateSpeech
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SpeechWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(speechSpec);
}
