// ─────────────────────────────────────────────────────────────────────────────
// SPELLING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SpellingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Spelling", glyph "✎") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Spelling worksheet without affecting the framework or any other
// plugin.
//
// T4B REWORK (quality over quantity):
//   - DENSITY: perPage 18 → 8 roomy rows.
//   - TASK MIX (four genuine formats — the old sheet was one MCQ template):
//       1. correct-spelling MCQ (the classic, three options);
//       2. FIX IT — "Fix this misspelled word: 'catt'" → cat (written);
//       3. MISSING LETTER — "Write the missing letter: ca__" → t; the mask is
//          only used when NO other real English word fits it (checked
//          against KNOWN_WORD_SET, so "c_t" is never asked — cat/cot/cut);
//       4. UNSCRAMBLE — "Put the letters in the right order: tac" → cat;
//          only when the letter set forms exactly ONE real English word
//          (KNOWN_WORD_SET again — "tac" would be rejected because "act"
//          is also a word).
//   - The procedural misspelling family engine is kept (it is what gives
//     this sheet its thousands-deep space) and now also feeds formats 2-3.
//   - ANSWER SAFETY: formats 3-4 are gated by real-word uniqueness checks,
//     so every written-answer item has exactly one correct completion.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { wordSet, KNOWN_WORD_SET, shuffleWords } from './words';

// ── Procedural misspelling generator ─────────────────────────────────────────
// The old bank held 16 hand-curated [correct, fake, fake] triples — an 8-or-16
// question space that HAD to repeat on any long sheet. Now every word in the
// grade's word set is EXPANDED into its full family of safe misspellings at
// load, giving thousands of distinct questions ("cat" beside (catt, cwat) is a
// different question from "cat" beside (cta, cact)).
//
// Four edit families, all safe for kids' sheets:
//   - doubled letter   (cat -> catt, ccat)
//   - swapped letters  (bird -> brid, ibrdb-style neighbour swaps)
//   - dropped letter   (bread -> bead, bred)  [words of 4+ letters only]
//   - inserted letter  (cat -> cwat, cact)    [interior consonants only]
// Candidates that collide with a real word are DISCARDED via KNOWN_WORD_SET
// (which includes COMMON_WORDS — chat/cart/stun/bend/... — so an option set
// never contains two genuine English words). Old curated fakes (brid, catt…)
// stay in KNOWN_WORD_SET, which also keeps them out of the new combinations.
const FAKE_CONSONANTS = 'bcdfghjklmnprstvwz';

// Cache: pure function of the word, and a 1000-question document asks for the
// same word's family many times (dealt evenly by the deck below).
const misspellingCache = new Map<string, string[]>();

function misspellings(word: string): string[] {
    const cached = misspellingCache.get(word);
    if (cached) return cached;
    const candidates = new Set<string>();
    for (let i = 0; i < word.length; i++) {
        candidates.add(word.slice(0, i) + word[i] + word[i] + word.slice(i + 1));
        if (i + 1 < word.length) {
            candidates.add(word.slice(0, i) + word[i + 1] + word[i] + word.slice(i + 2));
        }
        if (word.length >= 4) {
            candidates.add(word.slice(0, i) + word.slice(i + 1));
        }
        // Interior insertions only: an initial letter can turn "hat" into the
        // real words "that/what", and an appended "s" makes real plurals
        // ("cats") — both would put a second real word on the sheet.
        if (i + 1 < word.length) {
            for (const c of FAKE_CONSONANTS) {
                candidates.add(word.slice(0, i + 1) + c + word.slice(i + 1));
            }
        }
    }
    const fakes = [...candidates].filter(
        (w) => w !== word && w.length >= 3 && !KNOWN_WORD_SET.has(w)
    );
    misspellingCache.set(word, fakes);
    return fakes;
}

// ── Uniqueness helpers for the written formats (formats 2-4) ────────────────
// A written spelling task is only fair when the answer is forced. These
// helpers measure that against the SHARED dictionary (KNOWN_WORD_SET), not
// just the grade pool, so a child who knows a word outside the pool can
// never be marked wrong for the "wrong" answer.

// fake -> number of pool words whose misspelling family contains it. A FIX-IT
// item is only asked when the fake belongs to exactly ONE pool word.
function buildFakeOwners(pool: readonly string[]): Map<string, number> {
    const owners = new Map<string, number>();
    for (const w of pool) {
        for (const f of misspellings(w)) {
            owners.set(f, (owners.get(f) ?? 0) + 1);
        }
    }
    return owners;
}

// True when NO word in KNOWN_WORD_SET matches `pattern` (a word with one
// letter replaced by "__") except `word` itself — the MISSING-LETTER gate.
function maskIsUnique(pattern: string, word: string): boolean {
    const idx = pattern.indexOf('__');
    for (const known of KNOWN_WORD_SET) {
        if (known === word) continue;
        if (known.length !== word.length) continue;
        let ok = true;
        for (let i = 0; i < word.length; i++) {
            const pi = i < idx ? i : i + 1; // skip the "__" slot
            if (known[i] !== pattern[pi]) {
                ok = false;
                break;
            }
        }
        if (ok) return false;
    }
    return true;
}

// True when `word` is the ONLY member of KNOWN_WORD_SET with these letters —
// the UNSCRAMBLE gate (sorted-letter signature).
function anagramIsUnique(word: string): boolean {
    const sig = [...word].sort().join('');
    for (const known of KNOWN_WORD_SET) {
        if (known !== word && known.length === word.length && [...known].sort().join('') === sig) {
            return false;
        }
    }
    return true;
}

// Spelling: correct-spelling MCQ, fix-the-misspelling, missing letter and
// unscramble over the whole grade word set (45 words Year 1 … 151 Year 6),
// dealt from a deck so every word shows up before any repeats.
function generateSpelling(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = [...new Set(wordSet(caps.wordTier))];
    const wordDeck = createDeck(rng, pool);
    const familyCache = new Map<string, string[]>();
    const fakeOwners = buildFakeOwners(pool);
    // Per-deal family lookup (cached across the document).
    const familyOf = (w: string): string[] => {
        let f = familyCache.get(w);
        if (!f) {
            f = misspellings(w);
            familyCache.set(w, f);
        }
        return f;
    };
    // Classic MCQ builder — also the safe fallback when a written-format
    // candidate fails its uniqueness gate.
    const mcq = (correct: string): RawProblem => {
        const family = familyOf(correct);
        const f1 = rng.pick(family);
        let f2 = rng.pick(family);
        let guard = 0;
        while (f2 === f1 && guard < 12) {
            guard++;
            f2 = rng.pick(family);
        }
        if (f2 === f1) f2 = family[(family.indexOf(f1) + 1) % family.length];
        const options = shuffleWords(rng, [correct, f1, f2]);
        return { prompt: `Which word is spelled correctly? (${options.join(', ')})`, answer: correct };
    };
    return sampleUnique(
        count,
        () => {
            const correct = wordDeck.take();
            const roll = rng.next();
            if (roll < 0.4) return mcq(correct);
            if (roll < 0.6) {
                // Format 2 — FIX IT: only when the fake is one edit from
                // exactly ONE pool word (no two-answer corrections).
                const family = familyOf(correct);
                const safe = family.filter((f) => (fakeOwners.get(f) ?? 0) === 1);
                if (safe.length === 0) return mcq(correct);
                const fake = rng.pick(safe);
                return { prompt: `Fix this misspelled word: "${fake}"`, answer: correct };
            }
            if (roll < 0.8) {
                // Format 3 — MISSING LETTER: short words only (grade fit),
                // and only positions whose mask matches no other real word.
                if (correct.length < 3 || correct.length > 6) return mcq(correct);
                const positions: number[] = [];
                for (let i = 0; i < correct.length; i++) {
                    const pattern = correct.slice(0, i) + '__' + correct.slice(i + 1);
                    if (maskIsUnique(pattern, correct)) positions.push(i);
                }
                if (positions.length === 0) return mcq(correct);
                const i = rng.pick(positions);
                const pattern = correct.slice(0, i) + '__' + correct.slice(i + 1);
                return { prompt: `Write the missing letter: ${pattern}`, answer: correct[i] };
            }
            // Format 4 — UNSCRAMBLE: short words whose letters form exactly
            // one real English word. The scramble is a fresh rng shuffle; if
            // it lands on the original order it is re-rolled once (the
            // no-identity guard in shuffleWords covers words, so letters get
            // their own tiny guard here).
            if (correct.length < 3 || correct.length > 6) return mcq(correct);
            if (!anagramIsUnique(correct)) return mcq(correct);
            const letters = [...correct];
            let scrambled = shuffleWords(rng, letters).join('');
            if (scrambled === correct) {
                scrambled = [...letters].reverse().join('');
            }
            if (scrambled === correct) return mcq(correct);
            return { prompt: `Put the letters in the right order: ${scrambled}`, answer: correct };
        },
        // Fingerprint = the printed option set / mask / scramble, so the same
        // correct word with different fakes or gaps counts as a fresh item.
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const spellingSpec: WorksheetSpec = {
    id: 'spelling',
    label: 'Spelling',
    icon: '✎',
    // T4B density: 8 roomy rows per page (was 18).
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('spelling'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'short & tricky words' : 'short words'),
    generate: generateSpelling
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SpellingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(spellingSpec);
}
