// ─────────────────────────────────────────────────────────────────────────────
// SPELLING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SpellingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Spelling", glyph "✎") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Spelling worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { wordSet, KNOWN_WORD_SET, shuffleWords } from './words';

// ── Procedural misspelling generator ─────────────────────────────────────────
// The old bank held 16 hand-curated [correct, fake, fake] triples — an 8-or-16
// question space that HAD to repeat on any long sheet. Now every word in the
// grade's word set is EXPANDED into its full family of safe misspellings at
// load, giving thousands of distinct questions ("cat" beside (catt, cwat) is a
// different question from "cat" beside (cta, cact)).
//
// Four edit families, all safe for kids' sheets:
//   - doubled letter   (cat -> catt, ccat)
//   - swapped letters  (bird -> brid, ibrdb-style neighbour swaps)
//   - dropped letter   (bread -> bead, bred)  [words of 4+ letters only]
//   - inserted letter  (cat -> cwat, cact)    [interior consonants only]
// Candidates that collide with a real word are DISCARDED via KNOWN_WORD_SET
// (which includes COMMON_WORDS — chat/cart/stun/bend/... — so an option set
// never contains two genuine English words). Old curated fakes (brid, catt…)
// stay in KNOWN_WORD_SET, which also keeps them out of the new combinations.
const FAKE_CONSONANTS = 'bcdfghjklmnprstvwz';

// Cache: pure function of the word, and a 1000-question document asks for the
// same word's family many times (dealt evenly by the deck below).
const misspellingCache = new Map<string, string[]>();

function misspellings(word: string): string[] {
    const cached = misspellingCache.get(word);
    if (cached) return cached;
    const candidates = new Set<string>();
    for (let i = 0; i < word.length; i++) {
        candidates.add(word.slice(0, i) + word[i] + word[i] + word.slice(i + 1));
        if (i + 1 < word.length) {
            candidates.add(word.slice(0, i) + word[i + 1] + word[i] + word.slice(i + 2));
        }
        if (word.length >= 4) {
            candidates.add(word.slice(0, i) + word.slice(i + 1));
        }
        // Interior insertions only: an initial letter can turn "hat" into the
        // real words "that/what", and an appended "s" makes real plurals
        // ("cats") — both would put a second real word on the sheet.
        if (i + 1 < word.length) {
            for (const c of FAKE_CONSONANTS) {
                candidates.add(word.slice(0, i + 1) + c + word.slice(i + 1));
            }
        }
    }
    const fakes = [...candidates].filter(
        (w) => w !== word && w.length >= 3 && !KNOWN_WORD_SET.has(w)
    );
    misspellingCache.set(word, fakes);
    return fakes;
}

// Spelling: multiple-choice on spelling — the correct word beside two random
// misspellings from its family. Whole grade word set (45 words Year 1, 61
// Year 2) instead of the old 8-or-16 curated triples; dealt from a deck so
// every word shows up before any repeats.
function generateSpelling(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = wordSet(caps.wordTier);
    const wordDeck = createDeck(rng, pool);
    const familyCache = new Map<string, string[]>();
    return sampleUnique(
        count,
        () => {
            const correct = wordDeck.take();
            let family = familyCache.get(correct);
            if (!family) {
                family = misspellings(correct);
                familyCache.set(correct, family);
            }
            // Two distinct fakes; the guard never fires (families hold 40+
            // members) but keeps the pick total even on a freak word.
            const f1 = rng.pick(family);
            let f2 = rng.pick(family);
            let guard = 0;
            while (f2 === f1 && guard < 12) {
                guard++;
                f2 = rng.pick(family);
            }
            if (f2 === f1) f2 = family[(family.indexOf(f1) + 1) % family.length];
            const options = shuffleWords(rng, [correct, f1, f2]);
            return { prompt: `Which word is spelled correctly? (${options.join(', ')})`, answer: correct };
        },
        // Fingerprint = the printed option set, so the same correct word with
        // a different fake pair counts as a fresh question.
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const spellingSpec: WorksheetSpec = {
    id: 'spelling',
    label: 'Spelling',
    icon: '✎',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('spelling'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'short & tricky words' : 'short words'),
    generate: generateSpelling
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SpellingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(spellingSpec);
}
