// ─────────────────────────────────────────────────────────────────────────────
// SPELLING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SpellingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Spelling", glyph "✎") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Spelling worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { shuffleWords } from './words';

// Spelling triples [correct, misspelling A, misspelling B]. The misspellings
// are curated so that none of them is a real word (checked against
// KNOWN_WORD_SET at authoring time).
const SPELLING_TIER2: [string, string, string][] = [
    ['cat', 'catt', 'cadt'],
    ['dog', 'doog', 'doge'],
    ['fish', 'fissh', 'fush'],
    ['bird', 'brid', 'bired'],
    ['house', 'hous', 'huse'],
    ['sun', 'syun', 'suun'],
    ['apple', 'applee', 'appple'],
    ['frog', 'froge', 'freog']
];
const SPELLING_TIER3_EXTRA: [string, string, string][] = [
    ['school', 'scool', 'scoool'],
    ['teacher', 'techer', 'tocher'],
    ['family', 'familly', 'familie'],
    ['banana', 'bananna', 'bannana'],
    ['butterfly', 'buterfly', 'butrefly'],
    ['beautiful', 'beutiful', 'beauitful'],
    ['chocolate', 'chocolote', 'choclate'],
    ['elephant', 'elphant', 'elephent']
];

// Spelling: multiple-choice on spelling — the correct word beside two curated
// misspellings. Year 1 uses short words; Year 2 (tricky) adds the long set.
function generateSpelling(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const pool = caps.tricky ? [...SPELLING_TIER2, ...SPELLING_TIER3_EXTRA] : SPELLING_TIER2;
    for (let i = 0; i < count; i++) {
        const [correct, w1, w2] = rng.pick(pool);
        const options = shuffleWords(rng, [correct, w1, w2]);
        out.push({ prompt: `Which word is spelled correctly? (${options.join(', ')})`, answer: correct });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const spellingSpec: WorksheetSpec = {
    id: 'spelling',
    label: 'Spelling',
    icon: '✎',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('spelling'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'short & tricky words' : 'short words'),
    generate: generateSpelling
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SpellingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(spellingSpec);
}
