// ─────────────────────────────────────────────────────────────────────────────
// SYLLABLES WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SyllablesWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Syllables", glyph "∿") and which grades offer it
//     (Year 2 only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Syllables worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Syllable counts, Year 2 only (the only grade that offers the type). Grown
// from 14 to 34 words and dealt from a deck, so every word is asked before
// any repeats (the word list IS the fact space for this worksheet type).
const SYLLABLE_WORDS: [string, number][] = [
    ['banana', 3],
    ['apple', 2],
    ['water', 2],
    ['happy', 2],
    ['butter', 2],
    ['window', 2],
    ['garden', 2],
    ['button', 2],
    ['rabbit', 2],
    ['elephant', 3],
    ['computer', 3],
    ['pumpkin', 2],
    ['dinosaur', 3],
    ['helmet', 2],
    ['tiger', 2],
    ['lion', 2],
    ['monkey', 2],
    ['lady', 2],
    ['baby', 2],
    ['music', 2],
    ['paper', 2],
    ['pencil', 2],
    ['puppy', 2],
    ['kitten', 2],
    ['napkin', 2],
    ['basket', 2],
    ['market', 2],
    ['summer', 2],
    ['winter', 2],
    ['yellow', 3],
    ['potato', 3],
    ['tomato', 3],
    ['piano', 3],
    ['radio', 3],
    ['animal', 3],
    ['holiday', 3],
    ['together', 3],
    ['wonderful', 3],
    ['crocodile', 3],
    ['alligator', 4]
];

// Syllables: count the beats in a word (Year 2 only — buildDocument gates
// this on grade.available, so the pool above is the full Y2 list).
//
// NON-REPEATING SAMPLING: the deck guarantees every word appears before any
// repeats.
function generateSyllable(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const wordDeck = createDeck(rng, SYLLABLE_WORDS);
    return sampleUnique(
        count,
        () => {
            const [word, n] = wordDeck.take();
            return { prompt: `How many syllables are in "${word}"?`, answer: `${n}` };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const syllableSpec: WorksheetSpec = {
    id: 'syllable',
    label: 'Syllables',
    icon: '∿',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('syllable'),
    scope: () => 'count the beats',
    generate: generateSyllable
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SyllablesWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(syllableSpec);
}
