// ─────────────────────────────────────────────────────────────────────────────
// SYLLABLES WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SyllablesWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Syllables", glyph "∿") and which grades offer it
//     (Year 2 only — the only grade listing the type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Syllables worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Syllable counts, Year 2 only (the only grade that offers the type).
const SYLLABLE_WORDS: [string, number][] = [
    ['banana', 3],
    ['apple', 2],
    ['water', 2],
    ['happy', 2],
    ['butter', 2],
    ['window', 2],
    ['garden', 2],
    ['button', 2],
    ['rabbit', 2],
    ['elephant', 3],
    ['computer', 3],
    ['pumpkin', 2],
    ['dinosaur', 3],
    ['helmet', 2]
];

// Syllables: count the beats in a word (Year 2 only — buildDocument gates
// this on grade.available, so the pool below is the full Y2 list).
function generateSyllable(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const [word, n] = rng.pick(SYLLABLE_WORDS);
        out.push({ prompt: `How many syllables are in "${word}"?`, answer: `${n}` });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const syllableSpec: WorksheetSpec = {
    id: 'syllable',
    label: 'Syllables',
    icon: '∿',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('syllable'),
    scope: () => 'count the beats',
    generate: generateSyllable
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SyllablesWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(syllableSpec);
}
