// ─────────────────────────────────────────────────────────────────────────────
// TWIN WORDS (HOMOPHONES) WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `TwinWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Twin Words", glyph "2") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Twin Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Twin-word (homophone) items: [prompt with "__", the two printed options,
// the correct answer]. Items 0..39 are the Year 1 pairs (14 original + 13
// newly added pairs, two sentences each); the rest are the Year 2 (tricky)
// pairs. The bank IS the fact space for this worksheet type — every extra
// sentence multiplies how long a document runs before a repeat.
const HOMOPHONE_BASIC: [string, [string, string], string][] = [
    ['Put the pencil __ .', ['there', 'their'], 'there'],
    ['I want __ go to the park.', ['to', 'too'], 'to'],
    ['Is that __ book?', ['your', "you're"], 'your'],
    ['I have __ apples.', ['two', 'to'], 'two'],
    ['The dog is over __ .', ['there', 'their'], 'there'],
    ['__ late! I am sorry.', ['Too', 'To'], 'Too'],
    ['I can __ the bird.', ['see', 'sea'], 'see'],
    ['The boat sails on the __ .', ['sea', 'see'], 'sea'],
    ['He __ the race.', ['won', 'one'], 'won'],
    ['Only __ cookie is left.', ['one', 'won'], 'one'],
    ['The sky is __ .', ['blue', 'blew'], 'blue'],
    ['The wind __ the door open.', ['blew', 'blue'], 'blew'],
    ['Turn __ at the shop.', ['right', 'write'], 'right'],
    ['I will __ my name.', ['write', 'right'], 'write'],
    // hear/here
    ['Did you __ that noise?', ['hear', 'here'], 'hear'],
    ['Come and play __ with me.', ['hear', 'here'], 'here'],
    // be/bee
    ['I want to __ a pilot.', ['bee', 'be'], 'be'],
    ['The __ makes honey.', ['bee', 'be'], 'bee'],
    // by/buy
    ['Please sit __ me.', ['by', 'buy'], 'by'],
    ['Can I __ a treat?', ['by', 'buy'], 'buy'],
    // know/no
    ['I __ the answer.', ['no', 'know'], 'know'],
    ['There are __ cookies left.', ['know', 'no'], 'no'],
    // for/four
    ['This gift is __ you.', ['four', 'for'], 'for'],
    ['I have __ crayons.', ['for', 'four'], 'four'],
    // ate/eight
    ['She __ all her peas.', ['ate', 'eight'], 'ate'],
    ['I am __ years old.', ['ate', 'eight'], 'eight'],
    // sun/son
    ['The __ is very bright.', ['son', 'sun'], 'sun'],
    ['Her __ loves trucks.', ['sun', 'son'], 'son'],
    // week/weak
    ['I go to school every __ .', ['weak', 'week'], 'week'],
    ['The kitten felt __ after being sick.', ['week', 'weak'], 'weak'],
    // tail/tale
    ['The dog wagged its __ .', ['tale', 'tail'], 'tail'],
    ['Grandpa told a funny __ .', ['tail', 'tale'], 'tale'],
    // plain/plane
    ['The __ flew over the hills.', ['plain', 'plane'], 'plane'],
    ['I like __ rice with my dinner.', ['plane', 'plain'], 'plain'],
    // meet/meat
    ['We will __ at the park gate.', ['meat', 'meet'], 'meet'],
    ['I do not eat __ .', ['meet', 'meat'], 'meat'],
    // dear/deer
    ['I saw a __ in the woods.', ['dear', 'deer'], 'deer'],
    ['My mum is very __ to me.', ['deer', 'dear'], 'dear'],
    // new/knew
    ['I have a __ pencil case.', ['knew', 'new'], 'new'],
    ['I __ all the answers.', ['new', 'knew'], 'knew']
];
const HOMOPHONE_TRICKY: [string, [string, string], string][] = [
    ['The cat licked __ paw.', ['its', "it's"], 'its'],
    ['__ going to rain today.', ["It's", 'Its'], "It's"],
    ['The book is on __ desk.', ['her', 'here'], 'her'],
    ['Come __ and sit down.', ['here', 'her'], 'here'],
    ['Where __ you going?', ['are', 'our'], 'are'],
    ['__ team plays on Friday.', ['Our', 'Are'], 'Our'],
    ['__ went to the shop yesterday.', ['They', 'Their'], 'They'],
    ['We ate __ sandwiches.', ['their', 'they'], 'their'],
    // wear/where
    ['I will __ my warm coat.', ['where', 'wear'], 'wear'],
    ['__ is my school bag?', ['wear', 'where'], 'where'],
    // whose/who's
    ['__ jacket is on the hook?', ["Who's", 'Whose'], 'Whose'],
    ["__ ready for the race?", ['Whose', "Who's"], "Who's"]
];

// Upper-primary (Year 3+) homophone extension: ACARA Y3–6 spelling — the
// harder twin-word pairs, two sentences each.
const HOMOPHONE_UPPER: [string, [string, string], string][] = [
    // principal/principle
    ['The school __ spoke at assembly.', ['principle', 'principal'], 'principal'],
    ['Honesty is an important __ .', ['principal', 'principle'], 'principle'],
    // stationary/stationery
    ['The car was __ at the lights.', ['stationery', 'stationary'], 'stationary'],
    ['I bought pens from the __ shop.', ['stationary', 'stationery'], 'stationery'],
    // weather/whether
    ['The __ turned stormy.', ['whether', 'weather'], 'weather'],
    ['__ we go depends on the rain.', ['weather', 'whether'], 'whether'],
    // aloud/allowed
    ['She read the poem __ .', ['allowed', 'aloud'], 'aloud'],
    ['Eating is not __ in the library.', ['aloud', 'allowed'], 'allowed'],
    // board/bored
    ['I drew on the white __ .', ['bored', 'board'], 'board'],
    ['He was __ during the long film.', ['board', 'bored'], 'bored'],
    // coarse/course
    ['The sand felt rough and __ .', ['course', 'coarse'], 'coarse'],
    ['We ran the cross-country __ .', ['coarse', 'course'], 'course'],
    // host/ghost (near-twin, classic upper-primary trap)
    ['The spooky __ floated by.', ['host', 'ghost'], 'ghost'],
    ['Our __ welcomed us to the party.', ['ghost', 'host'], 'host'],
    // miner/minor
    ['The gold __ worked underground.', ['minor', 'miner'], 'miner'],
    ['A __ problem is only a small one.', ['miner', 'minor'], 'minor'],
    // role/roll
    ['She played the lead __ in the play.', ['roll', 'role'], 'role'],
    ['The ball began to __ down the hill.', ['role', 'roll'], 'roll'],
    // practice/practise (AU noun/verb split)
    ['Cricket __ is on Tuesday.', ['practise', 'practice'], 'practice'],
    ['We __ our times tables nightly.', ['practice', 'practise'], 'practise'],
    // licence/license (AU noun/verb split)
    ['My dog wears a __ tag.', ['license', 'licence'], 'licence'],
    ['The shopkeeper was __ to trade.', ['licence', 'licensed'], 'licensed']
];

// Twin words (homophones): pick the correct word for the blank. Basic pairs
// (there/their, to/too, your/you're, two/to, see/sea, one/won, blue/blew,
// right/write) are Year 1 and up; the extended pairs (its/it's, her/here,
// are/our, they/their, wear/where, whose/who's) are Year 2.
//
// NON-REPEATING SAMPLING: the item bank (40 basic + 12 tricky + 24 senior)
// is the whole fact space for this worksheet type — a deck guarantees every
// sentence is asked (shuffled option order included) before any sentence is
// asked twice.
function generateHomophone(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // Basic pairs (Y1+); tricky pairs (Y2+); upper-primary pairs (Y3+,
    // wordTier 4) — the AU licence/practice noun–verb splits included.
    const pool =
        caps.wordTier >= 4
            ? [...HOMOPHONE_BASIC, ...HOMOPHONE_TRICKY, ...HOMOPHONE_UPPER]
            : caps.tricky
              ? [...HOMOPHONE_BASIC, ...HOMOPHONE_TRICKY]
              : HOMOPHONE_BASIC;
    const itemDeck = createDeck(rng, pool);
    return sampleUnique(
        count,
        () => {
            const [prompt, [o1, o2], answer] = itemDeck.take();
            // Print the two options in a random order so "first option" is never
            // the safe habit to learn.
            const shown = shuffleWords(rng, [o1, o2]);
            return { prompt: `${prompt} (${shown.join(' or ')})`, answer };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests). Twin-word
// sentences are prose — single-column via singleColumn.
export const homophoneSpec: WorksheetSpec = {
    id: 'homophone',
    label: 'Twin Words',
    icon: '2',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('homophone'),
    scope: (grade: GradeConfig) =>
        grade.caps.wordTier >= 4
            ? 'basic, tricky & senior pairs'
            : grade.caps.tricky
              ? 'basic & tricky pairs'
              : 'basic pairs',
    generate: generateHomophone
};

// The plugin: a function the dashboard calls with its framework bundle.
export function TwinWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(homophoneSpec);
}
