// ─────────────────────────────────────────────────────────────────────────────
// TWIN WORDS (HOMOPHONES) WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `TwinWordsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Twin Words", glyph "2") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Twin Words worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { shuffleWords } from './words';

// Twin-word (homophone) items: [prompt with "__", the two printed options,
// the correct answer]. Items 0..5 are the basic Year 1 pairs; the rest are
// the Year 2 (tricky) pairs.
const HOMOPHONE_BASIC: [string, [string, string], string][] = [
    ['Put the pencil __ .', ['there', 'their'], 'there'],
    ['I want __ go to the park.', ['to', 'too'], 'to'],
    ['Is that __ book?', ['your', "you're"], 'your'],
    ['I have __ apples.', ['two', 'to'], 'two'],
    ['The dog is over __ .', ['there', 'their'], 'there'],
    ['__ late! I am sorry.', ['Too', 'To'], 'Too']
];
const HOMOPHONE_TRICKY: [string, [string, string], string][] = [
    ['The cat licked __ paw.', ['its', "it's"], 'its'],
    ['__ going to rain today.', ["It's", 'Its'], "It's"],
    ['The book is on __ desk.', ['her', 'here'], 'her'],
    ['Where __ you going?', ['are', 'our'], 'are'],
    ['__ went to the shop yesterday.', ['They', 'Their'], 'They']
];

// Twin words (homophones): pick the correct word for the blank. Basic pairs
// (there/their, to/too, your/you're, two/to, Too/To) are Year 1 and up; the
// extended pairs (its/it's, her/here, are/our, they/their) are Year 2.
function generateHomophone(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const pool = caps.tricky ? [...HOMOPHONE_BASIC, ...HOMOPHONE_TRICKY] : HOMOPHONE_BASIC;
    for (let i = 0; i < count; i++) {
        const [prompt, [o1, o2], answer] = rng.pick(pool);
        // Print the two options in a random order so "first option" is never
        // the safe habit to learn.
        const shown = shuffleWords(rng, [o1, o2]);
        out.push({ prompt: `${prompt} (${shown.join(' or ')})`, answer });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests). Twin-word
// sentences are prose — single-column via singleColumn.
export const homophoneSpec: WorksheetSpec = {
    id: 'homophone',
    label: 'Twin Words',
    icon: '2',
    perPage: 16,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('homophone'),
    scope: (grade: GradeConfig) => (grade.caps.tricky ? 'basic & tricky pairs' : 'basic pairs'),
    generate: generateHomophone
};

// The plugin: a function the dashboard calls with its framework bundle.
export function TwinWordsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(homophoneSpec);
}
