// ─────────────────────────────────────────────────────────────────────────────
// VOWELS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `VowelsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Vowels", glyph "e") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Vowels worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { wordSet } from './words';

// How many vowels a word has (the a-e-i-o-u letter rule, as worksheets teach
// it). `vowelLetter` returns the single vowel letter for words with exactly
// one vowel (those power the "which letter is the vowel?" variant).
function vowelCount(word: string): number {
    let n = 0;
    for (const ch of word.toLowerCase()) if ('aeiou'.includes(ch)) n += 1;
    return n;
}
function vowelLetter(word: string): string | undefined {
    for (const ch of word.toLowerCase()) if ('aeiou'.includes(ch)) return ch;
    return undefined;
}

// Vowels: count the vowels in a word, or (for words with exactly one vowel
// letter) name that letter.
function generateVowel(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const pool = wordSet(caps.wordTier).filter((w) => vowelCount(w) >= 1);
    for (let i = 0; i < count; i++) {
        const word = rng.pick(pool);
        const n = vowelCount(word);
        if (n === 1 && rng.next() < 0.5) {
            // Single-vowel words can also ask WHICH letter is the vowel.
            out.push({ prompt: `Which letter in "${word}" is the vowel?`, answer: vowelLetter(word)! });
        } else {
            out.push({ prompt: `How many vowels are in "${word}"?`, answer: `${n}` });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const vowelSpec: WorksheetSpec = {
    id: 'vowel',
    label: 'Vowels',
    icon: 'e',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('vowel'),
    scope: (grade: GradeConfig) => `vowels, word set ${grade.caps.wordTier}`,
    generate: generateVowel
};

// The plugin: a function the dashboard calls with its framework bundle.
export function VowelsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(vowelSpec);
}
