// ─────────────────────────────────────────────────────────────────────────────
// VOWELS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `VowelsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Vowels", glyph "e") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Vowels worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual, isEarlyCueBand, sampleUnique } from '../framework';
import { wordSet, KNOWN_WORD_SET, shuffleWords } from './words';

// ── Task design (T4A) ────────────────────────────────────────────────────────
// SEVEN materially different connected vowel tasks, dealt evenly from a kind
// deck so each page mixes recognize / count / choose / build / check work:
//
//   0 COUNT     "How many vowels are in 'apple'?"            (written answer)
//   1 RECOGNIZE "Which letter in 'cat' is the vowel?"        (single-vowel words)
//   2 CHOOSE    "Which word has 2 vowels? (...)"             (exactly one fits)
//   3 CHOOSE    "Which word has the vowel 'a'? (...)"        (exactly one fits)
//   4 BUILD     "Write the missing vowel: c __ t"           (answer 'a';
//              guarded — see UNAMBIGUOUS BLANKS below)
//   5 RECOGNIZE "Which letter is a vowel? (t, i, k)" /       the letter-level
//               "Which letter is NOT a vowel? (a, e, m)"     foundation skill
//   6 CHECK     "Does 'apple' start with a vowel? (yes / no)"
//
// DENSITY (E2): perPage 24 -> 8. Early-band write-the-vowel rows print a
// letter WRITE-BOX (tileBlanks 'letter') for the missing vowel.
//
// UNAMBIGUOUS BLANKS (E4): "c __ t" also fits the real word "cot", so a
// vowel-blank row is only printed when EITHER the picture cue identifies the
// word (Y1–Y3 band) OR the shown letters match EXACTLY ONE word in
// KNOWN_WORD_SET (uncued rows).
//
// MC DEGENERACY FIX (E3): the old tier-1 sheet printed 2-option rows because
// the starter bank has only ONE 2-vowel word ("moon"). The pool now joins the
// tier bank with a LOCAL curated set of KNOWN_WORD_SET members (every word
// below is already in the shared dictionary — words.ts stays read-only and
// the non-word contract is untouched), which supplies real distractors.

// LEARNING VISUALS (Y1–3 only — the early cue band, isEarlyCueBand = word
// tiers 2..4): the single-word kinds ("how many vowels are in apple?") carry
// a picture of that word — the apple cues the word whose vowels are being
// counted; the answer (a NUMBER or a letter) is never revealed by the
// picture. The multiple-choice kinds have no single depicted concept and stay
// text-only; Prep (tier 1) and Years 4+ (tiers 5-6) print legacy markup.
function picture(caps: Caps, word: string): string | undefined {
    return isEarlyCueBand(caps) && hasVisual(word) ? word : undefined;
}

// How many vowels a word has (the a-e-i-o-u letter rule, as worksheets teach
// it). `vowelLetter` returns the single vowel letter for words with exactly
// one vowel (those power the "which letter is the vowel?" variant).
function vowelCount(word: string): number {
    let n = 0;
    for (const ch of word.toLowerCase()) if ('aeiou'.includes(ch)) n += 1;
    return n;
}
function vowelLetter(word: string): string | undefined {
    for (const ch of word.toLowerCase()) if ('aeiou'.includes(ch)) return ch;
    return undefined;
}

// Local pool extension for the shallow early tiers (see MC DEGENERACY FIX):
// every member is ALREADY a KNOWN_WORD_SET word (asserted by the plugin
// tests), so this is a curated SELECTION of the shared dictionary, not new
// vocabulary. It adds 2-vowel words (book, spoon, beach...) and vowel-initial
// words (ant, ice, egg...) the tier-1/2 banks lack.
const VOWEL_POOL_EXTRA: readonly string[] = [
    'book', 'boot', 'food', 'tool', 'cool', 'zoo', 'spoon', 'meat', 'read',
    'team', 'seat', 'beach', 'see', 'ant', 'ice', 'egg'
];

// True when EXACTLY one known word matches the shown letters (`shown` holds
// the full word; `blanks` are the hidden positions) — the unambiguous-blanks
// guard for uncued write-the-vowel rows.
function patternUnique(shown: string, blanks: number[]): boolean {
    let matches = 0;
    for (const w of KNOWN_WORD_SET) {
        if (w.length !== shown.length) continue;
        let ok = true;
        for (let i = 0; i < shown.length; i++) {
            if (!blanks.includes(i) && w[i] !== shown[i]) {
                ok = false;
                break;
            }
        }
        if (ok && ++matches > 1) return false;
    }
    return matches === 1;
}

// Vowels — the seven kinds above over the grade word set.
//
// NON-REPEATING SAMPLING: words and vowel letters are dealt from decks and
// every question passes through sampleUnique keyed on the printed prompt.
function generateVowel(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const base = wordSet(caps.wordTier);
    const pool = [...(caps.wordTier <= 2 ? [...base, ...VOWEL_POOL_EXTRA] : base)].filter((w) => vowelCount(w) >= 1);
    const wordDeck = createDeck(rng, pool);
    const VOWELS = ['a', 'e', 'i', 'o', 'u'];
    const CONSONANTS = ['b', 'c', 'd', 'f', 'g', 'h', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'v', 'w', 'x', 'y'];
    const vowelDeck = createDeck(rng, VOWELS);
    const kindDeck = createDeck(rng, [0, 1, 2, 3, 4, 5, 6]);
    // Build a 3-option set: the answer plus two words chosen by `isDistractor`
    // (the answer's complement), printed shuffled. Returns null when the pool
    // cannot supply two distinct distractors within the guard budget — the
    // caller then falls back to a well-posed written form (never a 2-option
    // multiple-choice row).
    const choiceSet = (answer: string, isDistractor: (w: string) => boolean) => {
        const options = [answer];
        let guard = 0;
        while (options.length < 3 && guard < 48) {
            guard++;
            const pick = wordDeck.take();
            if (isDistractor(pick) && !options.includes(pick)) options.push(pick);
        }
        return options.length === 3 ? shuffleWords(rng, options) : null;
    };
    // The boxed-blank scaffold for write-the-vowel rows (early band only).
    const boxed = isEarlyCueBand(caps) ? { tileBlanks: 'letter' as const } : {};
    return sampleUnique(
        count,
        () => {
            const kind = kindDeck.take();
            if (kind === 0) {
                // Written count.
                const word = wordDeck.take();
                return {
                    prompt: `How many vowels are in "${word}"?`,
                    answer: `${vowelCount(word)}`,
                    visual: picture(caps, word)
                };
            }
            if (kind === 1) {
                // Single-vowel word: name its vowel letter.
                const word = wordDeck.take();
                if (vowelCount(word) !== 1) {
                    // Dealt a multi-vowel word — the count question is the
                    // only well-posed form for it.
                    return {
                        prompt: `How many vowels are in "${word}"?`,
                        answer: `${vowelCount(word)}`,
                        visual: picture(caps, word)
                    };
                }
                return {
                    prompt: `Which letter in "${word}" is the vowel?`,
                    answer: vowelLetter(word)!,
                    visual: picture(caps, word)
                };
            }
            if (kind === 2) {
                // MC: one option has exactly N vowels, two do not.
                const answer = wordDeck.take();
                const n = vowelCount(answer);
                const label = n === 1 ? '1 vowel' : `${n} vowels`;
                const shown = choiceSet(answer, (w) => vowelCount(w) !== n);
                if (!shown) {
                    return {
                        prompt: `How many vowels are in "${answer}"?`,
                        answer: `${n}`,
                        visual: picture(caps, answer)
                    };
                }
                return { prompt: `Which word has ${label}? (${shown.join(', ')})`, answer };
            }
            if (kind === 3) {
                // MC: one option contains the dealt vowel letter, two do not.
                const letter = vowelDeck.take();
                const contains = pool.filter((w) => w.includes(letter));
                const lacks = pool.filter((w) => !w.includes(letter));
                if (contains.length === 0 || lacks.length < 2) {
                    // Degenerate letter (everyone has it / almost nobody) — fall
                    // back to a count question so the draw is never wasted.
                    const word = wordDeck.take();
                    return { prompt: `How many vowels are in "${word}"?`, answer: `${vowelCount(word)}` };
                }
                const answer = rng.pick(contains);
                // Two DISTINCT words that lack the letter.
                const d1 = rng.pick(lacks);
                const d2 = rng.pick(lacks.filter((w) => w !== d1));
                const shown = shuffleWords(rng, [answer, d1, d2]);
                return { prompt: `Which word has the vowel "${letter}"? (${shown.join(', ')})`, answer };
            }
            if (kind === 4) {
                // BUILD: write the missing vowel letter. Guarded (E4): uncued
                // rows must have a single known word matching the pattern.
                const word = wordDeck.take();
                const vIdx = [...word].map((c, i) => ('aeiou'.includes(c) ? i : -1)).filter((i) => i >= 0);
                const pos = rng.pick(vIdx);
                const pic = picture(caps, word);
                if (!pic && !patternUnique(word, [pos])) {
                    return {
                        prompt: `How many vowels are in "${word}"?`,
                        answer: `${vowelCount(word)}`,
                        visual: pic
                    };
                }
                const shown = word.split('').map((c, i) => (i === pos ? '__' : c)).join(' ');
                return {
                    prompt: `Write the missing vowel: ${shown}`,
                    answer: word[pos],
                    visual: pic,
                    ...boxed
                };
            }
            if (kind === 5) {
                // RECOGNIZE at letter level: vowel among consonants, or the
                // lone consonant among vowels. Both directions are posed so
                // the child cannot learn to "always pick the odd shape".
                const askVowel = rng.next() < 0.5;
                if (askVowel) {
                    const v = vowelDeck.take();
                    const c1 = rng.pick(CONSONANTS);
                    const c2 = rng.pick(CONSONANTS.filter((c) => c !== c1));
                    const shown = shuffleWords(rng, [v, c1, c2]);
                    return { prompt: `Which letter is a vowel? (${shown.join(', ')})`, answer: v };
                }
                const v1 = vowelDeck.take();
                const v2 = VOWELS.find((v) => v !== v1)!;
                const c = rng.pick(CONSONANTS);
                const shown = shuffleWords(rng, [v1, v2, c]);
                return { prompt: `Which letter is NOT a vowel? (${shown.join(', ')})`, answer: c };
            }
            // CHECK: does the dealt word start with a vowel letter?
            const word = wordDeck.take();
            return {
                prompt: `Does "${word}" start with a vowel? (yes / no)`,
                answer: 'aeiou'.includes(word[0]) ? 'yes' : 'no',
                visual: picture(caps, word)
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const vowelSpec: WorksheetSpec = {
    id: 'vowel',
    label: 'Vowels',
    icon: 'e',
    // E2 density: 8 rows per A4 page.
    perPage: 8,
    offered: (grade: GradeConfig) => grade.available.includes('vowel'),
    scope: (grade: GradeConfig) => `vowels, word set ${grade.caps.wordTier}`,
    generate: generateVowel
};

// The plugin: a function the dashboard calls with its framework bundle.
export function VowelsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(vowelSpec);
}
