// ─────────────────────────────────────────────────────────────────────────────
// WORD GAPS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `WordGapsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Word Gaps", glyph "§") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Word Gaps worksheet without affecting the framework or any
// other plugin.
//
// T4B REWORK (quality over quantity):
//   - DENSITY: perPage 16 → 6 (single-column prose rows with writing room).
//   - TASK MIX (four genuine formats beyond the single MCQ template):
//       1. best-word MCQ (three options, two drawn from the item's four
//          curated non-fitting distractors — the classic);
//       2. WRITTEN gap — no options; only items whose answer is forced by
//          the sentence ("A __ has a long trunk." → elephant);
//       3. DOES-NOT-FIT — two words fit the gap, one does not; the child
//          names the odd word out (inverse reading skill);
//       4. RIDDLE — "Who am I?" clue sentence with three animal/thing
//          options — comprehension, not collocation matching.
//   - BANKS: local curated context expanded 30→50 basic (Y1) and 10→22
//     extended (Y2) gap items, plus 14 written-safe, 14 does-not-fit and
//     12 riddle items. words.ts is read-only shared data this wave; every
//     new word lives in THIS file.
//   - ANSWER SAFETY: distractors are curated to clearly NOT fit each
//     sentence; written items are only used where the meaning forces a
//     single answer; does-not-fit items curate two fitting + one odd word.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';
import { shuffleWords } from './words';

// Word-gap items: [sentence with one "__", the correct word, FOUR printed
// non-fitting options]. Tier 2 = the first 50; tier 3 adds the last 22
// (longer vocabulary). The generator draws TWO of the four bad options per
// question, so each item poses C(4,2)=6 different option pairs x 6 print
// orders = 36 distinct questions — the 72-item bank is ~2 600 questions deep.
const WORDGAP_BASIC: [string, string, [string, string, string, string]][] = [
    ['I drink a glass of __ .', 'milk', ['cat', 'tree', 'door', 'shoe']],
    ['We read a __ in class.', 'book', ['door', 'fish', 'cloud', 'spoon']],
    ['My __ is very small.', 'cat', ['desk', 'milk', 'rope', 'egg']],
    ['The sun is in the __ .', 'sky', ['water', 'box', 'mug', 'fork']],
    ['The fish lives in the __ .', 'water', ['sky', 'box', 'bread', 'chair']],
    ['I wear my __ to school.', 'hat', ['book', 'milk', 'sofa', 'rock']],
    ['I sleep in my __ .', 'bed', ['cup', 'bus', 'cloud', 'ring']],
    ['I ride the __ to school.', 'bus', ['cup', 'leg', 'spoon', 'cake']],
    ['I write with a __ .', 'pen', ['cup', 'bed', 'moon', 'duck']],
    ['I wear a __ on my head.', 'hat', ['box', 'pen', 'bread', 'star']],
    ['The __ barks at the mailman.', 'dog', ['pen', 'cup', 'cloud', 'train']],
    ['We play with a __ at the park.', 'ball', ['bed', 'milk', 'spoon', 'cloud']],
    ['The __ shines in the day.', 'sun', ['bed', 'pen', 'chair', 'cup']],
    ['A __ has a long trunk.', 'elephant', ['cat', 'frog', 'spoon', 'ring']],
    ['Mom bakes a __ for us.', 'cake', ['shoe', 'log', 'star', 'frog']],
    ['The fire feels __ .', 'hot', ['wet', 'soft', 'round', 'slow']],
    ['Fish swim in the __ .', 'water', ['milk', 'tree', 'cup', 'sofa']],
    ['I brush my __ every morning.', 'hair', ['shoe', 'bus', 'cake', 'moon']],
    ['The __ flies high in the wind.', 'kite', ['rock', 'pen', 'bread', 'bed']],
    ['Bees make sweet __ .', 'honey', ['shoes', 'books', 'rocks', 'cups']],
    ['The __ says moo.', 'cow', ['hen', 'moon', 'pen', 'soap']],
    ['I put the __ in my school bag.', 'pencil', ['moon', 'milk', 'sofa', 'frog']],
    ['The __ gives us wool.', 'sheep', ['dog', 'cup', 'star', 'bus']],
    ['A __ says quack.', 'duck', ['cat', 'bed', 'pen', 'cow']],
    ['I kick the __ on the field.', 'ball', ['bed', 'milk', 'chair', 'cloud']],
    ['I see with my __ .', 'eyes', ['ears', 'shoes', 'cups', 'stars']],
    ['Grandpa sits in his __ .', 'chair', ['cake', 'moon', 'fish', 'bus']],
    ['The baby drinks from her __ .', 'bottle', ['kitten', 'shoe', 'roof', 'spoon']],
    ['We watched a __ at the cinema.', 'movie', ['carrot', 'sock', 'ladder', 'pan']],
    ['The __ spun a web.', 'spider', ['rabbit', 'rock', 'spoon', 'cloud']],
    // T4B basic extension — new grade-fit Y1 context items.
    ['A __ has a long neck.', 'giraffe', ['cat', 'frog', 'spoon', 'ring']],
    ['The __ gives us eggs.', 'hen', ['moon', 'pen', 'cup', 'rock']],
    ['We wear a __ in the rain.', 'coat', ['ball', 'kite', 'egg', 'star']],
    ['The __ pulls the plough.', 'horse', ['cat', 'fish', 'cup', 'pen']],
    ['A __ hops and has long ears.', 'rabbit', ['duck', 'fish', 'spoon', 'ring']],
    ['The __ says baa.', 'sheep', ['cow', 'hen', 'moon', 'pen']],
    ['I cook food in the __ .', 'kitchen', ['bed', 'park', 'sky', 'bus']],
    ['We buy bread at the __ .', 'bakery', ['park', 'bed', 'sky', 'frog']],
    ['The __ runs on rails.', 'train', ['kite', 'boat', 'cup', 'pen']],
    ['The __ flies at night.', 'bat', ['duck', 'fish', 'cup', 'pen']],
    ['We grow carrots in the __ .', 'garden', ['sky', 'bed', 'bus', 'moon']],
    ['The __ rings to start class.', 'bell', ['moon', 'pot', 'pen', 'frog']],
    ['I sit at my __ to write.', 'desk', ['moon', 'fish', 'star', 'egg']],
    ['A __ has a hard shell.', 'turtle', ['duck', 'frog', 'hen', 'bat']],
    ['The __ stings if you swat it.', 'bee', ['hen', 'duck', 'cat', 'frog']],
    ['We listen to the __ in class.', 'teacher', ['moon', 'star', 'frog', 'boat']],
    ['The __ brings rain.', 'cloud', ['box', 'cup', 'pen', 'log']],
    ['A __ has a pouch.', 'kangaroo', ['emu', 'frog', 'cat', 'spoon']],
    ['The __ is an Australian bird that cannot fly.', 'emu', ['frog', 'fish', 'spoon', 'ring']],
    ['I ride a __ at the farm.', 'horse', ['frog', 'fish', 'bird', 'mouse']],
    ['A __ has a horn on its nose.', 'rhino', ['horse', 'frog', 'cat', 'hen']],
    ['I wear __ on my feet.', 'shoes', ['hat', 'coat', 'pen', 'cup']],
    ['We read stories in the __ .', 'library', ['kitchen', 'garden', 'park', 'bed']],
    ['The __ keeps food cold.', 'fridge', ['oven', 'pan', 'pot', 'kettle']],
    ['The __ helps us see in the dark.', 'torch', ['book', 'pen', 'cup', 'log']],
    ['We sleep under a __ when camping.', 'tent', ['kite', 'ball', 'hat', 'egg']],
    ['Birds build a __ in the tree.', 'nest', ['cup', 'box', 'pot', 'log']],
    ['A __ is a baby frog.', 'tadpole', ['fish', 'bird', 'hen', 'cat']],
    ['The __ makes honey in a hive.', 'bee', ['ant', 'spider', 'hen', 'duck']],
    ['A __ has stripes like a horse.', 'zebra', ['tiger', 'lion', 'frog', 'hen']],
    ['The __ is the king of the jungle.', 'lion', ['tiger', 'frog', 'hen', 'cat']],
    ['We see __ in the night sky.', 'stars', ['sun', 'moon', 'birds', 'fish']],
    ['A __ hops in the pond.', 'frog', ['fish', 'bird', 'hen', 'cat']],
    ['The __ flies from flower to flower.', 'butterfly', ['ant', 'spider', 'snail', 'frog']]
];
const WORDGAP_EXTRA: [string, string, [string, string, string, string]][] = [
    ['The king wears a golden __ .', 'crown', ['sock', 'pan', 'leaf', 'cup']],
    ['The farmer drives a __ .', 'tractor', ['teapot', 'cloud', 'shoe', 'ring']],
    ['We climb the __ to reach the roof.', 'ladder', ['puddle', 'spoon', 'cloud', 'apple']],
    ['A __ carries its house on its back.', 'snail', ['fox', 'mug', 'door', 'bell']],
    ['I cut paper with __ .', 'scissors', ['forks', 'clouds', 'cups', 'moons']],
    ['The __ flew home to its nest.', 'bird', ['fish', 'cake', 'mug', 'train']],
    ['We eat __ for breakfast.', 'bread', ['shoes', 'sky', 'spoons', 'rocks']],
    ['She brushes her __ every morning.', 'teeth', ['boots', 'sky', 'spoons', 'cakes']],
    ['I put my __ on before we go.', 'boots', ['bread', 'bird', 'spoons', 'clouds']],
    ['The chicken lays __ in the morning.', 'eggs', ['birds', 'boots', 'clouds', 'rocks']],
    // T4B extended vocabulary (Y2) — longer words and topic vocabulary.
    ['The __ cares for sick animals.', 'vet', ['chef', 'pilot', 'farmer', 'baker']],
    ['The __ tells us about the past.', 'history', ['maths', 'art', 'sport', 'music']],
    ['The __ erupts with hot lava.', 'volcano', ['desert', 'river', 'valley', 'island']],
    ['A __ is a long tunnel through a hill.', 'tunnel', ['bridge', 'dam', 'fence', 'wall']],
    ['The __ is a round map of the world.', 'globe', ['poster', 'photo', 'screen', 'mirror']],
    ['We plant __ to grow new plants.', 'seeds', ['rocks', 'jars', 'books', 'spoons']],
    ['A __ is a house for a horse.', 'stable', ['garage', 'tent', 'den', 'cage']],
    ['The __ delivers letters to our door.', 'postman', ['baker', 'butcher', 'pilot', 'chef']],
    ['A __ is a place where planes take off.', 'airport', ['station', 'harbour', 'depot', 'garage']],
    ['The __ is white and falls in winter.', 'snow', ['sand', 'dust', 'flour', 'salt']],
    ['A __ is a baby sheep.', 'lamb', ['calf', 'foal', 'kid', 'cub']],
    ['The __ is a big storm with spinning wind.', 'cyclone', ['breeze', 'shower', 'drizzle', 'gust']],
    ['The __ measures how heavy something is.', 'scale', ['clock', 'ruler', 'map', 'glass']],
    ['A __ is where water falls off a cliff.', 'waterfall', ['river', 'lake', 'pool', 'dam']],
    ['The __ tells the time with hands.', 'clock', ['bell', 'phone', 'watch', 'radio']],
    ['We keep our money in a bank or a __ .', 'piggy bank', ['bottle', 'basket', 'drawer', 'pocket']],
    ['A __ is a very large wave from the sea.', 'tsunami', ['ripple', 'splash', 'shower', 'puddle']],
    ['The __ is the person who puts out fires.', 'firefighter', ['pilot', 'nurse', 'cook', 'guard']]
];

// WRITTEN gap items: [sentence, answer] — used with NO options. Only items
// whose sentence meaning forces a single common answer are listed here.
const WORDGAP_WRITTEN: [string, string][] = [
    ['A __ has a long trunk.', 'elephant'],
    ['Bees make sweet __ .', 'honey'],
    ['The __ says moo.', 'cow'],
    ['Fish swim in the __ .', 'water'],
    ['The king wears a golden __ .', 'crown'],
    ['A __ says quack.', 'duck'],
    ['The __ flies high in the wind.', 'kite'],
    ['I cut paper with __ .', 'scissors'],
    ['A __ carries its house on its back.', 'snail'],
    ['The __ spun a web.', 'spider'],
    ['The farmer drives a __ .', 'tractor'],
    ['We climb the __ to reach the roof.', 'ladder'],
    ['The __ gives us wool.', 'sheep'],
    ['The baby drinks from her __ .', 'bottle']
];

// DOES-NOT-FIT items: [sentence with "__", fitting word A, fitting word B,
// odd word out]. The child names the word that does NOT fit the gap.
const WORDGAP_NOTFIT: [string, string, string, string][] = [
    ['I drink a glass of __ .', 'milk', 'water', 'shoe'],
    ['We read a __ in class.', 'book', 'story', 'spoon'],
    ['I wear my __ to school.', 'bag', 'hat', 'cloud'],
    ['I sleep in my __ .', 'bed', 'tent', 'fridge'],
    ['I write with a __ .', 'pen', 'pencil', 'moon'],
    ['The __ barks at strangers.', 'dog', 'puppy', 'fish'],
    ['We play with a __ at the park.', 'ball', 'kite', 'milk'],
    ['The __ gives us light and warmth.', 'sun', 'lamp', 'book'],
    ['Bees make sweet __ .', 'honey', 'syrup', 'rock'],
    ['The __ gives us wool.', 'sheep', 'llama', 'train'],
    ['I cut paper with __ .', 'scissors', 'knife', 'cloud'],
    ['The king wears a golden __ .', 'crown', 'ring', 'ball'],
    ['The farmer drives a __ .', 'tractor', 'truck', 'boat'],
    ['Fish swim in the __ .', 'water', 'sea', 'sky'],
    ['I brush my __ every morning.', 'teeth', 'hair', 'shoe']
];

// RIDDLE items: [clue sentence, answer, THREE non-fitting options]. "Who am
// I?" comprehension — the child reasons over the clue, not the collocation.
const WORDGAP_RIDDLE: [string, string, [string, string, string]][] = [
    ['I carry my house on my back. Who am I?', 'snail', ['fox', 'cat', 'frog']],
    ['I have a long trunk but no trousers. Who am I?', 'elephant', ['cat', 'frog', 'dog']],
    ['I make honey in a hive. Who am I?', 'bee', ['ant', 'spider', 'fly']],
    ['I spin a web at night. Who am I?', 'spider', ['bee', 'ant', 'snail']],
    ['I lay eggs on the beach and carry my house. Who am I?', 'turtle', ['snake', 'fish', 'bird']],
    ['I say quack and love to swim. Who am I?', 'duck', ['hen', 'owl', 'frog']],
    ['I am awake at night and sleep by day. Who am I?', 'bat', ['duck', 'hen', 'cow']],
    ['I guard the house and wag my tail. Who am I?', 'dog', ['cat', 'fish', 'bird']],
    ['I give wool and say baa. Who am I?', 'sheep', ['cow', 'pig', 'hen']],
    ['I have a pouch for my baby. Who am I?', 'kangaroo', ['emu', 'koala', 'wombat']],
    ['I bring rain and float in the sky. Who am I?', 'cloud', ['sun', 'moon', 'star']],
    ['I have hands but cannot clap. Who am I?', 'clock', ['bell', 'phone', 'gloves']]
];

// Word gaps: best-word MCQ, written gap, does-not-fit and riddle formats.
// In the MCQ the two wrong choices are DRAWN from the item's four curated
// non-fitting options, so the same sentence returns with a different option
// pair (and print order) as a genuinely fresh question.
//
// NON-REPEATING SAMPLING: every bank runs on its own deck (every sentence is
// asked before any repeats) and each question passes through sampleUnique
// keyed on the printed prompt.
function generateWordGap(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const pool = caps.wordTier >= 3 ? [...WORDGAP_BASIC, ...WORDGAP_EXTRA] : WORDGAP_BASIC;
    const itemDeck = createDeck(rng, pool);
    const writtenDeck = createDeck(rng, WORDGAP_WRITTEN);
    const notfitDeck = createDeck(rng, WORDGAP_NOTFIT);
    const riddleDeck = createDeck(rng, WORDGAP_RIDDLE);
    return sampleUnique(
        count,
        () => {
            const roll = rng.next();
            if (roll < 0.5) {
                // Format 1 — best-word MCQ (two of the four bad options).
                const [sentence, answer, bads] = itemDeck.take();
                const b1 = rng.pick(bads);
                const b2 = rng.pick(bads.filter((w) => w !== b1));
                const options = shuffleWords(rng, [answer, b1, b2]);
                return { prompt: `Choose the best word: ${sentence} (${options.join(', ')})`, answer };
            }
            if (roll < 0.7) {
                // Format 2 — written gap (meaning forces the single answer).
                const [sentence, answer] = writtenDeck.take();
                return { prompt: `Fill in the gap: ${sentence}`, answer };
            }
            if (roll < 0.85) {
                // Format 3 — does-not-fit: name the odd word out.
                const [sentence, fitA, fitB, odd] = notfitDeck.take();
                const options = shuffleWords(rng, [fitA, fitB, odd]);
                return { prompt: `Which word does NOT fit: ${sentence} (${options.join(', ')})`, answer: odd };
            }
            // Format 4 — riddle.
            const [clue, answer, bads] = riddleDeck.take();
            const options = shuffleWords(rng, [answer, ...bads]);
            return { prompt: `Which word is the riddle about? ${clue} (${options.join(', ')})`, answer };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests). Gap sentences
// are prose — single-column via singleColumn.
export const wordgapSpec: WorksheetSpec = {
    id: 'wordgap',
    label: 'Word Gaps',
    icon: '§',
    // T4B density: 6 roomy prose rows per page (was 16).
    perPage: 6,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('wordgap'),
    scope: () => 'best word in the gap',
    generate: generateWordGap
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WordGapsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(wordgapSpec);
}
