// ─────────────────────────────────────────────────────────────────────────────
// WORD TRACING WORKSHEET — a self-contained dashboard plugin (Prep
// handwriting: each letter's beginning word).
//
// The dashboard loads this plugin by calling
// `WordTracingWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Word Tracing", glyph "a") and which grades offer
//     it (Prep only — tracing is a Prep skill);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Word Tracing worksheet without affecting the framework or any
// other plugin.
//
// PRACTICE DESIGN (quality over quantity): the old sheet printed all 26
// A–Z words in a frozen order on one page. A traced WORD needs far more room
// than a single letter, so the sheet now prints SIX words per page in a
// SINGLE column of long full-width writing lines (like number tracing), and
// the six come from a seeded DECK over the word set (createDeck,
// framework/sampling.ts): each word is dealt exactly once per cycle, the
// deck reshuffles between cycles, and no word repeats back-to-back across a
// cycle boundary. Every page is therefore a different group in a different
// order; the 26-word set is finite, so long documents repeat words by
// nature — spread evenly by the deck, never a frozen re-print.
//
// DETERMINISM (unchanged contract): the deck draws from the document's ONE
// seeded Rng stream (seed = seedFrom([grade, id, refresh]), seed packing
// untouched), so the same seed always yields the same document and preview
// and print can never disagree. "Randomize" now genuinely re-rolls the
// word grouping.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, hasVisual } from '../framework';

// One word per letter: the trace target for that letter's word-tracing row.
// Every word begins with its letter, is a real word (kept in the shared
// KNOWN_WORD_SET in words.ts), and stays within the Prep-friendly tier 1/2
// vocabulary where one exists (apple/bird/fish/water are tier 2; the rest
// are short single sounds). G/Q/V/X/Y/Z have no short bank word, so they take
// the standard A–Z chart words (go, queen, van, xylophone, yellow, zoo).
// This is the DECK POOL — the pairs are dealt in seeded shuffled order, not
// printed as a frozen A–Z sheet.
const TRACE_WORDS: [string, string][] = [
    ['A', 'apple'],
    ['B', 'bird'],
    ['C', 'cat'],
    ['D', 'dog'],
    ['E', 'eat'],
    ['F', 'fish'],
    ['G', 'go'],
    ['H', 'hat'],
    ['I', 'in'],
    ['J', 'jam'],
    ['K', 'kick'],
    ['L', 'leg'],
    ['M', 'map'],
    ['N', 'net'],
    ['O', 'open'],
    ['P', 'pen'],
    ['Q', 'queen'],
    ['R', 'rat'],
    ['S', 'sun'],
    ['T', 'top'],
    ['U', 'up'],
    ['V', 'van'],
    ['W', 'water'],
    ['X', 'xylophone'],
    ['Y', 'yellow'],
    ['Z', 'zoo']
];

// Word tracing: each row shows [picture cue] the letter as the model and the
// real word that begins with it as the single faded trace target ("A" +
// "apple"). LEARNING VISUAL: the picture of the word itself (when registered)
// tells the Prep child WHICH word they are tracing — the trace target is the
// word, so the picture is a scaffold, never an extra answer; words without a
// registered pictogram print plain. The cue prints at the enlarged tracing
// size (PrintableSheet passes PictogramRow `size` for trace rows) so the
// picture matches the writable scale of the big trace target.
function generateWordTrace(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    // Seeded deck over the [letter, word] pairs: every page is a fresh
    // group, and one full cycle (26 rows) covers every word exactly once.
    const deck = createDeck(rng, TRACE_WORDS);
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const [letter, word] = deck.take();
        out.push({
            prompt: `Trace the word "${word}" (begins with "${letter}")`,
            answer: word,
            model: letter,
            trace: word,
            visual: hasVisual(word) ? word : undefined
        });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const wordTraceSpec: WorksheetSpec = {
    id: 'wordTrace',
    label: 'Word Tracing',
    icon: 'a',
    // 6 rows on long full-width writing lines: a traced word needs the whole
    // page width at the enlarged tracing scale, not a cramped half-column.
    perPage: 6,
    // Single column (like number tracing) — every row gets a full-width
    // dashed writing rule instead of a half-page one.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('wordTrace'),
    scope: () => 'A–Z beginning words',
    generate: generateWordTrace
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WordTracingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(wordTraceSpec);
}
