// ─────────────────────────────────────────────────────────────────────────────
// WORD TRACING WORKSHEET — a self-contained dashboard plugin (Prep
// handwriting: each letter's beginning word).
//
// The dashboard loads this plugin by calling
// `WordTracingWorksheet(dashboard)` with its configurations + layouts
// (see plugins/index.ts). Within this function the plugin describes:
//   - its SIDEBAR LABEL ("Word Tracing", glyph "a") and which grades offer
//     it (Prep only — tracing is a Prep skill);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Word Tracing worksheet without affecting the framework or any
// other plugin.
//
// DETERMINISM: the generator deliberately draws NO random numbers — the sheet
// content is the fixed ordered A–Z word set, which is exactly what word-shape
// practice needs. "Randomize" is a no-op for this type by design; multi-page
// documents repeat the same ordered set (repeated practice runs).
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// One word per letter: the trace target for that letter's word-tracing row.
// Every word begins with its letter, is a real word (kept in the shared
// KNOWN_WORD_SET in words.ts), and stays within the Prep-friendly tier 1/2
// vocabulary where one exists (apple/bird/fish/water are tier 2; the rest
// are short single sounds). G/Q/V/X/Y/Z have no short bank word, so they take
// the standard A–Z chart words (go, queen, van, xylophone, yellow, zoo).
const TRACE_WORDS: [string, string][] = [
    ['A', 'apple'],
    ['B', 'bird'],
    ['C', 'cat'],
    ['D', 'dog'],
    ['E', 'eat'],
    ['F', 'fish'],
    ['G', 'go'],
    ['H', 'hat'],
    ['I', 'in'],
    ['J', 'jam'],
    ['K', 'kick'],
    ['L', 'leg'],
    ['M', 'map'],
    ['N', 'net'],
    ['O', 'open'],
    ['P', 'pen'],
    ['Q', 'queen'],
    ['R', 'rat'],
    ['S', 'sun'],
    ['T', 'top'],
    ['U', 'up'],
    ['V', 'van'],
    ['W', 'water'],
    ['X', 'xylophone'],
    ['Y', 'yellow'],
    ['Z', 'zoo']
];

// Word tracing: each row shows the letter as the model and the real word
// that begins with it as the single faded trace target ("A" + "apple").
function generateWordTrace(_rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const [letter, word] = TRACE_WORDS[i % TRACE_WORDS.length];
        out.push({
            prompt: `Trace the word "${word}" (begins with "${letter}")`,
            answer: word,
            model: letter,
            trace: word
        });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const wordTraceSpec: WorksheetSpec = {
    id: 'wordTrace',
    label: 'Word Tracing',
    icon: 'a',
    perPage: 26,
    offered: (grade: GradeConfig) => grade.available.includes('wordTrace'),
    scope: () => 'A–Z beginning words',
    generate: generateWordTrace
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WordTracingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(wordTraceSpec);
}
