// ─────────────────────────────────────────────────────────────────────────────
// WRITING PROJECTS WORKSHEET — a self-contained dashboard plugin
// (upper primary: Year 3–6; ACARA v9-informed — Y3 AC9E3LY06/LE05/LA04,
// Y4 AC9E4LY06/LA03/LE03, Y5 AC9E5LY06/LA02, Y6 AC9E6LY06/LA01/LA03/LE05).
//
// The dashboard loads this plugin by calling `WritingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Writing Projects", glyph "✎") and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the framework's standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Writing Projects worksheet without affecting the framework
// or any other plugin.
//
// T5 DESIGN NOTES (extended writing — the second strong deficit filled):
//   * Each task is a PLAN-then-COMPOSE project printed on its own A4 page
//     (perPage 1): purpose + audience line, a scaffolded plan (three guided
//     lines with short ruled write-lines), then ruled composition space.
//   * GENRE PROGRESSION is explicit via caps.level: Y3 narrative/informative/
//     persuasive PARAGRAPHS with heavy planning support; Y4 text stages +
//     tension + linked ideas; Y5 purpose-specific structures, connectives,
//     attributed opinions and dialogue; Y6 ADAPTED structures — formality,
//     rebuttal, review/letter/technical forms and literary adaptation.
//     Year 5 and Year 6 task banks are different genres and demands.
//   * Open-ended by nature: the answer is MARKING GUIDANCE (success criteria
//     + sample ideas), never a false single "correct" text. It reaches the
//     paper only in teacher answer-key mode.
//   * Scaffold → core → stretch is carried by the plan lines themselves:
//     Y3 plans ask WHO/WHERE/WHAT-HAPPENS (support), Y6 plans ask the writer
//     to CHOOSE form + audience (stretch decision-making).
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Short ruled line for PLAN steps (six blanks); composition uses the full
// ten-blank RULE. Both render as connected fill-in blanks (see types.ts).
const PLAN_RULE = '__ __ __ __ __ __';
const RULE = '__ __ __ __ __ __ __ __ __ __';

// One writing project.
type WritingTask = {
    // Printed task title (genre label leads, e.g. "Narrative: ...").
    title: string;
    // Purpose + audience line (ACARA audience/purpose strands open every
    // year level — the student sees WHY and FOR WHOM before they write).
    brief: string;
    // Scaffolded plan prompts (3 lines).
    plan: [string, string, string];
    // Ruled composition lines to print.
    composeLines: number;
    // Teacher marking guidance (answer key): criteria + sample ideas.
    criteria: string;
    ideas: string;
};

// ── Year 3 (AC9E3LY06 paragraphs + compound sentences + tense; AC9E3LE05
//    literary creation; AC9E3LA04 paragraphs) ────────────────────────────────
const TASKS_Y3: readonly WritingTask[] = [
    {
        title: 'Narrative: The Day the Power Went Out',
        brief: 'Purpose: to tell a story. Audience: your classmates.',
        plan: ['Who was there and where were you? ', 'What happened first, and then? ', 'How did it end? '],
        composeLines: 8,
        criteria: 'Clear beginning, middle and end; at least one sentence joined with and/but/or/so; past tense kept the same throughout.',
        ideas: 'candles and torches; games by candlelight; the sudden silence when the fridge stopped'
    },
    {
        title: 'Narrative: The Wombat at the Doorstep',
        brief: 'Purpose: to create a story with a character. Audience: a younger buddy class.',
        plan: ['Who is your main character? ', 'What does the character do? ', 'What happens at the end? '],
        composeLines: 8,
        criteria: 'A character the reader can picture; simple events in order; a satisfying ending; time words (first, then, later) guiding the reader.',
        ideas: 'a round wombat sniffing the bin; Mum pretending to be asleep; the neighbourhood gathering'
    },
    {
        title: 'Informative: My Favourite Australian Animal',
        brief: 'Purpose: to describe and inform. Audience: a younger buddy class.',
        plan: ['Name your animal and one fact about it. ', 'Two details: what it looks like / where it lives. ', 'Tell us why you like it. '],
        composeLines: 8,
        criteria: 'A topic sentence that names the animal; two or three true details; a closing sentence; headings or labels optional.',
        ideas: 'platypus, echidna, kookaburra — choose one: beak, call, habitat, food'
    },
    {
        title: 'Informative: How to Make the Best Sandwich',
        brief: 'Purpose: to explain how to do something. Audience: someone who has never made one.',
        plan: ['What is the first step? ', 'What comes next, in order? ', 'How do you finish? '],
        composeLines: 8,
        criteria: 'Steps in the right order; action verbs (spread, layer, cut); number words or a list to guide the reader.',
        ideas: 'bread choices; spreading butter; layering salad; cutting diagonally'
    },
    {
        title: 'Persuasive: Why Our School Needs More Soccer Balls',
        brief: 'Purpose: to persuade. Audience: your school council.',
        plan: ['State your opinion clearly. ', 'Give your best reason. ', 'Give one more reason or an example. '],
        composeLines: 8,
        criteria: 'An opinion stated up front; at least two reasons joined with because/so; a closing sentence that asks for action.',
        ideas: 'waiting turns during lunchtime; flat balls; more teams could play'
    },
    {
        title: 'Recount: Our Sports Carnival Day',
        brief: 'Purpose: to recount real events. Audience: your family.',
        plan: ['Where and when did it happen? ', 'What happened first, next, last? ', 'What did you think about it? '],
        composeLines: 8,
        criteria: 'Events in time order; past tense kept consistent; at least one detail of what you saw or heard; a personal closing thought.',
        ideas: 'the march-in; your race or event; the medal ceremony; the icy pole afterwards'
    }
] as const;

// ── Year 4 (AC9E4LY06 linked ideas + complex sentences; AC9E4LA03 text
//    stages; AC9E4LE03 plot tension) ─────────────────────────────────────────
const TASKS_Y4: readonly WritingTask[] = [
    {
        title: 'Informative: How a Kite Stays in the Sky',
        brief: 'Purpose: to explain how something works. Audience: a school newsletter reader.',
        plan: ['Orientation: what is a kite? ', 'Steps: what happens, in order? ', 'Closing: what makes it stay up? '],
        composeLines: 9,
        criteria: 'Clear text stages (orientation → steps → closing); connectives of time/cause (first, because, so that); present tense for facts.',
        ideas: 'wind pushing the sail; the string pulling back; the tail keeping it steady'
    },
    {
        title: 'Narrative: The Long Walk Home',
        brief: 'Purpose: to tell a story that builds tension. Audience: your classmates.',
        plan: ['Set the scene: who, where, when? ', 'The problem appears — what changes? ', 'How is the tension resolved? '],
        composeLines: 9,
        criteria: 'A described setting; a moment of tension (short sentences, sensory detail); events linked with when/after/while; a resolved ending.',
        ideas: 'the last bus leaving; a dark shortcut; a familiar dog barking ahead'
    },
    {
        title: 'Informative: Life on an Australian Wheat Farm',
        brief: 'Purpose: to inform about a place. Audience: a city audience.',
        plan: ['Orientation: where is this farm? ', 'Details: what happens through the year? ', 'Closing: what is life like there? '],
        composeLines: 9,
        criteria: 'Grouped information with a topic sentence per paragraph; time connectives (in autumn, by summer); technical words used correctly (paddock, harvester, stubble).',
        ideas: 'autumn ploughing; winter green shoots; summer harvesters running at night'
    },
    {
        title: 'Persuasive: Should Students Choose Their Own Books?',
        brief: 'Purpose: to persuade with linked reasons. Audience: your teacher.',
        plan: ['State your point of view. ', 'Reason one, with an example. ', 'Reason two, and answer the other side. '],
        composeLines: 9,
        criteria: 'Point of view stated clearly; reasons linked with because/so/therefore; at least one sentence answering the other side (although/even though).',
        ideas: 'reading more when you choose; some books are too hard; librarians can help'
    },
    {
        title: 'Description: A Morning at the Beach',
        brief: 'Purpose: to describe using sensory detail. Audience: someone who has never been.',
        plan: ['What did you SEE first? ', 'What did you HEAR and SMELL? ', 'How did it feel to be there? '],
        composeLines: 9,
        criteria: 'Details for at least three senses; vivid adjectives and verbs; sentences that flow using and/but/when; no list-poetry (write in sentences).',
        ideas: 'grey swell at dawn; sand pipers; the smell of sunscreen; cold water ankles'
    },
    {
        title: 'Report: Our Excursion to the Historic Site',
        brief: 'Purpose: to report facts. Audience: your school newsletter.',
        plan: ['What/where/when — the facts. ', 'What did you see and do? ', 'What did you learn? '],
        composeLines: 9,
        criteria: 'Factual, third-person tone; paragraphs for different parts of the day; at least one quoted or attributed detail ("Our guide said...").',
        ideas: 'the guide\'s story; the artefacts you touched; the best exhibit'
    }
] as const;

// ── Year 5 (AC9E5LY06 purpose-specific structures, connectives, technical
//    vocab, dialogue; AC9E5LA02 attributed authoritative opinions) ───────────
const TASKS_Y5: readonly WritingTask[] = [
    {
        title: 'Persuasive: Should Recess Be Longer?',
        brief: 'Purpose: to argue a position. Audience: the school council.',
        plan: ['Thesis: your position in one sentence. ', 'Two reasons — attribute one ("According to..."). ', 'Answer the other side, then close. '],
        composeLines: 10,
        criteria: 'A clear thesis; reasons joined with because/so that; at least one ATTRIBUTED opinion (According to..., research shows...); a rebuttal of the other side.',
        ideas: 'brain-break research; rushed lunches; playground squabbles; learning time worries'
    },
    {
        title: 'Narrative: The Storm, From the Lighthouse',
        brief: 'Purpose: to tell a story from a character\'s viewpoint. Audience: your classmates.',
        plan: ['Who is telling the story (first person)? ', 'What do they see and fear? ', 'What do they decide to do? '],
        composeLines: 10,
        criteria: 'Consistent FIRST-PERSON viewpoint; thoughts and feelings shown, not just told; complex sentences for reason/condition (because/unless); a decisive moment.',
        ideas: 'counting flashes; the lamp room shaking; choosing to wake the keeper'
    },
    {
        title: 'Informative: Buses or Bikes? Getting to School Sustainably',
        brief: 'Purpose: to explain both sides. Audience: the school newsletter.',
        plan: ['Introduce the question. ', 'Side one: benefits and one problem. ', 'Side two: benefits and one problem, then conclude. '],
        composeLines: 10,
        criteria: 'Balanced structure (on one hand / on the other); technical vocabulary used correctly (emissions, patronage, infrastructure); a conclusion that weighs both sides.',
        ideas: 'traffic at drop-off; bike lanes; bus timetables; safe routes'
    },
    {
        title: 'Narrative with Dialogue: The Lost Dog',
        brief: 'Purpose: to tell a story that includes direct speech. Audience: a younger audience.',
        plan: ['Who finds the dog and where? ', 'What do the characters SAY? ', 'How is the problem solved? '],
        composeLines: 10,
        criteria: 'At least two lines of punctuated DIRECT SPEECH; speech moves the story forward; tense consistent; a clear resolution.',
        ideas: 'a collar with no tag; the note on the door; the street search'
    },
    {
        title: 'Persuasive: Why Every Student Should Learn an Instrument',
        brief: 'Purpose: to persuade with evidence. Audience: parents at a school forum.',
        plan: ['Position statement. ', 'Reason with an attributed example. ', 'Reason with a scenario ("If our school..."), then close. '],
        composeLines: 10,
        criteria: 'Position up front; at least one attributed fact/opinion; a conditional argument (if/when); formal register (no slang).',
        ideas: 'band program results; practice and patience; the school concert'
    },
    {
        title: 'Informative: How Bushfires Shape Australian Landscapes',
        brief: 'Purpose: to explain cause and effect. Audience: a science display panel.',
        plan: ['Opening fact about bushfires. ', 'Two cause-and-effect chains. ', 'What regrows afterwards? '],
        composeLines: 10,
        criteria: 'Cause/effect connectives (because, as a result, which means); accurate technical terms (germinate, ash, canopy); objective tone.',
        ideas: 'seeds needing heat; new growth after rain; animals returning'
    }
] as const;

// ── Year 6 (AC9E6LY06 varied complex structures + expanded verbs + vivid
//    vocabulary; AC9E6LA01 formality; AC9E6LA03 adapt structures;
//    AC9E6LE05 adapt literary texts) ─────────────────────────────────────────
const TASKS_Y6: readonly WritingTask[] = [
    {
        title: 'Review: Choose a Show or Book You Know',
        brief: 'Purpose: to review AND judge. Audience: families choosing their next outing. Decide: will you mainly inform or mainly persuade?',
        plan: ['State what you reviewed and your verdict. ', 'Two supported judgements (quote or detail). ', 'Who should try it, and why? '],
        composeLines: 10,
        criteria: 'A review structure (verdict up front, supported judgements, recommendation); evaluative vocabulary; at least one complex sentence with an embedded clause.',
        ideas: 'the strongest moment; what confused you; age suitability; compare with another show'
    },
    {
        title: 'Persuasive: Should Advertising Be Banned at School?',
        brief: 'Purpose: to argue with awareness of bias. Audience: the parents\' association.',
        plan: ['Position + why it matters now. ', 'Your best argument, with an attributed source. ', 'Rebut the sponsor side, then close. '],
        composeLines: 10,
        criteria: 'Formal register throughout; a named or attributed source; an explicit rebuttal (although/while); varied complex sentences (condition, concession).',
        ideas: 'sponsorship money; junk-food logos; student data; fair rules vs bans'
    },
    {
        title: 'Literary Adaptation: A Familiar Tale in a New Setting',
        brief: 'Purpose: to adapt a story you know well. Audience: your classmates. Choose a tale or legend you know and move it to a new Australian setting.',
        plan: ['Which tale, and what stays the same? ', 'What changes in the new setting? ', 'What mood will you create, and how? '],
        composeLines: 10,
        criteria: 'Recognisable borrowed structure with deliberate changes; setting described with vivid verbs and imagery; a maintained point of view.',
        ideas: 'a bush town instead of a castle; a cyclone instead of a storm; a clever stockwoman'
    },
    {
        title: 'Technical: Explain How a Device You Use Works',
        brief: 'Purpose: to explain technically. Audience: a younger student. Keep an objective tone.',
        plan: ['Name the device and its parts. ', 'How it works, step by step. ', 'One limitation or safety note. '],
        composeLines: 10,
        criteria: 'Technical vocabulary defined in context; present-tense factual clauses; logical connectors (first, consequently, finally); objective, formal tone.',
        ideas: 'a e-scooter brake; a microwave; a bike light — pick one you know'
    },
    {
        title: 'Formal Letter: A Safety Issue for Your Local Council',
        brief: 'Purpose: to persuade formally. Audience: your local councillor.',
        plan: ['Greeting + the issue in one sentence. ', 'Evidence: what you have seen or counted. ', 'Polite request for action + sign-off. '],
        composeLines: 10,
        criteria: 'Letter conventions (date, greeting, sign-off); formal phrasing (I am writing to..., would you consider...); one embedded clause giving evidence; a courteous call to action.',
        ideas: 'the crossing at lights; the broken path; speeding near the oval'
    },
    {
        title: 'Two Sides: The Same Event, Two Texts',
        brief: 'Purpose: to compare forms. Audience: yourself as editor. Write ONE news-style paragraph about a school event, then ONE opinion sentence about it.',
        plan: ['The facts of the event (who/what/when). ', 'One quoted or attributed detail. ', 'Your opinion sentence — mark it "Opinion:". '],
        composeLines: 10,
        criteria: 'Objective report conventions (facts, third person, attribution) clearly separated from a subjective opinion sentence; formality controlled.',
        ideas: 'the athletics carnival; the science fair; the fundraising concert'
    }
] as const;

// Explicit year-level routing via caps.level (T5) — clamp defensively.
const BANKS: Record<3 | 4 | 5 | 6, readonly WritingTask[]> = { 3: TASKS_Y3, 4: TASKS_Y4, 5: TASKS_Y5, 6: TASKS_Y6 };

// Render one task as a single multi-line prompt (plan scaffold + ruled
// composition space) + its marking-guidance answer.
function renderTask(t: WritingTask): RawProblem {
    const planLines = t.plan.map((p, i) => `${i + 1}. ${p}${PLAN_RULE}`).join('\n');
    const composeLines = Array.from({ length: t.composeLines }, () => RULE).join('\n');
    const prompt = [
        t.title,
        t.brief,
        '',
        'Plan first.',
        planLines,
        '',
        'Now write.',
        composeLines
    ].join('\n');
    // Open-ended task: marking guidance, not a false single key.
    const answer = `Success criteria: ${t.criteria}\nSample ideas: ${t.ideas}`;
    return { prompt, answer };
}

// Generator: deal the year's task bank without repeats; long documents
// re-deal whole tasks (a fresh project each page — repeats by design).
function generateWriting(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const level = Math.min(Math.max(caps.level, 3), 6) as 3 | 4 | 5 | 6;
    const deck = localDeck(rng, BANKS[level]);
    return sampleUnique(
        count,
        () => renderTask(deck.take()),
        (p) => p.prompt
    );
}

// Local Fisher–Yates shuffle (plugin isolation: no cross-plugin imports).
function shuffleLocal<T>(rng: Rng, items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
        const j = rng.int(0, i);
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
}

// Local deck (same contract as the framework's createDeck, kept local so the
// plugin file stays self-contained per the plugin contract in types.ts).
function localDeck<T>(rng: Rng, pool: readonly T[]): { take: () => T } {
    let queue = shuffleLocal(rng, pool);
    return {
        take: () => {
            if (queue.length === 0) queue = shuffleLocal(rng, pool);
            return queue.pop() as T;
        }
    };
}

// Per-year scope line — exposes the genre/structure progression.
const SCOPE_BY_LEVEL: Record<number, string> = {
    3: 'narrative, informative and persuasive paragraphs with a plan',
    4: 'text stages, linked ideas, tension and description',
    5: 'purpose-specific structures, connectives, dialogue and viewpoint',
    6: 'adapted structures — review, letter, technical and formal tone'
};

// The plugin's declarative spec (exported for its own tests). ONE extended
// writing project per A4 page — plan scaffold plus a full page of ruled
// composition space, the A4-safe budget for every year.
export const writingSpec: WorksheetSpec = {
    id: 'writing',
    label: 'Writing Projects',
    icon: '✎',
    perPage: 1,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('writing'),
    scope: (grade: GradeConfig) => SCOPE_BY_LEVEL[grade.caps.level] ?? SCOPE_BY_LEVEL[3],
    generate: generateWriting
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WritingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(writingSpec);
}
